// Dendro: C++ Equation Code Generation {{{{ 
// Dendro: TEMPORARY VARIABLES
// Dendro: END TEMPORARY VARIABLES

// Dendro: MAIN VARIABLES
//--
out.alpha[pp] = d.alpha_xx[pp] + d.alpha_yy[pp] + d.alpha_zz[pp];

//--
out.chi[pp] = d.chi_xx[pp] + d.chi_yy[pp] + d.chi_zz[pp];

//--
out.trK[pp] = d.trK_xx[pp] + d.trK_yy[pp] + d.trK_zz[pp];

//--
out.beta0[pp] = d.beta0_xx[pp] + d.beta0_yy[pp] + d.beta0_zz[pp];

//--
out.beta1[pp] = d.beta1_xx[pp] + d.beta1_yy[pp] + d.beta1_zz[pp];

//--
out.beta2[pp] = d.beta2_xx[pp] + d.beta2_yy[pp] + d.beta2_zz[pp];

//--
out.Gt0[pp] = d.Gt0_xx[pp] + d.Gt0_yy[pp] + d.Gt0_zz[pp];

//--
out.Gt1[pp] = d.Gt1_xx[pp] + d.Gt1_yy[pp] + d.Gt1_zz[pp];

//--
out.Gt2[pp] = d.Gt2_xx[pp] + d.Gt2_yy[pp] + d.Gt2_zz[pp];

//--
out.B0[pp] = d.B0_xx[pp] + d.B0_yy[pp] + d.B0_zz[pp];

//--
out.B1[pp] = d.B1_xx[pp] + d.B1_yy[pp] + d.B1_zz[pp];

//--
out.B2[pp] = d.B2_xx[pp] + d.B2_yy[pp] + d.B2_zz[pp];

//--
out.At00[pp] = d.At00_xx[pp] + d.At00_yy[pp] + d.At00_zz[pp];

//--
out.At01[pp] = d.At01_xx[pp] + d.At01_yy[pp] + d.At01_zz[pp];

//--
out.At02[pp] = d.At02_xx[pp] + d.At02_yy[pp] + d.At02_zz[pp];

//--
out.At11[pp] = d.At11_xx[pp] + d.At11_yy[pp] + d.At11_zz[pp];

//--
out.At12[pp] = d.At12_xx[pp] + d.At12_yy[pp] + d.At12_zz[pp];

//--
out.At22[pp] = d.At22_xx[pp] + d.At22_yy[pp] + d.At22_zz[pp];

//--
out.gt00[pp] = d.gt00_xx[pp] + d.gt00_yy[pp] + d.gt00_zz[pp];

//--
out.gt01[pp] = d.gt01_xx[pp] + d.gt01_yy[pp] + d.gt01_zz[pp];

//--
out.gt02[pp] = d.gt02_xx[pp] + d.gt02_yy[pp] + d.gt02_zz[pp];

//--
out.gt11[pp] = d.gt11_xx[pp] + d.gt11_yy[pp] + d.gt11_zz[pp];

//--
out.gt12[pp] = d.gt12_xx[pp] + d.gt12_yy[pp] + d.gt12_zz[pp];

//--
out.gt22[pp] = d.gt22_xx[pp] + d.gt22_yy[pp] + d.gt22_zz[pp];
// Dendro: END MAIN VARIABLES

// Dendro: }}}} End Code Generation 
