// deriv_x(dev_var_in, alphaInt, hx, sz, bflag);
// deriv_xx(dev_var_in, alphaInt, hx, sz, bflag);
// deriv_x(dev_var_in, beta0Int, hx, sz, bflag);
// deriv_xx(dev_var_in, beta0Int, hx, sz, bflag);
// deriv_x(dev_var_in, beta1Int, hx, sz, bflag);
// deriv_xx(dev_var_in, beta1Int, hx, sz, bflag);
// deriv_x(dev_var_in, beta2Int, hx, sz, bflag);
// deriv_xx(dev_var_in, beta2Int, hx, sz, bflag);
// deriv_x(dev_var_in, B0Int, hx, sz, bflag);
// deriv_x(dev_var_in, B1Int, hx, sz, bflag);
// deriv_x(dev_var_in, B2Int, hx, sz, bflag);
// deriv_x(dev_var_in, chiInt, hx, sz, bflag);
// deriv_xx(dev_var_in, chiInt, hx, sz, bflag);
// deriv_x(dev_var_in, Gt0Int, hx, sz, bflag);
// deriv_x(dev_var_in, Gt1Int, hx, sz, bflag);
// deriv_x(dev_var_in, Gt2Int, hx, sz, bflag);
// deriv_x(dev_var_in, KInt, hx, sz, bflag);
// deriv_x(dev_var_in, gt0Int, hx, sz, bflag);
// deriv_xx(dev_var_in, gt0Int, hx, sz, bflag);
// deriv_x(dev_var_in, gt1Int, hx, sz, bflag);
// deriv_xx(dev_var_in, gt1Int, hx, sz, bflag);
// deriv_x(dev_var_in, gt2Int, hx, sz, bflag);
// deriv_xx(dev_var_in, gt2Int, hx, sz, bflag);
// deriv_x(dev_var_in, gt3Int, hx, sz, bflag);
// deriv_xx(dev_var_in, gt3Int, hx, sz, bflag);
// deriv_x(dev_var_in, gt4Int, hx, sz, bflag);
// deriv_xx(dev_var_in, gt4Int, hx, sz, bflag);
// deriv_x(dev_var_in, gt5Int, hx, sz, bflag);
// deriv_xx(dev_var_in, gt5Int, hx, sz, bflag);
// deriv_x(dev_var_in, At0Int, hx, sz, bflag);
// deriv_x(dev_var_in, At1Int, hx, sz, bflag);
// deriv_x(dev_var_in, At2Int, hx, sz, bflag);
// deriv_x(dev_var_in, At3Int, hx, sz, bflag);
// deriv_x(dev_var_in, At4Int, hx, sz, bflag);
// deriv_x(dev_var_in, At5Int, hx, sz, bflag);

deriv_y(dev_var_in, alphaInt, hy, sz, bflag);
// deriv_yy(dev_var_in, alphaInt, hy, sz, bflag);
deriv_y(dev_var_in, beta0Int, hy, sz, bflag);
// deriv_yy(dev_var_in, beta0Int, hy, sz, bflag);
deriv_y(dev_var_in, beta1Int, hy, sz, bflag);
// deriv_yy(dev_var_in, beta1Int, hy, sz, bflag);
deriv_y(dev_var_in, beta2Int, hy, sz, bflag);
// deriv_yy(dev_var_in, beta2Int, hy, sz, bflag);
deriv_y(dev_var_in, B0Int, hy, sz, bflag);
deriv_y(dev_var_in, B1Int, hy, sz, bflag);
deriv_y(dev_var_in, B2Int, hy, sz, bflag);
deriv_y(dev_var_in, chiInt, hy, sz, bflag);
// deriv_yy(dev_var_in, chiInt, hy, sz, bflag);
deriv_y(dev_var_in, Gt0Int, hy, sz, bflag);
deriv_y(dev_var_in, Gt1Int, hy, sz, bflag);
deriv_y(dev_var_in, Gt2Int, hy, sz, bflag);
deriv_y(dev_var_in, KInt, hy, sz, bflag);
deriv_y(dev_var_in, gt0Int, hy, sz, bflag);
// deriv_yy(dev_var_in, gt0Int, hy, sz, bflag);
deriv_y(dev_var_in, gt1Int, hy, sz, bflag);
// deriv_yy(dev_var_in, gt1Int, hy, sz, bflag);
deriv_y(dev_var_in, gt2Int, hy, sz, bflag);
// deriv_yy(dev_var_in, gt2Int, hy, sz, bflag);
deriv_y(dev_var_in, gt3Int, hy, sz, bflag);
// deriv_yy(dev_var_in, gt3Int, hy, sz, bflag);
deriv_y(dev_var_in, gt4Int, hy, sz, bflag);
// deriv_yy(dev_var_in, gt4Int, hy, sz, bflag);
deriv_y(dev_var_in, gt5Int, hy, sz, bflag);
// deriv_yy(dev_var_in, gt5Int, hy, sz, bflag);
deriv_y(dev_var_in, At0Int, hy, sz, bflag);
deriv_y(dev_var_in, At1Int, hy, sz, bflag);
deriv_y(dev_var_in, At2Int, hy, sz, bflag);
deriv_y(dev_var_in, At3Int, hy, sz, bflag);
deriv_y(dev_var_in, At4Int, hy, sz, bflag);
deriv_y(dev_var_in, At5Int, hy, sz, bflag);

// deriv_z(dev_var_in, alphaInt, hz, sz, bflag);
// deriv_zz(dev_var_in, alphaInt, hz, sz, bflag);
// deriv_z(dev_var_in, beta0Int, hz, sz, bflag);
// deriv_zz(dev_var_in, beta0Int, hz, sz, bflag);
// deriv_z(dev_var_in, beta1Int, hz, sz, bflag);
// deriv_zz(dev_var_in, beta1Int, hz, sz, bflag);
// deriv_z(dev_var_in, beta2Int, hz, sz, bflag);
// deriv_zz(dev_var_in, beta2Int, hz, sz, bflag);
// deriv_z(dev_var_in, B0Int, hz, sz, bflag);
// deriv_z(dev_var_in, B1Int, hz, sz, bflag);
// deriv_z(dev_var_in, B2Int, hz, sz, bflag);
// deriv_z(dev_var_in, chiInt, hz, sz, bflag);
// deriv_zz(dev_var_in, chiInt, hz, sz, bflag);
// deriv_z(dev_var_in, Gt0Int, hz, sz, bflag);
// deriv_z(dev_var_in, Gt1Int, hz, sz, bflag);
// deriv_z(dev_var_in, Gt2Int, hz, sz, bflag);
// deriv_z(dev_var_in, KInt, hz, sz, bflag);
// deriv_z(dev_var_in, gt0Int, hz, sz, bflag);
// deriv_zz(dev_var_in, gt0Int, hz, sz, bflag);
// deriv_z(dev_var_in, gt1Int, hz, sz, bflag);
// deriv_zz(dev_var_in, gt1Int, hz, sz, bflag);
// deriv_z(dev_var_in, gt2Int, hz, sz, bflag);
// deriv_zz(dev_var_in, gt2Int, hz, sz, bflag);
// deriv_z(dev_var_in, gt3Int, hz, sz, bflag);
// deriv_zz(dev_var_in, gt3Int, hz, sz, bflag);
// deriv_z(dev_var_in, gt4Int, hz, sz, bflag);
// deriv_zz(dev_var_in, gt4Int, hz, sz, bflag);
// deriv_z(dev_var_in, gt5Int, hz, sz, bflag);
// deriv_zz(dev_var_in, gt5Int, hz, sz, bflag);
// deriv_z(dev_var_in, At0Int, hz, sz, bflag);
// deriv_z(dev_var_in, At1Int, hz, sz, bflag);
// deriv_z(dev_var_in, At2Int, hz, sz, bflag);
// deriv_z(dev_var_in, At3Int, hz, sz, bflag);
// deriv_z(dev_var_in, At4Int, hz, sz, bflag);
// deriv_z(dev_var_in, At5Int, hz, sz, bflag);
deriv_y(grad_0_gt0, 0, hy, sz, bflag);
// deriv_z(grad_0_gt0, 0, hz, sz, bflag);
// deriv_z(grad_1_gt0, 0, hz, sz, bflag);
deriv_y(grad_0_gt1, 0, hy, sz, bflag);
// deriv_z(grad_0_gt1, 0, hz, sz, bflag);
// deriv_z(grad_1_gt1, 0, hz, sz, bflag);
deriv_y(grad_0_gt2, 0, hy, sz, bflag);
// deriv_z(grad_0_gt2, 0, hz, sz, bflag);
// deriv_z(grad_1_gt2, 0, hz, sz, bflag);
deriv_y(grad_0_gt3, 0, hy, sz, bflag);
// deriv_z(grad_0_gt3, 0, hz, sz, bflag);
// deriv_z(grad_1_gt3, 0, hz, sz, bflag);
deriv_y(grad_0_gt4, 0, hy, sz, bflag);
// deriv_z(grad_0_gt4, 0, hz, sz, bflag);
// deriv_z(grad_1_gt4, 0, hz, sz, bflag);
deriv_y(grad_0_gt5, 0, hy, sz, bflag);
// deriv_z(grad_0_gt5, 0, hz, sz, bflag);
// deriv_z(grad_1_gt5, 0, hz, sz, bflag);
deriv_y(grad_0_chi, 0, hy, sz, bflag);
// deriv_z(grad_0_chi, 0, hz, sz, bflag);
// deriv_z(grad_1_chi, 0, hz, sz, bflag);
deriv_y(grad_0_alpha, 0, hy, sz, bflag);
// deriv_z(grad_0_alpha, 0, hz, sz, bflag);
// deriv_z(grad_1_alpha, 0, hz, sz, bflag);
deriv_y(grad_0_beta0, 0, hy, sz, bflag);
// deriv_z(grad_0_beta0, 0, hz, sz, bflag);
// deriv_z(grad_1_beta0, 0, hz, sz, bflag);
deriv_y(grad_0_beta1, 0, hy, sz, bflag);
// deriv_z(grad_0_beta1, 0, hz, sz, bflag);
// deriv_z(grad_1_beta1, 0, hz, sz, bflag);
deriv_y(grad_0_beta2, 0, hy, sz, bflag); 
// deriv_z(grad_0_beta2, 0, hz, sz, bflag);
// deriv_z(grad_1_beta2, 0, hz, sz, bflag);
