/**
 * @file grUtils.cpp
 * @brief Initial data dispatcher and utilities for the smokemax solver.
 *
 * Generated by dendrosym. Designed to be extended -- add new initial
 * data types by:
 *   1. Add a forward declaration at the top
 *   2. Add a case to the switch in initDataFuncToPhysCoords()
 *   3. Implement the function (here or in a separate file)
 *
 * Each initial data function receives physical (not grid) coordinates
 * and fills var[0..N-1] for all evolution variables. The ordering
 * matches the VAR enum in grDef.h:
 *   var[0] = alpha
 *   var[1] = chi
 *   var[2] = trK
 *   var[3] = beta0
 *   var[4] = beta1
 *   var[5] = beta2
 *   var[6] = Gt0
 *   var[7] = Gt1
 *   var[8] = Gt2
 *   var[9] = B0
 *   var[10] = B1
 *   var[11] = B2
 *   var[12] = At00
 *   var[13] = At01
 *   var[14] = At02
 *   var[15] = At11
 *   var[16] = At12
 *   var[17] = At22
 *   var[18] = gt00
 *   var[19] = gt01
 *   var[20] = gt02
 *   var[21] = gt11
 *   var[22] = gt12
 *   var[23] = gt22
 */

#include "grUtils.h"
#include "grDef.h"
#include "parameters.h"
#include "TwoPunctures.h"

#include <cmath>
#include <cstdlib>  // rand()/RAND_MAX for raw-C++ random initial data (e.g. noise IC)
#include <iostream>

namespace smokemax {

// forward declarations for initial data types
void minkowskiInit(double x, double y, double z, double *var);
void smokeFlatInit(double x, double y, double z, double *var);
void twoPuncturesInit(double x, double y, double z, double *var);
void twoPuncturesInitEstimate(double x, double y, double z, double *var);

/**
 * @brief Initial data dispatcher. Called for every grid point during init.
 *
 * Receives grid (octree) coordinates. Converts to physical coords
 * via the GRIDX_TO_X macros, then dispatches to the appropriate
 * initial data function based on the id_type runtime parameter.
 */
void initDataFuncToPhysCoords(const double xx1, const double yy1,
                              const double zz1, double *var) {
    // convert grid coords to physical coords
    const double xx = GRIDX_TO_X(xx1);
    const double yy = GRIDY_TO_Y(yy1);
    const double zz = GRIDZ_TO_Z(zz1);

    // zero everything first
    for (unsigned int i = 0; i < 24; i++) {
        var[i] = 0.0;
    }

    switch (SMOKEMAX_ID_TYPE) {
        case 0:
            twoPuncturesInit(xx, yy, zz, var);
            break;

        case 2:
            // auto-generated from symbolic expressions in the python config
            smokeFlatInit(xx, yy, zz, var);
            break;


        default:
            std::cout << "Unknown ID type: " << SMOKEMAX_ID_TYPE << std::endl;
            exit(1);
            break;
    }
}

/**@brief Cheap-estimate IC dispatcher used by function2Octree. Real IC is
 * applied via smokemaxCtx::init_grid() after the mesh is built. */
void initDataFuncToPhysCoordsForMesh(const double xx1, const double yy1,
                                     const double zz1, double *var) {
    const double xx = GRIDX_TO_X(xx1);
    const double yy = GRIDY_TO_Y(yy1);
    const double zz = GRIDZ_TO_Z(zz1);

    for (unsigned int i = 0; i < 24; i++) var[i] = 0.0;

    switch (SMOKEMAX_ID_TYPE) {
        case 0:
            twoPuncturesInitEstimate(xx, yy, zz, var);
            break;
        default:
            initDataFuncToPhysCoords(xx1, yy1, zz1, var);
            return;
    }
}

// -------------------------------------------------------------------------
// flat spacetime (minkowski) -- useful for testing and as a base
// -------------------------------------------------------------------------

void minkowskiInit(double x, double y, double z, double *var) {
    // everything defaults to zero from the dispatcher.
    // set the non-zero values for flat spacetime:
    var[VAR::U_ALPHA] = 1.0;  // alpha
    var[VAR::U_CHI] = 1.0;  // chi
    var[VAR::U_GT00] = 1.0;  // gt00 (flat metric diagonal)
    var[VAR::U_GT11] = 1.0;  // gt11 (flat metric diagonal)
    var[VAR::U_GT22] = 1.0;  // gt22 (flat metric diagonal)
}

// -------------------------------------------------------------------------
// TwoPunctures (id=0) -- reads the spectral solution from <prefix>_tpid_sol.bin
// produced by the standalone smokemax_tpid solver.
// -------------------------------------------------------------------------
void twoPuncturesInit(double x, double y, double z, double *var) {
    double mp, mm, mp_adm, mm_adm, E, J1, J2, J3;
    TwoPunctures(x, y, z, var, &mp, &mm, &mp_adm, &mm_adm, &E, &J1, &J2, &J3);
}


// -------------------------------------------------------------------------
// Position-dependent wavelet tolerance. No TwoPunctures dependency, so this
// stays outside the tpid guard -- solver_ctx calls it unconditionally.
// -------------------------------------------------------------------------
double computeWTolDCoords(double x, double y, double z, double *hx) {
    const double tolMin = SMOKEMAX_WAVELET_TOL;
    const double tolMax = SMOKEMAX_WAVELET_TOL_MAX;
    const double R0     = SMOKEMAX_WAVELET_TOL_FUNCTION_R0;
    const double R1     = SMOKEMAX_WAVELET_TOL_FUNCTION_R1;
    const double r      = std::sqrt(x * x + y * y + z * z);

    // Degenerate config: no usable ramp, so stay flat rather than divide by 0.
    if (!(tolMax > tolMin) || !(R1 > R0)) return tolMin;

    switch (SMOKEMAX_USE_WAVELET_TOL_FUNCTION) {
        case 1:  // linear ramp tolMin@R0 -> tolMax@R1 (BSSN computeWTol)
            return std::min(
                tolMax, std::max(tolMin, (tolMax - tolMin) / (R1 - R0) *
                                                 (r - R0) +
                                             tolMin));

        case 3: {
            // Decade-exponential falloff. BSSN keys the ceiling off its
            // outermost GW extraction radius; there is none here, so tolMax is
            // the ceiling and the profile is purely radial.
            if (r < R0) return tolMin;
            const double fac = (R1 - R0) / std::log10(tolMax / tolMin);
            return std::min(tolMax,
                            tolMin * std::pow(10.0, (r - R0) / fac));
        }

        case 0:
            return tolMin;

        default: {
            // 2/4/5/6 depend on GW radii or BH-tracking state not carried here.
            // Warn rather than silently flatten -- a flat tolerance saturates
            // below any depth ceiling and makes maxdepth look inert.
            static bool warned = false;
            if (!warned) {
                warned = true;
                std::cerr << "[smokemax] WARNING: use_wavelet_tol_function = "
                          << SMOKEMAX_USE_WAVELET_TOL_FUNCTION
                          << " is not implemented; falling back to a flat "
                             "wavelet_tol. Supported: 0, 1, 3." << std::endl;
            }
            return tolMin;
        }
    }
}

// -------------------------------------------------------------------------
// TwoPunctures mesh estimate -- analytic Brill-Lindquist + conformally-flat.
// Aij omitted (smooth, doesn't drive AMR).
// -------------------------------------------------------------------------
void twoPuncturesInitEstimate(double x, double y, double z, double *var) {
    const double xx = x - TPID::center_offset[0];
    const double yy = y - TPID::center_offset[1];
    const double zz = z - TPID::center_offset[2];

    const double dx_p = xx - TPID::par_b;
    const double dx_m = xx + TPID::par_b;
    const double eps2 = TPID::TCP_epsilon * TPID::TCP_epsilon;
    const double r_plus  = std::sqrt(dx_p * dx_p + yy * yy + zz * zz + eps2);
    const double r_minus = std::sqrt(dx_m * dx_m + yy * yy + zz * zz + eps2);

    const double psi_BL = 1.0
                        + 0.5 * TPID::par_m_plus  / r_plus
                        + 0.5 * TPID::par_m_minus / r_minus;

    // BSSN chi for conformally flat BL data: chi = 1/psi_BL^4.
    var[VAR::U_CHI]      = 1.0 / std::pow(psi_BL, 4);
    var[VAR::U_GT00] = 1.0;
    var[VAR::U_GT11] = 1.0;
    var[VAR::U_GT22] = 1.0;

    if (TPID::initial_lapse == 2) {
        var[VAR::U_ALPHA] = std::pow(psi_BL, TPID::initial_lapse_psi_exponent);
    } else {
        var[VAR::U_ALPHA] = 1.0;
    }
}

// -------------------------------------------------------------------------
// symbolic initial data -- auto-generated from python config expressions
// -------------------------------------------------------------------------

void smokeFlatInit(double x, double y, double z, double *var) {
    for (unsigned int i = 0; i < 24; i++) var[i] = 0.0;

    const double r = sqrt(x*x + y*y + z*z);

    var[VAR::U_ALPHA] = 1;
var[VAR::U_CHI] = 1;
var[VAR::U_TRK] = 0;
var[VAR::U_GT00] = 1;
var[VAR::U_GT11] = 1;
var[VAR::U_GT22] = 1;
}



// -------------------------------------------------------------------------
// analytical solution -- called per point for error comparison
// -------------------------------------------------------------------------

void analyticalSolution(const double xx, const double yy,
                        const double zz, const double time, double *var) {
    for (unsigned int i = 0; i < 24; i++) var[i] = 0.0;

    // use x, y, z, t as variable names so sympy-generated code works directly
    const double x = xx;
    const double y = yy;
    const double z = zz;
    const double t = time;
    const double r = sqrt(x*x + y*y + z*z);

    // auto-generated from symbolic expressions in the python config
    var[VAR::U_ALPHA] = (1.0/100.0)*exp(-(x*x) - (y*y) - (z*z))*cos(t) + 1;
}

void analyticalSolution_BLOCK(double **uZipAnalyticVars,
                              double **uZipAnalyticDiffVars,
                              const double **uZipVars, const double time,
                              const unsigned int &offset, const double *pmin,
                              const double *pmax, const unsigned int *sz,
                              const unsigned int &bflag) {
    const unsigned int nx = sz[0];
    const unsigned int ny = sz[1];
    const unsigned int nz = sz[2];

    const double hx = (pmax[0] - pmin[0]) / (nx - 1);
    const double hy = (pmax[1] - pmin[1]) / (ny - 1);
    const double hz = (pmax[2] - pmin[2]) / (nz - 1);

    const unsigned int PW = SMOKEMAX_PADDING_WIDTH;

    // pointers into the unzipped arrays for this block
    const double *alpha_num = &uZipVars[VAR::U_ALPHA][offset];
    double *alpha_ana = &uZipAnalyticVars[VAR::U_ALPHA][offset];
    double *alpha_diff = &uZipAnalyticDiffVars[VAR::U_ALPHA][offset];
    const double *chi_num = &uZipVars[VAR::U_CHI][offset];
    double *chi_ana = &uZipAnalyticVars[VAR::U_CHI][offset];
    double *chi_diff = &uZipAnalyticDiffVars[VAR::U_CHI][offset];
    const double *trK_num = &uZipVars[VAR::U_TRK][offset];
    double *trK_ana = &uZipAnalyticVars[VAR::U_TRK][offset];
    double *trK_diff = &uZipAnalyticDiffVars[VAR::U_TRK][offset];
    const double *beta0_num = &uZipVars[VAR::U_BETA0][offset];
    double *beta0_ana = &uZipAnalyticVars[VAR::U_BETA0][offset];
    double *beta0_diff = &uZipAnalyticDiffVars[VAR::U_BETA0][offset];
    const double *beta1_num = &uZipVars[VAR::U_BETA1][offset];
    double *beta1_ana = &uZipAnalyticVars[VAR::U_BETA1][offset];
    double *beta1_diff = &uZipAnalyticDiffVars[VAR::U_BETA1][offset];
    const double *beta2_num = &uZipVars[VAR::U_BETA2][offset];
    double *beta2_ana = &uZipAnalyticVars[VAR::U_BETA2][offset];
    double *beta2_diff = &uZipAnalyticDiffVars[VAR::U_BETA2][offset];
    const double *Gt0_num = &uZipVars[VAR::U_GT0][offset];
    double *Gt0_ana = &uZipAnalyticVars[VAR::U_GT0][offset];
    double *Gt0_diff = &uZipAnalyticDiffVars[VAR::U_GT0][offset];
    const double *Gt1_num = &uZipVars[VAR::U_GT1][offset];
    double *Gt1_ana = &uZipAnalyticVars[VAR::U_GT1][offset];
    double *Gt1_diff = &uZipAnalyticDiffVars[VAR::U_GT1][offset];
    const double *Gt2_num = &uZipVars[VAR::U_GT2][offset];
    double *Gt2_ana = &uZipAnalyticVars[VAR::U_GT2][offset];
    double *Gt2_diff = &uZipAnalyticDiffVars[VAR::U_GT2][offset];
    const double *B0_num = &uZipVars[VAR::U_B0][offset];
    double *B0_ana = &uZipAnalyticVars[VAR::U_B0][offset];
    double *B0_diff = &uZipAnalyticDiffVars[VAR::U_B0][offset];
    const double *B1_num = &uZipVars[VAR::U_B1][offset];
    double *B1_ana = &uZipAnalyticVars[VAR::U_B1][offset];
    double *B1_diff = &uZipAnalyticDiffVars[VAR::U_B1][offset];
    const double *B2_num = &uZipVars[VAR::U_B2][offset];
    double *B2_ana = &uZipAnalyticVars[VAR::U_B2][offset];
    double *B2_diff = &uZipAnalyticDiffVars[VAR::U_B2][offset];
    const double *At00_num = &uZipVars[VAR::U_AT00][offset];
    double *At00_ana = &uZipAnalyticVars[VAR::U_AT00][offset];
    double *At00_diff = &uZipAnalyticDiffVars[VAR::U_AT00][offset];
    const double *At01_num = &uZipVars[VAR::U_AT01][offset];
    double *At01_ana = &uZipAnalyticVars[VAR::U_AT01][offset];
    double *At01_diff = &uZipAnalyticDiffVars[VAR::U_AT01][offset];
    const double *At02_num = &uZipVars[VAR::U_AT02][offset];
    double *At02_ana = &uZipAnalyticVars[VAR::U_AT02][offset];
    double *At02_diff = &uZipAnalyticDiffVars[VAR::U_AT02][offset];
    const double *At11_num = &uZipVars[VAR::U_AT11][offset];
    double *At11_ana = &uZipAnalyticVars[VAR::U_AT11][offset];
    double *At11_diff = &uZipAnalyticDiffVars[VAR::U_AT11][offset];
    const double *At12_num = &uZipVars[VAR::U_AT12][offset];
    double *At12_ana = &uZipAnalyticVars[VAR::U_AT12][offset];
    double *At12_diff = &uZipAnalyticDiffVars[VAR::U_AT12][offset];
    const double *At22_num = &uZipVars[VAR::U_AT22][offset];
    double *At22_ana = &uZipAnalyticVars[VAR::U_AT22][offset];
    double *At22_diff = &uZipAnalyticDiffVars[VAR::U_AT22][offset];
    const double *gt00_num = &uZipVars[VAR::U_GT00][offset];
    double *gt00_ana = &uZipAnalyticVars[VAR::U_GT00][offset];
    double *gt00_diff = &uZipAnalyticDiffVars[VAR::U_GT00][offset];
    const double *gt01_num = &uZipVars[VAR::U_GT01][offset];
    double *gt01_ana = &uZipAnalyticVars[VAR::U_GT01][offset];
    double *gt01_diff = &uZipAnalyticDiffVars[VAR::U_GT01][offset];
    const double *gt02_num = &uZipVars[VAR::U_GT02][offset];
    double *gt02_ana = &uZipAnalyticVars[VAR::U_GT02][offset];
    double *gt02_diff = &uZipAnalyticDiffVars[VAR::U_GT02][offset];
    const double *gt11_num = &uZipVars[VAR::U_GT11][offset];
    double *gt11_ana = &uZipAnalyticVars[VAR::U_GT11][offset];
    double *gt11_diff = &uZipAnalyticDiffVars[VAR::U_GT11][offset];
    const double *gt12_num = &uZipVars[VAR::U_GT12][offset];
    double *gt12_ana = &uZipAnalyticVars[VAR::U_GT12][offset];
    double *gt12_diff = &uZipAnalyticDiffVars[VAR::U_GT12][offset];
    const double *gt22_num = &uZipVars[VAR::U_GT22][offset];
    double *gt22_ana = &uZipAnalyticVars[VAR::U_GT22][offset];
    double *gt22_diff = &uZipAnalyticDiffVars[VAR::U_GT22][offset];

    double var_exact[24];

    for (unsigned int k = PW; k < nz - PW; k++) {
        for (unsigned int j = PW; j < ny - PW; j++) {
            for (unsigned int i = PW; i < nx - PW; i++) {
                const double x = pmin[0] + i * hx;
                const double y = pmin[1] + j * hy;
                const double z = pmin[2] + k * hz;
                const unsigned int pp = i + nx * (j + ny * k);

                analyticalSolution(x, y, z, time, var_exact);

                // store analytical values and compute pointwise difference
                alpha_ana[pp] = var_exact[VAR::U_ALPHA];
                alpha_diff[pp] = alpha_ana[pp] - alpha_num[pp];
                chi_ana[pp] = var_exact[VAR::U_CHI];
                chi_diff[pp] = chi_ana[pp] - chi_num[pp];
                trK_ana[pp] = var_exact[VAR::U_TRK];
                trK_diff[pp] = trK_ana[pp] - trK_num[pp];
                beta0_ana[pp] = var_exact[VAR::U_BETA0];
                beta0_diff[pp] = beta0_ana[pp] - beta0_num[pp];
                beta1_ana[pp] = var_exact[VAR::U_BETA1];
                beta1_diff[pp] = beta1_ana[pp] - beta1_num[pp];
                beta2_ana[pp] = var_exact[VAR::U_BETA2];
                beta2_diff[pp] = beta2_ana[pp] - beta2_num[pp];
                Gt0_ana[pp] = var_exact[VAR::U_GT0];
                Gt0_diff[pp] = Gt0_ana[pp] - Gt0_num[pp];
                Gt1_ana[pp] = var_exact[VAR::U_GT1];
                Gt1_diff[pp] = Gt1_ana[pp] - Gt1_num[pp];
                Gt2_ana[pp] = var_exact[VAR::U_GT2];
                Gt2_diff[pp] = Gt2_ana[pp] - Gt2_num[pp];
                B0_ana[pp] = var_exact[VAR::U_B0];
                B0_diff[pp] = B0_ana[pp] - B0_num[pp];
                B1_ana[pp] = var_exact[VAR::U_B1];
                B1_diff[pp] = B1_ana[pp] - B1_num[pp];
                B2_ana[pp] = var_exact[VAR::U_B2];
                B2_diff[pp] = B2_ana[pp] - B2_num[pp];
                At00_ana[pp] = var_exact[VAR::U_AT00];
                At00_diff[pp] = At00_ana[pp] - At00_num[pp];
                At01_ana[pp] = var_exact[VAR::U_AT01];
                At01_diff[pp] = At01_ana[pp] - At01_num[pp];
                At02_ana[pp] = var_exact[VAR::U_AT02];
                At02_diff[pp] = At02_ana[pp] - At02_num[pp];
                At11_ana[pp] = var_exact[VAR::U_AT11];
                At11_diff[pp] = At11_ana[pp] - At11_num[pp];
                At12_ana[pp] = var_exact[VAR::U_AT12];
                At12_diff[pp] = At12_ana[pp] - At12_num[pp];
                At22_ana[pp] = var_exact[VAR::U_AT22];
                At22_diff[pp] = At22_ana[pp] - At22_num[pp];
                gt00_ana[pp] = var_exact[VAR::U_GT00];
                gt00_diff[pp] = gt00_ana[pp] - gt00_num[pp];
                gt01_ana[pp] = var_exact[VAR::U_GT01];
                gt01_diff[pp] = gt01_ana[pp] - gt01_num[pp];
                gt02_ana[pp] = var_exact[VAR::U_GT02];
                gt02_diff[pp] = gt02_ana[pp] - gt02_num[pp];
                gt11_ana[pp] = var_exact[VAR::U_GT11];
                gt11_diff[pp] = gt11_ana[pp] - gt11_num[pp];
                gt12_ana[pp] = var_exact[VAR::U_GT12];
                gt12_diff[pp] = gt12_ana[pp] - gt12_num[pp];
                gt22_ana[pp] = var_exact[VAR::U_GT22];
                gt22_diff[pp] = gt22_ana[pp] - gt22_num[pp];
            }
        }
    }
}

}  // namespace smokemax
