/**
 * @file parameters.cpp
 * @brief Parameter definitions and TOML reading for the smokemax solver.
 *
 * Generated by dendrosym. Safe to edit -- add new parameters, change
 * defaults, or customize the TOML reading logic as needed.
 *
 * TOML file format:
 *   Instead of flat keys like "emda::EMDA_LAMBDA", parameters are organized
 *   into TOML tables (sections). The reader searches each section for its
 *   expected keys, with no namespace prefix needed in the TOML file:
 *
 *     [solver]
 *     ele_order = 6
 *     compd_min = [-50.0, -50.0, -50.0]
 *
 *     [physics]
 *     lambda = [1, 1, 1, 1]
 *     eta = [0.4, 0.4]
 *
 *   For backward compatibility, flat keys like "EMDA_LAMBDA" (no quotes
 *   or namespace prefix needed) are also accepted at the top level.
 */

#include "parameters.h"

#include <param_reader.h>  // dendro_params:: generic TOML reader (shared)
#include <mpi.h>
#include <any>
#include <cctype>
#include <cstdlib>
#include <limits>
#include <stdexcept>
#include <type_traits>
#include <unordered_set>
#include <vector>

// =========================================================================
// Color codes for terminal output
// =========================================================================
#ifndef NRM
#define NRM "\x1B[0m"
#define RED "\x1B[31m"
#define GRN "\x1B[32m"
#define YLW "\x1B[33m"
#define BLU "\x1B[34m"
#endif

// =========================================================================
// Global variable definitions
// =========================================================================

namespace smokemax {
mem::memory_pool<double> SMOKEMAX_MEM_POOL = mem::memory_pool<double>(0, 16);
BH BH1;
BH BH2;
Point SMOKEMAX_BH_LOC[2];
double SMOKEMAX_BH_MERGE_TIME = std::numeric_limits<double>::max();
unsigned int SMOKEMAX_BH_MERGE_STEP = std::numeric_limits<unsigned int>::max();
unsigned int SMOKEMAX_BH1_MAX_LEV = 15;
unsigned int SMOKEMAX_BH2_MAX_LEV = 15;
double SMOKEMAX_BH1_AMR_R   = 1.0;
double SMOKEMAX_BH2_AMR_R   = 1.0;
double SMOKEMAX_AMR_R_RATIO = 1.618033988749895;
// 0 = no puncture excision in the reported constraint norms (default; keeps
// the norms byte-identical to before this was added). 1.0 matches BSSN.
double SMOKEMAX_BH1_CONSTRAINT_R = 0.0;
double SMOKEMAX_BH2_CONSTRAINT_R = 0.0;

// Runtime state
double SMOKEMAX_CURRENT_RK_COORD_TIME = 0;
unsigned int SMOKEMAX_CURRENT_RK_STEP = 0;
double* SMOKEMAX_DERIV_WORKSPACE = nullptr;

// [solver] defaults
unsigned int SMOKEMAX_ELE_ORDER = 6;
unsigned int SMOKEMAX_PADDING_WIDTH = SMOKEMAX_ELE_ORDER >> 1u;
double SMOKEMAX_COMPD_MIN[3] = {-50.0, -50.0, -50.0};
double SMOKEMAX_COMPD_MAX[3] = {50.0, 50.0, 50.0};
double SMOKEMAX_OCTREE_MIN[3] = {0.0, 0.0, 0.0};
// MAXDEPTH declared before OCTREE_MAX — TU static init runs in declaration
// order, so the OCTREE_MAX initializer reads the correct value
unsigned int SMOKEMAX_MAXDEPTH = 16;
unsigned int SMOKEMAX_MINDEPTH = 3;

// BSSN-style toggle: true = uniform grid at MINDEPTH inside [BLK_MIN, BLK_MAX],
// AMR off; false = function2Octree (wavelet-driven AMR)
bool SMOKEMAX_ENABLE_BLOCK_ADAPTIVITY = false;
double SMOKEMAX_BLK_MIN_X = -50.0;
double SMOKEMAX_BLK_MIN_Y = -50.0;
double SMOKEMAX_BLK_MIN_Z = -50.0;
double SMOKEMAX_BLK_MAX_X = 50.0;
double SMOKEMAX_BLK_MAX_Y = 50.0;
double SMOKEMAX_BLK_MAX_Z = 50.0;
double SMOKEMAX_OCTREE_MAX[3] = {
    (double)(1u << SMOKEMAX_MAXDEPTH),
    (double)(1u << SMOKEMAX_MAXDEPTH),
    (double)(1u << SMOKEMAX_MAXDEPTH)};
unsigned int SMOKEMAX_DIM = 3;

double SMOKEMAX_RK_TIME_BEGIN = 0.0;
double SMOKEMAX_RK_TIME_END = 800.0;
unsigned int SMOKEMAX_RK_TYPE = 1;
double SMOKEMAX_RK45_TIME_STEP_SIZE = 0.01;
double SMOKEMAX_RK45_DESIRED_TOL = 0.001;
double SMOKEMAX_CFL_FACTOR = 0.25;

unsigned int SMOKEMAX_IO_OUTPUT_FREQ = 1000;
unsigned int SMOKEMAX_TIME_STEP_OUTPUT_FREQ = 10;
unsigned int SMOKEMAX_CHECKPT_FREQ = 5000;
bool SMOKEMAX_RESTORE_SOLVER = false;
std::string SMOKEMAX_VTU_FILE_PREFIX = "vtu/smokemax_gr";
std::string SMOKEMAX_CHKPT_FILE_PREFIX = "cp/smokemax_cp";
std::string SMOKEMAX_PROFILE_FILE_PREFIX = "smokemax_prof";

unsigned int SMOKEMAX_NUM_EVOL_VARS_VTU_OUTPUT = 24;
unsigned int SMOKEMAX_NUM_CONST_VARS_VTU_OUTPUT = 6;
unsigned int SMOKEMAX_VTU_OUTPUT_EVOL_INDICES[24] = {
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23
};
unsigned int SMOKEMAX_VTU_OUTPUT_CONST_INDICES[6] = {
    0,
    1,
    2,
    3,
    4,
    5
};

// which variables terminal_output computes norms for. Just list the indices in
// the par ([] = none); the count is the list length. Defaults to all (current
// behaviour). Each selected var costs a ghost exchange, so narrow these to cut
// synchronization; constraints are only computed if the constraint list is set.
std::vector<unsigned int> SMOKEMAX_TERMINAL_OUTPUT_EVOL_INDICES = {
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23
};
std::vector<unsigned int> SMOKEMAX_TERMINAL_OUTPUT_CONST_INDICES = {
    0,
    1,
    2,
    3,
    4,
    5
};

bool SMOKEMAX_VTU_X_SLICE = true;
bool SMOKEMAX_VTU_Y_SLICE = false;
bool SMOKEMAX_VTU_Z_SLICE = false;

unsigned int SMOKEMAX_DENDRO_GRAIN_SZ = 50;
double SMOKEMAX_DENDRO_AMR_FAC = 0.1;
double SMOKEMAX_LOAD_IMB_TOL = 0.1;
unsigned int SMOKEMAX_ASYNC_COMM_K = 4;
unsigned int SMOKEMAX_INIT_GRID_ITER = 10;
unsigned int SMOKEMAX_REMESH_TEST_FREQ = 10;
unsigned int SMOKEMAX_NUM_REFINE_VARS = 24;
unsigned int SMOKEMAX_REFINE_VARIABLE_INDICES[24] = {
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23
};
double SMOKEMAX_WAVELET_TOL = 1e-05;
unsigned int SMOKEMAX_USE_WAVELET_TOL_FUNCTION = 3;
double SMOKEMAX_WAVELET_TOL_MAX = 0.001;
double SMOKEMAX_WAVELET_TOL_FUNCTION_R0 = 30.0;
double SMOKEMAX_WAVELET_TOL_FUNCTION_R1 = 220.0;
RefinementMode SMOKEMAX_REFINEMENT_MODE = static_cast<RefinementMode>(0);

double SMOKEMAX_GRID_MIN_X = -400.0;
double SMOKEMAX_GRID_MIN_Y = -400.0;
double SMOKEMAX_GRID_MIN_Z = -400.0;
double SMOKEMAX_GRID_MAX_X = 400.0;
double SMOKEMAX_GRID_MAX_Y = 400.0;
double SMOKEMAX_GRID_MAX_Z = 400.0;
unsigned int SMOKEMAX_SPLIT_FIX = 2;
// ENABLE_BLOCK_ADAPTIVITY defined above as bool

unsigned int SMOKEMAX_NUM_DERIVATIVES = 144;

std::string DENDRO_LOG_FILE = "logfile";
int DENDRO_LOG_FILE_LEVEL = 1;
int DENDRO_LOG_CONSOLE_LEVEL = 2;
bool DENDRO_LOG_FORCE_FILE_FLUSH = false;

// [dissipation]
double KO_DISS_SIGMA = 0.4;
bool USE_CONST_KO = false;
unsigned int DISSIPATION_TYPE = 0;

double SMOKEMAX_CURRENT_MIN_DX = (SMOKEMAX_COMPD_MAX[0] - SMOKEMAX_COMPD_MIN[0]) *
                             (1.0 / (double)(1u << SMOKEMAX_MAXDEPTH));

// evolution constraint floors (for pos_floor constraints).
// Independent per-variable floors, settable at runtime via [physics] <name>_floor.
// Default 1e-4 for all (incl. alpha): the moving-puncture lapse must be allowed to
// collapse toward 0 at a puncture, or the CCZ4 R/chi^2 source in Theta/Khat cannot be
// regularized by the gauge -- see BSSN (floors alpha at CHI_FLOOR=1e-4).
double CHI_FLOOR = 1e-4;

// initial data type (set from toml [initial_data] section)
unsigned int SMOKEMAX_ID_TYPE = 0;

// [physics] parameters from equation config

// DendroDerivatives system -- see dendrolib's derivs_factory.h for the full
// list of stencil names (E4/E6/E8, KIM*, BYU*, A4/A6/B4/B6/C4/C6, etc.)
std::unique_ptr<dendroderivs::DendroDerivatives> SMOKEMAX_DERIVS = nullptr;
std::string SMOKEMAX_DERIVTYPE_FIRST = "E6";
std::string SMOKEMAX_DERIVTYPE_SECOND = "E6";
bool SMOKEMAX_USE_FUSED_STENCILS = true;
std::vector<double> SMOKEMAX_DERIV_FIRST_COEFFS = {};
std::vector<double> SMOKEMAX_DERIV_SECOND_COEFFS = {};
unsigned int SMOKEMAX_DERIV_FIRST_MATID = 1;
unsigned int SMOKEMAX_DERIV_SECOND_MATID = 1;
std::string SMOKEMAX_INMATFILT_FIRST = "none";
std::string SMOKEMAX_INMATFILT_SECOND = "none";
std::vector<double> SMOKEMAX_INMATFILT_FIRST_COEFFS = {};
std::vector<double> SMOKEMAX_INMATFILT_SECOND_COEFFS = {};
std::string SMOKEMAX_POST_RHS_FILTER = "default";

}  // namespace smokemax

#ifdef SOLVER_ENABLE_AH
namespace AH {

std::unique_ptr<dendro_aeh::AEH_BHaHAHA> ah_finder = nullptr;
unsigned int AH_SOLVER_FREQ = 0;

// defaults for 3 horizons (2 individual + 1 common for BBH)
unsigned int N_HORIZONS                         = 3;
unsigned int N_RESOLUTIONS_MULTIGRID            = 3;
std::vector<int> MAX_ITERATIONS                 = {10000, 10000, 10000};
std::vector<double> INITIAL_X_CENTER            = {0.0, 0.0, 0.0};
std::vector<double> INITIAL_Y_CENTER            = {0.0, 0.0, 0.0};
std::vector<double> INITIAL_Z_CENTER            = {0.0, 0.0, 0.0};
std::vector<double> M_SCALE                     = {0.0, 0.0, 0.0};
std::vector<double> CFL_FACTOR                  = {1.0, 1.0, 1.0};
std::vector<double> THETA_L2_M_TOL              = {1.e-5, 1.e-5, 1.e-5};
std::vector<double> THETA_LINF_M_TOL            = {1.e-2, 1.e-2, 1.e-2};
std::vector<double> ETA_DAMP_M                  = {7.0, 7.0, 7.0};
std::vector<double> KO_STRENGTH                 = {0.0, 0.0, 0.0};
std::vector<double> MAX_SEARCH_RADIUS           = {1.5, 1.5, 1.5};
std::vector<int> NR_INTERP_MAX                  = {48, 48, 48};
int NTHETA_MAX                                  = 32;
int NPHI_MAX                                    = 64;
std::string AH_SAVE_DIR                         = "";
int NUM_RESOLUTIONS_AFTER_FIND                  = 3;
std::vector<int> NTHETA_ARRAY                   = {8, 16, 32};
std::vector<int> NPHI_ARRAY                     = {16, 32, 64};
int ENABLE_ETA_VARYING_ALG                      = 0;
int VERBOSITY_LEVEL                             = 1;

// The evolution variables BHaHAHA reads, in the order the transform below
// expects: chi, trace(K), At[6 symmetric], gt[6 symmetric]. Resolved in
// project_generator._resolve_ah_input_vars, from the config's ah_input_vars or
// by exact name match -- never by prefix, which once matched AtSecondOrder00
// and fed the finder the wrong six components.
const std::vector<int> AH_INDICES = {
    smokemax::VAR::U_CHI,
    smokemax::VAR::U_TRK,
    smokemax::VAR::U_AT00,
    smokemax::VAR::U_AT01,
    smokemax::VAR::U_AT02,
    smokemax::VAR::U_AT11,
    smokemax::VAR::U_AT12,
    smokemax::VAR::U_AT22,
    smokemax::VAR::U_GT00,
    smokemax::VAR::U_GT01,
    smokemax::VAR::U_GT02,
    smokemax::VAR::U_GT11,
    smokemax::VAR::U_GT12,
    smokemax::VAR::U_GT22,
};

}  // namespace AH
#endif

namespace GW {
unsigned int SMOKEMAX_GW_NUM_RADAII = 6;
unsigned int SMOKEMAX_GW_RADAII[6] = {50, 60, 70, 80, 90, 100};
unsigned int SMOKEMAX_GW_NUM_LMODES = 9;
unsigned int SMOKEMAX_GW_L_MODES[9] = {2, 3, 4, 5, 6, 7, 8, 9, 10};
}  // namespace GW

namespace smokemax {
// gw extraction frequency
unsigned int SMOKEMAX_GW_EXTRACT_FREQ = 0;  // 0 = disabled
}  // namespace smokemax

namespace TPID {
std::string FILE_PREFIX = "smokemax_id";
double par_b = 4.0;
double par_m_plus = 0.5;
double par_m_minus = 0.5;
double par_P_plus[3] = {0.0, 0.0, 0.0};
double par_P_minus[3] = {0.0, 0.0, 0.0};
double par_S_plus[3] = {0.0, 0.0, 0.0};
double par_S_minus[3] = {0.0, 0.0, 0.0};
double center_offset[3] = {0.0, 0.0, 0.0};
unsigned int give_bare_mass = 1;
int initial_lapse = 2;
unsigned int grid_setup_method = 1;
int solve_momentum_constraint = 1;
unsigned int verbose = 1;
double adm_tol = 1e-10;
double Newton_tol = 1e-10;
double initial_lapse_psi_exponent = -2.0;
unsigned int npoints_A = 60;
unsigned int npoints_B = 60;
unsigned int npoints_phi = 60;
unsigned int nintegration_theta = 60;
unsigned int nintegration_phi = 60;
bool use_Dilaton = false;
bool use_Interpolated_solution = false;
bool replace_lapse_with_sqrt_chi = false;
double par_alpha0 = 0.0;
double par_q_plus = 0.0;
double par_q_minus = 0.0;
double par_p_plus = 0.0;
double par_p_minus = 0.0;
double target_M_plus = 0.5;
double target_M_minus = 0.5;
}  // namespace TPID

// =========================================================================
// TOML Parameter Reading
// =========================================================================

namespace smokemax {

namespace {

// Thin forwarders to the shared dendro_params reader, binding this solver's
// legacy fallbacks ("smokemax::KEY" and "SMOKEMAX_KEY"). The
// section-first + case-insensitive + flat-key logic lives in <param_reader.h>.
template <typename T>
inline bool try_read(const toml::value& root, const std::string& section,
                     const std::string& key, T& out) {
    return dendro_params::try_read(root, section, key, out,
                                   "smokemax::", "SMOKEMAX_");
}

template <typename T, std::size_t N>
inline bool try_read_array(const toml::value& root, const std::string& section,
                           const std::string& key, T (&out)[N]) {
    return dendro_params::try_read_array(root, section, key, out,
                                         "smokemax::", "SMOKEMAX_");
}

}  // anonymous namespace

void readParamFile(const char* inFile, MPI_Comm comm) {
    int rank, npes;
    MPI_Comm_rank(comm, &rank);
    MPI_Comm_size(comm, &npes);

    const auto root = toml::parse(inFile);

    // Macro for required params: fail if not found
    #define READ_REQUIRED(section, key, var) \
        if (!try_read(root, section, key, var)) { \
            if (rank == 0) std::cerr << RED << "MISSING REQUIRED PARAMETER: " \
                << "[" << section << "] " << key << NRM << std::endl; \
            throw std::runtime_error("Missing required parameter: " + \
                                     std::string(key)); \
        }

    // Macro for optional params: warn if not found, keep default
    #define READ_OPTIONAL(section, key, var) \
        if (!try_read(root, section, key, var)) { \
            if (rank == 0) std::cout << YLW << "\tOptional param '" << key \
                << "' not found, using default" << NRM << std::endl; \
        }

    #define READ_REQUIRED_ARRAY(section, key, var) \
        if (!try_read_array(root, section, key, var)) { \
            if (rank == 0) std::cerr << RED << "MISSING REQUIRED ARRAY: " \
                << "[" << section << "] " << key << NRM << std::endl; \
            throw std::runtime_error("Missing required array: " + \
                                     std::string(key)); \
        }

    #define READ_OPTIONAL_ARRAY(section, key, var) \
        try_read_array(root, section, key, var)

    // =================================================================
    // [solver] - Mesh and time stepping
    // =================================================================
    READ_REQUIRED("solver", "maxdepth", SMOKEMAX_MAXDEPTH);
    READ_REQUIRED("solver", "dim", SMOKEMAX_DIM);
    READ_REQUIRED("solver", "rk_type", SMOKEMAX_RK_TYPE);
    READ_REQUIRED("solver", "rk_time_begin", SMOKEMAX_RK_TIME_BEGIN);
    READ_REQUIRED("solver", "rk_time_end", SMOKEMAX_RK_TIME_END);
    READ_REQUIRED("solver", "rk45_time_step_size", SMOKEMAX_RK45_TIME_STEP_SIZE);
    READ_REQUIRED("solver", "rk45_desired_tol", SMOKEMAX_RK45_DESIRED_TOL);
    READ_REQUIRED("solver", "io_output_freq", SMOKEMAX_IO_OUTPUT_FREQ);
    READ_REQUIRED("solver", "remesh_test_freq", SMOKEMAX_REMESH_TEST_FREQ);
    READ_REQUIRED("solver", "checkpt_freq", SMOKEMAX_CHECKPT_FREQ);
    READ_REQUIRED("solver", "vtu_file_prefix", SMOKEMAX_VTU_FILE_PREFIX);
    READ_REQUIRED("solver", "chkpt_file_prefix", SMOKEMAX_CHKPT_FILE_PREFIX);
    READ_REQUIRED("solver", "profile_file_prefix", SMOKEMAX_PROFILE_FILE_PREFIX);
    READ_REQUIRED("solver", "restore_solver", SMOKEMAX_RESTORE_SOLVER);
    READ_REQUIRED("solver", "dendro_grain_sz", SMOKEMAX_DENDRO_GRAIN_SZ);
    READ_REQUIRED("solver", "async_comm_k", SMOKEMAX_ASYNC_COMM_K);
    READ_REQUIRED("solver", "dendro_amr_fac", SMOKEMAX_DENDRO_AMR_FAC);
    READ_REQUIRED("solver", "load_imb_tol", SMOKEMAX_LOAD_IMB_TOL);

    READ_OPTIONAL("solver", "ele_order", SMOKEMAX_ELE_ORDER);
    READ_OPTIONAL("solver", "mindepth", SMOKEMAX_MINDEPTH);
    READ_OPTIONAL("solver", "enable_block_adaptivity",
                  SMOKEMAX_ENABLE_BLOCK_ADAPTIVITY);
    READ_OPTIONAL("solver", "blk_min_x", SMOKEMAX_BLK_MIN_X);
    READ_OPTIONAL("solver", "blk_min_y", SMOKEMAX_BLK_MIN_Y);
    READ_OPTIONAL("solver", "blk_min_z", SMOKEMAX_BLK_MIN_Z);
    READ_OPTIONAL("solver", "blk_max_x", SMOKEMAX_BLK_MAX_X);
    READ_OPTIONAL("solver", "blk_max_y", SMOKEMAX_BLK_MAX_Y);
    READ_OPTIONAL("solver", "blk_max_z", SMOKEMAX_BLK_MAX_Z);
    READ_OPTIONAL("solver", "cfl_factor", SMOKEMAX_CFL_FACTOR);
    READ_OPTIONAL("solver", "init_grid_iter", SMOKEMAX_INIT_GRID_ITER);
    READ_OPTIONAL("solver", "time_step_output_freq", SMOKEMAX_TIME_STEP_OUTPUT_FREQ);
    READ_OPTIONAL("solver", "num_refine_vars", SMOKEMAX_NUM_REFINE_VARS);
    READ_OPTIONAL("solver", "num_evol_vars_vtu_output", SMOKEMAX_NUM_EVOL_VARS_VTU_OUTPUT);
    READ_OPTIONAL("solver", "num_const_vars_vtu_output", SMOKEMAX_NUM_CONST_VARS_VTU_OUTPUT);
    // terminal_output norm selection: list of variable indices (count = length)
    if (root.contains("solver")) {
        const auto& _solver = root.at("solver");
        if (_solver.contains("terminal_output_evol_indices"))
            SMOKEMAX_TERMINAL_OUTPUT_EVOL_INDICES =
                toml::find<std::vector<unsigned int>>(_solver, "terminal_output_evol_indices");
        if (_solver.contains("terminal_output_const_indices"))
            SMOKEMAX_TERMINAL_OUTPUT_CONST_INDICES =
                toml::find<std::vector<unsigned int>>(_solver, "terminal_output_const_indices");
    }
    READ_OPTIONAL("solver", "vtu_x_slice", SMOKEMAX_VTU_X_SLICE);
    READ_OPTIONAL("solver", "vtu_y_slice", SMOKEMAX_VTU_Y_SLICE);
    READ_OPTIONAL("solver", "vtu_z_slice", SMOKEMAX_VTU_Z_SLICE);

    READ_REQUIRED_ARRAY("solver", "compd_min", SMOKEMAX_COMPD_MIN);
    READ_REQUIRED_ARRAY("solver", "compd_max", SMOKEMAX_COMPD_MAX);
    READ_OPTIONAL_ARRAY("solver", "octree_min", SMOKEMAX_OCTREE_MIN);
    // recompute OCTREE_MAX from the toml-loaded MAXDEPTH (static init used the
    // declared default); READ_OPTIONAL_ARRAY below overrides if user set it
    SMOKEMAX_OCTREE_MAX[0] = (double)(1u << SMOKEMAX_MAXDEPTH);
    SMOKEMAX_OCTREE_MAX[1] = (double)(1u << SMOKEMAX_MAXDEPTH);
    SMOKEMAX_OCTREE_MAX[2] = (double)(1u << SMOKEMAX_MAXDEPTH);
    READ_OPTIONAL_ARRAY("solver", "octree_max", SMOKEMAX_OCTREE_MAX);

    // recompute dependent values
    SMOKEMAX_PADDING_WIDTH = SMOKEMAX_ELE_ORDER >> 1u;
    SMOKEMAX_CURRENT_MIN_DX = (SMOKEMAX_COMPD_MAX[0] - SMOKEMAX_COMPD_MIN[0]) *
                                         (1.0 / (double)(1u << SMOKEMAX_MAXDEPTH));

    // =================================================================
    // [refinement]
    // =================================================================
    READ_OPTIONAL("refinement", "wavelet_tol", SMOKEMAX_WAVELET_TOL);
    READ_OPTIONAL("refinement", "wavelet_tol_max", SMOKEMAX_WAVELET_TOL_MAX);
    READ_OPTIONAL("refinement", "use_wavelet_tol_function", SMOKEMAX_USE_WAVELET_TOL_FUNCTION);
    READ_OPTIONAL("refinement", "wavelet_tol_function_r0", SMOKEMAX_WAVELET_TOL_FUNCTION_R0);
    READ_OPTIONAL("refinement", "wavelet_tol_function_r1", SMOKEMAX_WAVELET_TOL_FUNCTION_R1);
    {
        unsigned int mode_int = static_cast<unsigned int>(SMOKEMAX_REFINEMENT_MODE);
        try_read(root, "refinement", "mode", mode_int);
        SMOKEMAX_REFINEMENT_MODE = static_cast<RefinementMode>(mode_int);
    }
    READ_OPTIONAL("refinement", "amr_r_ratio", SMOKEMAX_AMR_R_RATIO);

    // =================================================================
    // [dissipation]
    // =================================================================
    READ_REQUIRED("dissipation", "ko_diss_sigma", KO_DISS_SIGMA);
    READ_OPTIONAL("dissipation", "use_const_ko", USE_CONST_KO);
    READ_OPTIONAL("dissipation", "dissipation_type", DISSIPATION_TYPE);

    // =================================================================
    // [physics] - Equation-specific parameters
    // These are read with their short names (no project prefix)
    // =================================================================

    // evolution constraint floors (optional; compiled defaults 1e-4)
    READ_OPTIONAL("physics", "chi_floor", CHI_FLOOR);

    // =================================================================
    // [initial_data]
    // =================================================================
    READ_OPTIONAL("initial_data", "id_type", SMOKEMAX_ID_TYPE);

    // read BH parameters from [bh1] and [bh2] sections
    {
        SMOKEMAX_BH1_MAX_LEV = SMOKEMAX_MAXDEPTH;
        SMOKEMAX_BH2_MAX_LEV = SMOKEMAX_MAXDEPTH;

        double mass = 0, bx = 0, by = 0, bz = 0, vx = 0, vy = 0, vz = 0;
        double spin = 0, spin_theta = 0, spin_phi = 0;

        if (root.contains("bh1")) {
            const auto& bh = root.at("bh1");
            if (bh.contains("mass")) mass = toml::find<double>(bh, "mass");
            if (bh.contains("x")) bx = toml::find<double>(bh, "x");
            if (bh.contains("y")) by = toml::find<double>(bh, "y");
            if (bh.contains("z")) bz = toml::find<double>(bh, "z");
            if (bh.contains("spin")) spin = toml::find<double>(bh, "spin");
            if (bh.contains("max_lev"))
                SMOKEMAX_BH1_MAX_LEV =
                    toml::find<unsigned int>(bh, "max_lev");
            if (bh.contains("amr_r"))
                SMOKEMAX_BH1_AMR_R = toml::find<double>(bh, "amr_r");
            if (bh.contains("constraint_r"))
                SMOKEMAX_BH1_CONSTRAINT_R =
                    toml::find<double>(bh, "constraint_r");
        }
        BH1 = BH(mass, bx, by, bz, vx, vy, vz, spin, spin_theta, spin_phi);
        SMOKEMAX_BH_LOC[0] = Point(bx, by, bz);

        mass = 0; bx = 0; by = 0; bz = 0;
        if (root.contains("bh2")) {
            const auto& bh = root.at("bh2");
            if (bh.contains("mass")) mass = toml::find<double>(bh, "mass");
            if (bh.contains("x")) bx = toml::find<double>(bh, "x");
            if (bh.contains("y")) by = toml::find<double>(bh, "y");
            if (bh.contains("z")) bz = toml::find<double>(bh, "z");
            if (bh.contains("spin")) spin = toml::find<double>(bh, "spin");
            if (bh.contains("max_lev"))
                SMOKEMAX_BH2_MAX_LEV =
                    toml::find<unsigned int>(bh, "max_lev");
            if (bh.contains("amr_r"))
                SMOKEMAX_BH2_AMR_R = toml::find<double>(bh, "amr_r");
            if (bh.contains("constraint_r"))
                SMOKEMAX_BH2_CONSTRAINT_R =
                    toml::find<double>(bh, "constraint_r");
        }
        BH2 = BH(mass, bx, by, bz, vx, vy, vz, spin, spin_theta, spin_phi);
        SMOKEMAX_BH_LOC[1] = Point(bx, by, bz);

        if (rank == 0) {
            std::cout << "BH1: mass=" << BH1.getBHMass()
                      << " loc=(" << BH1.getBHCoordX() << ","
                      << BH1.getBHCoordY() << "," << BH1.getBHCoordZ() << ")"
                      << std::endl;
        }
    }


    READ_OPTIONAL("initial_data", "tpid_file_prefix", TPID::FILE_PREFIX);
    READ_OPTIONAL("initial_data", "par_b", TPID::par_b);
    READ_OPTIONAL("initial_data", "par_m_plus", TPID::par_m_plus);
    READ_OPTIONAL("initial_data", "par_m_minus", TPID::par_m_minus);
    READ_OPTIONAL_ARRAY("initial_data", "par_P_plus", TPID::par_P_plus);
    READ_OPTIONAL_ARRAY("initial_data", "par_P_minus", TPID::par_P_minus);
    READ_OPTIONAL_ARRAY("initial_data", "par_S_plus", TPID::par_S_plus);
    READ_OPTIONAL_ARRAY("initial_data", "par_S_minus", TPID::par_S_minus);
    READ_OPTIONAL_ARRAY("initial_data", "center_offset", TPID::center_offset);

    // Seed the moving-puncture tracker from the TwoPunctures geometry:
    // the punctures sit at (center_offset +/- par_b * x_hat). Without explicit
    // [bh1]/[bh2] sections the tracked locations would otherwise default to the
    // origin -- which zeros the trajectory and trips a spurious t=0 merger.
    if (!root.contains("bh1") && !root.contains("bh2")) {
        SMOKEMAX_BH_LOC[0] = Point(TPID::center_offset[0] + TPID::par_b,
                                              TPID::center_offset[1],
                                              TPID::center_offset[2]);
        SMOKEMAX_BH_LOC[1] = Point(TPID::center_offset[0] - TPID::par_b,
                                              TPID::center_offset[1],
                                              TPID::center_offset[2]);
    }
    READ_OPTIONAL("initial_data", "give_bare_mass", TPID::give_bare_mass);
    READ_OPTIONAL("initial_data", "initial_lapse", TPID::initial_lapse);
    // spectral solver tuning -- expose every TPID knob so the TOML can
    // shrink npoints, loosen Newton tol, skip the momentum constraint, etc.
    READ_OPTIONAL("initial_data", "grid_setup_method", TPID::grid_setup_method);
    READ_OPTIONAL("initial_data", "solve_momentum_constraint", TPID::solve_momentum_constraint);
    READ_OPTIONAL("initial_data", "verbose", TPID::verbose);
    READ_OPTIONAL("initial_data", "adm_tol", TPID::adm_tol);
    READ_OPTIONAL("initial_data", "Newton_tol", TPID::Newton_tol);
    READ_OPTIONAL("initial_data", "initial_lapse_psi_exponent", TPID::initial_lapse_psi_exponent);
    READ_OPTIONAL("initial_data", "npoints_A", TPID::npoints_A);
    READ_OPTIONAL("initial_data", "npoints_B", TPID::npoints_B);
    READ_OPTIONAL("initial_data", "npoints_phi", TPID::npoints_phi);
    READ_OPTIONAL("initial_data", "nintegration_theta", TPID::nintegration_theta);
    READ_OPTIONAL("initial_data", "nintegration_phi", TPID::nintegration_phi);
    READ_OPTIONAL("initial_data", "use_Dilaton", TPID::use_Dilaton);
    READ_OPTIONAL("initial_data", "use_Interpolated_solution", TPID::use_Interpolated_solution);
    READ_OPTIONAL("initial_data", "replace_lapse_with_sqrt_chi", TPID::replace_lapse_with_sqrt_chi);
    READ_OPTIONAL("initial_data", "par_alpha0", TPID::par_alpha0);
    READ_OPTIONAL("initial_data", "par_q_plus", TPID::par_q_plus);
    READ_OPTIONAL("initial_data", "par_q_minus", TPID::par_q_minus);
    READ_OPTIONAL("initial_data", "target_M_plus", TPID::target_M_plus);
    READ_OPTIONAL("initial_data", "target_M_minus", TPID::target_M_minus);

    // =================================================================
    // [wave_extraction]
    // =================================================================
    READ_OPTIONAL("wave_extraction", "extract_freq", SMOKEMAX_GW_EXTRACT_FREQ);
    READ_OPTIONAL("wave_extraction", "num_radaii", GW::SMOKEMAX_GW_NUM_RADAII);
    READ_OPTIONAL("wave_extraction", "num_lmodes", GW::SMOKEMAX_GW_NUM_LMODES);
    // TODO: read radii and l_modes arrays from TOML

    // =================================================================
    // [logging]
    // =================================================================
    READ_OPTIONAL("logging", "log_file", DENDRO_LOG_FILE);
    READ_OPTIONAL("logging", "log_file_level", DENDRO_LOG_FILE_LEVEL);
    READ_OPTIONAL("logging", "log_console_level", DENDRO_LOG_CONSOLE_LEVEL);
    READ_OPTIONAL("logging", "force_file_flush", DENDRO_LOG_FORCE_FILE_FLUSH);

#ifdef SOLVER_ENABLE_AH
    // =================================================================
    // [apparent_horizon]
    // =================================================================
    READ_OPTIONAL("apparent_horizon", "solver_freq", AH::AH_SOLVER_FREQ);

    // read bhahaha config from [apparent_horizon] section
    if (root.contains("apparent_horizon")) {
        const auto& ah_sec = root.at("apparent_horizon");

        // scalar params
        if (ah_sec.contains("n_horizons")) AH::N_HORIZONS = toml::find<unsigned int>(ah_sec, "n_horizons");
        if (ah_sec.contains("n_resolutions_multigrid")) AH::N_RESOLUTIONS_MULTIGRID = toml::find<unsigned int>(ah_sec, "n_resolutions_multigrid");
        if (ah_sec.contains("ntheta_max")) AH::NTHETA_MAX = toml::find<int>(ah_sec, "ntheta_max");
        if (ah_sec.contains("nphi_max")) AH::NPHI_MAX = toml::find<int>(ah_sec, "nphi_max");
        if (ah_sec.contains("save_dir")) AH::AH_SAVE_DIR = toml::find<std::string>(ah_sec, "save_dir");
        if (ah_sec.contains("num_resolutions_after_find")) AH::NUM_RESOLUTIONS_AFTER_FIND = toml::find<int>(ah_sec, "num_resolutions_after_find");
        if (ah_sec.contains("enable_eta_varying_alg")) AH::ENABLE_ETA_VARYING_ALG = toml::find<int>(ah_sec, "enable_eta_varying_alg");
        if (ah_sec.contains("verbosity_level")) AH::VERBOSITY_LEVEL = toml::find<int>(ah_sec, "verbosity_level");

        // vector params (per-horizon)
        if (ah_sec.contains("max_iterations")) AH::MAX_ITERATIONS = toml::find<std::vector<int>>(ah_sec, "max_iterations");
        if (ah_sec.contains("m_scale")) AH::M_SCALE = toml::find<std::vector<double>>(ah_sec, "m_scale");
        if (ah_sec.contains("cfl_factor")) AH::CFL_FACTOR = toml::find<std::vector<double>>(ah_sec, "cfl_factor");
        if (ah_sec.contains("theta_l2_m_tol")) AH::THETA_L2_M_TOL = toml::find<std::vector<double>>(ah_sec, "theta_l2_m_tol");
        if (ah_sec.contains("theta_linf_m_tol")) AH::THETA_LINF_M_TOL = toml::find<std::vector<double>>(ah_sec, "theta_linf_m_tol");
        if (ah_sec.contains("eta_damp_m")) AH::ETA_DAMP_M = toml::find<std::vector<double>>(ah_sec, "eta_damp_m");
        if (ah_sec.contains("ko_strength")) AH::KO_STRENGTH = toml::find<std::vector<double>>(ah_sec, "ko_strength");
        if (ah_sec.contains("max_search_radius")) AH::MAX_SEARCH_RADIUS = toml::find<std::vector<double>>(ah_sec, "max_search_radius");
        if (ah_sec.contains("nr_interp_max")) AH::NR_INTERP_MAX = toml::find<std::vector<int>>(ah_sec, "nr_interp_max");
        if (ah_sec.contains("initial_x_center")) AH::INITIAL_X_CENTER = toml::find<std::vector<double>>(ah_sec, "initial_x_center");
        if (ah_sec.contains("initial_y_center")) AH::INITIAL_Y_CENTER = toml::find<std::vector<double>>(ah_sec, "initial_y_center");
        if (ah_sec.contains("initial_z_center")) AH::INITIAL_Z_CENTER = toml::find<std::vector<double>>(ah_sec, "initial_z_center");
        if (ah_sec.contains("ntheta_array")) AH::NTHETA_ARRAY = toml::find<std::vector<int>>(ah_sec, "ntheta_array");
        if (ah_sec.contains("nphi_array")) AH::NPHI_ARRAY = toml::find<std::vector<int>>(ah_sec, "nphi_array");
    }

    if (AH::AH_SOLVER_FREQ > 0) {
        // build simple BH data from BH1/BH2 for the finder
        std::vector<dendro_aeh::SimpleBlackHoleData> simpleBHData = {
            dendro_aeh::SimpleBlackHoleData(
                BH1.getBHCoordX(), BH1.getBHCoordY(), BH1.getBHCoordZ(),
                BH1.getBHMass()),
            dendro_aeh::SimpleBlackHoleData(
                BH2.getBHCoordX(), BH2.getBHCoordY(), BH2.getBHCoordZ(),
                BH2.getBHMass()),
        };
        // enable_bh_tracking only says there IS black-hole data; it does not say
        // there are two. A single puncture parks an inert mass-0 BH2 far away
        // (the phantom guard), and with is_bbh true the finder forces horizon 1
        // onto that phantom with M_scale = 0 and fails with error code 14.
        bool is_bbh = (BH2.getBHMass() > 0.0);

        // transform: maps the interpolated evolution vars (AH_INDICES order)
        // to the 12 physical components [gd[6], Kd[6]] BHaHAHA expects.
        auto transform = [](const std::vector<double>& inputs) {
            // default: BSSN-style (chi, trK, At[6], gt[6])
            std::vector<double> output(12, 0.0);

            const double chi     = inputs[0];
            const double trK_val = inputs[1];
            const double inv_chi = 1.0 / chi;
            const double trK_third = (1.0 / 3.0) * trK_val;

            // gd[ij] = gt[ij] / chi
            for (int i = 0; i < 6; i++)
                output[i] = inputs[8 + i] * inv_chi;

            // Kd[ij] = At[ij] / chi + (1/3) * gd[ij] * trK
            for (int i = 0; i < 6; i++)
                output[6 + i] = inputs[2 + i] * inv_chi + output[i] * trK_third;

            return output;
        };

        Point grid_limits[2];
        grid_limits[0] = Point(SMOKEMAX_OCTREE_MIN[0],
                               SMOKEMAX_OCTREE_MIN[1],
                               SMOKEMAX_OCTREE_MIN[2]);
        grid_limits[1] = Point(SMOKEMAX_OCTREE_MAX[0],
                               SMOKEMAX_OCTREE_MAX[1],
                               SMOKEMAX_OCTREE_MAX[2]);

        Point domain_limits[2];
        domain_limits[0] = Point(SMOKEMAX_COMPD_MIN[0],
                                 SMOKEMAX_COMPD_MIN[1],
                                 SMOKEMAX_COMPD_MIN[2]);
        domain_limits[1] = Point(SMOKEMAX_COMPD_MAX[0],
                                 SMOKEMAX_COMPD_MAX[1],
                                 SMOKEMAX_COMPD_MAX[2]);

        AH::ah_finder = std::make_unique<dendro_aeh::AEH_BHaHAHA>(
            AH::N_HORIZONS, is_bbh,
            AH::INITIAL_X_CENTER, AH::INITIAL_Y_CENTER, AH::INITIAL_Z_CENTER,
            AH::N_RESOLUTIONS_MULTIGRID, AH::M_SCALE, AH::CFL_FACTOR,
            AH::MAX_ITERATIONS, AH::THETA_L2_M_TOL, AH::THETA_LINF_M_TOL,
            AH::ETA_DAMP_M, AH::KO_STRENGTH, AH::MAX_SEARCH_RADIUS,
            AH::NR_INTERP_MAX, AH::NTHETA_MAX, AH::NPHI_MAX, AH::AH_SAVE_DIR,
            simpleBHData, AH::AH_INDICES, transform, grid_limits, domain_limits,
            SMOKEMAX_IO_OUTPUT_FREQ, AH::NUM_RESOLUTIONS_AFTER_FIND,
            AH::NTHETA_ARRAY, AH::NPHI_ARRAY, AH::ENABLE_ETA_VARYING_ALG,
            AH::VERBOSITY_LEVEL);

        if (rank == 0) {
            std::cout << "Apparent horizon finder initialized ("
                      << AH::N_HORIZONS << " horizons, freq="
                      << AH::AH_SOLVER_FREQ << ")" << std::endl;
        }
    }
#endif

    // [derivatives] -- see dendrolib's derivs_factory.h for valid type names
    READ_OPTIONAL("derivatives", "type_first", SMOKEMAX_DERIVTYPE_FIRST);
    READ_OPTIONAL("derivatives", "type_second", SMOKEMAX_DERIVTYPE_SECOND);
    READ_OPTIONAL("derivatives", "matid_first", SMOKEMAX_DERIV_FIRST_MATID);
    READ_OPTIONAL("derivatives", "matid_second", SMOKEMAX_DERIV_SECOND_MATID);
    READ_OPTIONAL("derivatives", "filter_first", SMOKEMAX_INMATFILT_FIRST);
    READ_OPTIONAL("derivatives", "filter_second", SMOKEMAX_INMATFILT_SECOND);
    READ_OPTIONAL("derivatives", "post_rhs_filter", SMOKEMAX_POST_RHS_FILTER);
    READ_OPTIONAL("derivatives", "use_fused_stencils",
                  SMOKEMAX_USE_FUSED_STENCILS);

    SMOKEMAX_DERIVS = std::make_unique<dendroderivs::DendroDerivatives>(
        SMOKEMAX_DERIVTYPE_FIRST, SMOKEMAX_DERIVTYPE_SECOND,
        SMOKEMAX_ELE_ORDER,
        SMOKEMAX_DERIV_FIRST_COEFFS, SMOKEMAX_DERIV_SECOND_COEFFS,
        SMOKEMAX_DERIV_FIRST_MATID, SMOKEMAX_DERIV_SECOND_MATID,
        SMOKEMAX_INMATFILT_FIRST, SMOKEMAX_INMATFILT_SECOND,
        SMOKEMAX_INMATFILT_FIRST_COEFFS, SMOKEMAX_INMATFILT_SECOND_COEFFS,
        SMOKEMAX_POST_RHS_FILTER);

    if (rank == 0) {
        std::cout << "DendroDerivatives initialized: "
                  << SMOKEMAX_DERIVS->toString() << std::endl;
    }

    #undef READ_REQUIRED
    #undef READ_OPTIONAL
    #undef READ_REQUIRED_ARRAY
    #undef READ_OPTIONAL_ARRAY

    if (rank == 0) {
        std::cout << GRN << "Parameter file loaded successfully." << NRM << std::endl;
    }
}

void dumpParamFile(std::ostream& sout, int root, MPI_Comm comm) {
    int rank;
    MPI_Comm_rank(comm, &rank);
    if (rank != root) return;

    // Dumps parsed in-memory values, not the par file, so a silently-kept
    // compiled default is visible in the log.
    const std::streamsize old_prec = sout.precision();
    sout << std::setprecision(17);

    auto arr = [&sout](const char* name, const auto* a, std::size_t n) {
        sout << name << " = [";
        for (std::size_t i = 0; i < n; ++i)
            sout << a[i] << (i + 1 < n ? ", " : "");
        sout << "]" << std::endl;
    };

    sout << "# ==== SMOKEMAX parameter dump (parsed values, not the par file) ===="
         << std::endl;

    sout << "\n[solver]" << std::endl;
    sout << "dim = " << SMOKEMAX_DIM << std::endl;
    sout << "ele_order = " << SMOKEMAX_ELE_ORDER << std::endl;
    sout << "padding_width = " << SMOKEMAX_PADDING_WIDTH << std::endl;
    sout << "maxdepth = " << SMOKEMAX_MAXDEPTH << std::endl;
    sout << "mindepth = " << SMOKEMAX_MINDEPTH << std::endl;
    arr("compd_min", SMOKEMAX_COMPD_MIN, 3);
    arr("compd_max", SMOKEMAX_COMPD_MAX, 3);
    arr("octree_min", SMOKEMAX_OCTREE_MIN, 3);
    arr("octree_max", SMOKEMAX_OCTREE_MAX, 3);
    sout << "enable_block_adaptivity = " << SMOKEMAX_ENABLE_BLOCK_ADAPTIVITY
         << std::endl;
    sout << "rk_type = " << SMOKEMAX_RK_TYPE << std::endl;
    sout << "rk_time_begin = " << SMOKEMAX_RK_TIME_BEGIN << std::endl;
    sout << "rk_time_end = " << SMOKEMAX_RK_TIME_END << std::endl;
    sout << "rk45_time_step_size = " << SMOKEMAX_RK45_TIME_STEP_SIZE << std::endl;
    sout << "rk45_desired_tol = " << SMOKEMAX_RK45_DESIRED_TOL << std::endl;
    sout << "cfl_factor = " << SMOKEMAX_CFL_FACTOR << std::endl;
    sout << "io_output_freq = " << SMOKEMAX_IO_OUTPUT_FREQ << std::endl;
    sout << "time_step_output_freq = " << SMOKEMAX_TIME_STEP_OUTPUT_FREQ
         << std::endl;
    sout << "checkpt_freq = " << SMOKEMAX_CHECKPT_FREQ << std::endl;
    sout << "restore_solver = " << SMOKEMAX_RESTORE_SOLVER << std::endl;
    sout << "dendro_grain_sz = " << SMOKEMAX_DENDRO_GRAIN_SZ << std::endl;
    sout << "dendro_amr_fac = " << SMOKEMAX_DENDRO_AMR_FAC << std::endl;
    sout << "load_imb_tol = " << SMOKEMAX_LOAD_IMB_TOL << std::endl;
    sout << "async_comm_k = " << SMOKEMAX_ASYNC_COMM_K << std::endl;
    sout << "init_grid_iter = " << SMOKEMAX_INIT_GRID_ITER << std::endl;
    sout << "remesh_test_freq = " << SMOKEMAX_REMESH_TEST_FREQ << std::endl;
    sout << "num_refine_vars = " << SMOKEMAX_NUM_REFINE_VARS << std::endl;

    sout << "\n[refinement]" << std::endl;
    sout << "mode = " << static_cast<unsigned int>(SMOKEMAX_REFINEMENT_MODE)
         << "   # 0=WAMR 1=EH 2=EH_WAMR 3=BH_LOC 4=BH_WAMR" << std::endl;
    sout << "wavelet_tol = " << SMOKEMAX_WAVELET_TOL << std::endl;
    sout << "wavelet_tol_max = " << SMOKEMAX_WAVELET_TOL_MAX << std::endl;
    sout << "use_wavelet_tol_function = " << SMOKEMAX_USE_WAVELET_TOL_FUNCTION
         << std::endl;
    sout << "wavelet_tol_function_r0 = " << SMOKEMAX_WAVELET_TOL_FUNCTION_R0
         << std::endl;
    sout << "wavelet_tol_function_r1 = " << SMOKEMAX_WAVELET_TOL_FUNCTION_R1
         << std::endl;
    sout << "amr_r_ratio = " << SMOKEMAX_AMR_R_RATIO << std::endl;

    sout << "\n[dissipation]" << std::endl;
    sout << "ko_diss_sigma = " << KO_DISS_SIGMA << std::endl;
    sout << "use_const_ko = " << USE_CONST_KO << std::endl;
    sout << "dissipation_type = " << DISSIPATION_TYPE << std::endl;

    sout << "\n[derivatives]" << std::endl;
    sout << "type_first = \"" << SMOKEMAX_DERIVTYPE_FIRST << "\"" << std::endl;
    sout << "type_second = \"" << SMOKEMAX_DERIVTYPE_SECOND << "\"" << std::endl;
    sout << "use_fused_stencils = "
         << (SMOKEMAX_USE_FUSED_STENCILS ? "true" : "false") << std::endl;

    // [physics]: generated from the equation config's ParameterVariables, so a
    // system's own parameters appear here without touching this template.
    sout << "\n[physics]" << std::endl;
    sout << "chi_floor = " << CHI_FLOOR << std::endl;

    sout << "\n[initial_data]" << std::endl;
    sout << "id_type = " << SMOKEMAX_ID_TYPE;
    sout << std::endl;

    for (int b = 0; b < 2; ++b) {
        const double cr =
            (b == 0) ? SMOKEMAX_BH1_CONSTRAINT_R : SMOKEMAX_BH2_CONSTRAINT_R;
        sout << "\n[bh" << (b + 1) << "]" << std::endl;
        sout << "loc = [" << SMOKEMAX_BH_LOC[b].x() << ", "
             << SMOKEMAX_BH_LOC[b].y() << ", "
             << SMOKEMAX_BH_LOC[b].z() << "]" << std::endl;
        sout << "max_lev = "
             << ((b == 0) ? SMOKEMAX_BH1_MAX_LEV : SMOKEMAX_BH2_MAX_LEV)
             << std::endl;
        sout << "amr_r = "
             << ((b == 0) ? SMOKEMAX_BH1_AMR_R : SMOKEMAX_BH2_AMR_R)
             << std::endl;
        sout << "constraint_r = " << cr;
        if (cr <= 0.0)
            sout << "   # 0 = norms include the puncture; BSSN uses 1.0, so rms"
                    " is not comparable to a BSSN log";
        sout << std::endl;
    }

    sout << "\n# ==== end parameter dump ====" << std::endl;
    sout << std::setprecision(old_prec);
}

}  // namespace smokemax
