/**
 * @file physcon.cpp
 * @brief Constraint evaluation for the smokemax solver.
 *
 * Generated by dendrosym. Safe to edit -- only gencode/*.cpp.inc files
 * get regenerated when equations change.
 *
 * Computes constraint variables (Hamiltonian, momentum, etc.) from the
 * evolution variables. Same block-dispatch + derivative workspace pattern
 * as rhs.cpp.
 */

#include "physcon.h"
#include "parameters.h"
#include "profile_params.h"
#include "block_geometry.h"

using namespace std;
using namespace smokemax;

// -------------------------------------------------------------------------
// block-level dispatch
// -------------------------------------------------------------------------

void smokemaxConstraints(double **uzipConsVars, const double **uZipVars,
                     const ot::Block *blkList, unsigned int numBlocks) {

    const Point pt_min(smokemax::SMOKEMAX_COMPD_MIN[0],
                       smokemax::SMOKEMAX_COMPD_MIN[1],
                       smokemax::SMOKEMAX_COMPD_MIN[2]);
    const Point pt_max(smokemax::SMOKEMAX_COMPD_MAX[0],
                       smokemax::SMOKEMAX_COMPD_MAX[1],
                       smokemax::SMOKEMAX_COMPD_MAX[2]);
    const Point oct_min(smokemax::SMOKEMAX_OCTREE_MIN[0],
                        smokemax::SMOKEMAX_OCTREE_MIN[1],
                        smokemax::SMOKEMAX_OCTREE_MIN[2]);
    const Point oct_max(smokemax::SMOKEMAX_OCTREE_MAX[0],
                        smokemax::SMOKEMAX_OCTREE_MAX[1],
                        smokemax::SMOKEMAX_OCTREE_MAX[2]);

    // ot::BlockGeometryRange yields per-block offset/sz/bflag/dx/ptmin/ptmax and
    // hoists the grid->physical scaling out of the per-block loop.
    for (const auto &b : ot::BlockGeometryRange(blkList, numBlocks, pt_min,
                                                pt_max, oct_min, oct_max))
        smokemaxphyscon(uzipConsVars, uZipVars, b.offset, b.ptmin,
                                  b.ptmax, b.sz, b.bflag);
}

// -------------------------------------------------------------------------
// per-block constraint computation
// -------------------------------------------------------------------------

// derivative-workspace struct (grouped buffers + self-sizing bind/count)
#include "../gencode/smokemax_constraint_deriv_struct.cpp.inc"

void smokemaxphyscon(double **unzipConsVars, const double **uZipVars,
                 const unsigned int &offset, const double *pmin,
                 const double *pmax, const unsigned int *sz,
                 const unsigned int &bflag) {

    // evolution variables (read)
        struct {
        const double *alpha;
        const double *chi;
        const double *trK;
        const double *beta0;
        const double *beta1;
        const double *beta2;
        const double *Gt0;
        const double *Gt1;
        const double *Gt2;
        const double *B0;
        const double *B1;
        const double *B2;
        const double *At00;
        const double *At01;
        const double *At02;
        const double *At11;
        const double *At12;
        const double *At22;
        const double *gt00;
        const double *gt01;
        const double *gt02;
        const double *gt11;
        const double *gt12;
        const double *gt22;
    } in;
    in.alpha = &uZipVars[VAR::U_ALPHA][offset];
    in.chi = &uZipVars[VAR::U_CHI][offset];
    in.trK = &uZipVars[VAR::U_TRK][offset];
    in.beta0 = &uZipVars[VAR::U_BETA0][offset];
    in.beta1 = &uZipVars[VAR::U_BETA1][offset];
    in.beta2 = &uZipVars[VAR::U_BETA2][offset];
    in.Gt0 = &uZipVars[VAR::U_GT0][offset];
    in.Gt1 = &uZipVars[VAR::U_GT1][offset];
    in.Gt2 = &uZipVars[VAR::U_GT2][offset];
    in.B0 = &uZipVars[VAR::U_B0][offset];
    in.B1 = &uZipVars[VAR::U_B1][offset];
    in.B2 = &uZipVars[VAR::U_B2][offset];
    in.At00 = &uZipVars[VAR::U_AT00][offset];
    in.At01 = &uZipVars[VAR::U_AT01][offset];
    in.At02 = &uZipVars[VAR::U_AT02][offset];
    in.At11 = &uZipVars[VAR::U_AT11][offset];
    in.At12 = &uZipVars[VAR::U_AT12][offset];
    in.At22 = &uZipVars[VAR::U_AT22][offset];
    in.gt00 = &uZipVars[VAR::U_GT00][offset];
    in.gt01 = &uZipVars[VAR::U_GT01][offset];
    in.gt02 = &uZipVars[VAR::U_GT02][offset];
    in.gt11 = &uZipVars[VAR::U_GT11][offset];
    in.gt12 = &uZipVars[VAR::U_GT12][offset];
    in.gt22 = &uZipVars[VAR::U_GT22][offset];


    // constraint output variables (write)
        struct {
        double *ham;
        double *mom0;
        double *mom1;
        double *mom2;
        double *psi4_real;
        double *psi4_imag;
    } out;
    out.ham = &unzipConsVars[VAR_CONSTRAINT::C_HAM][offset];
    out.mom0 = &unzipConsVars[VAR_CONSTRAINT::C_MOM0][offset];
    out.mom1 = &unzipConsVars[VAR_CONSTRAINT::C_MOM1][offset];
    out.mom2 = &unzipConsVars[VAR_CONSTRAINT::C_MOM2][offset];
    out.psi4_real = &unzipConsVars[VAR_CONSTRAINT::C_PSI4_REAL][offset];
    out.psi4_imag = &unzipConsVars[VAR_CONSTRAINT::C_PSI4_IMAG][offset];


    const unsigned int nx = sz[0];
    const unsigned int ny = sz[1];
    const unsigned int nz = sz[2];

    const double hx = (pmax[0] - pmin[0]) / (nx - 1);
    const double hy = (pmax[1] - pmin[1]) / (ny - 1);
    const double hz = (pmax[2] - pmin[2]) / (nz - 1);

    

    const unsigned int PW = smokemax::SMOKEMAX_PADDING_WIDTH;
    unsigned int n = sz[0] * sz[1] * sz[2];
    const unsigned int BLK_SZ = n;
    double *const deriv_base = smokemax::SMOKEMAX_DERIV_WORKSPACE;

    auto &SOLVER_DERIVS = *smokemax::SMOKEMAX_DERIVS;

    // derivative computation for constraints
    smokemax_constraint_derivs_t d;
    d.bind(deriv_base, BLK_SZ);

    // intermediate (compound-expression) derivatives: materialize the compound
    // into a staged d.* buffer before deriv_calc differentiates it.
#include "../gencode/smokemax_constraint_intermediate_grad.cpp.inc"

#include "../gencode/smokemax_constraint_deriv_calc.cpp.inc"

    // main constraint computation loop
    for (unsigned int k = PW; k < nz - PW; k++) {
        for (unsigned int j = PW; j < ny - PW; j++) {
            for (unsigned int i = PW; i < nx - PW; i++) {
                const double x = pmin[0] + i * hx;
                const double y = pmin[1] + j * hy;
                const double z = pmin[2] + k * hz;

                const unsigned int pp = i + nx * (j + ny * k);

#include "../gencode/smokemax_constraint_rhs_eqns.cpp.inc"
            }
        }
    }

    // cleanup
#include "../gencode/smokemax_constraint_intermediate_grad_dealloc.cpp.inc"

#include "../gencode/smokemax_constraint_deriv_memdealloc.cpp.inc"
}
