/**
 * @file rhs.cpp
 * @brief RHS computation for the smokemax solver.
 *
 * Generated by dendrosym. Safe to edit -- only gencode/*.cpp.inc files
 * get regenerated when equations change.
 *
 * Layout:
 *   1. Block-level dispatch (smokemaxRHS)
 *   2. Per-block RHS (smokemaxrhs)
 *      - variable extraction (pointers into unzipped arrays)
 *      - parameter extraction (local copies of global params)
 *      - derivative workspace + stencil computation
 *      - main RHS equation loop (the generated code)
 *      - boundary conditions (Sommerfeld radiation)
 *      - KO dissipation / filtering
 *   3. Boundary condition implementation
 */

#include "rhs.h"
#include "parameters.h"
#include "profile_params.h"
#include "block_geometry.h"

using namespace std;
using namespace smokemax;

// -------------------------------------------------------------------------
// block-level dispatch -- iterates over octree blocks and calls per-block rhs
// -------------------------------------------------------------------------

void smokemaxRHS(double **uzipVarsRHS, const double **uZipVars,
             const ot::Block *blkList, unsigned int numBlocks,
             const double curr_time, const double **uZipConstVars) {

    const Point pt_min(smokemax::SMOKEMAX_COMPD_MIN[0],
                       smokemax::SMOKEMAX_COMPD_MIN[1],
                       smokemax::SMOKEMAX_COMPD_MIN[2]);
    const Point pt_max(smokemax::SMOKEMAX_COMPD_MAX[0],
                       smokemax::SMOKEMAX_COMPD_MAX[1],
                       smokemax::SMOKEMAX_COMPD_MAX[2]);
    const Point oct_min(smokemax::SMOKEMAX_OCTREE_MIN[0],
                        smokemax::SMOKEMAX_OCTREE_MIN[1],
                        smokemax::SMOKEMAX_OCTREE_MIN[2]);
    const Point oct_max(smokemax::SMOKEMAX_OCTREE_MAX[0],
                        smokemax::SMOKEMAX_OCTREE_MAX[1],
                        smokemax::SMOKEMAX_OCTREE_MAX[2]);

    // ot::BlockGeometryRange yields per-block offset/sz/bflag/dx/ptmin/ptmax and
    // hoists the grid->physical scaling out of the per-block loop.
    for (const auto &b : ot::BlockGeometryRange(blkList, numBlocks, pt_min,
                                                pt_max, oct_min, oct_max))
        smokemaxrhs(uzipVarsRHS, (const double **)uZipVars, b.offset,
                b.ptmin, b.ptmax, b.sz, b.bflag, curr_time,
                (const double **)uZipConstVars);
}

// -------------------------------------------------------------------------
// per-block rhs -- this is where the actual computation happens
// -------------------------------------------------------------------------

// derivative-workspace struct (grouped buffers + self-sizing bind/count)
#include "../gencode/smokemax_evolution_deriv_struct.cpp.inc"

void smokemaxrhs(double **unzipVarsRHS, const double **uZipVars,
             const unsigned int &offset, const double *pmin, const double *pmax,
             const unsigned int *sz, const unsigned int &bflag, const double t,
             const double **uZipConstVars) {

    // -- variable extraction --
    // const pointers into the unzipped arrays for this block.
    // each pointer (alpha, chi, gt00, ...) starts at `offset` into
    // the global unzipped array. rhs pointers are where we write output.
        struct {
        const double *alpha;
        const double *chi;
        const double *trK;
        const double *beta0;
        const double *beta1;
        const double *beta2;
        const double *Gt0;
        const double *Gt1;
        const double *Gt2;
        const double *B0;
        const double *B1;
        const double *B2;
        const double *At00;
        const double *At01;
        const double *At02;
        const double *At11;
        const double *At12;
        const double *At22;
        const double *gt00;
        const double *gt01;
        const double *gt02;
        const double *gt11;
        const double *gt12;
        const double *gt22;
    } in;
    in.alpha = &uZipVars[VAR::U_ALPHA][offset];
    in.chi = &uZipVars[VAR::U_CHI][offset];
    in.trK = &uZipVars[VAR::U_TRK][offset];
    in.beta0 = &uZipVars[VAR::U_BETA0][offset];
    in.beta1 = &uZipVars[VAR::U_BETA1][offset];
    in.beta2 = &uZipVars[VAR::U_BETA2][offset];
    in.Gt0 = &uZipVars[VAR::U_GT0][offset];
    in.Gt1 = &uZipVars[VAR::U_GT1][offset];
    in.Gt2 = &uZipVars[VAR::U_GT2][offset];
    in.B0 = &uZipVars[VAR::U_B0][offset];
    in.B1 = &uZipVars[VAR::U_B1][offset];
    in.B2 = &uZipVars[VAR::U_B2][offset];
    in.At00 = &uZipVars[VAR::U_AT00][offset];
    in.At01 = &uZipVars[VAR::U_AT01][offset];
    in.At02 = &uZipVars[VAR::U_AT02][offset];
    in.At11 = &uZipVars[VAR::U_AT11][offset];
    in.At12 = &uZipVars[VAR::U_AT12][offset];
    in.At22 = &uZipVars[VAR::U_AT22][offset];
    in.gt00 = &uZipVars[VAR::U_GT00][offset];
    in.gt01 = &uZipVars[VAR::U_GT01][offset];
    in.gt02 = &uZipVars[VAR::U_GT02][offset];
    in.gt11 = &uZipVars[VAR::U_GT11][offset];
    in.gt12 = &uZipVars[VAR::U_GT12][offset];
    in.gt22 = &uZipVars[VAR::U_GT22][offset];


        struct {
        double *alpha;
        double *chi;
        double *trK;
        double *beta0;
        double *beta1;
        double *beta2;
        double *Gt0;
        double *Gt1;
        double *Gt2;
        double *B0;
        double *B1;
        double *B2;
        double *At00;
        double *At01;
        double *At02;
        double *At11;
        double *At12;
        double *At22;
        double *gt00;
        double *gt01;
        double *gt02;
        double *gt11;
        double *gt12;
        double *gt22;
    } out;
    out.alpha = &unzipVarsRHS[VAR::U_ALPHA][offset];
    out.chi = &unzipVarsRHS[VAR::U_CHI][offset];
    out.trK = &unzipVarsRHS[VAR::U_TRK][offset];
    out.beta0 = &unzipVarsRHS[VAR::U_BETA0][offset];
    out.beta1 = &unzipVarsRHS[VAR::U_BETA1][offset];
    out.beta2 = &unzipVarsRHS[VAR::U_BETA2][offset];
    out.Gt0 = &unzipVarsRHS[VAR::U_GT0][offset];
    out.Gt1 = &unzipVarsRHS[VAR::U_GT1][offset];
    out.Gt2 = &unzipVarsRHS[VAR::U_GT2][offset];
    out.B0 = &unzipVarsRHS[VAR::U_B0][offset];
    out.B1 = &unzipVarsRHS[VAR::U_B1][offset];
    out.B2 = &unzipVarsRHS[VAR::U_B2][offset];
    out.At00 = &unzipVarsRHS[VAR::U_AT00][offset];
    out.At01 = &unzipVarsRHS[VAR::U_AT01][offset];
    out.At02 = &unzipVarsRHS[VAR::U_AT02][offset];
    out.At11 = &unzipVarsRHS[VAR::U_AT11][offset];
    out.At12 = &unzipVarsRHS[VAR::U_AT12][offset];
    out.At22 = &unzipVarsRHS[VAR::U_AT22][offset];
    out.gt00 = &unzipVarsRHS[VAR::U_GT00][offset];
    out.gt01 = &unzipVarsRHS[VAR::U_GT01][offset];
    out.gt02 = &unzipVarsRHS[VAR::U_GT02][offset];
    out.gt11 = &unzipVarsRHS[VAR::U_GT11][offset];
    out.gt12 = &unzipVarsRHS[VAR::U_GT12][offset];
    out.gt22 = &unzipVarsRHS[VAR::U_GT22][offset];


    mem::memory_pool<double> *__mem_pool = &SMOKEMAX_MEM_POOL;

    const unsigned int nx = sz[0];
    const unsigned int ny = sz[1];
    const unsigned int nz = sz[2];

    const double hx = (pmax[0] - pmin[0]) / (nx - 1);
    const double hy = (pmax[1] - pmin[1]) / (ny - 1);
    const double hz = (pmax[2] - pmin[2]) / (nz - 1);

    // -- parameters --
    

    int idx[3];
    const unsigned int PW = smokemax::SMOKEMAX_PADDING_WIDTH;
    unsigned int n = sz[0] * sz[1] * sz[2];

    smokemax::timer::t_deriv.start();

    const unsigned int BLK_SZ = n;
    const unsigned int bytes = n * sizeof(double);

    // derivative workspace -- one big allocation that holds all precomputed
    // derivative arrays. each alpha_x etc. is a pointer at offset N*BLK_SZ.
    double *const deriv_base = smokemax::SMOKEMAX_DERIV_WORKSPACE;

    // configurable derivative object (replaces old per-order derivs.cpp)
    auto &SOLVER_DERIVS = *smokemax::SMOKEMAX_DERIVS;

    // -- standard derivative computation --
    // d.bind() carves the workspace into named buffers (d.alpha_x, d.alpha_xy, ...).
    smokemax_evolution_derivs_t d;
    d.bind(deriv_base, BLK_SZ);

    // -- intermediate (compound-expression) derivatives --
    // when equations differentiate a compound expression (e.g. d(chi*gt)), the
    // compound is materialized once into a staged d.* buffer here; deriv_calc
    // below then differentiates it alongside the ordinary derivatives.
#include "../gencode/smokemax_evolution_intermediate_grad.cpp.inc"

    // deriv_calc fills the derivative buffers with the finite-difference stencils
    // (including the staged derivatives of the intermediate buffers above).
#include "../gencode/smokemax_evolution_deriv_calc.cpp.inc"

    smokemax::timer::t_deriv.stop();

    // -- main rhs loop --
    // this is where the generated equations live. the included file has
    // all the CSE-optimized code with DENDRO_nnnn temporaries.
    smokemax::timer::t_rhs.start();
    for (unsigned int k = PW; k < nz - PW; k++) {
        for (unsigned int j = PW; j < ny - PW; j++) {
            for (unsigned int i = PW; i < nx - PW; i++) {
                const double x = pmin[0] + i * hx;
                const double y = pmin[1] + j * hy;
                const double z = pmin[2] + k * hz;

                const unsigned int pp = i + nx * (j + ny * k);
                const double r_coord = sqrt(x * x + y * y + z * z);

#include "../gencode/smokemax_evolution_rhs_eqns.cpp.inc"
            }
        }
    }
    smokemax::timer::t_rhs.stop();

    // -- deallocate intermediate derivatives --
#include "../gencode/smokemax_evolution_intermediate_grad_dealloc.cpp.inc"

    // -- boundary conditions --
    // sommerfeld radiation bcs: each variable gets an outgoing-wave condition
    // with a specified falloff rate and asymptotic value.
    if (bflag != 0) {
        smokemax::timer::t_bdyc.start();
            // per-variable sommerfeld bc data: {rhs, field, dx, dy, dz, falloff, asymptotic}
    struct __bc_row {
        double *rhs;
        const double *f, *gx, *gy, *gz;
        double falloff, asymptotic;
    };
    const __bc_row __bc_rows[] = {
        {out.alpha, in.alpha, d.alpha_x, d.alpha_y, d.alpha_z, 1.0, 0.0},
        {out.chi, in.chi, d.chi_x, d.chi_y, d.chi_z, 1.0, 0.0},
        {out.trK, in.trK, d.trK_x, d.trK_y, d.trK_z, 1.0, 0.0},
        {out.beta0, in.beta0, d.beta0_x, d.beta0_y, d.beta0_z, 1.0, 0.0},
        {out.beta1, in.beta1, d.beta1_x, d.beta1_y, d.beta1_z, 1.0, 0.0},
        {out.beta2, in.beta2, d.beta2_x, d.beta2_y, d.beta2_z, 1.0, 0.0},
        {out.Gt0, in.Gt0, d.Gt0_x, d.Gt0_y, d.Gt0_z, 1.0, 0.0},
        {out.Gt1, in.Gt1, d.Gt1_x, d.Gt1_y, d.Gt1_z, 1.0, 0.0},
        {out.Gt2, in.Gt2, d.Gt2_x, d.Gt2_y, d.Gt2_z, 1.0, 0.0},
        {out.B0, in.B0, d.B0_x, d.B0_y, d.B0_z, 1.0, 0.0},
        {out.B1, in.B1, d.B1_x, d.B1_y, d.B1_z, 1.0, 0.0},
        {out.B2, in.B2, d.B2_x, d.B2_y, d.B2_z, 1.0, 0.0},
        {out.At00, in.At00, d.At00_x, d.At00_y, d.At00_z, 1.0, 0.0},
        {out.At01, in.At01, d.At01_x, d.At01_y, d.At01_z, 1.0, 0.0},
        {out.At02, in.At02, d.At02_x, d.At02_y, d.At02_z, 1.0, 0.0},
        {out.At11, in.At11, d.At11_x, d.At11_y, d.At11_z, 1.0, 0.0},
        {out.At12, in.At12, d.At12_x, d.At12_y, d.At12_z, 1.0, 0.0},
        {out.At22, in.At22, d.At22_x, d.At22_y, d.At22_z, 1.0, 0.0},
        {out.gt00, in.gt00, d.gt00_x, d.gt00_y, d.gt00_z, 1.0, 0.0},
        {out.gt01, in.gt01, d.gt01_x, d.gt01_y, d.gt01_z, 1.0, 0.0},
        {out.gt02, in.gt02, d.gt02_x, d.gt02_y, d.gt02_z, 1.0, 0.0},
        {out.gt11, in.gt11, d.gt11_x, d.gt11_y, d.gt11_z, 1.0, 0.0},
        {out.gt12, in.gt12, d.gt12_x, d.gt12_y, d.gt12_z, 1.0, 0.0},
        {out.gt22, in.gt22, d.gt22_x, d.gt22_y, d.gt22_z, 1.0, 0.0},
    };
    for (const auto &__r : __bc_rows)
        smokemax_bcs(__r.rhs, __r.f, __r.gx, __r.gy, __r.gz, pmin, pmax, __r.falloff, __r.asymptotic, sz, bflag);

        smokemax::timer::t_bdyc.stop();
    }

    // -- kreiss-oliger dissipation --
    // adds numerical dissipation to damp high-frequency noise.
    // using the DendroDerivatives filter api -- handles ko internally
    if (!SOLVER_DERIVS.do_filter_before()) {
        smokemax::timer::t_ko.start();
        const double sigma = KO_DISS_SIGMA;

        // per-variable ko filter inputs: {field, rhs, dx, dy, dz}
        struct __ko_row {
            const double *u;
            double *u_rhs;
            double *gx, *gy, *gz;
        };
        const __ko_row __ko_rows[] = {
            { in.alpha, out.alpha, d.alpha_x, d.alpha_y, d.alpha_z },
            { in.chi, out.chi, d.chi_x, d.chi_y, d.chi_z },
            { in.trK, out.trK, d.trK_x, d.trK_y, d.trK_z },
            { in.beta0, out.beta0, d.beta0_x, d.beta0_y, d.beta0_z },
            { in.beta1, out.beta1, d.beta1_x, d.beta1_y, d.beta1_z },
            { in.beta2, out.beta2, d.beta2_x, d.beta2_y, d.beta2_z },
            { in.Gt0, out.Gt0, d.Gt0_x, d.Gt0_y, d.Gt0_z },
            { in.Gt1, out.Gt1, d.Gt1_x, d.Gt1_y, d.Gt1_z },
            { in.Gt2, out.Gt2, d.Gt2_x, d.Gt2_y, d.Gt2_z },
            { in.B0, out.B0, d.B0_x, d.B0_y, d.B0_z },
            { in.B1, out.B1, d.B1_x, d.B1_y, d.B1_z },
            { in.B2, out.B2, d.B2_x, d.B2_y, d.B2_z },
            { in.At00, out.At00, d.At00_x, d.At00_y, d.At00_z },
            { in.At01, out.At01, d.At01_x, d.At01_y, d.At01_z },
            { in.At02, out.At02, d.At02_x, d.At02_y, d.At02_z },
            { in.At11, out.At11, d.At11_x, d.At11_y, d.At11_z },
            { in.At12, out.At12, d.At12_x, d.At12_y, d.At12_z },
            { in.At22, out.At22, d.At22_x, d.At22_y, d.At22_z },
            { in.gt00, out.gt00, d.gt00_x, d.gt00_y, d.gt00_z },
            { in.gt01, out.gt01, d.gt01_x, d.gt01_y, d.gt01_z },
            { in.gt02, out.gt02, d.gt02_x, d.gt02_y, d.gt02_z },
            { in.gt11, out.gt11, d.gt11_x, d.gt11_y, d.gt11_z },
            { in.gt12, out.gt12, d.gt12_x, d.gt12_y, d.gt12_z },
            { in.gt22, out.gt22, d.gt22_x, d.gt22_y, d.gt22_z },
        };
        for (const auto &__r : __ko_rows)
            SOLVER_DERIVS.filter(__r.u, __r.u_rhs, __r.gx, __r.gy, __r.gz,
                                   hx, hy, hz, sigma, sz, bflag);
        smokemax::timer::t_ko.stop();
    }

    // -- deallocate standard derivatives --
    smokemax::timer::t_deriv.start();
#include "../gencode/smokemax_evolution_deriv_memdealloc.cpp.inc"
    smokemax::timer::t_deriv.stop();
}

// -------------------------------------------------------------------------
// sommerfeld radiation boundary conditions
//
// applies an outgoing-wave condition at domain boundaries:
//   f_rhs = -(1/r)(x*dxf + y*dyf + z*dzf + falloff*(f - f_asymptotic))
//
// each variable has its own falloff rate and asymptotic value, set by
// the config's set_bhs_falloff_and_asymptotic() call.
// -------------------------------------------------------------------------

void smokemax_bcs(double *f_rhs, const double *f,
              const double *dxf, const double *dyf, const double *dzf,
              const double *pmin, const double *pmax,
              const double f_falloff, const double f_asymptotic,
              const unsigned int *sz, const unsigned int &bflag) {

    const unsigned int nx = sz[0];
    const unsigned int ny = sz[1];
    const unsigned int nz = sz[2];

    double hx = (pmax[0] - pmin[0]) / (nx - 1);
    double hy = (pmax[1] - pmin[1]) / (ny - 1);
    double hz = (pmax[2] - pmin[2]) / (nz - 1);

    const unsigned int PW = smokemax::SMOKEMAX_PADDING_WIDTH;

    unsigned int ib = PW;
    unsigned int jb = PW;
    unsigned int kb = PW;
    unsigned int ie = nx - PW;
    unsigned int je = ny - PW;
    unsigned int ke = nz - PW;

    double x, y, z;
    unsigned int pp;
    double inv_r;

    // apply on each boundary face that's flagged
    if (bflag & (1u << OCT_DIR_LEFT)) {
        for (unsigned int k = kb; k < ke; k++) {
            z = pmin[2] + k * hz;
            for (unsigned int j = jb; j < je; j++) {
                y = pmin[1] + j * hy;
                for (unsigned int i = ib; i < ib + PW; i++) {
                    x = pmin[0] + i * hx;
                    pp = i + nx * (j + ny * k);
                    inv_r = 1.0 / sqrt(x * x + y * y + z * z);
                    f_rhs[pp] = -inv_r * (x * dxf[pp] + y * dyf[pp] + z * dzf[pp]
                                + f_falloff * (f[pp] - f_asymptotic));
                }
            }
        }
    }

    if (bflag & (1u << OCT_DIR_RIGHT)) {
        for (unsigned int k = kb; k < ke; k++) {
            z = pmin[2] + k * hz;
            for (unsigned int j = jb; j < je; j++) {
                y = pmin[1] + j * hy;
                for (unsigned int i = ie - PW; i < ie; i++) {
                    x = pmin[0] + i * hx;
                    pp = i + nx * (j + ny * k);
                    inv_r = 1.0 / sqrt(x * x + y * y + z * z);
                    f_rhs[pp] = -inv_r * (x * dxf[pp] + y * dyf[pp] + z * dzf[pp]
                                + f_falloff * (f[pp] - f_asymptotic));
                }
            }
        }
    }

    if (bflag & (1u << OCT_DIR_DOWN)) {
        for (unsigned int k = kb; k < ke; k++) {
            z = pmin[2] + k * hz;
            for (unsigned int j = jb; j < jb + PW; j++) {
                y = pmin[1] + j * hy;
                for (unsigned int i = ib; i < ie; i++) {
                    x = pmin[0] + i * hx;
                    pp = i + nx * (j + ny * k);
                    inv_r = 1.0 / sqrt(x * x + y * y + z * z);
                    f_rhs[pp] = -inv_r * (x * dxf[pp] + y * dyf[pp] + z * dzf[pp]
                                + f_falloff * (f[pp] - f_asymptotic));
                }
            }
        }
    }

    if (bflag & (1u << OCT_DIR_UP)) {
        for (unsigned int k = kb; k < ke; k++) {
            z = pmin[2] + k * hz;
            for (unsigned int j = je - PW; j < je; j++) {
                y = pmin[1] + j * hy;
                for (unsigned int i = ib; i < ie; i++) {
                    x = pmin[0] + i * hx;
                    pp = i + nx * (j + ny * k);
                    inv_r = 1.0 / sqrt(x * x + y * y + z * z);
                    f_rhs[pp] = -inv_r * (x * dxf[pp] + y * dyf[pp] + z * dzf[pp]
                                + f_falloff * (f[pp] - f_asymptotic));
                }
            }
        }
    }

    if (bflag & (1u << OCT_DIR_BACK)) {
        for (unsigned int k = kb; k < kb + PW; k++) {
            z = pmin[2] + k * hz;
            for (unsigned int j = jb; j < je; j++) {
                y = pmin[1] + j * hy;
                for (unsigned int i = ib; i < ie; i++) {
                    x = pmin[0] + i * hx;
                    pp = i + nx * (j + ny * k);
                    inv_r = 1.0 / sqrt(x * x + y * y + z * z);
                    f_rhs[pp] = -inv_r * (x * dxf[pp] + y * dyf[pp] + z * dzf[pp]
                                + f_falloff * (f[pp] - f_asymptotic));
                }
            }
        }
    }

    if (bflag & (1u << OCT_DIR_FRONT)) {
        for (unsigned int k = ke - PW; k < ke; k++) {
            z = pmin[2] + k * hz;
            for (unsigned int j = jb; j < je; j++) {
                y = pmin[1] + j * hy;
                for (unsigned int i = ib; i < ie; i++) {
                    x = pmin[0] + i * hx;
                    pp = i + nx * (j + ny * k);
                    inv_r = 1.0 / sqrt(x * x + y * y + z * z);
                    f_rhs[pp] = -inv_r * (x * dxf[pp] + y * dyf[pp] + z * dzf[pp]
                                + f_falloff * (f[pp] - f_asymptotic));
                }
            }
        }
    }
}

void freeze_bcs(double *f_rhs, const unsigned int *sz,
                const unsigned int &bflag) {
    const unsigned int nx = sz[0];
    const unsigned int ny = sz[1];
    const unsigned int nz = sz[2];
    const unsigned int PW = smokemax::SMOKEMAX_PADDING_WIDTH;

    unsigned int ib = PW, jb = PW, kb = PW;
    unsigned int ie = nx - PW, je = ny - PW, ke = nz - PW;

    // zero out rhs at each flagged boundary face
    if (bflag & (1u << OCT_DIR_LEFT))
        for (unsigned int k = kb; k < ke; k++)
            for (unsigned int j = jb; j < je; j++)
                for (unsigned int i = ib; i < ib + PW; i++)
                    f_rhs[i + nx * (j + ny * k)] = 0.0;

    if (bflag & (1u << OCT_DIR_RIGHT))
        for (unsigned int k = kb; k < ke; k++)
            for (unsigned int j = jb; j < je; j++)
                for (unsigned int i = ie - PW; i < ie; i++)
                    f_rhs[i + nx * (j + ny * k)] = 0.0;

    if (bflag & (1u << OCT_DIR_DOWN))
        for (unsigned int k = kb; k < ke; k++)
            for (unsigned int j = jb; j < jb + PW; j++)
                for (unsigned int i = ib; i < ie; i++)
                    f_rhs[i + nx * (j + ny * k)] = 0.0;

    if (bflag & (1u << OCT_DIR_UP))
        for (unsigned int k = kb; k < ke; k++)
            for (unsigned int j = je - PW; j < je; j++)
                for (unsigned int i = ib; i < ie; i++)
                    f_rhs[i + nx * (j + ny * k)] = 0.0;

    if (bflag & (1u << OCT_DIR_BACK))
        for (unsigned int k = kb; k < kb + PW; k++)
            for (unsigned int j = jb; j < je; j++)
                for (unsigned int i = ib; i < ie; i++)
                    f_rhs[i + nx * (j + ny * k)] = 0.0;

    if (bflag & (1u << OCT_DIR_FRONT))
        for (unsigned int k = ke - PW; k < ke; k++)
            for (unsigned int j = jb; j < je; j++)
                for (unsigned int i = ib; i < ie; i++)
                    f_rhs[i + nx * (j + ny * k)] = 0.0;
}
