/**
 * @file smokemaxCtx.cpp
 * @brief Solver context implementation for the smokemax solver.
 *
 * Generated by dendrosym. Safe to edit -- only gencode/*.cpp.inc files
 * get regenerated when equations change.
 *
 * Based on the EM4 solver context pattern from dendrolib.
 */

#include "smokemaxCtx.h"
#include "bh_refine.h"
#include "grUtils.h"
#include "TwoPunctures.h"
// TP_MPI_COMM is declared extern in the TP code
extern MPI_Comm TP_MPI_COMM;
#include "gw_extract.h"
#include "punctureTracker.h"

#include <cmath>
#include <iomanip>
#include <fstream>
#include <sstream>

#include "TreeNode.h"
#include "meshUtils.h"
#include "mathUtils.h"
#include "mesh.h"
#include "meshUtils.h"
#include "mpi.h"
#include "oct2vtk.h"
#include "oda.h"
#include "octUtils.h"
#include "point.h"

// checkpoint I/O primitives (dendrolib): binary octree + variable I/O, plus the
// nlohmann `json` alias (from checkPoint.h) used for the self-describing meta.
#include "checkPoint.h"
#include <filesystem>
#include "b91_util.h"  // base91 encode/decode for the compact BH-history blob

namespace smokemax {


// defined in grUtils.cpp
void initDataFuncToPhysCoords(const double xx, const double yy,
                              const double zz, double *var);

// =========================================================================
// constructor / destructor
// =========================================================================

SMOKEMAXCtx::SMOKEMAXCtx(ot::Mesh *pMesh)
    : ts::Ctx<SMOKEMAXCtx, DendroScalar, unsigned int>() {

    m_uiMesh = pMesh;

    // evolution variables
    m_var[VL::CPU_EV].create_vector(m_uiMesh, ot::DVEC_TYPE::OCT_SHARED_NODES,
        ot::DVEC_LOC::HOST, 24, true);
    m_var[VL::CPU_EV_UZ_IN].create_vector(m_uiMesh,
        ot::DVEC_TYPE::OCT_LOCAL_WITH_PADDING, ot::DVEC_LOC::HOST,
        24, true);
    m_var[VL::CPU_EV_UZ_OUT].create_vector(m_uiMesh,
        ot::DVEC_TYPE::OCT_LOCAL_WITH_PADDING, ot::DVEC_LOC::HOST,
        24, true);

    // constraint variables
    m_var[VL::CPU_CV].create_vector(m_uiMesh, ot::DVEC_TYPE::OCT_SHARED_NODES,
        ot::DVEC_LOC::HOST, 6, true);
    m_var[VL::CPU_CV_UZ_IN].create_vector(m_uiMesh,
        ot::DVEC_TYPE::OCT_LOCAL_WITH_PADDING, ot::DVEC_LOC::HOST,
        6, true);

    // analytical solution and difference vectors
    m_var[VL::CPU_ANALYTIC].create_vector(m_uiMesh, ot::DVEC_TYPE::OCT_SHARED_NODES,
        ot::DVEC_LOC::HOST, 24, true);
    m_var[VL::CPU_ANALYTIC_DIFF].create_vector(m_uiMesh, ot::DVEC_TYPE::OCT_SHARED_NODES,
        ot::DVEC_LOC::HOST, 24, true);

    m_uiBHLoc[0] = Point(SMOKEMAX_BH_LOC[0].x(),
                         SMOKEMAX_BH_LOC[0].y(),
                         SMOKEMAX_BH_LOC[0].z());
    m_uiBHLoc[1] = Point(SMOKEMAX_BH_LOC[1].x(),
                         SMOKEMAX_BH_LOC[1].y(),
                         SMOKEMAX_BH_LOC[1].z());
    m_bIsBHMerged = false;
    m_dMergeTime = std::numeric_limits<double>::max();
    m_uiMergeStep = std::numeric_limits<uint32_t>::max();
    m_bConstraintsComputed = false;
    m_uiWroteGridInfoHeader = false;

    // time stepping info
    m_uiTinfo._m_uiStep = 0;
    m_uiTinfo._m_uiT = 0;
    m_uiTinfo._m_uiTh = SMOKEMAX_RK45_TIME_STEP_SIZE;

    // allocate MPI communication context for async ghost exchange
    ot::alloc_mpi_ctx<DendroScalar>(m_uiMesh, m_mpi_ctx, 24,
                                     SMOKEMAX_ASYNC_COMM_K);
}

SMOKEMAXCtx::~SMOKEMAXCtx() {
    ot::dealloc_mpi_ctx<DendroScalar>(m_uiMesh, m_mpi_ctx, 24,
                                       SMOKEMAX_ASYNC_COMM_K);
    for (unsigned int i = 0; i < VL::END; i++) {
        m_var[i].destroy_vector();
    }
}

// =========================================================================
// initialization
// =========================================================================

int SMOKEMAXCtx::initialize() {
    if (SMOKEMAX_RESTORE_SOLVER) {
        // initialize() is called again from ets->init(); restore exactly once
        // so we don't re-read the checkpoint / rebuild the mesh a second time.
        if (!m_bCheckpointRestored) {
            restore_checkpt();
            m_bCheckpointRestored = true;
        }
        return 0;
    }

    init_grid();
    return 0;
}

int SMOKEMAXCtx::init_grid() {
    if (!m_uiMesh->isActive()) return 0;

    DVec &m_evar = m_var[VL::CPU_EV];

    const ot::TreeNode *pNodes = &(*(m_uiMesh->getAllElements().begin()));
    const unsigned int eleOrder = m_uiMesh->getElementOrder();
    const unsigned int *e2n_cg = &(*(m_uiMesh->getE2NMapping().begin()));
    const unsigned int *e2n_dg = &(*(m_uiMesh->getE2NMapping_DG().begin()));
    const unsigned int nPe = m_uiMesh->getNumNodesPerElement();
    const unsigned int nodeLocalBegin = m_uiMesh->getNodeLocalBegin();
    const unsigned int nodeLocalEnd = m_uiMesh->getNodeLocalEnd();

    DendroScalar *zipIn[24];
    m_evar.to_2d(zipIn);

    // two-punctures: do the elliptic solve first (collective, all ranks)
    double mp, mm, mp_adm, mm_adm, E, J1, J2, J3;
    double var1[24];
    if (SMOKEMAX_ID_TYPE == 0) {
        TP_MPI_COMM = m_uiMesh->getMPIGlobalCommunicator();
        TwoPunctures(0.0, 0.0, 0.0, var1, &mp, &mm, &mp_adm, &mm_adm,
                     &E, &J1, &J2, &J3);
    }

    for (unsigned int elem = m_uiMesh->getElementLocalBegin();
         elem < m_uiMesh->getElementLocalEnd(); elem++) {

        DendroScalar var[24];

        for (unsigned int k = 0; k < (eleOrder + 1); k++)
            for (unsigned int j = 0; j < (eleOrder + 1); j++)
                for (unsigned int i = 0; i < (eleOrder + 1); i++) {

                    const unsigned int nodeLookUp_CG =
                        e2n_cg[elem * nPe +
                               k * (eleOrder + 1) * (eleOrder + 1) +
                               j * (eleOrder + 1) + i];

                    if (nodeLookUp_CG >= nodeLocalBegin &&
                        nodeLookUp_CG < nodeLocalEnd) {

                        const unsigned int nodeLookUp_DG =
                            e2n_dg[elem * nPe +
                                   k * (eleOrder + 1) * (eleOrder + 1) +
                                   j * (eleOrder + 1) + i];

                        unsigned int ownerID, ii_x, jj_y, kk_z;
                        m_uiMesh->dg2eijk(nodeLookUp_DG, ownerID, ii_x, jj_y, kk_z);

                        const DendroScalar len =
                            (double)(1u << (m_uiMaxDepth - pNodes[ownerID].getLevel()));
                        const DendroScalar x =
                            pNodes[ownerID].getX() + ii_x * (len / eleOrder);
                        const DendroScalar y =
                            pNodes[ownerID].getY() + jj_y * (len / eleOrder);
                        const DendroScalar z =
                            pNodes[ownerID].getZ() + kk_z * (len / eleOrder);

                        if (SMOKEMAX_ID_TYPE == 0) {
                            // tp solver: interpolate the stored solution
                            TwoPunctures(
                                (double)GRIDX_TO_X(x), (double)GRIDY_TO_Y(y),
                                (double)GRIDZ_TO_Z(z), var,
                                &mp, &mm, &mp_adm, &mm_adm, &E, &J1, &J2, &J3);
                        } else {
                            initDataFuncToPhysCoords((double)x, (double)y, (double)z, var);
                        }

                        for (unsigned int v = 0; v < 24; v++)
                            zipIn[v][nodeLookUp_CG] = var[v];
                    }
                }
    }

    // enforce evolution constraints on initial data
    for (unsigned int node = nodeLocalBegin; node < nodeLocalEnd; node++) {
        enforce_smokemax_constraints(zipIn, node);
    }

    return 0;
}

// =========================================================================
// rhs -- unzip, call generated equations, zip back
// =========================================================================

int SMOKEMAXCtx::rhs(DVec *in, DVec *out, unsigned int sz,
                                DendroScalar time) {

    smokemax::timer::t_unzip_async.start();
    this->unzip(*in, m_var[VL::CPU_EV_UZ_IN], SMOKEMAX_ASYNC_COMM_K);
    smokemax::timer::t_unzip_async.stop();

    DendroScalar *unzipIn[24];
    DendroScalar *unzipOut[24];

    m_var[CPU_EV_UZ_IN].to_2d(unzipIn);
    m_var[CPU_EV_UZ_OUT].to_2d(unzipOut);

    const ot::Block *blkList = m_uiMesh->getLocalBlockList().data();
    const unsigned int numBlocks = m_uiMesh->getLocalBlockList().size();

    DendroScalar *unzipConsIn[6];
    m_var[CPU_CV_UZ_IN].to_2d(unzipConsIn);

    smokemaxRHS(
        unzipOut, (const double **)unzipIn,
        blkList, numBlocks, time,
        (const double **)unzipConsIn
    );

    smokemax::timer::t_zip.start();
    this->zip(m_var[CPU_EV_UZ_OUT], *out);
    smokemax::timer::t_zip.stop();

    return 0;
}

// =========================================================================
// stage / timestep hooks
// =========================================================================

int SMOKEMAXCtx::pre_stage(DVec &sIn) { return 0; }
// post_stage receives the RK stage derivative, not a state -- enforcement of
// algebraic constraints happens in post_timestep, which the ETS already calls
// on every intermediate stage state.
int SMOKEMAXCtx::post_stage(DVec &sIn) { return 0; }
int SMOKEMAXCtx::pre_timestep(DVec &sIn) { return 0; }

int SMOKEMAXCtx::post_timestep(DVec &sIn) {
    if (!m_uiMesh->isActive()) return 0;

    DendroScalar *zipIn[24];
    sIn.to_2d(zipIn);

    const unsigned int nodeLocalBegin = m_uiMesh->getNodeLocalBegin();
    const unsigned int nodeLocalEnd = m_uiMesh->getNodeLocalEnd();

    for (unsigned int node = nodeLocalBegin; node < nodeLocalEnd; node++) {
        enforce_smokemax_constraints(zipIn, node);
    }

    return 0;
}

int SMOKEMAXCtx::pre_stage_blk(DendroScalar *unzipIn,
    DendroScalar *unzipOut, unsigned int *blkIDs, unsigned int numBlocks,
    DendroScalar *blk_dx) { return 0; }

int SMOKEMAXCtx::post_stage_blk(DendroScalar *unzipIn,
    DendroScalar *unzipOut, unsigned int *blkIDs, unsigned int numBlocks,
    DendroScalar *blk_dx) { return 0; }

int SMOKEMAXCtx::post_timestep_blk(DendroScalar *unzipIn,
    DendroScalar *unzipOut, unsigned int *blkIDs, unsigned int numBlocks,
    DendroScalar *blk_dx) { return 0; }

// =========================================================================
// constraint computation
// =========================================================================

void SMOKEMAXCtx::compute_constraint_variables() {
    if (m_bConstraintsComputed) return;
    if (!m_uiMesh->isActive()) return;

    DVec &m_evar = m_var[VL::CPU_EV];

    this->unzip(m_evar, m_var[VL::CPU_EV_UZ_IN], SMOKEMAX_ASYNC_COMM_K);

    DendroScalar *unzipIn[24];
    DendroScalar *unzipConsOut[6];

    m_var[CPU_EV_UZ_IN].to_2d(unzipIn);
    m_var[CPU_CV_UZ_IN].to_2d(unzipConsOut);

    const ot::Block *blkList = m_uiMesh->getLocalBlockList().data();
    const unsigned int numBlocks = m_uiMesh->getLocalBlockList().size();

    smokemaxConstraints(unzipConsOut, (const double **)unzipIn,
                                  blkList, numBlocks);

    this->zip(m_var[CPU_CV_UZ_IN], m_var[VL::CPU_CV]);

    m_uiMesh->readFromGhostBegin(m_var[VL::CPU_CV].get_vec_ptr(),
                                  m_var[VL::CPU_CV].get_dof());
    m_uiMesh->readFromGhostEnd(m_var[VL::CPU_CV].get_vec_ptr(),
                                m_var[VL::CPU_CV].get_dof());

    m_bConstraintsComputed = true;
}

int SMOKEMAXCtx::extract_constraints() {
    // TODO: write constraint norms to file
    return 0;
}

// =========================================================================
// analytical solution comparison
//
// computes the analytical solution at each CG node and stores the
// pointwise difference in CPU_ANALYTIC_DIFF. operates on the zipped
// (CG) mesh directly, same pattern as init_grid.
// =========================================================================

void SMOKEMAXCtx::compute_analytical() {
    if (!m_uiMesh->isActive()) return;

    const ot::TreeNode *pNodes = &(*(m_uiMesh->getAllElements().begin()));
    const unsigned int eleOrder = m_uiMesh->getElementOrder();
    const unsigned int *e2n_cg = &(*(m_uiMesh->getE2NMapping().begin()));
    const unsigned int *e2n_dg = &(*(m_uiMesh->getE2NMapping_DG().begin()));
    const unsigned int nPe = m_uiMesh->getNumNodesPerElement();
    const unsigned int nodeLocalBegin = m_uiMesh->getNodeLocalBegin();
    const unsigned int nodeLocalEnd = m_uiMesh->getNodeLocalEnd();

    DendroScalar *evolVar[24];
    DendroScalar *analyticVar[24];
    DendroScalar *analyticDiffVar[24];

    m_var[VL::CPU_EV].to_2d(evolVar);
    m_var[VL::CPU_ANALYTIC].to_2d(analyticVar);
    m_var[VL::CPU_ANALYTIC_DIFF].to_2d(analyticDiffVar);

    const double time = m_uiTinfo._m_uiT;

    // iterate over all CG nodes (same loop structure as init_grid)
    for (unsigned int elem = m_uiMesh->getElementLocalBegin();
         elem < m_uiMesh->getElementLocalEnd(); elem++) {

        DendroScalar var_exact[24];

        for (unsigned int k = 0; k < (eleOrder + 1); k++)
            for (unsigned int j = 0; j < (eleOrder + 1); j++)
                for (unsigned int i = 0; i < (eleOrder + 1); i++) {

                    const unsigned int nodeLookUp_CG =
                        e2n_cg[elem * nPe +
                               k * (eleOrder + 1) * (eleOrder + 1) +
                               j * (eleOrder + 1) + i];

                    if (nodeLookUp_CG >= nodeLocalBegin &&
                        nodeLookUp_CG < nodeLocalEnd) {

                        const unsigned int nodeLookUp_DG =
                            e2n_dg[elem * nPe +
                                   k * (eleOrder + 1) * (eleOrder + 1) +
                                   j * (eleOrder + 1) + i];

                        unsigned int ownerID, ii_x, jj_y, kk_z;
                        m_uiMesh->dg2eijk(nodeLookUp_DG, ownerID, ii_x, jj_y, kk_z);

                        const DendroScalar len =
                            (double)(1u << (m_uiMaxDepth - pNodes[ownerID].getLevel()));
                        // octree coords
                        const DendroScalar ox =
                            pNodes[ownerID].getX() + ii_x * (len / eleOrder);
                        const DendroScalar oy =
                            pNodes[ownerID].getY() + jj_y * (len / eleOrder);
                        const DendroScalar oz =
                            pNodes[ownerID].getZ() + kk_z * (len / eleOrder);

                        // convert to physical coords
                        const double px = GRIDX_TO_X(ox);
                        const double py = GRIDY_TO_Y(oy);
                        const double pz = GRIDZ_TO_Z(oz);

                        analyticalSolution(px, py, pz, time, var_exact);

                        for (unsigned int v = 0; v < 24; v++) {
                            analyticVar[v][nodeLookUp_CG] = var_exact[v];
                            analyticDiffVar[v][nodeLookUp_CG] =
                                analyticVar[v][nodeLookUp_CG] - evolVar[v][nodeLookUp_CG];
                        }
                    }
                }
    }
}

// =========================================================================
// output
// =========================================================================

// =========================================================================
// gravitational wave extraction
// =========================================================================

int SMOKEMAXCtx::extract_gravitational_waves() {
    if (!m_uiMesh->isActive()) return 0;

    // make sure constraints (including Psi4) are computed
    this->compute_constraint_variables();

    DendroScalar *consVar[6];
    m_var[VL::CPU_CV].to_2d(consVar);

    // build the extraction config from our parameters
    dendro_gr::GWExtractionConfig gw_config;
    gw_config.psi4_real_idx = VAR_CONSTRAINT::C_PSI4_REAL;
    gw_config.psi4_imag_idx = VAR_CONSTRAINT::C_PSI4_IMAG;
    gw_config.file_prefix = SMOKEMAX_PROFILE_FILE_PREFIX;
    for (unsigned int i = 0; i < GW::SMOKEMAX_GW_NUM_RADAII; i++)
        gw_config.radii.push_back(GW::SMOKEMAX_GW_RADAII[i]);
    for (unsigned int i = 0; i < GW::SMOKEMAX_GW_NUM_LMODES; i++)
        gw_config.l_modes.push_back(GW::SMOKEMAX_GW_L_MODES[i]);
    for (int i = 0; i < 3; i++) {
        gw_config.compd_min[i] = SMOKEMAX_COMPD_MIN[i];
        gw_config.compd_max[i] = SMOKEMAX_COMPD_MAX[i];
        gw_config.octree_min[i] = SMOKEMAX_OCTREE_MIN[i];
        gw_config.octree_max[i] = SMOKEMAX_OCTREE_MAX[i];
    }

    dendro_gr::extractFarFieldPsi4(m_uiMesh, (const DendroScalar **)consVar,
                                    m_uiTinfo._m_uiStep, m_uiTinfo._m_uiT,
                                    gw_config);
    return 0;
}

// =========================================================================
// apparent horizon finder
// =========================================================================

void SMOKEMAXCtx::findAH() {
#ifdef SOLVER_ENABLE_AH
    if (!m_uiMesh->isActive()) return;
    if (AH::ah_finder == nullptr) return;

    DVec &m_evar = m_var[VL::CPU_EV];

    // ghost exchange and unzip
    m_uiMesh->readFromGhostBegin(m_evar.get_vec_ptr(), m_evar.get_dof());
    m_uiMesh->readFromGhostEnd(m_evar.get_vec_ptr(), m_evar.get_dof());
    this->unzip(m_evar, m_var[VL::CPU_EV_UZ_IN], SMOKEMAX_ASYNC_COMM_K);

    DendroScalar *eVar[24];
    m_evar.to_2d(eVar);

    // build list of BH locations to search near
    std::vector<Point> bh_locations;
    bh_locations.push_back(m_uiBHLoc[0]);
    bh_locations.push_back(m_uiBHLoc[1]);

    AH::ah_finder->find_horizons(m_uiMesh, (const double **)eVar,
                                  m_uiTinfo._m_uiStep, m_uiTinfo._m_uiT,
                                  bh_locations);
#endif
}

// =========================================================================
// output
// =========================================================================

int SMOKEMAXCtx::write_vtu() {
    if (!m_uiMesh->isActive()) return 0;

    DendroScalar *evolVar[24];
    m_var[VL::CPU_EV].to_2d(evolVar);

    this->compute_constraint_variables();
    DendroScalar *consVar[6];
    m_var[VL::CPU_CV].to_2d(consVar);

    this->compute_analytical();
    DendroScalar *analyticVar[24];
    DendroScalar *analyticDiffVar[24];
    m_var[VL::CPU_ANALYTIC].to_2d(analyticVar);
    m_var[VL::CPU_ANALYTIC_DIFF].to_2d(analyticDiffVar);

    // build the list of data arrays and names for VTU output
    std::vector<std::string> pDataNames;
    std::vector<double *> pDataVec;

    const unsigned int numEvolVars = SMOKEMAX_NUM_EVOL_VARS_VTU_OUTPUT;
    const unsigned int numConstVars = SMOKEMAX_NUM_CONST_VARS_VTU_OUTPUT;

    // evolution variables
    for (unsigned int i = 0; i < numEvolVars; i++) {
        pDataNames.push_back(std::string(
            SMOKEMAX_VAR_NAMES[SMOKEMAX_VTU_OUTPUT_EVOL_INDICES[i]]));
        pDataVec.push_back(evolVar[SMOKEMAX_VTU_OUTPUT_EVOL_INDICES[i]]);
    }

    // constraint variables
    for (unsigned int i = 0; i < numConstVars; i++) {
        pDataNames.push_back(std::string(
            SMOKEMAX_VAR_CONSTRAINT_NAMES[SMOKEMAX_VTU_OUTPUT_CONST_INDICES[i]]));
        pDataVec.push_back(consVar[SMOKEMAX_VTU_OUTPUT_CONST_INDICES[i]]);
    }

    // analytical + diff
    for (unsigned int i = 0; i < numEvolVars; i++) {
        unsigned int idx = SMOKEMAX_VTU_OUTPUT_EVOL_INDICES[i];
        pDataNames.push_back(std::string(SMOKEMAX_VAR_NAMES[idx]) + "_ANLYT");
        pDataVec.push_back(analyticVar[idx]);
    }
    for (unsigned int i = 0; i < numEvolVars; i++) {
        unsigned int idx = SMOKEMAX_VTU_OUTPUT_EVOL_INDICES[i];
        pDataNames.push_back(std::string(SMOKEMAX_VAR_NAMES[idx]) + "_DIFF");
        pDataVec.push_back(analyticDiffVar[idx]);
    }

    // convert to char* array for the vtk api
    std::vector<const char *> pDataNames_char;
    for (auto &s : pDataNames) pDataNames_char.push_back(s.c_str());

    const char *fDataNames[] = {"Time", "Cycle"};
    const double fData[] = {m_uiTinfo._m_uiT, (double)m_uiTinfo._m_uiStep};

    char fPrefix[256];
    sprintf(fPrefix, "%s_%06d", SMOKEMAX_VTU_FILE_PREFIX.c_str(),
            m_uiTinfo._m_uiStep);

    // if any slice flag is set, emit a 2D slice via mesh2vtu_slice (matches
    // BSSN_GR). plane goes through the octree center; first true flag wins.
    // all flags false -> full 3D output.
    const bool slice_x = smokemax::SMOKEMAX_VTU_X_SLICE;
    const bool slice_y = smokemax::SMOKEMAX_VTU_Y_SLICE;
    const bool slice_z = smokemax::SMOKEMAX_VTU_Z_SLICE;

    if (slice_x || slice_y || slice_z) {
        const unsigned int center = 1u << (m_uiMaxDepth - 1);
        unsigned int s_val[3] = {center, center, center};
        unsigned int s_norm[3] = {0, 0, 0};
        if      (slice_x) s_norm[0] = 1;
        else if (slice_y) s_norm[1] = 1;
        else              s_norm[2] = 1;

        io::vtk::mesh2vtu_slice(
            m_uiMesh, s_val, s_norm, fPrefix, 2, fDataNames, fData,
            (unsigned int)pDataVec.size(),
            pDataNames_char.data(),
            (const double **)pDataVec.data());
    } else {
        io::vtk::mesh2vtuFine(
            m_uiMesh, fPrefix, 2, fDataNames, fData,
            (unsigned int)pDataVec.size(),
            pDataNames_char.data(),
            (const double **)pDataVec.data());
    }

    return 0;
}

int SMOKEMAXCtx::terminal_output() {
    if (!m_uiMesh->isActive()) return 0;

    const int rank = m_uiMesh->getMPIRank();
    const MPI_Comm comm = m_uiMesh->getMPICommunicator();
    const unsigned int nLocal = m_uiMesh->getNumLocalMeshNodes();
    const unsigned int nodeBegin = m_uiMesh->getNodeLocalBegin();

    if (rank == 0) {
        std::cout << "[SMOKEMAX] step=" << m_uiTinfo._m_uiStep
                  << " t=" << m_uiTinfo._m_uiT
                  << " dt=" << m_uiTinfo._m_uiTh
                  << " elements=" << m_uiGlobalMeshElements
                  << std::endl;
    }

    // Report per-node + volume-averaged RMS deviation from flat space,
    // sqrt(int (u - u_flat)^2 dV / V): the per-point departure from the
    // background, O(amp) and grid-independent. Only the variables listed in
    // SMOKEMAX_TERMINAL_OUTPUT_* are computed -- each needs a ghost
    // exchange, so narrow those in the par to cut synchronization.
    const size_t dof = m_uiMesh->getDegOfFreedom();
    const auto& termEvolSel = SMOKEMAX_TERMINAL_OUTPUT_EVOL_INDICES;
    const auto& termConsSel = SMOKEMAX_TERMINAL_OUTPUT_CONST_INDICES;

    // u_flat per var (reference IC is homogeneous -> one eval). Unset -> 0.
    double flat_ref[24];
    for (unsigned int v = 0; v < 24; v++) flat_ref[v] = 0.0;
    DendroScalar *zippedUp[24];
    m_var[VL::CPU_EV].to_2d(zippedUp);

    double invMeshVolume = 0.0;
    if (!termEvolSel.empty() || !termConsSel.empty()) {
        // V = int 1 dV (works for AMR and uniform grids)
        std::vector<double> onesVec;
        m_uiMesh->createVector(onesVec);
        for (size_t i = 0; i < dof; i++) onesVec[i] = 1.0;
        const double meshVolume =
            integrateScalarFieldOnMesh(m_uiMesh, onesVec.data());
        invMeshVolume = (meshVolume > 0.0) ? (1.0 / meshVolume) : 0.0;
    }

    if (!termEvolSel.empty()) {
        std::vector<double> devVec;
        m_uiMesh->createVector(devVec);
        for (unsigned int v : termEvolSel) {
            if (v >= 24) continue;
            double l_min = vecMin(&zippedUp[v][nodeBegin], nLocal, comm);
            double l_max = vecMax(&zippedUp[v][nodeBegin], nLocal, comm);
            for (size_t i = 0; i < dof; i++) devVec[i] = zippedUp[v][i] - flat_ref[v];
            // rms = per-node RMS; rms_vol = volume-weighted (AMR-aware)
            double rms = normRMSE(&devVec[nodeBegin], nLocal, comm);
            double rms_vol = std::sqrt(
                calculateL2FullMeshIntegration(m_uiMesh, devVec.data()) * invMeshVolume);
            if (rank == 0) {
                std::cout << "\t[var]:  " << std::setw(12)
                          << SMOKEMAX_VAR_NAMES[v]
                          << " (min, max, rms_dev, rms_dev_vol) : \t ( "
                          << l_min << ", " << l_max << ", " << rms << ", "
                          << rms_vol << ") "
                          << std::endl;
            }
        }
    }

    // compute and print analytical solution error norms
    this->compute_analytical();

    DendroScalar *zippedDiff[24];
    m_var[VL::CPU_ANALYTIC_DIFF].to_2d(zippedDiff);

    // write csv header on first step
    char fName[256];
    sprintf(fName, "%s_ANALYTICAL_DIFF.csv", SMOKEMAX_PROFILE_FILE_PREFIX.c_str());

    if (rank == 0 && m_uiTinfo._m_uiStep == 0) {
        std::ofstream fileDiff(fName, std::ofstream::trunc);
        fileDiff << "Timestep,Time,";
        for (unsigned int v = 0; v < 24; v++) {
            std::string name = SMOKEMAX_VAR_NAMES[v];
            fileDiff << name << "_DIFF_MIN," << name << "_DIFF_MAX,"
                     << name << "_DIFF_L2," << name << "_DIFF_RMSE,"
                     << name << "_DIFF_NRMSE," << name << "_DIFF_MAE,";
        }
        fileDiff << std::endl;
        fileDiff.close();
    }

    // compute and print per-variable error norms
    if (rank == 0) {
        std::ofstream fileDiff(fName, std::ofstream::app);
        fileDiff << m_uiTinfo._m_uiStep << "," << m_uiTinfo._m_uiT << ",";

        for (unsigned int v = 0; v < 24; v++) {
            double l_min = vecMin(&zippedDiff[v][nodeBegin], nLocal, comm);
            double l_max = vecMax(&zippedDiff[v][nodeBegin], nLocal, comm);
            double l2 = normL2(&zippedDiff[v][nodeBegin], nLocal, comm);
            double rmse = normRMSE(&zippedDiff[v][nodeBegin], nLocal, comm);
            double nrmse = normNRMSE(&zippedDiff[v][nodeBegin],
                                      &zippedUp[v][nodeBegin], nLocal, comm);
            double mae = normMAE(&zippedDiff[v][nodeBegin], nLocal, comm);

            std::cout << "\t[diff]: " << std::setw(12)
                      << std::string(SMOKEMAX_VAR_NAMES[v]) + "_DIFF"
                      << " (min, max, l2, rmse, nrmse, mae) : \t ( "
                      << l_min << ", " << l_max << ", " << l2 << ", "
                      << rmse << ", " << nrmse << ", " << mae << ") "
                      << std::endl;

            fileDiff << l_min << "," << l_max << "," << l2 << ","
                     << rmse << "," << nrmse << "," << mae << ",";
        }
        fileDiff << std::endl;
        fileDiff.close();
    }

    // constraint norms -- only computed if any are selected (the constraint
    // computation itself is expensive, so this skips it entirely otherwise)
    if (!termConsSel.empty()) {
        this->compute_constraint_variables();

        DendroScalar *zippedCons[6];
        m_var[VL::CPU_CV].to_2d(zippedCons);

        // Optional puncture excision for the constraint norms. Nodes within
        // BH<n>_CONSTRAINT_R of a puncture are dropped from the *masked*
        // norms. Both radii default to 0 -> mask inactive -> the unmasked
        // norms below are reported exactly as before.
        //
        // Why this exists: BSSN's constraint norm
        // (BSSN_GR/include/grUtils.tcc, computeConstraintL2Norm) excises a
        // ball of radius BSSN_BH1_CONSTRAINT_R (production value 1.0) around
        // each puncture, and it *must* -- BSSN's Hamiltonian constraint is
        // non-finite at a puncture, so the unmasked norm is NaN. Our norms
        // include the puncture, where essentially all of the violation lives.
        // Comparing the two logs directly is therefore meaningless; setting
        // constraint_r to BSSN's value makes rms_msk a like-for-like number.
        const double bh1_cr = smokemax::SMOKEMAX_BH1_CONSTRAINT_R;
        const double bh2_cr = smokemax::SMOKEMAX_BH2_CONSTRAINT_R;
        const bool maskActive = (bh1_cr > 0.0 || bh2_cr > 0.0);

        std::vector<double> consMask;
        if (maskActive) {
            // 1.0 = keep, 0.0 = excised. Built over the whole dof range; only
            // the local slice is used below, so shared nodes can be written
            // more than once without double counting.
            consMask.resize(dof, 1.0);

            const ot::TreeNode *pNodes = m_uiMesh->getAllElements().data();
            const unsigned int *e2n_cg = &(*(m_uiMesh->getE2NMapping().begin()));
            const unsigned int *e2n_dg = &(*(m_uiMesh->getE2NMapping_DG().begin()));
            const unsigned int eleOrder = m_uiMesh->getElementOrder();
            const unsigned int nPe = m_uiMesh->getNumNodesPerElement();
            const unsigned int nodeLocalEnd = m_uiMesh->getNodeLocalEnd();

            for (unsigned int elem = m_uiMesh->getElementLocalBegin();
                 elem < m_uiMesh->getElementLocalEnd(); elem++) {
                for (unsigned int k = 0; k < (eleOrder + 1); k++)
                    for (unsigned int j = 0; j < (eleOrder + 1); j++)
                        for (unsigned int i = 0; i < (eleOrder + 1); i++) {
                            const unsigned int nIdx =
                                k * (eleOrder + 1) * (eleOrder + 1) +
                                j * (eleOrder + 1) + i;
                            const unsigned int nodeLookUp_CG =
                                e2n_cg[elem * nPe + nIdx];
                            if (nodeLookUp_CG < nodeBegin ||
                                nodeLookUp_CG >= nodeLocalEnd)
                                continue;

                            const unsigned int nodeLookUp_DG =
                                e2n_dg[elem * nPe + nIdx];
                            unsigned int ownerID, ii_x, jj_y, kk_z;
                            m_uiMesh->dg2eijk(nodeLookUp_DG, ownerID, ii_x,
                                              jj_y, kk_z);

                            const double len = (double)(1u << (m_uiMaxDepth -
                                pNodes[ownerID].getLevel()));
                            const double xo =
                                pNodes[ownerID].getX() + ii_x * (len / eleOrder);
                            const double yo =
                                pNodes[ownerID].getY() + jj_y * (len / eleOrder);
                            const double zo =
                                pNodes[ownerID].getZ() + kk_z * (len / eleOrder);

                            const Point gp(GRIDX_TO_X(xo), GRIDY_TO_Y(yo),
                                           GRIDZ_TO_Z(zo));
                            const double d1 =
                                (gp - smokemax::SMOKEMAX_BH_LOC[0]).abs();
                            const double d2 =
                                (gp - smokemax::SMOKEMAX_BH_LOC[1]).abs();
                            if (d1 < bh1_cr || d2 < bh2_cr)
                                consMask[nodeLookUp_CG] = 0.0;
                        }
            }
        }

        // At a 2:1 jump the fine side comes from degree-(eleOrder)
        // prolongation; a second derivative divides that by h^2, leaving those
        // DOFs one order short of the interior scheme. rms_int drops them.
        // Conservative: drops the whole element, not just the stencil radius.
        std::vector<double> ifaceMask(dof, 1.0);
        {
            const ot::TreeNode *pN = m_uiMesh->getAllElements().data();
            const unsigned int *e2n = &(*(m_uiMesh->getE2NMapping().begin()));
            const unsigned int *e2e = &(*(m_uiMesh->getE2EMapping().begin()));
            const unsigned int nDir = m_uiMesh->getNumDirections();
            const unsigned int nPe_ = m_uiMesh->getNumNodesPerElement();
            const unsigned int nEnd = m_uiMesh->getNodeLocalEnd();

            // all elements, not just local: a node owned here can belong to a
            // jump-adjacent element owned by another rank
            for (unsigned int elem = m_uiMesh->getElementPreGhostBegin();
                 elem < m_uiMesh->getElementPostGhostEnd(); elem++) {
                const unsigned int lev = pN[elem].getLevel();
                bool nearJump = false;
                for (unsigned int d = 0; d < nDir && !nearJump; d++) {
                    const unsigned int nb = e2e[elem * nDir + d];
                    if (nb != LOOK_UP_TABLE_DEFAULT &&
                        pN[nb].getLevel() != lev)
                        nearJump = true;
                }
                if (!nearJump) continue;
                for (unsigned int n = 0; n < nPe_; n++) {
                    const unsigned int nd = e2n[elem * nPe_ + n];
                    if (nd >= nodeBegin && nd < nEnd) ifaceMask[nd] = 0.0;
                }
            }
        }

        // constraints -> 0 in the continuum, so RMS is the violation directly
        for (unsigned int v : termConsSel) {
            if (v >= 6) continue;
            double l_min = vecMin(&zippedCons[v][nodeBegin], nLocal, comm);
            double l_max = vecMax(&zippedCons[v][nodeBegin], nLocal, comm);
            double rms = normRMSE(&zippedCons[v][nodeBegin], nLocal, comm);
            double rms_vol =
                std::sqrt(calculateL2FullMeshIntegration(m_uiMesh, zippedCons[v]) *
                          invMeshVolume);

            // sqrt(sum c^2 / N) over kept nodes -- same formula as normRMSE
            // and as BSSN's computeConstraintL2Norm, just over the kept set.
            double rms_msk = rms;
            if (maskActive) {
                double l_acc[2] = {0.0, 0.0};  // {sum c^2, kept-node count}
                for (unsigned int n = 0; n < nLocal; n++) {
                    if (consMask[nodeBegin + n] == 0.0) continue;
                    const double c = zippedCons[v][nodeBegin + n];
                    l_acc[0] += c * c;
                    l_acc[1] += 1.0;
                }
                double g_acc[2] = {0.0, 0.0};
                MPI_Allreduce(l_acc, g_acc, 2, MPI_DOUBLE, MPI_SUM, comm);
                rms_msk = (g_acc[1] > 0.0)
                              ? std::sqrt(g_acc[0] / g_acc[1])
                              : 0.0;
            }

            // same formula again, additionally dropping the interface collar
            double rms_int = 0.0;
            {
                double l_acc[2] = {0.0, 0.0};
                for (unsigned int n = 0; n < nLocal; n++) {
                    if (ifaceMask[nodeBegin + n] == 0.0) continue;
                    if (maskActive && consMask[nodeBegin + n] == 0.0) continue;
                    const double c = zippedCons[v][nodeBegin + n];
                    l_acc[0] += c * c;
                    l_acc[1] += 1.0;
                }
                double g_acc[2] = {0.0, 0.0};
                MPI_Allreduce(l_acc, g_acc, 2, MPI_DOUBLE, MPI_SUM, comm);
                rms_int = (g_acc[1] > 0.0)
                              ? std::sqrt(g_acc[0] / g_acc[1])
                              : 0.0;
            }

            if (rank == 0) {
                std::cout << "\t[con]:  " << std::setw(12)
                          << SMOKEMAX_VAR_CONSTRAINT_NAMES[v]
                          << " (min, max, rms, rms_vol, rms_msk, rms_int) : \t ( "
                          << l_min << ", " << l_max << ", " << rms << ", "
                          << rms_vol << ", " << rms_msk << ", " << rms_int << ") "
                          << std::endl;
            }
        }
    }

    return 0;
}

void SMOKEMAXCtx::write_grid_summary_data() {
    calculate_full_grid_size();
}

// =========================================================================
// remeshing
// =========================================================================

bool SMOKEMAXCtx::is_remesh() {
    if (SMOKEMAX_REFINEMENT_MODE == REFINE_MODE_NONE) return false;

    auto run_wamr = [this]() {
        this->unzip(m_var[VL::CPU_EV], m_var[VL::CPU_EV_UZ_IN],
                    SMOKEMAX_ASYNC_COMM_K);
        DendroScalar *unzipVar[24];
        m_var[VL::CPU_EV_UZ_IN].to_2d(unzipVar);
        std::function<double(double, double, double, double *)> wtolFn =
            [](double x, double y, double z, double *hx) {
                return computeWTolDCoords(x, y, z, hx);
            };
        return m_uiMesh->isReMeshUnzip(
            (const DendroScalar **)unzipVar,
            SMOKEMAX_REFINE_VARIABLE_INDICES,
            SMOKEMAX_NUM_REFINE_VARS,
            wtolFn,
            SMOKEMAX_DENDRO_AMR_FAC);
    };

    auto run_bh_loc = [this](bool overwrite) {
        dendro_gr::BHLocCfg cfg;
        // Only refine around active BHs; an inert (mass-0) puncture must not
        // build a phantom onion. No-op for a real binary (both > tol).
        constexpr double BH_ACTIVE_MASS_TOL = 1.0e-6;
        if (BH1.getBHMass() > BH_ACTIVE_MASS_TOL) {
            cfg.bh_locations.push_back(m_uiBHLoc[0]);
            cfg.bh_amr_radii.push_back(SMOKEMAX_BH1_AMR_R);
            cfg.bh_max_levels.push_back(SMOKEMAX_BH1_MAX_LEV);
        }
        if (BH2.getBHMass() > BH_ACTIVE_MASS_TOL) {
            cfg.bh_locations.push_back(m_uiBHLoc[1]);
            cfg.bh_amr_radii.push_back(SMOKEMAX_BH2_AMR_R);
            cfg.bh_max_levels.push_back(SMOKEMAX_BH2_MAX_LEV);
        }
        cfg.ratio         = SMOKEMAX_AMR_R_RATIO;
        cfg.min_level     = SMOKEMAX_MINDEPTH;
        cfg.overwrite     = overwrite;
        return dendro_gr::isRemeshBH(m_uiMesh, cfg);
    };

    switch (SMOKEMAX_REFINEMENT_MODE) {
        case WAMR:    return run_wamr();
        case BH_LOC:  return run_bh_loc(/*overwrite=*/true);
        case BH_WAMR: {
            const bool r1 = run_wamr();
            const bool r2 = run_bh_loc(/*overwrite=*/false);
            return r1 || r2;
        }
        default: return run_wamr();  // EH/EH_WAMR not yet ported
    }
}

int SMOKEMAXCtx::grid_transfer(const ot::Mesh *m_new) {
    // dealloc old MPI context
    ot::dealloc_mpi_ctx<DendroScalar>(m_uiMesh, m_mpi_ctx, 24,
                                       SMOKEMAX_ASYNC_COMM_K);

    // transfer evolution variables to the new mesh (interpolation)
    DVec::grid_transfer(m_uiMesh, m_new, m_var[VL::CPU_EV]);

    // destroy everything that depends on the old mesh layout
    m_var[VL::CPU_CV].destroy_vector();
    m_var[VL::CPU_CV_UZ_IN].destroy_vector();
    m_var[VL::CPU_EV_UZ_IN].destroy_vector();
    m_var[VL::CPU_EV_UZ_OUT].destroy_vector();
    m_var[VL::CPU_ANALYTIC].destroy_vector();
    m_var[VL::CPU_ANALYTIC_DIFF].destroy_vector();

    // reallocate on the new mesh
    // note: the base class swaps m_uiMesh after this returns, so use m_new
    m_var[VL::CPU_EV_UZ_IN].create_vector(m_new,
        ot::DVEC_TYPE::OCT_LOCAL_WITH_PADDING, ot::DVEC_LOC::HOST,
        24, true);
    m_var[VL::CPU_EV_UZ_OUT].create_vector(m_new,
        ot::DVEC_TYPE::OCT_LOCAL_WITH_PADDING, ot::DVEC_LOC::HOST,
        24, true);
    m_var[VL::CPU_CV].create_vector(m_new, ot::DVEC_TYPE::OCT_SHARED_NODES,
        ot::DVEC_LOC::HOST, 6, true);
    m_var[VL::CPU_CV_UZ_IN].create_vector(m_new,
        ot::DVEC_TYPE::OCT_LOCAL_WITH_PADDING, ot::DVEC_LOC::HOST,
        6, true);
    m_var[VL::CPU_ANALYTIC].create_vector(m_new, ot::DVEC_TYPE::OCT_SHARED_NODES,
        ot::DVEC_LOC::HOST, 24, true);
    m_var[VL::CPU_ANALYTIC_DIFF].create_vector(m_new, ot::DVEC_TYPE::OCT_SHARED_NODES,
        ot::DVEC_LOC::HOST, 24, true);

    // alloc MPI context on new mesh
    ot::alloc_mpi_ctx<DendroScalar>(m_new, m_mpi_ctx, 24,
                                     SMOKEMAX_ASYNC_COMM_K);

    return 0;
}

void SMOKEMAXCtx::calculate_full_grid_size() {
    DendroIntL localElements = m_uiMesh->getNumLocalMeshElements();
    DendroIntL localNodes = m_uiMesh->getNumLocalMeshNodes();

    par::Mpi_Reduce(&localElements, &m_uiGlobalMeshElements, 1,
                     MPI_SUM, 0, m_uiMesh->getMPIGlobalCommunicator());
    par::Mpi_Reduce(&localNodes, &m_uiGlobalGridPoints, 1,
                     MPI_SUM, 0, m_uiMesh->getMPIGlobalCommunicator());
}

// =========================================================================
// checkpointing
//
// Two alternating slots (0/1) for crash safety, plus a `<prefix>.latest`
// sentinel written LAST via an atomic rename: a crash mid-write never advances
// it, so restore always lands on the last *fully complete* checkpoint. The
// metadata is a single self-describing, versioned JSON file -- adding new state
// is one line in write_checkpt() + one defaulted line in restore_checkpt().
// The heavy mesh/variable data uses dendrolib's binary io::checkpoint helpers.
// =========================================================================

// checkpoint layout version -- bump only on an incompatible format change.
static const unsigned int SMOKEMAX_CHKPT_FORMAT_VERSION = 1;

int SMOKEMAXCtx::write_checkpt() {
    if (!m_uiMesh->isActive()) return 0;

    const unsigned int rank = m_uiMesh->getMPIRank();
    const unsigned int slot =
        (m_uiTinfo._m_uiStep / SMOKEMAX_CHECKPT_FREQ) % 2;

    char fname[512];

    // (1) octree topology -- one binary file per (active) rank
    const ot::TreeNode *pNodes = &(*(m_uiMesh->getAllElements().begin() +
                                     m_uiMesh->getElementLocalBegin()));
    sprintf(fname, "%s_%u_octree_%u.oct",
            SMOKEMAX_CHKPT_FILE_PREFIX.c_str(), slot, rank);
    io::checkpoint::writeOctToFile(fname, pNodes,
                                   m_uiMesh->getNumLocalMeshElements());

    // (2) evolution variables -- one binary file per (active) rank
    DendroScalar *eVar[24];
    m_var[VL::CPU_EV].to_2d(eVar);
    sprintf(fname, "%s_%u_vars_%u.var",
            SMOKEMAX_CHKPT_FILE_PREFIX.c_str(), slot, rank);
    io::checkpoint::writeVecToFile(fname, m_uiMesh, (const DendroScalar **)eVar,
                                   24);

    // (3) self-describing metadata -- single JSON file (active rank 0)
    if (rank == 0) {
        json meta;
        meta["format_version"] = SMOKEMAX_CHKPT_FORMAT_VERSION;
        meta["num_evol_vars"]  = 24;
        // element order from the mesh (authoritative; m_uiElementOrder is not
        // guaranteed initialized in the ctx).
        meta["ele_order"]      = m_uiMesh->getElementOrder();
        meta["active_comm_sz"] = m_uiMesh->getMPICommSize();
        meta["time"]["tb"]     = m_uiTinfo._m_uiTb;
        meta["time"]["te"]     = m_uiTinfo._m_uiTe;
        meta["time"]["t"]      = m_uiTinfo._m_uiT;
        meta["time"]["step"]   = m_uiTinfo._m_uiStep;
        meta["time"]["dt"]     = m_uiTinfo._m_uiTh;
        meta["wavelet_tol"]    = SMOKEMAX_WAVELET_TOL;
        meta["load_imb_tol"]   = SMOKEMAX_LOAD_IMB_TOL;
        meta["bh"]["loc"] = json::array({
            json::array({m_uiBHLoc[0].x(), m_uiBHLoc[0].y(), m_uiBHLoc[0].z()}),
            json::array({m_uiBHLoc[1].x(), m_uiBHLoc[1].y(), m_uiBHLoc[1].z()})});
        meta["bh"]["merged"]     = m_bIsBHMerged;
        meta["bh"]["merge_time"] = m_dMergeTime;
        meta["bh"]["merge_step"] = m_uiMergeStep;
        // BH location/time history -> flat double vectors -> base91 (compact,
        // self-describing length; mirrors dendro_bh::BHHistory::encode).
        std::vector<double> locHist;
        locHist.reserve(m_uiBHLocHistory.size() * 6);
        for (const auto &p : m_uiBHLocHistory) {
            locHist.push_back(p.first.x());
            locHist.push_back(p.first.y());
            locHist.push_back(p.first.z());
            locHist.push_back(p.second.x());
            locHist.push_back(p.second.y());
            locHist.push_back(p.second.z());
        }
        meta["bh"]["loc_history_b91"]  = dendro_aeh::b91_encode(locHist);
        meta["bh"]["time_history_b91"] = dendro_aeh::b91_encode(m_uiBHTimeHistory);
        sprintf(fname, "%s_%u.meta.json",
                SMOKEMAX_CHKPT_FILE_PREFIX.c_str(), slot);
        std::ofstream mf(fname);
        mf << std::setw(2) << meta << std::endl;
        mf.close();
    }

    // (4) sentinel: barrier so every active rank's .oct/.var/.meta is flushed,
    //     then rank 0 atomically publishes which slot is now complete + valid.
    MPI_Barrier(m_uiMesh->getMPICommunicator());
    if (rank == 0) {
        json latest;
        latest["format_version"] = SMOKEMAX_CHKPT_FORMAT_VERSION;
        latest["slot"]           = slot;
        latest["step"]           = (uint64_t)m_uiTinfo._m_uiStep;
        char tmpf[512], finalf[512];
        sprintf(tmpf, "%s.latest.tmp",
                SMOKEMAX_CHKPT_FILE_PREFIX.c_str());
        sprintf(finalf, "%s.latest", SMOKEMAX_CHKPT_FILE_PREFIX.c_str());
        std::ofstream lf(tmpf);
        lf << latest << std::endl;
        lf.close();
        std::filesystem::rename(tmpf, finalf);  // atomic publish
        std::cout << "[smokemax] checkpoint written: slot " << slot
                  << " step " << m_uiTinfo._m_uiStep
                  << " t=" << m_uiTinfo._m_uiT << std::endl;
    }
    return 0;
}

int SMOKEMAXCtx::restore_checkpt() {
    MPI_Comm comm = m_uiMesh->getMPIGlobalCommunicator();
    int rank, npes;
    MPI_Comm_rank(comm, &rank);
    MPI_Comm_size(comm, &npes);

    // (1) rank 0 reads the sentinel to find the last complete slot; broadcast.
    int slot = -1;
    if (rank == 0) {
        char lname[512];
        sprintf(lname, "%s.latest", SMOKEMAX_CHKPT_FILE_PREFIX.c_str());
        if (std::filesystem::exists(lname)) {
            std::ifstream lf(lname);
            json latest;
            lf >> latest;
            slot = latest.value("slot", -1);
        }
    }
    par::Mpi_Bcast(&slot, 1, 0, comm);

    if (slot < 0) {
        if (!rank)
            std::cout << "[smokemax] no valid checkpoint ("
                      << SMOKEMAX_CHKPT_FILE_PREFIX
                      << ".latest missing) -- starting from initial data."
                      << std::endl;
        init_grid();
        return 0;
    }

    // (2) every rank reads the (small) self-describing metadata for that slot.
    char fname[512];
    sprintf(fname, "%s_%d.meta.json",
            SMOKEMAX_CHKPT_FILE_PREFIX.c_str(), slot);
    json meta;
    {
        std::ifstream mf(fname);
        if (!mf) {
            if (!rank)
                std::cerr << "[smokemax] checkpoint metadata missing: "
                          << fname << std::endl;
            MPI_Abort(comm, 0);
        }
        mf >> meta;
    }

    const unsigned int file_nvars = meta.value("num_evol_vars", 0u);
    if (file_nvars != 24) {
        if (!rank)
            std::cerr << "[smokemax] checkpoint var-count mismatch: file="
                      << file_nvars << " expected=" << 24
                      << std::endl;
        MPI_Abort(comm, 0);
    }
    const unsigned int active_comm_sz = meta["active_comm_sz"];
    // element order from the checkpoint (the ctx's m_uiElementOrder may be
    // unset here; the metadata value is authoritative for rebuilding the mesh).
    const unsigned int ele_order = meta["ele_order"].get<unsigned int>();

    // restore time-stepper state (the ETS pulls this via get_ts_info()).
    m_uiTinfo._m_uiTb   = meta["time"]["tb"].get<double>();
    m_uiTinfo._m_uiTe   = meta["time"]["te"].get<double>();
    m_uiTinfo._m_uiT    = meta["time"]["t"].get<double>();
    m_uiTinfo._m_uiStep = meta["time"]["step"].get<unsigned int>();
    m_uiTinfo._m_uiTh   = meta["time"]["dt"].get<double>();

    if (meta.contains("bh")) {
        const auto &bh = meta["bh"];
        m_uiBHLoc[0] = Point(bh["loc"][0][0].get<double>(),
                             bh["loc"][0][1].get<double>(),
                             bh["loc"][0][2].get<double>());
        m_uiBHLoc[1] = Point(bh["loc"][1][0].get<double>(),
                             bh["loc"][1][1].get<double>(),
                             bh["loc"][1][2].get<double>());
        SMOKEMAX_BH_LOC[0] = m_uiBHLoc[0];
        SMOKEMAX_BH_LOC[1] = m_uiBHLoc[1];
        m_bIsBHMerged = bh.value("merged", false);
        m_dMergeTime  = bh.value("merge_time",
                                 std::numeric_limits<double>::max());
        m_uiMergeStep = bh.value("merge_step",
                                 std::numeric_limits<uint32_t>::max());
        m_uiBHLocHistory.clear();
        m_uiBHTimeHistory.clear();
        if (bh.contains("loc_history_b91") && bh.contains("time_history_b91")) {
            std::vector<double> lh = dendro_aeh::b91_decode<double>(
                bh["loc_history_b91"].get<std::string>());
            std::vector<double> th = dendro_aeh::b91_decode<double>(
                bh["time_history_b91"].get<std::string>());
            for (size_t i = 0; i + 5 < lh.size(); i += 6)
                m_uiBHLocHistory.push_back(std::make_pair(
                    Point(lh[i], lh[i + 1], lh[i + 2]),
                    Point(lh[i + 3], lh[i + 4], lh[i + 5])));
            m_uiBHTimeHistory.assign(th.begin(), th.end());
        }
    }

    if (active_comm_sz > (unsigned int)npes) {
        if (!rank)
            std::cerr << "[smokemax] checkpoint was written with "
                      << active_comm_sz << " active ranks; cannot restore on "
                      << npes << " (communicator shrinking unsupported)."
                      << std::endl;
        MPI_Abort(comm, 0);
    }

    // (3) active ranks read their octree slice (file index = active rank).
    const bool isActive = ((unsigned int)rank < active_comm_sz);
    MPI_Comm activeComm;
    par::splitComm2way(!isActive, &activeComm, comm);

    std::vector<ot::TreeNode> octree;
    int readStatus = 0, readStatusG = 0;
    if (isActive) {
        int activeRank;
        MPI_Comm_rank(activeComm, &activeRank);
        sprintf(fname, "%s_%d_octree_%d.oct",
                SMOKEMAX_CHKPT_FILE_PREFIX.c_str(), slot, activeRank);
        readStatus = io::checkpoint::readOctFromFile(fname, octree);
    }
    par::Mpi_Allreduce(&readStatus, &readStatusG, 1, MPI_MAX, comm);
    if (readStatusG != 0) {
        if (!rank)
            std::cerr << "[smokemax] checkpoint octree (.oct) read "
                         "failed/corrupt." << std::endl;
        MPI_Abort(comm, 0);
    }

    // (4) rebuild the mesh from the restored octree.
    ot::Mesh *newMesh =
        new ot::Mesh(octree, 1, ele_order, active_comm_sz, comm);
    newMesh->setDomainBounds(
        Point(SMOKEMAX_GRID_MIN_X, SMOKEMAX_GRID_MIN_Y,
              SMOKEMAX_GRID_MIN_Z),
        Point(SMOKEMAX_GRID_MAX_X, SMOKEMAX_GRID_MAX_Y,
              SMOKEMAX_GRID_MAX_Z));

    // (5) move every mesh-sized allocation onto the new mesh.
    ot::dealloc_mpi_ctx<DendroScalar>(m_uiMesh, m_mpi_ctx,
                                      24,
                                      SMOKEMAX_ASYNC_COMM_K);
    for (unsigned int i = 0; i < VL::END; i++) m_var[i].destroy_vector();

    m_var[VL::CPU_EV].create_vector(newMesh, ot::DVEC_TYPE::OCT_SHARED_NODES,
        ot::DVEC_LOC::HOST, 24, true);
    m_var[VL::CPU_EV_UZ_IN].create_vector(newMesh,
        ot::DVEC_TYPE::OCT_LOCAL_WITH_PADDING, ot::DVEC_LOC::HOST,
        24, true);
    m_var[VL::CPU_EV_UZ_OUT].create_vector(newMesh,
        ot::DVEC_TYPE::OCT_LOCAL_WITH_PADDING, ot::DVEC_LOC::HOST,
        24, true);
    m_var[VL::CPU_CV].create_vector(newMesh, ot::DVEC_TYPE::OCT_SHARED_NODES,
        ot::DVEC_LOC::HOST, 6, true);
    m_var[VL::CPU_CV_UZ_IN].create_vector(newMesh,
        ot::DVEC_TYPE::OCT_LOCAL_WITH_PADDING, ot::DVEC_LOC::HOST,
        6, true);
    m_var[VL::CPU_ANALYTIC].create_vector(newMesh,
        ot::DVEC_TYPE::OCT_SHARED_NODES, ot::DVEC_LOC::HOST,
        24, true);
    m_var[VL::CPU_ANALYTIC_DIFF].create_vector(newMesh,
        ot::DVEC_TYPE::OCT_SHARED_NODES, ot::DVEC_LOC::HOST,
        24, true);

    ot::alloc_mpi_ctx<DendroScalar>(newMesh, m_mpi_ctx,
                                    24,
                                    SMOKEMAX_ASYNC_COMM_K);

    // (6) active ranks load the evolution variables onto the new mesh.
    if (isActive) {
        int activeRank;
        MPI_Comm_rank(activeComm, &activeRank);
        DendroScalar *inVar[24];
        m_var[VL::CPU_EV].to_2d(inVar);
        sprintf(fname, "%s_%d_vars_%d.var",
                SMOKEMAX_CHKPT_FILE_PREFIX.c_str(), slot, activeRank);
        readStatus = io::checkpoint::readVecFromFile(fname, newMesh, inVar,
                                                     24);
    }
    MPI_Comm_free(&activeComm);
    par::Mpi_Allreduce(&readStatus, &readStatusG, 1, MPI_MAX, comm);
    if (readStatusG != 0) {
        if (!rank)
            std::cerr << "[smokemax] checkpoint variables (.var) read "
                         "failed/corrupt." << std::endl;
        MPI_Abort(comm, 0);
    }

    // (7) swap in the restored mesh; main re-sizes derivs + builds the ETS
    //     (which picks up the restored TSInfo) after initialize() returns.
    std::swap(m_uiMesh, newMesh);
    delete newMesh;

    if (!rank)
        std::cout << "[smokemax] checkpoint restore OK -- resuming at"
                  << " step " << m_uiTinfo._m_uiStep
                  << " t=" << m_uiTinfo._m_uiT << " (slot " << slot << ")"
                  << std::endl;
    return 0;
}

// =========================================================================
// black hole tracking
// =========================================================================

void SMOKEMAXCtx::evolve_bh_loc() {
    // first call (e.g. step 0): seed the history, nothing to integrate yet
    if (m_uiBHTimeHistory.empty()) {
        store_bh_loc_history();
        return;
    }
    // dt since the last tracked time; guard against a repeat call at same t
    const double dt = m_uiTinfo._m_uiT - m_uiBHTimeHistory.back();
    if (dt <= 0.0) return;

    DVec &m_evar = m_var[VL::CPU_EV];
    m_uiMesh->readFromGhostBegin(m_evar.get_vec_ptr(), m_evar.get_dof());
    m_uiMesh->readFromGhostEnd(m_evar.get_vec_ptr(), m_evar.get_dof());
    DendroScalar *evar[24];
    m_evar.to_2d(evar);

    const unsigned int beta_idx[3] = {VAR::U_BETA0, VAR::U_BETA1, VAR::U_BETA2};
    Point grid_limits[2] = {
        Point(SMOKEMAX_OCTREE_MIN[0], SMOKEMAX_OCTREE_MIN[1],
              SMOKEMAX_OCTREE_MIN[2]),
        Point(SMOKEMAX_OCTREE_MAX[0], SMOKEMAX_OCTREE_MAX[1],
              SMOKEMAX_OCTREE_MAX[2])};
    Point domain_limits[2] = {
        Point(SMOKEMAX_COMPD_MIN[0], SMOKEMAX_COMPD_MIN[1],
              SMOKEMAX_COMPD_MIN[2]),
        Point(SMOKEMAX_COMPD_MAX[0], SMOKEMAX_COMPD_MAX[1],
              SMOKEMAX_COMPD_MAX[2])};

    Point newLoc[2];
    dendro_gr::trackPunctures(m_uiMesh, (double **)evar, beta_idx, m_uiBHLoc,
                              newLoc, 2, grid_limits, domain_limits, dt);

    // Pin an inert (mass-0) BH at its initial location; don't chase a
    // nonexistent well. No-op for a real binary (both > tol).
    constexpr double BH_ACTIVE_MASS_TOL = 1.0e-6;
    if (BH1.getBHMass() > BH_ACTIVE_MASS_TOL) m_uiBHLoc[0] = newLoc[0];
    if (BH2.getBHMass() > BH_ACTIVE_MASS_TOL) m_uiBHLoc[1] = newLoc[1];
    SMOKEMAX_BH_LOC[0] = m_uiBHLoc[0];
    SMOKEMAX_BH_LOC[1] = m_uiBHLoc[1];
    store_bh_loc_history();
}

void SMOKEMAXCtx::store_bh_loc_history() {
    m_uiBHLocHistory.push_back(std::make_pair(m_uiBHLoc[0], m_uiBHLoc[1]));
    m_uiBHTimeHistory.push_back(m_uiTinfo._m_uiT);
}

int SMOKEMAXCtx::write_bh_coords() {
    dendro_gr::writeBHTrajectory(m_uiMesh, m_uiBHLoc, 2, m_uiTinfo._m_uiStep,
                                 m_uiTinfo._m_uiT,
                                 SMOKEMAX_PROFILE_FILE_PREFIX);
    return 0;
}

bool SMOKEMAXCtx::is_bh_merged(double tol) {
    if (m_bIsBHMerged) return true;
    // No binary to merge if either BH is inert. No-op for a real binary.
    constexpr double BH_ACTIVE_MASS_TOL = 1.0e-6;
    if (BH1.getBHMass() <= BH_ACTIVE_MASS_TOL ||
        BH2.getBHMass() <= BH_ACTIVE_MASS_TOL)
        return false;
    double dist = (m_uiBHLoc[0] - m_uiBHLoc[1]).abs();
    return dist < tol;
}

void SMOKEMAXCtx::set_is_merged(double time, uint32_t step) {
    m_bIsBHMerged = true;
    m_dMergeTime = time;
    m_uiMergeStep = step;
    SMOKEMAX_BH_MERGE_TIME = time;
    SMOKEMAX_BH_MERGE_STEP = step;
}

void SMOKEMAXCtx::prepare_for_next_iter() {
    m_bConstraintsComputed = false;
}

int SMOKEMAXCtx::finalize() { return 0; }

}  // namespace smokemax
