#include "temp_test_grad_arrays.h"

namespace cuda {
     double * gpu_grad_0_alpha = NULL;
     double * gpu_grad_1_alpha = NULL;
     double * gpu_grad_2_alpha = NULL;
     double * gpu_grad_0_beta0 = NULL;
     double * gpu_grad_1_beta0 = NULL;
     double * gpu_grad_2_beta0 = NULL;
     double * gpu_grad_0_beta1 = NULL;
     double * gpu_grad_1_beta1 = NULL;
     double * gpu_grad_2_beta1 = NULL;
     double * gpu_grad_0_beta2 = NULL;
     double * gpu_grad_1_beta2 = NULL;
     double * gpu_grad_2_beta2 = NULL;
     double * gpu_grad_0_B0 = NULL;
     double * gpu_grad_1_B0 = NULL;
     double * gpu_grad_2_B0 = NULL;
     double * gpu_grad_0_B1 = NULL;
     double * gpu_grad_1_B1 = NULL;
     double * gpu_grad_2_B1 = NULL;
     double * gpu_grad_0_B2 = NULL;
     double * gpu_grad_1_B2 = NULL;
     double * gpu_grad_2_B2 = NULL;
     double * gpu_grad_0_chi = NULL;
     double * gpu_grad_1_chi = NULL;
     double * gpu_grad_2_chi = NULL;
     double * gpu_grad_0_Gt0 = NULL;
     double * gpu_grad_1_Gt0 = NULL;
     double * gpu_grad_2_Gt0 = NULL;
     double * gpu_grad_0_Gt1 = NULL;
     double * gpu_grad_1_Gt1 = NULL;
     double * gpu_grad_2_Gt1 = NULL;
     double * gpu_grad_0_Gt2 = NULL;
     double * gpu_grad_1_Gt2 = NULL;
     double * gpu_grad_2_Gt2 = NULL;
     double * gpu_grad_0_K = NULL;
     double * gpu_grad_1_K = NULL;
     double * gpu_grad_2_K = NULL;
     double * gpu_grad_0_gt0 = NULL;
     double * gpu_grad_1_gt0 = NULL;
     double * gpu_grad_2_gt0 = NULL;
     double * gpu_grad_0_gt1 = NULL;
     double * gpu_grad_1_gt1 = NULL;
     double * gpu_grad_2_gt1 = NULL;
     double * gpu_grad_0_gt2 = NULL;
     double * gpu_grad_1_gt2 = NULL;
     double * gpu_grad_2_gt2 = NULL;
     double * gpu_grad_0_gt3 = NULL;
     double * gpu_grad_1_gt3 = NULL;
     double * gpu_grad_2_gt3 = NULL;
     double * gpu_grad_0_gt4 = NULL;
     double * gpu_grad_1_gt4 = NULL;
     double * gpu_grad_2_gt4 = NULL;
     double * gpu_grad_0_gt5 = NULL;
     double * gpu_grad_1_gt5 = NULL;
     double * gpu_grad_2_gt5 = NULL;
     double * gpu_grad_0_At0 = NULL;
     double * gpu_grad_1_At0 = NULL;
     double * gpu_grad_2_At0 = NULL;
     double * gpu_grad_0_At1 = NULL;
     double * gpu_grad_1_At1 = NULL;
     double * gpu_grad_2_At1 = NULL;
     double * gpu_grad_0_At2 = NULL;
     double * gpu_grad_1_At2 = NULL;
     double * gpu_grad_2_At2 = NULL;
     double * gpu_grad_0_At3 = NULL;
     double * gpu_grad_1_At3 = NULL;
     double * gpu_grad_2_At3 = NULL;
     double * gpu_grad_0_At4 = NULL;
     double * gpu_grad_1_At4 = NULL;
     double * gpu_grad_2_At4 = NULL;
     double * gpu_grad_0_At5 = NULL;
     double * gpu_grad_1_At5 = NULL;
     double * gpu_grad_2_At5 = NULL;
     double * gpu_grad2_0_0_gt0 = NULL;
     double * gpu_grad2_0_1_gt0 = NULL;
     double * gpu_grad2_0_2_gt0 = NULL;
     double * gpu_grad2_1_1_gt0 = NULL;
     double * gpu_grad2_1_2_gt0 = NULL;
     double * gpu_grad2_2_2_gt0 = NULL;
     double * gpu_grad2_0_0_gt1 = NULL;
     double * gpu_grad2_0_1_gt1 = NULL;
     double * gpu_grad2_0_2_gt1 = NULL;
     double * gpu_grad2_1_1_gt1 = NULL;
     double * gpu_grad2_1_2_gt1 = NULL;
     double * gpu_grad2_2_2_gt1 = NULL;
     double * gpu_grad2_0_0_gt2 = NULL;
     double * gpu_grad2_0_1_gt2 = NULL;
     double * gpu_grad2_0_2_gt2 = NULL;
     double * gpu_grad2_1_1_gt2 = NULL;
     double * gpu_grad2_1_2_gt2 = NULL;
     double * gpu_grad2_2_2_gt2 = NULL;
     double * gpu_grad2_0_0_gt3 = NULL;
     double * gpu_grad2_0_1_gt3 = NULL;
     double * gpu_grad2_0_2_gt3 = NULL;
     double * gpu_grad2_1_1_gt3 = NULL;
     double * gpu_grad2_1_2_gt3 = NULL;
     double * gpu_grad2_2_2_gt3 = NULL;
     double * gpu_grad2_0_0_gt4 = NULL;
     double * gpu_grad2_0_1_gt4 = NULL;
     double * gpu_grad2_0_2_gt4 = NULL;
     double * gpu_grad2_1_1_gt4 = NULL;
     double * gpu_grad2_1_2_gt4 = NULL;
     double * gpu_grad2_2_2_gt4 = NULL;
     double * gpu_grad2_0_0_gt5 = NULL;
     double * gpu_grad2_0_1_gt5 = NULL;
     double * gpu_grad2_0_2_gt5 = NULL;
     double * gpu_grad2_1_1_gt5 = NULL;
     double * gpu_grad2_1_2_gt5 = NULL;
     double * gpu_grad2_2_2_gt5 = NULL;
     double * gpu_grad2_0_0_chi = NULL;
     double * gpu_grad2_0_1_chi = NULL;
     double * gpu_grad2_0_2_chi = NULL;
     double * gpu_grad2_1_1_chi = NULL;
     double * gpu_grad2_1_2_chi = NULL;
     double * gpu_grad2_2_2_chi = NULL;
     double * gpu_grad2_0_0_alpha = NULL;
     double * gpu_grad2_0_1_alpha = NULL;
     double * gpu_grad2_0_2_alpha = NULL;
     double * gpu_grad2_1_1_alpha = NULL;
     double * gpu_grad2_1_2_alpha = NULL;
     double * gpu_grad2_2_2_alpha = NULL;
     double * gpu_grad2_0_0_beta0 = NULL;
     double * gpu_grad2_0_1_beta0 = NULL;
     double * gpu_grad2_0_2_beta0 = NULL;
     double * gpu_grad2_1_1_beta0 = NULL;
     double * gpu_grad2_1_2_beta0 = NULL;
     double * gpu_grad2_2_2_beta0 = NULL;
     double * gpu_grad2_0_0_beta1 = NULL;
     double * gpu_grad2_0_1_beta1 = NULL;
     double * gpu_grad2_0_2_beta1 = NULL;
     double * gpu_grad2_1_1_beta1 = NULL;
     double * gpu_grad2_1_2_beta1 = NULL;
     double * gpu_grad2_2_2_beta1 = NULL;
     double * gpu_grad2_0_0_beta2 = NULL;
     double * gpu_grad2_0_1_beta2 = NULL;
     double * gpu_grad2_0_2_beta2 = NULL;
     double * gpu_grad2_1_1_beta2 = NULL;
     double * gpu_grad2_1_2_beta2 = NULL;
     double * gpu_grad2_2_2_beta2 = NULL;
     double * gpu_agrad_0_gt0 = NULL;
     double * gpu_agrad_1_gt0 = NULL;
     double * gpu_agrad_2_gt0 = NULL;
     double * gpu_agrad_0_gt1 = NULL;
     double * gpu_agrad_1_gt1 = NULL;
     double * gpu_agrad_2_gt1 = NULL;
     double * gpu_agrad_0_gt2 = NULL;
     double * gpu_agrad_1_gt2 = NULL;
     double * gpu_agrad_2_gt2 = NULL;
     double * gpu_agrad_0_gt3 = NULL;
     double * gpu_agrad_1_gt3 = NULL;
     double * gpu_agrad_2_gt3 = NULL;
     double * gpu_agrad_0_gt4 = NULL;
     double * gpu_agrad_1_gt4 = NULL;
     double * gpu_agrad_2_gt4 = NULL;
     double * gpu_agrad_0_gt5 = NULL;
     double * gpu_agrad_1_gt5 = NULL;
     double * gpu_agrad_2_gt5 = NULL;
     double * gpu_agrad_0_At0 = NULL;
     double * gpu_agrad_1_At0 = NULL;
     double * gpu_agrad_2_At0 = NULL;
     double * gpu_agrad_0_At1 = NULL;
     double * gpu_agrad_1_At1 = NULL;
     double * gpu_agrad_2_At1 = NULL;
     double * gpu_agrad_0_At2 = NULL;
     double * gpu_agrad_1_At2 = NULL;
     double * gpu_agrad_2_At2 = NULL;
     double * gpu_agrad_0_At3 = NULL;
     double * gpu_agrad_1_At3 = NULL;
     double * gpu_agrad_2_At3 = NULL;
     double * gpu_agrad_0_At4 = NULL;
     double * gpu_agrad_1_At4 = NULL;
     double * gpu_agrad_2_At4 = NULL;
     double * gpu_agrad_0_At5 = NULL;
     double * gpu_agrad_1_At5 = NULL;
     double * gpu_agrad_2_At5 = NULL;
     double * gpu_agrad_0_alpha = NULL;
     double * gpu_agrad_1_alpha = NULL;
     double * gpu_agrad_2_alpha = NULL;
     double * gpu_agrad_0_beta0 = NULL;
     double * gpu_agrad_1_beta0 = NULL;
     double * gpu_agrad_2_beta0 = NULL;
     double * gpu_agrad_0_beta1 = NULL;
     double * gpu_agrad_1_beta1 = NULL;
     double * gpu_agrad_2_beta1 = NULL;
     double * gpu_agrad_0_beta2 = NULL;
     double * gpu_agrad_1_beta2 = NULL;
     double * gpu_agrad_2_beta2 = NULL;
     double * gpu_agrad_0_chi = NULL;
     double * gpu_agrad_1_chi = NULL;
     double * gpu_agrad_2_chi = NULL;
     double * gpu_agrad_0_Gt0 = NULL;
     double * gpu_agrad_1_Gt0 = NULL;
     double * gpu_agrad_2_Gt0 = NULL;
     double * gpu_agrad_0_Gt1 = NULL;
     double * gpu_agrad_1_Gt1 = NULL;
     double * gpu_agrad_2_Gt1 = NULL;
     double * gpu_agrad_0_Gt2 = NULL;
     double * gpu_agrad_1_Gt2 = NULL;
     double * gpu_agrad_2_Gt2 = NULL;
     double * gpu_agrad_0_K = NULL;
     double * gpu_agrad_1_K = NULL;
     double * gpu_agrad_2_K = NULL;
     double * gpu_agrad_0_B0 = NULL;
     double * gpu_agrad_1_B0 = NULL;
     double * gpu_agrad_2_B0 = NULL;
     double * gpu_agrad_0_B1 = NULL;
     double * gpu_agrad_1_B1 = NULL;
     double * gpu_agrad_2_B1 = NULL;
     double * gpu_agrad_0_B2 = NULL;
     double * gpu_agrad_1_B2 = NULL;
     double * gpu_agrad_2_B2 = NULL;
     double * gpu_kograd_0_alpha = NULL;
     double * gpu_kograd_1_alpha = NULL;
     double * gpu_kograd_2_alpha = NULL;
     double * gpu_kograd_0_beta0 = NULL;
     double * gpu_kograd_1_beta0 = NULL;
     double * gpu_kograd_2_beta0 = NULL;
     double * gpu_kograd_0_beta1 = NULL;
     double * gpu_kograd_1_beta1 = NULL;
     double * gpu_kograd_2_beta1 = NULL;
     double * gpu_kograd_0_beta2 = NULL;
     double * gpu_kograd_1_beta2 = NULL;
     double * gpu_kograd_2_beta2 = NULL;
     double * gpu_kograd_0_B0 = NULL;
     double * gpu_kograd_1_B0 = NULL;
     double * gpu_kograd_2_B0 = NULL;
     double * gpu_kograd_0_B1 = NULL;
     double * gpu_kograd_1_B1 = NULL;
     double * gpu_kograd_2_B1 = NULL;
     double * gpu_kograd_0_B2 = NULL;
     double * gpu_kograd_1_B2 = NULL;
     double * gpu_kograd_2_B2 = NULL;
     double * gpu_kograd_0_chi = NULL;
     double * gpu_kograd_1_chi = NULL;
     double * gpu_kograd_2_chi = NULL;
     double * gpu_kograd_0_Gt0 = NULL;
     double * gpu_kograd_1_Gt0 = NULL;
     double * gpu_kograd_2_Gt0 = NULL;
     double * gpu_kograd_0_Gt1 = NULL;
     double * gpu_kograd_1_Gt1 = NULL;
     double * gpu_kograd_2_Gt1 = NULL;
     double * gpu_kograd_0_Gt2 = NULL;
     double * gpu_kograd_1_Gt2 = NULL;
     double * gpu_kograd_2_Gt2 = NULL;
     double * gpu_kograd_0_K = NULL;
     double * gpu_kograd_1_K = NULL;
     double * gpu_kograd_2_K = NULL;
     double * gpu_kograd_0_gt0 = NULL;
     double * gpu_kograd_1_gt0 = NULL;
     double * gpu_kograd_2_gt0 = NULL;
     double * gpu_kograd_0_gt1 = NULL;
     double * gpu_kograd_1_gt1 = NULL;
     double * gpu_kograd_2_gt1 = NULL;
     double * gpu_kograd_0_gt2 = NULL;
     double * gpu_kograd_1_gt2 = NULL;
     double * gpu_kograd_2_gt2 = NULL;
     double * gpu_kograd_0_gt3 = NULL;
     double * gpu_kograd_1_gt3 = NULL;
     double * gpu_kograd_2_gt3 = NULL;
     double * gpu_kograd_0_gt4 = NULL;
     double * gpu_kograd_1_gt4 = NULL;
     double * gpu_kograd_2_gt4 = NULL;
     double * gpu_kograd_0_gt5 = NULL;
     double * gpu_kograd_1_gt5 = NULL;
     double * gpu_kograd_2_gt5 = NULL;
     double * gpu_kograd_0_At0 = NULL;
     double * gpu_kograd_1_At0 = NULL;
     double * gpu_kograd_2_At0 = NULL;
     double * gpu_kograd_0_At1 = NULL;
     double * gpu_kograd_1_At1 = NULL;
     double * gpu_kograd_2_At1 = NULL;
     double * gpu_kograd_0_At2 = NULL;
     double * gpu_kograd_1_At2 = NULL;
     double * gpu_kograd_2_At2 = NULL;
     double * gpu_kograd_0_At3 = NULL;
     double * gpu_kograd_1_At3 = NULL;
     double * gpu_kograd_2_At3 = NULL;
     double * gpu_kograd_0_At4 = NULL;
     double * gpu_kograd_1_At4 = NULL;
     double * gpu_kograd_2_At4 = NULL;
     double * gpu_kograd_0_At5 = NULL;
     double * gpu_kograd_1_At5 = NULL;
     double * gpu_kograd_2_At5 = NULL;

     void intermediate_arrays_dtoh(cuda::MemoryDerivs md, int eleSize)
     {
        gpu_grad_0_alpha = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_alpha = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_alpha = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_beta0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_beta0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_beta0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_beta1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_beta1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_beta1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_beta2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_beta2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_beta2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_B0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_B0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_B0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_B1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_B1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_B1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_B2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_B2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_B2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_chi = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_chi = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_chi = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_Gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_Gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_Gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_Gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_Gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_Gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_Gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_Gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_Gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_K = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_K = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_K = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_gt3 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_gt3 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_gt3 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_gt4 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_gt4 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_gt4 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_gt5 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_gt5 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_gt5 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_At0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_At0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_At0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_At1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_At1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_At1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_At2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_At2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_At2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_At3 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_At3 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_At3 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_At4 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_At4 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_At4 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_0_At5 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_1_At5 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad_2_At5 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_0_gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_1_gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_2_gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_1_gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_2_gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_2_2_gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_0_gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_1_gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_2_gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_1_gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_2_gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_2_2_gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_0_gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_1_gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_2_gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_1_gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_2_gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_2_2_gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_0_gt3 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_1_gt3 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_2_gt3 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_1_gt3 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_2_gt3 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_2_2_gt3 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_0_gt4 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_1_gt4 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_2_gt4 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_1_gt4 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_2_gt4 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_2_2_gt4 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_0_gt5 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_1_gt5 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_2_gt5 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_1_gt5 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_2_gt5 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_2_2_gt5 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_0_chi = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_1_chi = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_2_chi = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_1_chi = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_2_chi = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_2_2_chi = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_0_alpha = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_1_alpha = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_2_alpha = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_1_alpha = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_2_alpha = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_2_2_alpha = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_0_beta0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_1_beta0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_2_beta0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_1_beta0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_2_beta0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_2_2_beta0 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_0_beta1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_1_beta1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_2_beta1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_1_beta1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_2_beta1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_2_2_beta1 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_0_beta2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_1_beta2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_0_2_beta2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_1_beta2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_1_2_beta2 = (double *) calloc(eleSize, sizeof(double));
        gpu_grad2_2_2_beta2 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_gt3 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_gt3 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_gt3 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_gt4 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_gt4 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_gt4 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_gt5 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_gt5 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_gt5 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_At0 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_At0 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_At0 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_At1 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_At1 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_At1 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_At2 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_At2 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_At2 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_At3 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_At3 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_At3 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_At4 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_At4 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_At4 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_At5 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_At5 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_At5 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_alpha = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_alpha = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_alpha = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_beta0 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_beta0 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_beta0 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_beta1 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_beta1 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_beta1 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_beta2 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_beta2 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_beta2 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_chi = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_chi = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_chi = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_Gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_Gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_Gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_Gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_Gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_Gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_Gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_Gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_Gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_K = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_K = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_K = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_B0 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_B0 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_B0 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_B1 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_B1 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_B1 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_0_B2 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_1_B2 = (double *) calloc(eleSize, sizeof(double));
        gpu_agrad_2_B2 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_alpha = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_alpha = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_alpha = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_beta0 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_beta0 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_beta0 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_beta1 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_beta1 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_beta1 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_beta2 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_beta2 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_beta2 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_B0 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_B0 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_B0 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_B1 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_B1 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_B1 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_B2 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_B2 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_B2 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_chi = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_chi = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_chi = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_Gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_Gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_Gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_Gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_Gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_Gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_Gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_Gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_Gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_K = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_K = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_K = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_gt0 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_gt1 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_gt2 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_gt3 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_gt3 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_gt3 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_gt4 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_gt4 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_gt4 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_gt5 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_gt5 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_gt5 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_At0 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_At0 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_At0 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_At1 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_At1 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_At1 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_At2 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_At2 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_At2 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_At3 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_At3 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_At3 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_At4 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_At4 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_At4 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_0_At5 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_1_At5 = (double *) calloc(eleSize, sizeof(double));
        gpu_kograd_2_At5 = (double *) calloc(eleSize, sizeof(double));

        cudaMemcpy(gpu_grad_0_alpha, md.__grad_0_alpha, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_alpha, md.__grad_1_alpha, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_alpha, md.__grad_2_alpha, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_beta0, md.__grad_0_beta0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_beta0, md.__grad_1_beta0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_beta0, md.__grad_2_beta0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_beta1, md.__grad_0_beta1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_beta1, md.__grad_1_beta1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_beta1, md.__grad_2_beta1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_beta2, md.__grad_0_beta2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_beta2, md.__grad_1_beta2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_beta2, md.__grad_2_beta2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_B0, md.__grad_0_B0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_B0, md.__grad_1_B0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_B0, md.__grad_2_B0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_B1, md.__grad_0_B1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_B1, md.__grad_1_B1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_B1, md.__grad_2_B1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_B2, md.__grad_0_B2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_B2, md.__grad_1_B2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_B2, md.__grad_2_B2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_chi, md.__grad_0_chi, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_chi, md.__grad_1_chi, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_chi, md.__grad_2_chi, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_Gt0, md.__grad_0_Gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_Gt0, md.__grad_1_Gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_Gt0, md.__grad_2_Gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_Gt1, md.__grad_0_Gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_Gt1, md.__grad_1_Gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_Gt1, md.__grad_2_Gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_Gt2, md.__grad_0_Gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_Gt2, md.__grad_1_Gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_Gt2, md.__grad_2_Gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_K, md.__grad_0_K, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_K, md.__grad_1_K, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_K, md.__grad_2_K, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_gt0, md.__grad_0_gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_gt0, md.__grad_1_gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_gt0, md.__grad_2_gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_gt1, md.__grad_0_gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_gt1, md.__grad_1_gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_gt1, md.__grad_2_gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_gt2, md.__grad_0_gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_gt2, md.__grad_1_gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_gt2, md.__grad_2_gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_gt3, md.__grad_0_gt3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_gt3, md.__grad_1_gt3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_gt3, md.__grad_2_gt3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_gt4, md.__grad_0_gt4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_gt4, md.__grad_1_gt4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_gt4, md.__grad_2_gt4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_gt5, md.__grad_0_gt5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_gt5, md.__grad_1_gt5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_gt5, md.__grad_2_gt5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_At0, md.__grad_0_At0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_At0, md.__grad_1_At0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_At0, md.__grad_2_At0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_At1, md.__grad_0_At1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_At1, md.__grad_1_At1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_At1, md.__grad_2_At1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_At2, md.__grad_0_At2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_At2, md.__grad_1_At2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_At2, md.__grad_2_At2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_At3, md.__grad_0_At3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_At3, md.__grad_1_At3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_At3, md.__grad_2_At3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_At4, md.__grad_0_At4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_At4, md.__grad_1_At4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_At4, md.__grad_2_At4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_0_At5, md.__grad_0_At5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_1_At5, md.__grad_1_At5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad_2_At5, md.__grad_2_At5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_0_gt0, md.__grad2_0_0_gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_1_gt0, md.__grad2_0_1_gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_2_gt0, md.__grad2_0_2_gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_1_gt0, md.__grad2_1_1_gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_2_gt0, md.__grad2_1_2_gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_2_2_gt0, md.__grad2_2_2_gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_0_gt1, md.__grad2_0_0_gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_1_gt1, md.__grad2_0_1_gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_2_gt1, md.__grad2_0_2_gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_1_gt1, md.__grad2_1_1_gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_2_gt1, md.__grad2_1_2_gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_2_2_gt1, md.__grad2_2_2_gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_0_gt2, md.__grad2_0_0_gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_1_gt2, md.__grad2_0_1_gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_2_gt2, md.__grad2_0_2_gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_1_gt2, md.__grad2_1_1_gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_2_gt2, md.__grad2_1_2_gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_2_2_gt2, md.__grad2_2_2_gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_0_gt3, md.__grad2_0_0_gt3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_1_gt3, md.__grad2_0_1_gt3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_2_gt3, md.__grad2_0_2_gt3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_1_gt3, md.__grad2_1_1_gt3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_2_gt3, md.__grad2_1_2_gt3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_2_2_gt3, md.__grad2_2_2_gt3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_0_gt4, md.__grad2_0_0_gt4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_1_gt4, md.__grad2_0_1_gt4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_2_gt4, md.__grad2_0_2_gt4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_1_gt4, md.__grad2_1_1_gt4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_2_gt4, md.__grad2_1_2_gt4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_2_2_gt4, md.__grad2_2_2_gt4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_0_gt5, md.__grad2_0_0_gt5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_1_gt5, md.__grad2_0_1_gt5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_2_gt5, md.__grad2_0_2_gt5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_1_gt5, md.__grad2_1_1_gt5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_2_gt5, md.__grad2_1_2_gt5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_2_2_gt5, md.__grad2_2_2_gt5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_0_chi, md.__grad2_0_0_chi, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_1_chi, md.__grad2_0_1_chi, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_2_chi, md.__grad2_0_2_chi, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_1_chi, md.__grad2_1_1_chi, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_2_chi, md.__grad2_1_2_chi, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_2_2_chi, md.__grad2_2_2_chi, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_0_alpha, md.__grad2_0_0_alpha, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_1_alpha, md.__grad2_0_1_alpha, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_2_alpha, md.__grad2_0_2_alpha, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_1_alpha, md.__grad2_1_1_alpha, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_2_alpha, md.__grad2_1_2_alpha, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_2_2_alpha, md.__grad2_2_2_alpha, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_0_beta0, md.__grad2_0_0_beta0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_1_beta0, md.__grad2_0_1_beta0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_2_beta0, md.__grad2_0_2_beta0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_1_beta0, md.__grad2_1_1_beta0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_2_beta0, md.__grad2_1_2_beta0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_2_2_beta0, md.__grad2_2_2_beta0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_0_beta1, md.__grad2_0_0_beta1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_1_beta1, md.__grad2_0_1_beta1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_2_beta1, md.__grad2_0_2_beta1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_1_beta1, md.__grad2_1_1_beta1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_2_beta1, md.__grad2_1_2_beta1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_2_2_beta1, md.__grad2_2_2_beta1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_0_beta2, md.__grad2_0_0_beta2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_1_beta2, md.__grad2_0_1_beta2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_0_2_beta2, md.__grad2_0_2_beta2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_1_beta2, md.__grad2_1_1_beta2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_1_2_beta2, md.__grad2_1_2_beta2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_grad2_2_2_beta2, md.__grad2_2_2_beta2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_gt0, md.__agrad_0_gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_gt0, md.__agrad_1_gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_gt0, md.__agrad_2_gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_gt1, md.__agrad_0_gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_gt1, md.__agrad_1_gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_gt1, md.__agrad_2_gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_gt2, md.__agrad_0_gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_gt2, md.__agrad_1_gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_gt2, md.__agrad_2_gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_gt3, md.__agrad_0_gt3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_gt3, md.__agrad_1_gt3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_gt3, md.__agrad_2_gt3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_gt4, md.__agrad_0_gt4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_gt4, md.__agrad_1_gt4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_gt4, md.__agrad_2_gt4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_gt5, md.__agrad_0_gt5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_gt5, md.__agrad_1_gt5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_gt5, md.__agrad_2_gt5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_At0, md.__agrad_0_At0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_At0, md.__agrad_1_At0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_At0, md.__agrad_2_At0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_At1, md.__agrad_0_At1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_At1, md.__agrad_1_At1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_At1, md.__agrad_2_At1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_At2, md.__agrad_0_At2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_At2, md.__agrad_1_At2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_At2, md.__agrad_2_At2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_At3, md.__agrad_0_At3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_At3, md.__agrad_1_At3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_At3, md.__agrad_2_At3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_At4, md.__agrad_0_At4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_At4, md.__agrad_1_At4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_At4, md.__agrad_2_At4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_At5, md.__agrad_0_At5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_At5, md.__agrad_1_At5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_At5, md.__agrad_2_At5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_alpha, md.__agrad_0_alpha, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_alpha, md.__agrad_1_alpha, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_alpha, md.__agrad_2_alpha, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_beta0, md.__agrad_0_beta0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_beta0, md.__agrad_1_beta0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_beta0, md.__agrad_2_beta0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_beta1, md.__agrad_0_beta1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_beta1, md.__agrad_1_beta1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_beta1, md.__agrad_2_beta1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_beta2, md.__agrad_0_beta2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_beta2, md.__agrad_1_beta2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_beta2, md.__agrad_2_beta2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_chi, md.__agrad_0_chi, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_chi, md.__agrad_1_chi, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_chi, md.__agrad_2_chi, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_Gt0, md.__agrad_0_Gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_Gt0, md.__agrad_1_Gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_Gt0, md.__agrad_2_Gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_Gt1, md.__agrad_0_Gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_Gt1, md.__agrad_1_Gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_Gt1, md.__agrad_2_Gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_Gt2, md.__agrad_0_Gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_Gt2, md.__agrad_1_Gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_Gt2, md.__agrad_2_Gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_K, md.__agrad_0_K, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_K, md.__agrad_1_K, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_K, md.__agrad_2_K, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_B0, md.__agrad_0_B0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_B0, md.__agrad_1_B0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_B0, md.__agrad_2_B0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_B1, md.__agrad_0_B1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_B1, md.__agrad_1_B1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_B1, md.__agrad_2_B1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_0_B2, md.__agrad_0_B2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_1_B2, md.__agrad_1_B2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_agrad_2_B2, md.__agrad_2_B2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_alpha, md.__kograd_0_alpha, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_alpha, md.__kograd_1_alpha, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_alpha, md.__kograd_2_alpha, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_beta0, md.__kograd_0_beta0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_beta0, md.__kograd_1_beta0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_beta0, md.__kograd_2_beta0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_beta1, md.__kograd_0_beta1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_beta1, md.__kograd_1_beta1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_beta1, md.__kograd_2_beta1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_beta2, md.__kograd_0_beta2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_beta2, md.__kograd_1_beta2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_beta2, md.__kograd_2_beta2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_B0, md.__kograd_0_B0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_B0, md.__kograd_1_B0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_B0, md.__kograd_2_B0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_B1, md.__kograd_0_B1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_B1, md.__kograd_1_B1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_B1, md.__kograd_2_B1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_B2, md.__kograd_0_B2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_B2, md.__kograd_1_B2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_B2, md.__kograd_2_B2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_chi, md.__kograd_0_chi, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_chi, md.__kograd_1_chi, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_chi, md.__kograd_2_chi, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_Gt0, md.__kograd_0_Gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_Gt0, md.__kograd_1_Gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_Gt0, md.__kograd_2_Gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_Gt1, md.__kograd_0_Gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_Gt1, md.__kograd_1_Gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_Gt1, md.__kograd_2_Gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_Gt2, md.__kograd_0_Gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_Gt2, md.__kograd_1_Gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_Gt2, md.__kograd_2_Gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_K, md.__kograd_0_K, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_K, md.__kograd_1_K, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_K, md.__kograd_2_K, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_gt0, md.__kograd_0_gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_gt0, md.__kograd_1_gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_gt0, md.__kograd_2_gt0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_gt1, md.__kograd_0_gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_gt1, md.__kograd_1_gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_gt1, md.__kograd_2_gt1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_gt2, md.__kograd_0_gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_gt2, md.__kograd_1_gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_gt2, md.__kograd_2_gt2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_gt3, md.__kograd_0_gt3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_gt3, md.__kograd_1_gt3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_gt3, md.__kograd_2_gt3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_gt4, md.__kograd_0_gt4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_gt4, md.__kograd_1_gt4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_gt4, md.__kograd_2_gt4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_gt5, md.__kograd_0_gt5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_gt5, md.__kograd_1_gt5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_gt5, md.__kograd_2_gt5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_At0, md.__kograd_0_At0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_At0, md.__kograd_1_At0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_At0, md.__kograd_2_At0, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_At1, md.__kograd_0_At1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_At1, md.__kograd_1_At1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_At1, md.__kograd_2_At1, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_At2, md.__kograd_0_At2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_At2, md.__kograd_1_At2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_At2, md.__kograd_2_At2, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_At3, md.__kograd_0_At3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_At3, md.__kograd_1_At3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_At3, md.__kograd_2_At3, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_At4, md.__kograd_0_At4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_At4, md.__kograd_1_At4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_At4, md.__kograd_2_At4, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_0_At5, md.__kograd_0_At5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_1_At5, md.__kograd_1_At5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);
        cudaMemcpy(gpu_kograd_2_At5, md.__kograd_2_At5, sizeof(double)*eleSize, cudaMemcpyDeviceToHost);

        CUDA_CHECK_ERROR();
     } 

     void release_intermediate_array_memory()
     {
        free(gpu_grad_0_alpha);
        free(gpu_grad_1_alpha);
        free(gpu_grad_2_alpha);
        free(gpu_grad_0_beta0);
        free(gpu_grad_1_beta0);
        free(gpu_grad_2_beta0);
        free(gpu_grad_0_beta1);
        free(gpu_grad_1_beta1);
        free(gpu_grad_2_beta1);
        free(gpu_grad_0_beta2);
        free(gpu_grad_1_beta2);
        free(gpu_grad_2_beta2);
        free(gpu_grad_0_B0);
        free(gpu_grad_1_B0);
        free(gpu_grad_2_B0);
        free(gpu_grad_0_B1);
        free(gpu_grad_1_B1);
        free(gpu_grad_2_B1);
        free(gpu_grad_0_B2);
        free(gpu_grad_1_B2);
        free(gpu_grad_2_B2);
        free(gpu_grad_0_chi);
        free(gpu_grad_1_chi);
        free(gpu_grad_2_chi);
        free(gpu_grad_0_Gt0);
        free(gpu_grad_1_Gt0);
        free(gpu_grad_2_Gt0);
        free(gpu_grad_0_Gt1);
        free(gpu_grad_1_Gt1);
        free(gpu_grad_2_Gt1);
        free(gpu_grad_0_Gt2);
        free(gpu_grad_1_Gt2);
        free(gpu_grad_2_Gt2);
        free(gpu_grad_0_K);
        free(gpu_grad_1_K);
        free(gpu_grad_2_K);
        free(gpu_grad_0_gt0);
        free(gpu_grad_1_gt0);
        free(gpu_grad_2_gt0);
        free(gpu_grad_0_gt1);
        free(gpu_grad_1_gt1);
        free(gpu_grad_2_gt1);
        free(gpu_grad_0_gt2);
        free(gpu_grad_1_gt2);
        free(gpu_grad_2_gt2);
        free(gpu_grad_0_gt3);
        free(gpu_grad_1_gt3);
        free(gpu_grad_2_gt3);
        free(gpu_grad_0_gt4);
        free(gpu_grad_1_gt4);
        free(gpu_grad_2_gt4);
        free(gpu_grad_0_gt5);
        free(gpu_grad_1_gt5);
        free(gpu_grad_2_gt5);
        free(gpu_grad_0_At0);
        free(gpu_grad_1_At0);
        free(gpu_grad_2_At0);
        free(gpu_grad_0_At1);
        free(gpu_grad_1_At1);
        free(gpu_grad_2_At1);
        free(gpu_grad_0_At2);
        free(gpu_grad_1_At2);
        free(gpu_grad_2_At2);
        free(gpu_grad_0_At3);
        free(gpu_grad_1_At3);
        free(gpu_grad_2_At3);
        free(gpu_grad_0_At4);
        free(gpu_grad_1_At4);
        free(gpu_grad_2_At4);
        free(gpu_grad_0_At5);
        free(gpu_grad_1_At5);
        free(gpu_grad_2_At5);
        free(gpu_grad2_0_0_gt0);
        free(gpu_grad2_0_1_gt0);
        free(gpu_grad2_0_2_gt0);
        free(gpu_grad2_1_1_gt0);
        free(gpu_grad2_1_2_gt0);
        free(gpu_grad2_2_2_gt0);
        free(gpu_grad2_0_0_gt1);
        free(gpu_grad2_0_1_gt1);
        free(gpu_grad2_0_2_gt1);
        free(gpu_grad2_1_1_gt1);
        free(gpu_grad2_1_2_gt1);
        free(gpu_grad2_2_2_gt1);
        free(gpu_grad2_0_0_gt2);
        free(gpu_grad2_0_1_gt2);
        free(gpu_grad2_0_2_gt2);
        free(gpu_grad2_1_1_gt2);
        free(gpu_grad2_1_2_gt2);
        free(gpu_grad2_2_2_gt2);
        free(gpu_grad2_0_0_gt3);
        free(gpu_grad2_0_1_gt3);
        free(gpu_grad2_0_2_gt3);
        free(gpu_grad2_1_1_gt3);
        free(gpu_grad2_1_2_gt3);
        free(gpu_grad2_2_2_gt3);
        free(gpu_grad2_0_0_gt4);
        free(gpu_grad2_0_1_gt4);
        free(gpu_grad2_0_2_gt4);
        free(gpu_grad2_1_1_gt4);
        free(gpu_grad2_1_2_gt4);
        free(gpu_grad2_2_2_gt4);
        free(gpu_grad2_0_0_gt5);
        free(gpu_grad2_0_1_gt5);
        free(gpu_grad2_0_2_gt5);
        free(gpu_grad2_1_1_gt5);
        free(gpu_grad2_1_2_gt5);
        free(gpu_grad2_2_2_gt5);
        free(gpu_grad2_0_0_chi);
        free(gpu_grad2_0_1_chi);
        free(gpu_grad2_0_2_chi);
        free(gpu_grad2_1_1_chi);
        free(gpu_grad2_1_2_chi);
        free(gpu_grad2_2_2_chi);
        free(gpu_grad2_0_0_alpha);
        free(gpu_grad2_0_1_alpha);
        free(gpu_grad2_0_2_alpha);
        free(gpu_grad2_1_1_alpha);
        free(gpu_grad2_1_2_alpha);
        free(gpu_grad2_2_2_alpha);
        free(gpu_grad2_0_0_beta0);
        free(gpu_grad2_0_1_beta0);
        free(gpu_grad2_0_2_beta0);
        free(gpu_grad2_1_1_beta0);
        free(gpu_grad2_1_2_beta0);
        free(gpu_grad2_2_2_beta0);
        free(gpu_grad2_0_0_beta1);
        free(gpu_grad2_0_1_beta1);
        free(gpu_grad2_0_2_beta1);
        free(gpu_grad2_1_1_beta1);
        free(gpu_grad2_1_2_beta1);
        free(gpu_grad2_2_2_beta1);
        free(gpu_grad2_0_0_beta2);
        free(gpu_grad2_0_1_beta2);
        free(gpu_grad2_0_2_beta2);
        free(gpu_grad2_1_1_beta2);
        free(gpu_grad2_1_2_beta2);
        free(gpu_grad2_2_2_beta2);
        free(gpu_agrad_0_gt0);
        free(gpu_agrad_1_gt0);
        free(gpu_agrad_2_gt0);
        free(gpu_agrad_0_gt1);
        free(gpu_agrad_1_gt1);
        free(gpu_agrad_2_gt1);
        free(gpu_agrad_0_gt2);
        free(gpu_agrad_1_gt2);
        free(gpu_agrad_2_gt2);
        free(gpu_agrad_0_gt3);
        free(gpu_agrad_1_gt3);
        free(gpu_agrad_2_gt3);
        free(gpu_agrad_0_gt4);
        free(gpu_agrad_1_gt4);
        free(gpu_agrad_2_gt4);
        free(gpu_agrad_0_gt5);
        free(gpu_agrad_1_gt5);
        free(gpu_agrad_2_gt5);
        free(gpu_agrad_0_At0);
        free(gpu_agrad_1_At0);
        free(gpu_agrad_2_At0);
        free(gpu_agrad_0_At1);
        free(gpu_agrad_1_At1);
        free(gpu_agrad_2_At1);
        free(gpu_agrad_0_At2);
        free(gpu_agrad_1_At2);
        free(gpu_agrad_2_At2);
        free(gpu_agrad_0_At3);
        free(gpu_agrad_1_At3);
        free(gpu_agrad_2_At3);
        free(gpu_agrad_0_At4);
        free(gpu_agrad_1_At4);
        free(gpu_agrad_2_At4);
        free(gpu_agrad_0_At5);
        free(gpu_agrad_1_At5);
        free(gpu_agrad_2_At5);
        free(gpu_agrad_0_alpha);
        free(gpu_agrad_1_alpha);
        free(gpu_agrad_2_alpha);
        free(gpu_agrad_0_beta0);
        free(gpu_agrad_1_beta0);
        free(gpu_agrad_2_beta0);
        free(gpu_agrad_0_beta1);
        free(gpu_agrad_1_beta1);
        free(gpu_agrad_2_beta1);
        free(gpu_agrad_0_beta2);
        free(gpu_agrad_1_beta2);
        free(gpu_agrad_2_beta2);
        free(gpu_agrad_0_chi);
        free(gpu_agrad_1_chi);
        free(gpu_agrad_2_chi);
        free(gpu_agrad_0_Gt0);
        free(gpu_agrad_1_Gt0);
        free(gpu_agrad_2_Gt0);
        free(gpu_agrad_0_Gt1);
        free(gpu_agrad_1_Gt1);
        free(gpu_agrad_2_Gt1);
        free(gpu_agrad_0_Gt2);
        free(gpu_agrad_1_Gt2);
        free(gpu_agrad_2_Gt2);
        free(gpu_agrad_0_K);
        free(gpu_agrad_1_K);
        free(gpu_agrad_2_K);
        free(gpu_agrad_0_B0);
        free(gpu_agrad_1_B0);
        free(gpu_agrad_2_B0);
        free(gpu_agrad_0_B1);
        free(gpu_agrad_1_B1);
        free(gpu_agrad_2_B1);
        free(gpu_agrad_0_B2);
        free(gpu_agrad_1_B2);
        free(gpu_agrad_2_B2);
        free(gpu_kograd_0_alpha);
        free(gpu_kograd_1_alpha);
        free(gpu_kograd_2_alpha);
        free(gpu_kograd_0_beta0);
        free(gpu_kograd_1_beta0);
        free(gpu_kograd_2_beta0);
        free(gpu_kograd_0_beta1);
        free(gpu_kograd_1_beta1);
        free(gpu_kograd_2_beta1);
        free(gpu_kograd_0_beta2);
        free(gpu_kograd_1_beta2);
        free(gpu_kograd_2_beta2);
        free(gpu_kograd_0_B0);
        free(gpu_kograd_1_B0);
        free(gpu_kograd_2_B0);
        free(gpu_kograd_0_B1);
        free(gpu_kograd_1_B1);
        free(gpu_kograd_2_B1);
        free(gpu_kograd_0_B2);
        free(gpu_kograd_1_B2);
        free(gpu_kograd_2_B2);
        free(gpu_kograd_0_chi);
        free(gpu_kograd_1_chi);
        free(gpu_kograd_2_chi);
        free(gpu_kograd_0_Gt0);
        free(gpu_kograd_1_Gt0);
        free(gpu_kograd_2_Gt0);
        free(gpu_kograd_0_Gt1);
        free(gpu_kograd_1_Gt1);
        free(gpu_kograd_2_Gt1);
        free(gpu_kograd_0_Gt2);
        free(gpu_kograd_1_Gt2);
        free(gpu_kograd_2_Gt2);
        free(gpu_kograd_0_K);
        free(gpu_kograd_1_K);
        free(gpu_kograd_2_K);
        free(gpu_kograd_0_gt0);
        free(gpu_kograd_1_gt0);
        free(gpu_kograd_2_gt0);
        free(gpu_kograd_0_gt1);
        free(gpu_kograd_1_gt1);
        free(gpu_kograd_2_gt1);
        free(gpu_kograd_0_gt2);
        free(gpu_kograd_1_gt2);
        free(gpu_kograd_2_gt2);
        free(gpu_kograd_0_gt3);
        free(gpu_kograd_1_gt3);
        free(gpu_kograd_2_gt3);
        free(gpu_kograd_0_gt4);
        free(gpu_kograd_1_gt4);
        free(gpu_kograd_2_gt4);
        free(gpu_kograd_0_gt5);
        free(gpu_kograd_1_gt5);
        free(gpu_kograd_2_gt5);
        free(gpu_kograd_0_At0);
        free(gpu_kograd_1_At0);
        free(gpu_kograd_2_At0);
        free(gpu_kograd_0_At1);
        free(gpu_kograd_1_At1);
        free(gpu_kograd_2_At1);
        free(gpu_kograd_0_At2);
        free(gpu_kograd_1_At2);
        free(gpu_kograd_2_At2);
        free(gpu_kograd_0_At3);
        free(gpu_kograd_1_At3);
        free(gpu_kograd_2_At3);
        free(gpu_kograd_0_At4);
        free(gpu_kograd_1_At4);
        free(gpu_kograd_2_At4);
        free(gpu_kograd_0_At5);
        free(gpu_kograd_1_At5);
        free(gpu_kograd_2_At5);
     }
}

 double * cpu_grad_0_alpha = NULL;
 double * cpu_grad_1_alpha = NULL;
 double * cpu_grad_2_alpha = NULL;
 double * cpu_grad_0_beta0 = NULL;
 double * cpu_grad_1_beta0 = NULL;
 double * cpu_grad_2_beta0 = NULL;
 double * cpu_grad_0_beta1 = NULL;
 double * cpu_grad_1_beta1 = NULL;
 double * cpu_grad_2_beta1 = NULL;
 double * cpu_grad_0_beta2 = NULL;
 double * cpu_grad_1_beta2 = NULL;
 double * cpu_grad_2_beta2 = NULL;
 double * cpu_grad_0_B0 = NULL;
 double * cpu_grad_1_B0 = NULL;
 double * cpu_grad_2_B0 = NULL;
 double * cpu_grad_0_B1 = NULL;
 double * cpu_grad_1_B1 = NULL;
 double * cpu_grad_2_B1 = NULL;
 double * cpu_grad_0_B2 = NULL;
 double * cpu_grad_1_B2 = NULL;
 double * cpu_grad_2_B2 = NULL;
 double * cpu_grad_0_chi = NULL;
 double * cpu_grad_1_chi = NULL;
 double * cpu_grad_2_chi = NULL;
 double * cpu_grad_0_Gt0 = NULL;
 double * cpu_grad_1_Gt0 = NULL;
 double * cpu_grad_2_Gt0 = NULL;
 double * cpu_grad_0_Gt1 = NULL;
 double * cpu_grad_1_Gt1 = NULL;
 double * cpu_grad_2_Gt1 = NULL;
 double * cpu_grad_0_Gt2 = NULL;
 double * cpu_grad_1_Gt2 = NULL;
 double * cpu_grad_2_Gt2 = NULL;
 double * cpu_grad_0_K = NULL;
 double * cpu_grad_1_K = NULL;
 double * cpu_grad_2_K = NULL;
 double * cpu_grad_0_gt0 = NULL;
 double * cpu_grad_1_gt0 = NULL;
 double * cpu_grad_2_gt0 = NULL;
 double * cpu_grad_0_gt1 = NULL;
 double * cpu_grad_1_gt1 = NULL;
 double * cpu_grad_2_gt1 = NULL;
 double * cpu_grad_0_gt2 = NULL;
 double * cpu_grad_1_gt2 = NULL;
 double * cpu_grad_2_gt2 = NULL;
 double * cpu_grad_0_gt3 = NULL;
 double * cpu_grad_1_gt3 = NULL;
 double * cpu_grad_2_gt3 = NULL;
 double * cpu_grad_0_gt4 = NULL;
 double * cpu_grad_1_gt4 = NULL;
 double * cpu_grad_2_gt4 = NULL;
 double * cpu_grad_0_gt5 = NULL;
 double * cpu_grad_1_gt5 = NULL;
 double * cpu_grad_2_gt5 = NULL;
 double * cpu_grad_0_At0 = NULL;
 double * cpu_grad_1_At0 = NULL;
 double * cpu_grad_2_At0 = NULL;
 double * cpu_grad_0_At1 = NULL;
 double * cpu_grad_1_At1 = NULL;
 double * cpu_grad_2_At1 = NULL;
 double * cpu_grad_0_At2 = NULL;
 double * cpu_grad_1_At2 = NULL;
 double * cpu_grad_2_At2 = NULL;
 double * cpu_grad_0_At3 = NULL;
 double * cpu_grad_1_At3 = NULL;
 double * cpu_grad_2_At3 = NULL;
 double * cpu_grad_0_At4 = NULL;
 double * cpu_grad_1_At4 = NULL;
 double * cpu_grad_2_At4 = NULL;
 double * cpu_grad_0_At5 = NULL;
 double * cpu_grad_1_At5 = NULL;
 double * cpu_grad_2_At5 = NULL;
 double * cpu_grad2_0_0_gt0 = NULL;
 double * cpu_grad2_0_1_gt0 = NULL;
 double * cpu_grad2_0_2_gt0 = NULL;
 double * cpu_grad2_1_1_gt0 = NULL;
 double * cpu_grad2_1_2_gt0 = NULL;
 double * cpu_grad2_2_2_gt0 = NULL;
 double * cpu_grad2_0_0_gt1 = NULL;
 double * cpu_grad2_0_1_gt1 = NULL;
 double * cpu_grad2_0_2_gt1 = NULL;
 double * cpu_grad2_1_1_gt1 = NULL;
 double * cpu_grad2_1_2_gt1 = NULL;
 double * cpu_grad2_2_2_gt1 = NULL;
 double * cpu_grad2_0_0_gt2 = NULL;
 double * cpu_grad2_0_1_gt2 = NULL;
 double * cpu_grad2_0_2_gt2 = NULL;
 double * cpu_grad2_1_1_gt2 = NULL;
 double * cpu_grad2_1_2_gt2 = NULL;
 double * cpu_grad2_2_2_gt2 = NULL;
 double * cpu_grad2_0_0_gt3 = NULL;
 double * cpu_grad2_0_1_gt3 = NULL;
 double * cpu_grad2_0_2_gt3 = NULL;
 double * cpu_grad2_1_1_gt3 = NULL;
 double * cpu_grad2_1_2_gt3 = NULL;
 double * cpu_grad2_2_2_gt3 = NULL;
 double * cpu_grad2_0_0_gt4 = NULL;
 double * cpu_grad2_0_1_gt4 = NULL;
 double * cpu_grad2_0_2_gt4 = NULL;
 double * cpu_grad2_1_1_gt4 = NULL;
 double * cpu_grad2_1_2_gt4 = NULL;
 double * cpu_grad2_2_2_gt4 = NULL;
 double * cpu_grad2_0_0_gt5 = NULL;
 double * cpu_grad2_0_1_gt5 = NULL;
 double * cpu_grad2_0_2_gt5 = NULL;
 double * cpu_grad2_1_1_gt5 = NULL;
 double * cpu_grad2_1_2_gt5 = NULL;
 double * cpu_grad2_2_2_gt5 = NULL;
 double * cpu_grad2_0_0_chi = NULL;
 double * cpu_grad2_0_1_chi = NULL;
 double * cpu_grad2_0_2_chi = NULL;
 double * cpu_grad2_1_1_chi = NULL;
 double * cpu_grad2_1_2_chi = NULL;
 double * cpu_grad2_2_2_chi = NULL;
 double * cpu_grad2_0_0_alpha = NULL;
 double * cpu_grad2_0_1_alpha = NULL;
 double * cpu_grad2_0_2_alpha = NULL;
 double * cpu_grad2_1_1_alpha = NULL;
 double * cpu_grad2_1_2_alpha = NULL;
 double * cpu_grad2_2_2_alpha = NULL;
 double * cpu_grad2_0_0_beta0 = NULL;
 double * cpu_grad2_0_1_beta0 = NULL;
 double * cpu_grad2_0_2_beta0 = NULL;
 double * cpu_grad2_1_1_beta0 = NULL;
 double * cpu_grad2_1_2_beta0 = NULL;
 double * cpu_grad2_2_2_beta0 = NULL;
 double * cpu_grad2_0_0_beta1 = NULL;
 double * cpu_grad2_0_1_beta1 = NULL;
 double * cpu_grad2_0_2_beta1 = NULL;
 double * cpu_grad2_1_1_beta1 = NULL;
 double * cpu_grad2_1_2_beta1 = NULL;
 double * cpu_grad2_2_2_beta1 = NULL;
 double * cpu_grad2_0_0_beta2 = NULL;
 double * cpu_grad2_0_1_beta2 = NULL;
 double * cpu_grad2_0_2_beta2 = NULL;
 double * cpu_grad2_1_1_beta2 = NULL;
 double * cpu_grad2_1_2_beta2 = NULL;
 double * cpu_grad2_2_2_beta2 = NULL;
 double * cpu_agrad_0_gt0 = NULL;
 double * cpu_agrad_1_gt0 = NULL;
 double * cpu_agrad_2_gt0 = NULL;
 double * cpu_agrad_0_gt1 = NULL;
 double * cpu_agrad_1_gt1 = NULL;
 double * cpu_agrad_2_gt1 = NULL;
 double * cpu_agrad_0_gt2 = NULL;
 double * cpu_agrad_1_gt2 = NULL;
 double * cpu_agrad_2_gt2 = NULL;
 double * cpu_agrad_0_gt3 = NULL;
 double * cpu_agrad_1_gt3 = NULL;
 double * cpu_agrad_2_gt3 = NULL;
 double * cpu_agrad_0_gt4 = NULL;
 double * cpu_agrad_1_gt4 = NULL;
 double * cpu_agrad_2_gt4 = NULL;
 double * cpu_agrad_0_gt5 = NULL;
 double * cpu_agrad_1_gt5 = NULL;
 double * cpu_agrad_2_gt5 = NULL;
 double * cpu_agrad_0_At0 = NULL;
 double * cpu_agrad_1_At0 = NULL;
 double * cpu_agrad_2_At0 = NULL;
 double * cpu_agrad_0_At1 = NULL;
 double * cpu_agrad_1_At1 = NULL;
 double * cpu_agrad_2_At1 = NULL;
 double * cpu_agrad_0_At2 = NULL;
 double * cpu_agrad_1_At2 = NULL;
 double * cpu_agrad_2_At2 = NULL;
 double * cpu_agrad_0_At3 = NULL;
 double * cpu_agrad_1_At3 = NULL;
 double * cpu_agrad_2_At3 = NULL;
 double * cpu_agrad_0_At4 = NULL;
 double * cpu_agrad_1_At4 = NULL;
 double * cpu_agrad_2_At4 = NULL;
 double * cpu_agrad_0_At5 = NULL;
 double * cpu_agrad_1_At5 = NULL;
 double * cpu_agrad_2_At5 = NULL;
 double * cpu_agrad_0_alpha = NULL;
 double * cpu_agrad_1_alpha = NULL;
 double * cpu_agrad_2_alpha = NULL;
 double * cpu_agrad_0_beta0 = NULL;
 double * cpu_agrad_1_beta0 = NULL;
 double * cpu_agrad_2_beta0 = NULL;
 double * cpu_agrad_0_beta1 = NULL;
 double * cpu_agrad_1_beta1 = NULL;
 double * cpu_agrad_2_beta1 = NULL;
 double * cpu_agrad_0_beta2 = NULL;
 double * cpu_agrad_1_beta2 = NULL;
 double * cpu_agrad_2_beta2 = NULL;
 double * cpu_agrad_0_chi = NULL;
 double * cpu_agrad_1_chi = NULL;
 double * cpu_agrad_2_chi = NULL;
 double * cpu_agrad_0_Gt0 = NULL;
 double * cpu_agrad_1_Gt0 = NULL;
 double * cpu_agrad_2_Gt0 = NULL;
 double * cpu_agrad_0_Gt1 = NULL;
 double * cpu_agrad_1_Gt1 = NULL;
 double * cpu_agrad_2_Gt1 = NULL;
 double * cpu_agrad_0_Gt2 = NULL;
 double * cpu_agrad_1_Gt2 = NULL;
 double * cpu_agrad_2_Gt2 = NULL;
 double * cpu_agrad_0_K = NULL;
 double * cpu_agrad_1_K = NULL;
 double * cpu_agrad_2_K = NULL;
 double * cpu_agrad_0_B0 = NULL;
 double * cpu_agrad_1_B0 = NULL;
 double * cpu_agrad_2_B0 = NULL;
 double * cpu_agrad_0_B1 = NULL;
 double * cpu_agrad_1_B1 = NULL;
 double * cpu_agrad_2_B1 = NULL;
 double * cpu_agrad_0_B2 = NULL;
 double * cpu_agrad_1_B2 = NULL;
 double * cpu_agrad_2_B2 = NULL;
 double * cpu_kograd_0_alpha = NULL;
 double * cpu_kograd_1_alpha = NULL;
 double * cpu_kograd_2_alpha = NULL;
 double * cpu_kograd_0_beta0 = NULL;
 double * cpu_kograd_1_beta0 = NULL;
 double * cpu_kograd_2_beta0 = NULL;
 double * cpu_kograd_0_beta1 = NULL;
 double * cpu_kograd_1_beta1 = NULL;
 double * cpu_kograd_2_beta1 = NULL;
 double * cpu_kograd_0_beta2 = NULL;
 double * cpu_kograd_1_beta2 = NULL;
 double * cpu_kograd_2_beta2 = NULL;
 double * cpu_kograd_0_B0 = NULL;
 double * cpu_kograd_1_B0 = NULL;
 double * cpu_kograd_2_B0 = NULL;
 double * cpu_kograd_0_B1 = NULL;
 double * cpu_kograd_1_B1 = NULL;
 double * cpu_kograd_2_B1 = NULL;
 double * cpu_kograd_0_B2 = NULL;
 double * cpu_kograd_1_B2 = NULL;
 double * cpu_kograd_2_B2 = NULL;
 double * cpu_kograd_0_chi = NULL;
 double * cpu_kograd_1_chi = NULL;
 double * cpu_kograd_2_chi = NULL;
 double * cpu_kograd_0_Gt0 = NULL;
 double * cpu_kograd_1_Gt0 = NULL;
 double * cpu_kograd_2_Gt0 = NULL;
 double * cpu_kograd_0_Gt1 = NULL;
 double * cpu_kograd_1_Gt1 = NULL;
 double * cpu_kograd_2_Gt1 = NULL;
 double * cpu_kograd_0_Gt2 = NULL;
 double * cpu_kograd_1_Gt2 = NULL;
 double * cpu_kograd_2_Gt2 = NULL;
 double * cpu_kograd_0_K = NULL;
 double * cpu_kograd_1_K = NULL;
 double * cpu_kograd_2_K = NULL;
 double * cpu_kograd_0_gt0 = NULL;
 double * cpu_kograd_1_gt0 = NULL;
 double * cpu_kograd_2_gt0 = NULL;
 double * cpu_kograd_0_gt1 = NULL;
 double * cpu_kograd_1_gt1 = NULL;
 double * cpu_kograd_2_gt1 = NULL;
 double * cpu_kograd_0_gt2 = NULL;
 double * cpu_kograd_1_gt2 = NULL;
 double * cpu_kograd_2_gt2 = NULL;
 double * cpu_kograd_0_gt3 = NULL;
 double * cpu_kograd_1_gt3 = NULL;
 double * cpu_kograd_2_gt3 = NULL;
 double * cpu_kograd_0_gt4 = NULL;
 double * cpu_kograd_1_gt4 = NULL;
 double * cpu_kograd_2_gt4 = NULL;
 double * cpu_kograd_0_gt5 = NULL;
 double * cpu_kograd_1_gt5 = NULL;
 double * cpu_kograd_2_gt5 = NULL;
 double * cpu_kograd_0_At0 = NULL;
 double * cpu_kograd_1_At0 = NULL;
 double * cpu_kograd_2_At0 = NULL;
 double * cpu_kograd_0_At1 = NULL;
 double * cpu_kograd_1_At1 = NULL;
 double * cpu_kograd_2_At1 = NULL;
 double * cpu_kograd_0_At2 = NULL;
 double * cpu_kograd_1_At2 = NULL;
 double * cpu_kograd_2_At2 = NULL;
 double * cpu_kograd_0_At3 = NULL;
 double * cpu_kograd_1_At3 = NULL;
 double * cpu_kograd_2_At3 = NULL;
 double * cpu_kograd_0_At4 = NULL;
 double * cpu_kograd_1_At4 = NULL;
 double * cpu_kograd_2_At4 = NULL;
 double * cpu_kograd_0_At5 = NULL;
 double * cpu_kograd_1_At5 = NULL;
 double * cpu_kograd_2_At5 = NULL;
