// Generated by Dendro-GR SymPyGR code generation framework
// date: 2018-09-23 15:19:04.215951
// location: bssn/cuda_gr/utils

calc_ko_deriv42_x_bflag(tid, grad_0_gt0, dev_var_in, gt0Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_gt0, dev_var_in, gt0Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_gt0, dev_var_in, gt0Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_gt1, dev_var_in, gt1Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_gt1, dev_var_in, gt1Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_gt1, dev_var_in, gt1Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_gt2, dev_var_in, gt2Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_gt2, dev_var_in, gt2Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_gt2, dev_var_in, gt2Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_gt3, dev_var_in, gt3Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_gt3, dev_var_in, gt3Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_gt3, dev_var_in, gt3Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_gt4, dev_var_in, gt4Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_gt4, dev_var_in, gt4Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_gt4, dev_var_in, gt4Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_gt5, dev_var_in, gt5Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_gt5, dev_var_in, gt5Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_gt5, dev_var_in, gt5Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_At0, dev_var_in, At0Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_At0, dev_var_in, At0Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_At0, dev_var_in, At0Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_At1, dev_var_in, At1Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_At1, dev_var_in, At1Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_At1, dev_var_in, At1Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_At2, dev_var_in, At2Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_At2, dev_var_in, At2Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_At2, dev_var_in, At2Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_At3, dev_var_in, At3Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_At3, dev_var_in, At3Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_At3, dev_var_in, At3Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_At4, dev_var_in, At4Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_At4, dev_var_in, At4Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_At4, dev_var_in, At4Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_At5, dev_var_in, At5Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_At5, dev_var_in, At5Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_At5, dev_var_in, At5Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_alpha, dev_var_in, alphaInt, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_alpha, dev_var_in, alphaInt, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_alpha, dev_var_in, alphaInt, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_beta0, dev_var_in, beta0Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_beta0, dev_var_in, beta0Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_beta0, dev_var_in, beta0Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_beta1, dev_var_in, beta1Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_beta1, dev_var_in, beta1Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_beta1, dev_var_in, beta1Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_beta2, dev_var_in, beta2Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_beta2, dev_var_in, beta2Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_beta2, dev_var_in, beta2Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_chi, dev_var_in, chiInt, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_chi, dev_var_in, chiInt, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_chi, dev_var_in, chiInt, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_Gt0, dev_var_in, Gt0Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_Gt0, dev_var_in, Gt0Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_Gt0, dev_var_in, Gt0Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_Gt1, dev_var_in, Gt1Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_Gt1, dev_var_in, Gt1Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_Gt1, dev_var_in, Gt1Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_Gt2, dev_var_in, Gt2Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_Gt2, dev_var_in, Gt2Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_Gt2, dev_var_in, Gt2Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_K, dev_var_in, KInt, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_K, dev_var_in, KInt, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_K, dev_var_in, KInt, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_B0, dev_var_in, B0Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_B0, dev_var_in, B0Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_B0, dev_var_in, B0Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_B1, dev_var_in, B1Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_B1, dev_var_in, B1Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_B1, dev_var_in, B1Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

calc_ko_deriv42_x_bflag(tid, grad_0_B2, dev_var_in, B2Int, hx, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_y_bflag(tid, grad_1_B2, dev_var_in, B2Int, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_ko_deriv42_z_bflag(tid, grad_2_B2, dev_var_in, B2Int, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

