// Generated by Dendro-GR SymPyGR code generation framework
// date: 2018-10-27 14:07:04.009449
// location: bssn/cuda_gr/utils

globaltoshared(grad_0_gt0, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_y(tile_size, grad2_0_1_gt0, shared_var_in, 0, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_z(tile_size, grad2_0_2_gt0, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_1_gt0, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_z(tile_size, grad2_1_2_gt0, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_0_gt1, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_y(tile_size, grad2_0_1_gt1, shared_var_in, 0, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_z(tile_size, grad2_0_2_gt1, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_1_gt1, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_z(tile_size, grad2_1_2_gt1, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_0_gt2, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_y(tile_size, grad2_0_1_gt2, shared_var_in, 0, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_z(tile_size, grad2_0_2_gt2, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_1_gt2, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_z(tile_size, grad2_1_2_gt2, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_0_gt3, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_y(tile_size, grad2_0_1_gt3, shared_var_in, 0, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_z(tile_size, grad2_0_2_gt3, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_1_gt3, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_z(tile_size, grad2_1_2_gt3, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_0_gt4, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_y(tile_size, grad2_0_1_gt4, shared_var_in, 0, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_z(tile_size, grad2_0_2_gt4, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_1_gt4, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_z(tile_size, grad2_1_2_gt4, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_0_gt5, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_y(tile_size, grad2_0_1_gt5, shared_var_in, 0, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_z(tile_size, grad2_0_2_gt5, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_1_gt5, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_z(tile_size, grad2_1_2_gt5, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_0_chi, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_y(tile_size, grad2_0_1_chi, shared_var_in, 0, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_z(tile_size, grad2_0_2_chi, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_1_chi, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_z(tile_size, grad2_1_2_chi, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_0_alpha, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_y(tile_size, grad2_0_1_alpha, shared_var_in, 0, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_z(tile_size, grad2_0_2_alpha, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_1_alpha, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_z(tile_size, grad2_1_2_alpha, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_0_beta0, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_y(tile_size, grad2_0_1_beta0, shared_var_in, 0, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_z(tile_size, grad2_0_2_beta0, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_1_beta0, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_z(tile_size, grad2_1_2_beta0, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_0_beta1, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_y(tile_size, grad2_0_1_beta1, shared_var_in, 0, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_z(tile_size, grad2_0_2_beta1, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_1_beta1, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_z(tile_size, grad2_1_2_beta1, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_0_beta2, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_y(tile_size, grad2_0_1_beta2, shared_var_in, 0, hy, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_z(tile_size, grad2_0_2_beta2, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(grad_1_beta2, shared_var_in, 0, 2, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_z(tile_size, grad2_1_2_beta2, shared_var_in, 0, hz, host_sz_x, host_sz_y, host_sz_z, bflag);



globaltoshared(dev_var_in, shared_var_in, gt0Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_gt0, dev_var_in, shared_var_in, gt0Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_gt0, dev_var_in, shared_var_in, gt0Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_gt0, dev_var_in, shared_var_in, gt0Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, gt1Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_gt1, dev_var_in, shared_var_in, gt1Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_gt1, dev_var_in, shared_var_in, gt1Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_gt1, dev_var_in, shared_var_in, gt1Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, gt2Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_gt2, dev_var_in, shared_var_in, gt2Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_gt2, dev_var_in, shared_var_in, gt2Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_gt2, dev_var_in, shared_var_in, gt2Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, gt3Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_gt3, dev_var_in, shared_var_in, gt3Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_gt3, dev_var_in, shared_var_in, gt3Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_gt3, dev_var_in, shared_var_in, gt3Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, gt4Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_gt4, dev_var_in, shared_var_in, gt4Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_gt4, dev_var_in, shared_var_in, gt4Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_gt4, dev_var_in, shared_var_in, gt4Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, gt5Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_gt5, dev_var_in, shared_var_in, gt5Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_gt5, dev_var_in, shared_var_in, gt5Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_gt5, dev_var_in, shared_var_in, gt5Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, At0Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_At0, dev_var_in, shared_var_in, At0Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_At0, dev_var_in, shared_var_in, At0Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_At0, dev_var_in, shared_var_in, At0Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, At1Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_At1, dev_var_in, shared_var_in, At1Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_At1, dev_var_in, shared_var_in, At1Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_At1, dev_var_in, shared_var_in, At1Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, At2Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_At2, dev_var_in, shared_var_in, At2Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_At2, dev_var_in, shared_var_in, At2Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_At2, dev_var_in, shared_var_in, At2Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, At3Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_At3, dev_var_in, shared_var_in, At3Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_At3, dev_var_in, shared_var_in, At3Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_At3, dev_var_in, shared_var_in, At3Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, At4Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_At4, dev_var_in, shared_var_in, At4Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_At4, dev_var_in, shared_var_in, At4Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_At4, dev_var_in, shared_var_in, At4Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, At5Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_At5, dev_var_in, shared_var_in, At5Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_At5, dev_var_in, shared_var_in, At5Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_At5, dev_var_in, shared_var_in, At5Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, alphaInt, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_alpha, dev_var_in, shared_var_in, alphaInt, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_alpha, dev_var_in, shared_var_in, alphaInt, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_alpha, dev_var_in, shared_var_in, alphaInt, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, beta0Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_beta0, dev_var_in, shared_var_in, beta0Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_beta0, dev_var_in, shared_var_in, beta0Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_beta0, dev_var_in, shared_var_in, beta0Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, beta1Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_beta1, dev_var_in, shared_var_in, beta1Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_beta1, dev_var_in, shared_var_in, beta1Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_beta1, dev_var_in, shared_var_in, beta1Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, beta2Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_beta2, dev_var_in, shared_var_in, beta2Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_beta2, dev_var_in, shared_var_in, beta2Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_beta2, dev_var_in, shared_var_in, beta2Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, chiInt, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_chi, dev_var_in, shared_var_in, chiInt, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_chi, dev_var_in, shared_var_in, chiInt, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_chi, dev_var_in, shared_var_in, chiInt, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, Gt0Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_Gt0, dev_var_in, shared_var_in, Gt0Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_Gt0, dev_var_in, shared_var_in, Gt0Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_Gt0, dev_var_in, shared_var_in, Gt0Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, Gt1Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_Gt1, dev_var_in, shared_var_in, Gt1Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_Gt1, dev_var_in, shared_var_in, Gt1Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_Gt1, dev_var_in, shared_var_in, Gt1Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, Gt2Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_Gt2, dev_var_in, shared_var_in, Gt2Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_Gt2, dev_var_in, shared_var_in, Gt2Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_Gt2, dev_var_in, shared_var_in, Gt2Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, KInt, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_K, dev_var_in, shared_var_in, KInt, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_K, dev_var_in, shared_var_in, KInt, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_K, dev_var_in, shared_var_in, KInt, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, B0Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_B0, dev_var_in, shared_var_in, B0Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_B0, dev_var_in, shared_var_in, B0Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_B0, dev_var_in, shared_var_in, B0Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, B1Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_B1, dev_var_in, shared_var_in, B1Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_B1, dev_var_in, shared_var_in, B1Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_B1, dev_var_in, shared_var_in, B1Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

globaltoshared(dev_var_in, shared_var_in, B2Int, 3, x_offset, y_offset, z_offset, nx, ny);
calc_deriv42_adv_x(tile_size, agrad_0_B2, dev_var_in, shared_var_in, B2Int, hx, beta0Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_y(tile_size, agrad_1_B2, dev_var_in, shared_var_in, B2Int, hy, beta1Int, host_sz_x, host_sz_y, host_sz_z, bflag);
calc_deriv42_adv_z(tile_size, agrad_2_B2, dev_var_in, shared_var_in, B2Int, hz, beta2Int, host_sz_x, host_sz_y, host_sz_z, bflag);

