"""emda_matter_rhs.py -- emit matter-sector RHS (12 fields) as a CSE'd
C++ include for the EMDA cascade-full plugin.

The 12 matter-sector RHS components (dilatonPhi, kappa, capitalPi,
capitalXi, perpE[3], perpB[3], dampingPsi, dampingPhi) are pure-matter
evolution equations -- they don't share much with the BSSN cascade and
are cheap (Phase 1 inspection: ~8K total ops vs the BSSN sector's
~700K). So we just CSE them together and emit a small overlay file that
the cascade-full plugin includes inside its per-point loop.

Approach mirrors codegen/emda_matter_source.py:
  1. Import emdabssn_eqns_configs and call dendroConfigs.get_rhs_eqns_flat
     to get all 36 RHS expressions in flat form.
  2. Filter by LHS name (membership in the matter set).
  3. Replace SymPy Derivatives -> grad_*[pp] and UndefinedFunctions ->
     field[pp] symbols.
  4. SymPy CSE the 12 expressions together.
  5. Emit `lhs = rhs;` assignments (NOT +=, since the harness leaves
     these uninitialised at the point of include).

Output: harness_emda/src/gencode/emda_matter_rhs.cpp.inc
"""

from __future__ import annotations

import argparse
import os
import sys

EMDA_GR = os.environ.get("DENDRO_EMDA_GR", os.path.expanduser("~/research/emda-gr"))
if EMDA_GR not in sys.path:
    sys.path.insert(0, EMDA_GR)

import sympy as sym  # noqa: E402

import emdabssn_eqns_configs as E  # noqa: E402

# Reuse the helper from matter_source for symbol substitution.
from dendrosym.cascade.systems.emda.matter_source import replace_derivs_and_funcs  # noqa: E402


_MATTER_FIELDS = [
    "dilatonPhi", "kappa", "capitalPi", "capitalXi",
    "perpE0", "perpE1", "perpE2",
    "perpB0", "perpB1", "perpB2",
    "dampingPsi", "dampingPhi",
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", required=True)
    args = ap.parse_args()

    print("Loading dendrosym + EMDA config (slow, ~30s)...")
    rhs_exprs, rhs_names = E.dendroConfigs.get_rhs_eqns_flat("evolution")
    name_to_expr = {str(n): e for n, e in zip(rhs_names, rhs_exprs)}

    pp_assigns = []
    for fld in _MATTER_FIELDS:
        key = f"{fld}[pp]"
        if key not in name_to_expr:
            print(f"  WARNING: missing {key} in flat RHS list", file=sys.stderr)
            continue
        expr = sym.S(name_to_expr[key])
        pp_assigns.append((f"{fld}_rhs[pp]", replace_derivs_and_funcs(expr)))

    print(f"  Picked {len(pp_assigns)} matter RHS expressions.")
    print("Running SymPy CSE...")
    rhs_list = [r for _, r in pp_assigns]
    cse_subs, cse_rhss = sym.cse(
        rhs_list, symbols=sym.numbered_symbols("MATR_"))
    print(f"  CSE produced {len(cse_subs)} temporaries.")

    lines = [
        "// Matter-sector RHS (12 fields) for EMDA-BSSN.",
        "// Generated by codegen/emda_matter_rhs.py -- do not edit.",
        "//",
        "// Targets (=, not +=): dilatonPhi_rhs, kappa_rhs, capitalPi_rhs,",
        "//                      capitalXi_rhs, perpE0..2_rhs, perpB0..2_rhs,",
        "//                      dampingPsi_rhs, dampingPhi_rhs.",
        f"// {len(cse_subs)} CSE temporaries. Expects state pointers,",
        "// grad_*/grad2_* deriv pointers, and EMDA constants",
        "// (alpha_theory[2], eta[2], lambda[4], lf[2]) in scope.",
        "{",
    ]
    for sym_name, sub_expr in cse_subs:
        code = sym.ccode(sub_expr)
        lines.append(f"  const double {sym_name} = {code};")
    for (lhs, _), rhs_simplified in zip(pp_assigns, cse_rhss):
        code = sym.ccode(rhs_simplified)
        lines.append(f"  {lhs} = {code};")
    lines.append("}")

    out = "\n".join(lines) + "\n"
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w") as f:
        f.write(out)
    print(f"Wrote {args.output} ({len(out)} bytes, "
          f"{len(out.splitlines())} lines)")


if __name__ == "__main__":
    main()
