/**
 * @file grDef.h
 * @brief Variable enums, coordinate macros, and name arrays for smokemax.
 *
 * Generated by dendrosym. If you add variables in the Python config,
 * regenerate this file. Custom enums or macros can be added below
 * the generated sections.
 *
 * The VAR enum ordering matches the order variables were added via
 * add_evolution_variables() in the Python config, which also determines
 * the layout of the uZipVars array.
 */

#ifndef DENDRO_GRDEF_H
#define DENDRO_GRDEF_H

// coordinate transforms between grid space and physical space
#define Rx (smokemax::SMOKEMAX_COMPD_MAX[0] - smokemax::SMOKEMAX_COMPD_MIN[0])
#define Ry (smokemax::SMOKEMAX_COMPD_MAX[1] - smokemax::SMOKEMAX_COMPD_MIN[1])
#define Rz (smokemax::SMOKEMAX_COMPD_MAX[2] - smokemax::SMOKEMAX_COMPD_MIN[2])

#define RgX (smokemax::SMOKEMAX_OCTREE_MAX[0] - smokemax::SMOKEMAX_OCTREE_MIN[0])
#define RgY (smokemax::SMOKEMAX_OCTREE_MAX[1] - smokemax::SMOKEMAX_OCTREE_MIN[1])
#define RgZ (smokemax::SMOKEMAX_OCTREE_MAX[2] - smokemax::SMOKEMAX_OCTREE_MIN[2])

#define GRIDX_TO_X(xg) \
    (((Rx / RgX) * (xg - smokemax::SMOKEMAX_OCTREE_MIN[0])) + smokemax::SMOKEMAX_COMPD_MIN[0])
#define GRIDY_TO_Y(yg) \
    (((Ry / RgY) * (yg - smokemax::SMOKEMAX_OCTREE_MIN[1])) + smokemax::SMOKEMAX_COMPD_MIN[1])
#define GRIDZ_TO_Z(zg) \
    (((Rz / RgZ) * (zg - smokemax::SMOKEMAX_OCTREE_MIN[2])) + smokemax::SMOKEMAX_COMPD_MIN[2])

#define X_TO_GRIDX(xc) \
    (((RgX / Rx) * (xc - smokemax::SMOKEMAX_COMPD_MIN[0])) + smokemax::SMOKEMAX_OCTREE_MIN[0])
#define Y_TO_GRIDY(yc) \
    (((RgY / Ry) * (yc - smokemax::SMOKEMAX_COMPD_MIN[1])) + smokemax::SMOKEMAX_OCTREE_MIN[1])
#define Z_TO_GRIDZ(zc) \
    (((RgZ / Rz) * (zc - smokemax::SMOKEMAX_COMPD_MIN[2])) + smokemax::SMOKEMAX_OCTREE_MIN[2])

enum RKType { RK3 = 0, RK4, RK45 };

namespace smokemax {

// evolution variable enum -- ordering matches the python config
enum VAR
{
    U_ALPHA = 0,
    U_CHI,
    U_TRK,
    U_BETA0,
    U_BETA1,
    U_BETA2,
    U_GT0,
    U_GT1,
    U_GT2,
    U_B0,
    U_B1,
    U_B2,
    U_AT00,
    U_AT01,
    U_AT02,
    U_AT11,
    U_AT12,
    U_AT22,
    U_GT00,
    U_GT01,
    U_GT02,
    U_GT11,
    U_GT12,
    U_GT22
};

// constraint variable enum
enum VAR_CONSTRAINT
{
    C_HAM = 0,
    C_MOM0,
    C_MOM1,
    C_MOM2,
    C_PSI4_REAL,
    C_PSI4_IMAG
};

// human-readable name arrays (for logging and vtu output)
static const char *SMOKEMAX_VAR_NAMES[] = {"U_ALPHA", "U_CHI", "U_TRK", "U_BETA0", "U_BETA1", "U_BETA2", "U_GT0", "U_GT1", "U_GT2", "U_B0", "U_B1", "U_B2", "U_AT00", "U_AT01", "U_AT02", "U_AT11", "U_AT12", "U_AT22", "U_GT00", "U_GT01", "U_GT02", "U_GT11", "U_GT12", "U_GT22"};


static const char *SMOKEMAX_VAR_CONSTRAINT_NAMES[] = {"C_HAM", "C_MOM0", "C_MOM1", "C_MOM2", "C_PSI4_REAL", "C_PSI4_IMAG"};


// iterable lists for looping over all variables
static const VAR SMOKEMAX_VAR_ITERABLE_LIST[] = {U_ALPHA, U_CHI, U_TRK, U_BETA0, U_BETA1, U_BETA2, U_GT0, U_GT1, U_GT2, U_B0, U_B1, U_B2, U_AT00, U_AT01, U_AT02, U_AT11, U_AT12, U_AT22, U_GT00, U_GT01, U_GT02, U_GT11, U_GT12, U_GT22};


static const VAR_CONSTRAINT SMOKEMAX_VAR_CONSTRAINT_ITERABLE_LIST[] = {C_HAM, C_MOM0, C_MOM1, C_MOM2, C_PSI4_REAL, C_PSI4_IMAG};


// refinement strategy
enum RefinementMode {
    WAMR = 0,
    EH,
    EH_WAMR,
    BH_LOC,
    BH_WAMR,
    REFINE_MODE_NONE
};

}  // namespace smokemax

#endif  // DENDRO_GRDEF_H
