/**
 * @file parameters.h
 * @brief Parameter declarations for the smokemax solver.
 *
 * Generated by dendrosym. Safe to edit -- add new parameters as needed.
 *
 * Parameters are read from a TOML file at runtime. The TOML file uses
 * sections to organize parameters by category:
 *
 *   [solver]          - mesh, time stepping, I/O
 *   [physics]         - equation-specific theory parameters
 *   [initial_data]    - initial condition setup
 *   [bh1] / [bh2]    - per-black-hole parameters
 *   [refinement]      - AMR settings
 *   [dissipation]     - KO dissipation settings
 *   [wave_extraction] - gravitational wave extraction
 */

#ifndef PARAMETERS_H
#define PARAMETERS_H

#include <string.h>
#include <iostream>
#include <vector>

#include <toml.hpp>

#include "dendro.h"
#include "memory_pool.h"
#include "parUtils.h"
#include <memory>
#include "derivatives.h"

#include "bh.h"
#include "grDef.h"

namespace smokemax {

// -----------------------------------------------------------------
// Core functions
// -----------------------------------------------------------------
void readParamFile(const char* inFile, MPI_Comm comm);
void dumpParamFile(std::ostream& sout, int root, MPI_Comm comm);

// -----------------------------------------------------------------
// Runtime state (not from TOML)
// -----------------------------------------------------------------
extern mem::memory_pool<double> SMOKEMAX_MEM_POOL;

extern BH BH1;
extern BH BH2;
extern Point SMOKEMAX_BH_LOC[2];
extern unsigned int SMOKEMAX_BH1_MAX_LEV;
extern unsigned int SMOKEMAX_BH2_MAX_LEV;
extern double SMOKEMAX_BH1_AMR_R;
extern double SMOKEMAX_BH2_AMR_R;
extern double SMOKEMAX_AMR_R_RATIO;
// Radius of the ball around each puncture excluded from the *masked*
// constraint norms reported by terminal_output(). 0 = no mask (default), which
// leaves the reported norms exactly as they were. Set to 1.0 to reproduce
// BSSN's convention (BSSN_BH1_CONSTRAINT_R), which is what makes a
// like-for-like constraint comparison against BSSN possible: BSSN's
// Hamiltonian constraint is non-finite at a puncture, so its norm is only
// defined with the puncture excised.
extern double SMOKEMAX_BH1_CONSTRAINT_R;
extern double SMOKEMAX_BH2_CONSTRAINT_R;

extern double SMOKEMAX_CURRENT_RK_COORD_TIME;
extern unsigned int SMOKEMAX_CURRENT_RK_STEP;

extern double* SMOKEMAX_DERIV_WORKSPACE;
extern double SMOKEMAX_CURRENT_MIN_DX;
extern double SMOKEMAX_BH_MERGE_TIME;
extern unsigned int SMOKEMAX_BH_MERGE_STEP;

// -----------------------------------------------------------------
// [solver] - Mesh and time stepping
// -----------------------------------------------------------------
extern unsigned int SMOKEMAX_ELE_ORDER;
extern unsigned int SMOKEMAX_PADDING_WIDTH;
extern double SMOKEMAX_COMPD_MIN[3];
extern double SMOKEMAX_COMPD_MAX[3];
extern double SMOKEMAX_OCTREE_MIN[3];
extern double SMOKEMAX_OCTREE_MAX[3];
extern unsigned int SMOKEMAX_DIM;
extern unsigned int SMOKEMAX_MAXDEPTH;
extern unsigned int SMOKEMAX_MINDEPTH;

// Block-adaptive mesh: if true, the initial octree is a uniform grid at
// MINDEPTH over the block region [BLK_MIN, BLK_MAX], with AMR disabled.
// If false, function2Octree is used (wavelet-driven AMR enabled).
// Matches BSSN_GR's BSSN_ENABLE_BLOCK_ADAPTIVITY convention.
extern bool SMOKEMAX_ENABLE_BLOCK_ADAPTIVITY;
extern double SMOKEMAX_BLK_MIN_X;
extern double SMOKEMAX_BLK_MIN_Y;
extern double SMOKEMAX_BLK_MIN_Z;
extern double SMOKEMAX_BLK_MAX_X;
extern double SMOKEMAX_BLK_MAX_Y;
extern double SMOKEMAX_BLK_MAX_Z;

extern double SMOKEMAX_RK_TIME_BEGIN;
extern double SMOKEMAX_RK_TIME_END;
extern unsigned int SMOKEMAX_RK_TYPE;
extern double SMOKEMAX_RK45_TIME_STEP_SIZE;
extern double SMOKEMAX_RK45_DESIRED_TOL;
extern double SMOKEMAX_CFL_FACTOR;

// I/O
extern unsigned int SMOKEMAX_IO_OUTPUT_FREQ;
extern unsigned int SMOKEMAX_TIME_STEP_OUTPUT_FREQ;
extern unsigned int SMOKEMAX_CHECKPT_FREQ;
extern bool SMOKEMAX_RESTORE_SOLVER;
extern std::string SMOKEMAX_VTU_FILE_PREFIX;
extern std::string SMOKEMAX_CHKPT_FILE_PREFIX;
extern std::string SMOKEMAX_PROFILE_FILE_PREFIX;

extern unsigned int SMOKEMAX_NUM_EVOL_VARS_VTU_OUTPUT;
extern unsigned int SMOKEMAX_NUM_CONST_VARS_VTU_OUTPUT;
extern unsigned int SMOKEMAX_VTU_OUTPUT_EVOL_INDICES[24];
extern unsigned int SMOKEMAX_VTU_OUTPUT_CONST_INDICES[6];
// terminal_output norm selection: variable index lists (count = list length)
extern std::vector<unsigned int> SMOKEMAX_TERMINAL_OUTPUT_EVOL_INDICES;
extern std::vector<unsigned int> SMOKEMAX_TERMINAL_OUTPUT_CONST_INDICES;
extern bool SMOKEMAX_VTU_X_SLICE;
extern bool SMOKEMAX_VTU_Y_SLICE;
extern bool SMOKEMAX_VTU_Z_SLICE;

// Mesh management
extern unsigned int SMOKEMAX_DENDRO_GRAIN_SZ;
extern double SMOKEMAX_DENDRO_AMR_FAC;
extern double SMOKEMAX_LOAD_IMB_TOL;
extern unsigned int SMOKEMAX_ASYNC_COMM_K;
extern unsigned int SMOKEMAX_INIT_GRID_ITER;
extern unsigned int SMOKEMAX_REMESH_TEST_FREQ;
extern unsigned int SMOKEMAX_NUM_REFINE_VARS;
extern unsigned int SMOKEMAX_REFINE_VARIABLE_INDICES[24];
extern double SMOKEMAX_WAVELET_TOL;
extern unsigned int SMOKEMAX_USE_WAVELET_TOL_FUNCTION;
extern double SMOKEMAX_WAVELET_TOL_MAX;
extern double SMOKEMAX_WAVELET_TOL_FUNCTION_R0;
extern double SMOKEMAX_WAVELET_TOL_FUNCTION_R1;
extern RefinementMode SMOKEMAX_REFINEMENT_MODE;

// grid bounds (physical domain for domain decomposition)
extern double SMOKEMAX_GRID_MIN_X;
extern double SMOKEMAX_GRID_MIN_Y;
extern double SMOKEMAX_GRID_MIN_Z;
extern double SMOKEMAX_GRID_MAX_X;
extern double SMOKEMAX_GRID_MAX_Y;
extern double SMOKEMAX_GRID_MAX_Z;
extern unsigned int SMOKEMAX_SPLIT_FIX;
extern unsigned int SMOKEMAX_ASYNC_COMM_K;
// ENABLE_BLOCK_ADAPTIVITY declared earlier as `bool` (BSSN-style).

// Logging
extern std::string DENDRO_LOG_FILE;
extern int DENDRO_LOG_FILE_LEVEL;
extern int DENDRO_LOG_CONSOLE_LEVEL;
extern bool DENDRO_LOG_FORCE_FILE_FLUSH;

// -----------------------------------------------------------------
// [physics] - Equation-specific parameters
//
// These correspond to the ParameterVariable objects defined in the
// Python equation config file.
// -----------------------------------------------------------------

// -----------------------------------------------------------------
// [dissipation]
// -----------------------------------------------------------------
// [initial_data]
extern unsigned int SMOKEMAX_ID_TYPE;

// evolution constraint floors
extern double CHI_FLOOR;

extern double KO_DISS_SIGMA;
extern bool USE_CONST_KO;
extern unsigned int DISSIPATION_TYPE;

// -----------------------------------------------------------------
// DendroDerivatives object (configurable stencils + filtering)
//
// This replaces the old per-stencil-order derivs.cpp approach.
// Derivative type, order, and filtering are all set at runtime
// from the TOML parameter file.
// -----------------------------------------------------------------
extern std::unique_ptr<dendroderivs::DendroDerivatives> SMOKEMAX_DERIVS;
extern std::string SMOKEMAX_DERIVTYPE_FIRST;
extern std::string SMOKEMAX_DERIVTYPE_SECOND;
extern std::vector<double> SMOKEMAX_DERIV_FIRST_COEFFS;
extern std::vector<double> SMOKEMAX_DERIV_SECOND_COEFFS;
extern unsigned int SMOKEMAX_DERIV_FIRST_MATID;
extern unsigned int SMOKEMAX_DERIV_SECOND_MATID;
extern std::string SMOKEMAX_INMATFILT_FIRST;
extern std::string SMOKEMAX_INMATFILT_SECOND;
extern std::vector<double> SMOKEMAX_INMATFILT_FIRST_COEFFS;
extern std::vector<double> SMOKEMAX_INMATFILT_SECOND_COEFFS;
extern std::string SMOKEMAX_POST_RHS_FILTER;
// fused in-kernel stencils: a runtime request, not a guarantee. Only explicit
// local stencils can be inlined into the RHS body -- a compact/matrix engine
// derivative is a banded solve along a whole line -- so the solver degrades to
// the precomputed derivative pass when the engine cannot honour it.
extern bool SMOKEMAX_USE_FUSED_STENCILS;

// -----------------------------------------------------------------
// Derivative count (auto-computed from equations)
// -----------------------------------------------------------------
extern unsigned int SMOKEMAX_NUM_DERIVATIVES;

}  // namespace smokemax

#ifdef SOLVER_ENABLE_AH
#include "aeh_bhahaha.h"

namespace AH {

extern std::unique_ptr<dendro_aeh::AEH_BHaHAHA> ah_finder;
extern unsigned int AH_SOLVER_FREQ;

// bhahaha configuration (all have sensible defaults, override via toml)
extern unsigned int N_HORIZONS;
extern unsigned int N_RESOLUTIONS_MULTIGRID;
extern std::vector<int> MAX_ITERATIONS;
extern std::vector<double> INITIAL_X_CENTER;
extern std::vector<double> INITIAL_Y_CENTER;
extern std::vector<double> INITIAL_Z_CENTER;
extern std::vector<double> M_SCALE;
extern std::vector<double> CFL_FACTOR;
extern std::vector<double> THETA_L2_M_TOL;
extern std::vector<double> THETA_LINF_M_TOL;
extern std::vector<double> ETA_DAMP_M;
extern std::vector<double> KO_STRENGTH;
extern std::vector<double> MAX_SEARCH_RADIUS;
extern std::vector<int> NR_INTERP_MAX;
extern int NTHETA_MAX;
extern int NPHI_MAX;
extern std::string AH_SAVE_DIR;
extern int NUM_RESOLUTIONS_AFTER_FIND;
extern std::vector<int> NTHETA_ARRAY;
extern std::vector<int> NPHI_ARRAY;
extern int ENABLE_ETA_VARYING_ALG;
extern int VERBOSITY_LEVEL;

// indices into evolution variable array for BHaHAHA
// order: chi, trK, At00..At22(6), gt00..gt22(6) = 14 total
extern const std::vector<int> AH_INDICES;

}  // namespace AH
#endif

// TPID parameters are declared in dendrolib GR/include/tpid_params.h
// and defined in this solver's parameters.cpp
#include "tpid_params.h"

// -----------------------------------------------------------------
// [wave_extraction]
// -----------------------------------------------------------------
namespace GW {
extern unsigned int SMOKEMAX_GW_NUM_RADAII;
extern unsigned int SMOKEMAX_GW_RADAII[];
extern unsigned int SMOKEMAX_GW_NUM_LMODES;
extern unsigned int SMOKEMAX_GW_L_MODES[];
static const unsigned int SMOKEMAX_GW_OUTPUT_PRECISION = 10;
}  // namespace GW

// gw extraction frequency (in project namespace for main loop access)
namespace smokemax {
extern unsigned int SMOKEMAX_GW_EXTRACT_FREQ;
}  // namespace smokemax

#endif  // PARAMETERS_H
