/**
 * @file physcon.h
 * @brief Constraint evaluation declarations for the smokemax solver.
 *
 * Generated by dendrosym. Safe to edit.
 */

#ifndef PHYSCON_H
#define PHYSCON_H

#include <cmath>
#include <iostream>

#include "block.h"
#include "grDef.h"
#include "parameters.h"

/**@brief Computes constraint variables iterating over all the blocks. */
void smokemaxConstraints(double **uzipConsVars, const double **uZipVars,
                     const ot::Block *blkList, unsigned int numBlocks);

/**@brief Per-block constraint computation. */
void smokemaxphyscon(double **unzipConsVars, const double **uZipVars,
                 const unsigned int &offset, const double *pmin,
                 const double *pmax, const unsigned int *sz,
                 const unsigned int &bflag);

#endif  // PHYSCON_H
