/**
 * @file smokemax_constraints.h
 * @brief Evolution constraint enforcement for the smokemax solver.
 *
 * Generated by dendrosym. Safe to edit.
 *
 * Called after each RK timestep (and during initialization) to enforce
 * algebraic constraints on the evolution variables. Important for numerical
 * stability -- conformal metric determinant must stay 1, traceless tensors
 * must stay traceless, and some fields need positive floors to avoid
 * division by zero.
 *
 * enforce_smokemax_constraints() receives a 2D array of variable
 * pointers and a node index. Reads and modifies variables in-place.
 */

#ifndef SMOKEMAX_CONSTRAINTS_H
#define SMOKEMAX_CONSTRAINTS_H

#include "grDef.h"
#include "parameters.h"

#include <cmath>
#include <iostream>

namespace smokemax {

inline void enforce_smokemax_constraints(double **uzipVars,
                                     const unsigned int node) {
    // generated by dendrosym -- variable names adjusted to match function params
    const double one_third = 1.0 / 3.0;
    double **uiVar = uzipVars;  // alias for codegen compatibility
////
//// CODE TO REQUIRE METRIC DETERMINANT TO BE ONE
double gt[3][3];

gt[0][0] = uiVar[VAR::U_GT00][node];
gt[0][1] = uiVar[VAR::U_GT01][node];
gt[0][2] = uiVar[VAR::U_GT02][node];
gt[1][1] = uiVar[VAR::U_GT11][node];
gt[1][2] = uiVar[VAR::U_GT12][node];
gt[2][2] = uiVar[VAR::U_GT22][node];
gt[1][0] = gt[0][1];
gt[2][0] = gt[0][2];
gt[2][1] = gt[1][2];

double det_gt = gt[0][0] * (gt[1][1] * gt[2][2] - gt[1][2] * gt[1][2]) - gt[0][1] * gt[0][1] * gt[2][2] + 2.0 * gt[0][1] * gt[0][2] * gt[1][2] - gt[0][2] * gt[0][2] * gt[1][1];

if (det_gt < 0.0){
    std::cout << "Determinant of gt is negative: " << det_gt << std::endl;
    exit(0);
}
double det_gt_to_neg_third = 1.0 / pow(det_gt, one_third);
for (unsigned int j = 0; j < 3; j++)
{
    for (unsigned int i = 0; i < 3; i++)
{
        gt[i][j] *= det_gt_to_neg_third;
    }
}

det_gt = gt[0][0] * (gt[1][1] * gt[2][2] - gt[1][2] * gt[1][2]) - gt[0][1] * gt[0][1] * gt[2][2] + 2.0 * gt[0][1] * gt[0][2] * gt[1][2] - gt[0][2] * gt[0][2] * gt[1][1];

if (fabs(det_gt - 1.0) > 1.0e-6) {
    std::cout.precision(14);
    std::cout << "det(gt) != 1.0 det=" << std::fixed << det_gt << std::endl;
    std::cout << "    gt(1,1)" << gt[0][0] << std::endl;
    std::cout << "    gt(1,2)" << gt[0][1] << std::endl;
    std::cout << "    gt(1,3)" << gt[0][1] << std::endl;
    std::cout << "    gt(2,2)" << gt[1][1] << std::endl;
    std::cout << "    gt(2,3)" << gt[1][2] << std::endl;
    std::cout << "    gt(3,3)" << gt[2][2] << std::endl;
exit(0);
}

double gt_up[3][3];
double idet_gt = 1.0 / det_gt;
gt_up[0][0] = idet_gt * (gt[1][1] * gt[2][2] - gt[1][2] * gt[1][2]);
gt_up[0][1] = idet_gt * (-gt[0][1] * gt[2][2] + gt[0][2] * gt[1][2]);
gt_up[0][2] = idet_gt * (gt[0][1] * gt[1][2] - gt[0][2] * gt[1][1]);
gt_up[1][1] = idet_gt * (gt[0][0] * gt[2][2] - gt[0][2] * gt[0][2]);
gt_up[1][2] = idet_gt * (-gt[0][0] * gt[1][2] + gt[0][1] * gt[0][2]);
gt_up[2][2] = idet_gt * (gt[0][0] * gt[1][1] - gt[0][1] * gt[0][1]);
gt_up[1][0] = gt_up[0][1];
gt_up[2][0] = gt_up[0][2];
gt_up[2][1] = gt_up[1][2];

////
////APPLYING TRACE ZERO TO At
double At[3][3];

At[0][0] = uiVar[VAR::U_AT00][node];
At[0][1] = uiVar[VAR::U_AT01][node];
At[0][2] = uiVar[VAR::U_AT02][node];
At[1][1] = uiVar[VAR::U_AT11][node];
At[1][2] = uiVar[VAR::U_AT12][node];
At[2][2] = uiVar[VAR::U_AT22][node];
At[1][0] = At[0][1];
At[2][0] = At[0][2];
At[2][1] = At[1][2];

//// one third of the trace:
double ot_trace_At = one_third * (At[0][0] * gt_up[0][0] + At[1][1] * gt_up[1][1] + At[2][2] * gt_up[2][2] + 2.0 * (At[0][1] * gt_up[0][1] + At[0][2] * gt_up[0][2] + At[1][2] * gt_up[1][2]));

At[0][0] -= ot_trace_At * gt[0][0];
At[0][1] -= ot_trace_At * gt[0][1];
At[0][2] -= ot_trace_At * gt[0][2];
At[1][1] -= ot_trace_At * gt[1][1];
At[1][2] -= ot_trace_At * gt[1][2];
At[2][2] -= ot_trace_At * gt[2][2];
//// now the actual trace:
double trace_At = At[0][0] * gt_up[0][0] + At[1][1] * gt_up[1][1] + At[2][2] * gt_up[2][2] + 2.0 * (At[0][1] * gt_up[0][1] + At[0][2] * gt_up[0][2] + At[1][2] * gt_up[1][2]);

if (fabs(trace_At) > 1.0e-6)
{
    std::cout << "ERROR: tr(At) != 0, ="  << trace_At << std::endl;
    std::cout << "       At(1,1)=" << At[0][0] << std::endl;
    std::cout << "       At(1,2)=" << At[0][1] << std::endl;
    std::cout << "       At(1,3)=" << At[0][2] << std::endl;
    std::cout << "       At(2,2)=" << At[1][1] << std::endl;
    std::cout << "       At(2,3)=" << At[1][2] << std::endl;
    std::cout << "       At(3,3)=" << At[2][2] << std::endl;
    exit(0);
}

uiVar[VAR::U_AT00][node] = At[0][0];
uiVar[VAR::U_AT01][node] = At[0][1];
uiVar[VAR::U_AT02][node] = At[0][2];
uiVar[VAR::U_AT11][node] = At[1][1];
uiVar[VAR::U_AT12][node] = At[1][2];
uiVar[VAR::U_AT22][node] = At[2][2];

//// END APPLICATION OF TRACE ZERO
////

////
////APPLYING POSITIVE FLOOR TO chi
uiVar[VAR::U_CHI][node] = std::max(uiVar[VAR::U_CHI][node], CHI_FLOOR);
//// END APPLICATION OF POSITIVE FLOOR
////

//// NOW UPDATING THE METRIC VALUES
uiVar[VAR::U_GT00][node] = gt[0][0];
uiVar[VAR::U_GT01][node] = gt[0][1];
uiVar[VAR::U_GT02][node] = gt[0][2];
uiVar[VAR::U_GT11][node] = gt[1][1];
uiVar[VAR::U_GT12][node] = gt[1][2];
uiVar[VAR::U_GT22][node] = gt[2][2];


}

}  // namespace smokemax

#endif  // SMOKEMAX_CONSTRAINTS_H
