  double *adx_gt0, *ady_gt0, *adz_gt0, *adx_gt1;
  double *ady_gt1, *adz_gt1, *adx_gt2, *ady_gt2;
  double *adz_gt2, *adx_gt3, *ady_gt3, *adz_gt3;
  double *adx_gt4, *ady_gt4, *adz_gt4, *adx_gt5;
  double *ady_gt5, *adz_gt5, *adx_At0, *ady_At0;
  double *adz_At0, *adx_At1, *ady_At1, *adz_At1;
  double *adx_At2, *ady_At2, *adz_At2, *adx_At3;
  double *ady_At3, *adz_At3, *adx_At4, *ady_At4;
  double *adz_At4, *adx_At5, *ady_At5, *adz_At5;
  double *adx_alpha, *ady_alpha, *adz_alpha, *adx_beta0;
  double *ady_beta0, *adz_beta0, *adx_beta1, *ady_beta1;
  double *adz_beta1, *adx_beta2, *ady_beta2, *adz_beta2;
  double *adx_chi, *ady_chi, *adz_chi, *adx_Gt0;
  double *ady_Gt0, *adz_Gt0, *adx_Gt1, *ady_Gt1;
  double *adz_Gt1, *adx_Gt2, *ady_Gt2, *adz_Gt2;
  double *adx_K, *ady_K, *adz_K, *adx_B0;
  double *ady_B0, *adz_B0, *adx_B1, *ady_B1;
  double *adz_B1, *adx_B2, *ady_B2, *adz_B2;
  posix_memalign((void **)&adx_gt0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_gt0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_gt0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_gt1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_gt1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_gt1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_gt2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_gt2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_gt2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_gt3, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_gt3, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_gt3, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_gt4, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_gt4, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_gt4, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_gt5, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_gt5, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_gt5, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_At0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_At0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_At0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_At1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_At1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_At1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_At2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_At2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_At2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_At3, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_At3, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_At3, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_At4, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_At4, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_At4, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_At5, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_At5, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_At5, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_alpha, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_alpha, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_alpha, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_beta0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_beta0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_beta0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_beta1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_beta1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_beta1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_beta2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_beta2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_beta2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_chi, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_chi, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_chi, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_Gt0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_Gt0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_Gt0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_Gt1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_Gt1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_Gt1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_Gt2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_Gt2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_Gt2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_K, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_K, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_K, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_B0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_B0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_B0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_B1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_B1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_B1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adx_B2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&ady_B2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&adz_B2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  adx_gt0 += 2;
  ady_gt0 += 2;
  adz_gt0 += 2;
  adx_gt1 += 2;
  ady_gt1 += 2;
  adz_gt1 += 2;
  adx_gt2 += 2;
  ady_gt2 += 2;
  adz_gt2 += 2;
  adx_gt3 += 2;
  ady_gt3 += 2;
  adz_gt3 += 2;
  adx_gt4 += 2;
  ady_gt4 += 2;
  adz_gt4 += 2;
  adx_gt5 += 2;
  ady_gt5 += 2;
  adz_gt5 += 2;
  adx_At0 += 2;
  ady_At0 += 2;
  adz_At0 += 2;
  adx_At1 += 2;
  ady_At1 += 2;
  adz_At1 += 2;
  adx_At2 += 2;
  ady_At2 += 2;
  adz_At2 += 2;
  adx_At3 += 2;
  ady_At3 += 2;
  adz_At3 += 2;
  adx_At4 += 2;
  ady_At4 += 2;
  adz_At4 += 2;
  adx_At5 += 2;
  ady_At5 += 2;
  adz_At5 += 2;
  adx_alpha += 2;
  ady_alpha += 2;
  adz_alpha += 2;
  adx_beta0 += 2;
  ady_beta0 += 2;
  adz_beta0 += 2;
  adx_beta1 += 2;
  ady_beta1 += 2;
  adz_beta1 += 2;
  adx_beta2 += 2;
  ady_beta2 += 2;
  adz_beta2 += 2;
  adx_chi += 2;
  ady_chi += 2;
  adz_chi += 2;
  adx_Gt0 += 2;
  ady_Gt0 += 2;
  adz_Gt0 += 2;
  adx_Gt1 += 2;
  ady_Gt1 += 2;
  adz_Gt1 += 2;
  adx_Gt2 += 2;
  ady_Gt2 += 2;
  adz_Gt2 += 2;
  adx_K += 2;
  ady_K += 2;
  adz_K += 2;
  adx_B0 += 2;
  ady_B0 += 2;
  adz_B0 += 2;
  adx_B1 += 2;
  ady_B1 += 2;
  adz_B1 += 2;
  adx_B2 += 2;
  ady_B2 += 2;
  adz_B2 += 2;
