  dx_alpha -= 2;
  dy_alpha -= 2;
  dz_alpha -= 2;
  dx_beta0 -= 2;
  dy_beta0 -= 2;
  dz_beta0 -= 2;
  dx_beta1 -= 2;
  dy_beta1 -= 2;
  dz_beta1 -= 2;
  dx_beta2 -= 2;
  dy_beta2 -= 2;
  dz_beta2 -= 2;
  dx_B0 -= 2;
  dy_B0 -= 2;
  dz_B0 -= 2;
  dx_B1 -= 2;
  dy_B1 -= 2;
  dz_B1 -= 2;
  dx_B2 -= 2;
  dy_B2 -= 2;
  dz_B2 -= 2;
  dx_chi -= 2;
  dy_chi -= 2;
  dz_chi -= 2;
  dx_Gt0 -= 2;
  dy_Gt0 -= 2;
  dz_Gt0 -= 2;
  dx_Gt1 -= 2;
  dy_Gt1 -= 2;
  dz_Gt1 -= 2;
  dx_Gt2 -= 2;
  dy_Gt2 -= 2;
  dz_Gt2 -= 2;
  dx_K -= 2;
  dy_K -= 2;
  dz_K -= 2;
  dx_gt0 -= 2;
  dy_gt0 -= 2;
  dz_gt0 -= 2;
  dx_gt1 -= 2;
  dy_gt1 -= 2;
  dz_gt1 -= 2;
  dx_gt2 -= 2;
  dy_gt2 -= 2;
  dz_gt2 -= 2;
  dx_gt3 -= 2;
  dy_gt3 -= 2;
  dz_gt3 -= 2;
  dx_gt4 -= 2;
  dy_gt4 -= 2;
  dz_gt4 -= 2;
  dx_gt5 -= 2;
  dy_gt5 -= 2;
  dz_gt5 -= 2;
  dx_At0 -= 2;
  dy_At0 -= 2;
  dz_At0 -= 2;
  dx_At1 -= 2;
  dy_At1 -= 2;
  dz_At1 -= 2;
  dx_At2 -= 2;
  dy_At2 -= 2;
  dz_At2 -= 2;
  dx_At3 -= 2;
  dy_At3 -= 2;
  dz_At3 -= 2;
  dx_At4 -= 2;
  dy_At4 -= 2;
  dz_At4 -= 2;
  dx_At5 -= 2;
  dy_At5 -= 2;
  dz_At5 -= 2;
  dxx_gt0 -= 2;
  dxy_gt0 -= 2;
  dxz_gt0 -= 2;
  dyy_gt0 -= 2;
  dyz_gt0 -= 2;
  dzz_gt0 -= 2;
  dxx_gt1 -= 2;
  dxy_gt1 -= 2;
  dxz_gt1 -= 2;
  dyy_gt1 -= 2;
  dyz_gt1 -= 2;
  dzz_gt1 -= 2;
  dxx_gt2 -= 2;
  dxy_gt2 -= 2;
  dxz_gt2 -= 2;
  dyy_gt2 -= 2;
  dyz_gt2 -= 2;
  dzz_gt2 -= 2;
  dxx_gt3 -= 2;
  dxy_gt3 -= 2;
  dxz_gt3 -= 2;
  dyy_gt3 -= 2;
  dyz_gt3 -= 2;
  dzz_gt3 -= 2;
  dxx_gt4 -= 2;
  dxy_gt4 -= 2;
  dxz_gt4 -= 2;
  dyy_gt4 -= 2;
  dyz_gt4 -= 2;
  dzz_gt4 -= 2;
  dxx_gt5 -= 2;
  dxy_gt5 -= 2;
  dxz_gt5 -= 2;
  dyy_gt5 -= 2;
  dyz_gt5 -= 2;
  dzz_gt5 -= 2;
  dxx_chi -= 2;
  dxy_chi -= 2;
  dxz_chi -= 2;
  dyy_chi -= 2;
  dyz_chi -= 2;
  dzz_chi -= 2;
  dxx_alpha -= 2;
  dxy_alpha -= 2;
  dxz_alpha -= 2;
  dyy_alpha -= 2;
  dyz_alpha -= 2;
  dzz_alpha -= 2;
  dxx_beta0 -= 2;
  dxy_beta0 -= 2;
  dxz_beta0 -= 2;
  dyy_beta0 -= 2;
  dyz_beta0 -= 2;
  dzz_beta0 -= 2;
  dxx_beta1 -= 2;
  dxy_beta1 -= 2;
  dxz_beta1 -= 2;
  dyy_beta1 -= 2;
  dyz_beta1 -= 2;
  dzz_beta1 -= 2;
  dxx_beta2 -= 2;
  dxy_beta2 -= 2;
  dxz_beta2 -= 2;
  dyy_beta2 -= 2;
  dyz_beta2 -= 2;
  dzz_beta2 -= 2;
  free(dx_alpha);
  free(dy_alpha);
  free(dz_alpha);
  free(dx_beta0);
  free(dy_beta0);
  free(dz_beta0);
  free(dx_beta1);
  free(dy_beta1);
  free(dz_beta1);
  free(dx_beta2);
  free(dy_beta2);
  free(dz_beta2);
  free(dx_B0);
  free(dy_B0);
  free(dz_B0);
  free(dx_B1);
  free(dy_B1);
  free(dz_B1);
  free(dx_B2);
  free(dy_B2);
  free(dz_B2);
  free(dx_chi);
  free(dy_chi);
  free(dz_chi);
  free(dx_Gt0);
  free(dy_Gt0);
  free(dz_Gt0);
  free(dx_Gt1);
  free(dy_Gt1);
  free(dz_Gt1);
  free(dx_Gt2);
  free(dy_Gt2);
  free(dz_Gt2);
  free(dx_K);
  free(dy_K);
  free(dz_K);
  free(dx_gt0);
  free(dy_gt0);
  free(dz_gt0);
  free(dx_gt1);
  free(dy_gt1);
  free(dz_gt1);
  free(dx_gt2);
  free(dy_gt2);
  free(dz_gt2);
  free(dx_gt3);
  free(dy_gt3);
  free(dz_gt3);
  free(dx_gt4);
  free(dy_gt4);
  free(dz_gt4);
  free(dx_gt5);
  free(dy_gt5);
  free(dz_gt5);
  free(dx_At0);
  free(dy_At0);
  free(dz_At0);
  free(dx_At1);
  free(dy_At1);
  free(dz_At1);
  free(dx_At2);
  free(dy_At2);
  free(dz_At2);
  free(dx_At3);
  free(dy_At3);
  free(dz_At3);
  free(dx_At4);
  free(dy_At4);
  free(dz_At4);
  free(dx_At5);
  free(dy_At5);
  free(dz_At5);
  free(dxx_gt0);
  free(dxy_gt0);
  free(dxz_gt0);
  free(dyy_gt0);
  free(dyz_gt0);
  free(dzz_gt0);
  free(dxx_gt1);
  free(dxy_gt1);
  free(dxz_gt1);
  free(dyy_gt1);
  free(dyz_gt1);
  free(dzz_gt1);
  free(dxx_gt2);
  free(dxy_gt2);
  free(dxz_gt2);
  free(dyy_gt2);
  free(dyz_gt2);
  free(dzz_gt2);
  free(dxx_gt3);
  free(dxy_gt3);
  free(dxz_gt3);
  free(dyy_gt3);
  free(dyz_gt3);
  free(dzz_gt3);
  free(dxx_gt4);
  free(dxy_gt4);
  free(dxz_gt4);
  free(dyy_gt4);
  free(dyz_gt4);
  free(dzz_gt4);
  free(dxx_gt5);
  free(dxy_gt5);
  free(dxz_gt5);
  free(dyy_gt5);
  free(dyz_gt5);
  free(dzz_gt5);
  free(dxx_chi);
  free(dxy_chi);
  free(dxz_chi);
  free(dyy_chi);
  free(dyz_chi);
  free(dzz_chi);
  free(dxx_alpha);
  free(dxy_alpha);
  free(dxz_alpha);
  free(dyy_alpha);
  free(dyz_alpha);
  free(dzz_alpha);
  free(dxx_beta0);
  free(dxy_beta0);
  free(dxz_beta0);
  free(dyy_beta0);
  free(dyz_beta0);
  free(dzz_beta0);
  free(dxx_beta1);
  free(dxy_beta1);
  free(dxz_beta1);
  free(dyy_beta1);
  free(dyz_beta1);
  free(dzz_beta1);
  free(dxx_beta2);
  free(dxy_beta2);
  free(dxz_beta2);
  free(dyy_beta2);
  free(dyz_beta2);
  free(dzz_beta2);
