  adx_gt0 -= 2;
  ady_gt0 -= 2;
  adz_gt0 -= 2;
  adx_gt1 -= 2;
  ady_gt1 -= 2;
  adz_gt1 -= 2;
  adx_gt2 -= 2;
  ady_gt2 -= 2;
  adz_gt2 -= 2;
  adx_gt3 -= 2;
  ady_gt3 -= 2;
  adz_gt3 -= 2;
  adx_gt4 -= 2;
  ady_gt4 -= 2;
  adz_gt4 -= 2;
  adx_gt5 -= 2;
  ady_gt5 -= 2;
  adz_gt5 -= 2;
  adx_At0 -= 2;
  ady_At0 -= 2;
  adz_At0 -= 2;
  adx_At1 -= 2;
  ady_At1 -= 2;
  adz_At1 -= 2;
  adx_At2 -= 2;
  ady_At2 -= 2;
  adz_At2 -= 2;
  adx_At3 -= 2;
  ady_At3 -= 2;
  adz_At3 -= 2;
  adx_At4 -= 2;
  ady_At4 -= 2;
  adz_At4 -= 2;
  adx_At5 -= 2;
  ady_At5 -= 2;
  adz_At5 -= 2;
  adx_alpha -= 2;
  ady_alpha -= 2;
  adz_alpha -= 2;
  adx_beta0 -= 2;
  ady_beta0 -= 2;
  adz_beta0 -= 2;
  adx_beta1 -= 2;
  ady_beta1 -= 2;
  adz_beta1 -= 2;
  adx_beta2 -= 2;
  ady_beta2 -= 2;
  adz_beta2 -= 2;
  adx_chi -= 2;
  ady_chi -= 2;
  adz_chi -= 2;
  adx_Gt0 -= 2;
  ady_Gt0 -= 2;
  adz_Gt0 -= 2;
  adx_Gt1 -= 2;
  ady_Gt1 -= 2;
  adz_Gt1 -= 2;
  adx_Gt2 -= 2;
  ady_Gt2 -= 2;
  adz_Gt2 -= 2;
  adx_K -= 2;
  ady_K -= 2;
  adz_K -= 2;
  adx_B0 -= 2;
  ady_B0 -= 2;
  adz_B0 -= 2;
  adx_B1 -= 2;
  ady_B1 -= 2;
  adz_B1 -= 2;
  adx_B2 -= 2;
  ady_B2 -= 2;
  adz_B2 -= 2;
  free(adx_gt0);
  free(ady_gt0);
  free(adz_gt0);
  free(adx_gt1);
  free(ady_gt1);
  free(adz_gt1);
  free(adx_gt2);
  free(ady_gt2);
  free(adz_gt2);
  free(adx_gt3);
  free(ady_gt3);
  free(adz_gt3);
  free(adx_gt4);
  free(ady_gt4);
  free(adz_gt4);
  free(adx_gt5);
  free(ady_gt5);
  free(adz_gt5);
  free(adx_At0);
  free(ady_At0);
  free(adz_At0);
  free(adx_At1);
  free(ady_At1);
  free(adz_At1);
  free(adx_At2);
  free(ady_At2);
  free(adz_At2);
  free(adx_At3);
  free(ady_At3);
  free(adz_At3);
  free(adx_At4);
  free(ady_At4);
  free(adz_At4);
  free(adx_At5);
  free(ady_At5);
  free(adz_At5);
  free(adx_alpha);
  free(ady_alpha);
  free(adz_alpha);
  free(adx_beta0);
  free(ady_beta0);
  free(adz_beta0);
  free(adx_beta1);
  free(ady_beta1);
  free(adz_beta1);
  free(adx_beta2);
  free(ady_beta2);
  free(adz_beta2);
  free(adx_chi);
  free(ady_chi);
  free(adz_chi);
  free(adx_Gt0);
  free(ady_Gt0);
  free(adz_Gt0);
  free(adx_Gt1);
  free(ady_Gt1);
  free(adz_Gt1);
  free(adx_Gt2);
  free(ady_Gt2);
  free(adz_Gt2);
  free(adx_K);
  free(ady_K);
  free(adz_K);
  free(adx_B0);
  free(ady_B0);
  free(adz_B0);
  free(adx_B1);
  free(ady_B1);
  free(adz_B1);
  free(adx_B2);
  free(ady_B2);
  free(adz_B2);
