  double *dx_alpha, *dy_alpha, *dz_alpha, *dx_beta0;
  double *dy_beta0, *dz_beta0, *dx_beta1, *dy_beta1;
  double *dz_beta1, *dx_beta2, *dy_beta2, *dz_beta2;
  double *dx_B0, *dy_B0, *dz_B0, *dx_B1;
  double *dy_B1, *dz_B1, *dx_B2, *dy_B2;
  double *dz_B2, *dx_chi, *dy_chi, *dz_chi;
  double *dx_Gt0, *dy_Gt0, *dz_Gt0, *dx_Gt1;
  double *dy_Gt1, *dz_Gt1, *dx_Gt2, *dy_Gt2;
  double *dz_Gt2, *dx_K, *dy_K, *dz_K;
  double *dx_gt0, *dy_gt0, *dz_gt0, *dx_gt1;
  double *dy_gt1, *dz_gt1, *dx_gt2, *dy_gt2;
  double *dz_gt2, *dx_gt3, *dy_gt3, *dz_gt3;
  double *dx_gt4, *dy_gt4, *dz_gt4, *dx_gt5;
  double *dy_gt5, *dz_gt5, *dx_At0, *dy_At0;
  double *dz_At0, *dx_At1, *dy_At1, *dz_At1;
  double *dx_At2, *dy_At2, *dz_At2, *dx_At3;
  double *dy_At3, *dz_At3, *dx_At4, *dy_At4;
  double *dz_At4, *dx_At5, *dy_At5, *dz_At5;
  double *dxx_gt0, *dxy_gt0, *dxz_gt0, *dyy_gt0;
  double *dyz_gt0, *dzz_gt0, *dxx_gt1, *dxy_gt1;
  double *dxz_gt1, *dyy_gt1, *dyz_gt1, *dzz_gt1;
  double *dxx_gt2, *dxy_gt2, *dxz_gt2, *dyy_gt2;
  double *dyz_gt2, *dzz_gt2, *dxx_gt3, *dxy_gt3;
  double *dxz_gt3, *dyy_gt3, *dyz_gt3, *dzz_gt3;
  double *dxx_gt4, *dxy_gt4, *dxz_gt4, *dyy_gt4;
  double *dyz_gt4, *dzz_gt4, *dxx_gt5, *dxy_gt5;
  double *dxz_gt5, *dyy_gt5, *dyz_gt5, *dzz_gt5;
  double *dxx_chi, *dxy_chi, *dxz_chi, *dyy_chi;
  double *dyz_chi, *dzz_chi, *dxx_alpha, *dxy_alpha;
  double *dxz_alpha, *dyy_alpha, *dyz_alpha, *dzz_alpha;
  double *dxx_beta0, *dxy_beta0, *dxz_beta0, *dyy_beta0;
  double *dyz_beta0, *dzz_beta0, *dxx_beta1, *dxy_beta1;
  double *dxz_beta1, *dyy_beta1, *dyz_beta1, *dzz_beta1;
  double *dxx_beta2, *dxy_beta2, *dxz_beta2, *dyy_beta2;
  double *dyz_beta2, *dzz_beta2;
  posix_memalign((void **)&dx_alpha, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_alpha, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_alpha, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_beta0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_beta0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_beta0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_beta1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_beta1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_beta1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_beta2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_beta2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_beta2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_B0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_B0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_B0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_B1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_B1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_B1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_B2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_B2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_B2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_chi, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_chi, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_chi, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_Gt0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_Gt0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_Gt0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_Gt1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_Gt1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_Gt1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_Gt2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_Gt2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_Gt2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_K, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_K, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_K, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_gt0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_gt0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_gt0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_gt1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_gt1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_gt1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_gt2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_gt2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_gt2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_gt3, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_gt3, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_gt3, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_gt4, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_gt4, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_gt4, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_gt5, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_gt5, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_gt5, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_At0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_At0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_At0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_At1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_At1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_At1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_At2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_At2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_At2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_At3, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_At3, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_At3, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_At4, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_At4, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_At4, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dx_At5, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dy_At5, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dz_At5, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxx_gt0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxy_gt0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxz_gt0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyy_gt0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyz_gt0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dzz_gt0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxx_gt1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxy_gt1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxz_gt1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyy_gt1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyz_gt1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dzz_gt1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxx_gt2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxy_gt2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxz_gt2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyy_gt2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyz_gt2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dzz_gt2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxx_gt3, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxy_gt3, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxz_gt3, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyy_gt3, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyz_gt3, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dzz_gt3, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxx_gt4, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxy_gt4, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxz_gt4, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyy_gt4, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyz_gt4, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dzz_gt4, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxx_gt5, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxy_gt5, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxz_gt5, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyy_gt5, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyz_gt5, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dzz_gt5, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxx_chi, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxy_chi, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxz_chi, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyy_chi, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyz_chi, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dzz_chi, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxx_alpha, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxy_alpha, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxz_alpha, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyy_alpha, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyz_alpha, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dzz_alpha, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxx_beta0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxy_beta0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxz_beta0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyy_beta0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyz_beta0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dzz_beta0, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxx_beta1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxy_beta1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxz_beta1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyy_beta1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyz_beta1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dzz_beta1, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxx_beta2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxy_beta2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dxz_beta2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyy_beta2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dyz_beta2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  posix_memalign((void **)&dzz_beta2, align, (n+AVX_SIMD_LENGTH) * sizeof(double));
  dx_alpha += 2;
  dy_alpha += 2;
  dz_alpha += 2;
  dx_beta0 += 2;
  dy_beta0 += 2;
  dz_beta0 += 2;
  dx_beta1 += 2;
  dy_beta1 += 2;
  dz_beta1 += 2;
  dx_beta2 += 2;
  dy_beta2 += 2;
  dz_beta2 += 2;
  dx_B0 += 2;
  dy_B0 += 2;
  dz_B0 += 2;
  dx_B1 += 2;
  dy_B1 += 2;
  dz_B1 += 2;
  dx_B2 += 2;
  dy_B2 += 2;
  dz_B2 += 2;
  dx_chi += 2;
  dy_chi += 2;
  dz_chi += 2;
  dx_Gt0 += 2;
  dy_Gt0 += 2;
  dz_Gt0 += 2;
  dx_Gt1 += 2;
  dy_Gt1 += 2;
  dz_Gt1 += 2;
  dx_Gt2 += 2;
  dy_Gt2 += 2;
  dz_Gt2 += 2;
  dx_K += 2;
  dy_K += 2;
  dz_K += 2;
  dx_gt0 += 2;
  dy_gt0 += 2;
  dz_gt0 += 2;
  dx_gt1 += 2;
  dy_gt1 += 2;
  dz_gt1 += 2;
  dx_gt2 += 2;
  dy_gt2 += 2;
  dz_gt2 += 2;
  dx_gt3 += 2;
  dy_gt3 += 2;
  dz_gt3 += 2;
  dx_gt4 += 2;
  dy_gt4 += 2;
  dz_gt4 += 2;
  dx_gt5 += 2;
  dy_gt5 += 2;
  dz_gt5 += 2;
  dx_At0 += 2;
  dy_At0 += 2;
  dz_At0 += 2;
  dx_At1 += 2;
  dy_At1 += 2;
  dz_At1 += 2;
  dx_At2 += 2;
  dy_At2 += 2;
  dz_At2 += 2;
  dx_At3 += 2;
  dy_At3 += 2;
  dz_At3 += 2;
  dx_At4 += 2;
  dy_At4 += 2;
  dz_At4 += 2;
  dx_At5 += 2;
  dy_At5 += 2;
  dz_At5 += 2;
  dxx_gt0 += 2;
  dxy_gt0 += 2;
  dxz_gt0 += 2;
  dyy_gt0 += 2;
  dyz_gt0 += 2;
  dzz_gt0 += 2;
  dxx_gt1 += 2;
  dxy_gt1 += 2;
  dxz_gt1 += 2;
  dyy_gt1 += 2;
  dyz_gt1 += 2;
  dzz_gt1 += 2;
  dxx_gt2 += 2;
  dxy_gt2 += 2;
  dxz_gt2 += 2;
  dyy_gt2 += 2;
  dyz_gt2 += 2;
  dzz_gt2 += 2;
  dxx_gt3 += 2;
  dxy_gt3 += 2;
  dxz_gt3 += 2;
  dyy_gt3 += 2;
  dyz_gt3 += 2;
  dzz_gt3 += 2;
  dxx_gt4 += 2;
  dxy_gt4 += 2;
  dxz_gt4 += 2;
  dyy_gt4 += 2;
  dyz_gt4 += 2;
  dzz_gt4 += 2;
  dxx_gt5 += 2;
  dxy_gt5 += 2;
  dxz_gt5 += 2;
  dyy_gt5 += 2;
  dyz_gt5 += 2;
  dzz_gt5 += 2;
  dxx_chi += 2;
  dxy_chi += 2;
  dxz_chi += 2;
  dyy_chi += 2;
  dyz_chi += 2;
  dzz_chi += 2;
  dxx_alpha += 2;
  dxy_alpha += 2;
  dxz_alpha += 2;
  dyy_alpha += 2;
  dyz_alpha += 2;
  dzz_alpha += 2;
  dxx_beta0 += 2;
  dxy_beta0 += 2;
  dxz_beta0 += 2;
  dyy_beta0 += 2;
  dyz_beta0 += 2;
  dzz_beta0 += 2;
  dxx_beta1 += 2;
  dxy_beta1 += 2;
  dxz_beta1 += 2;
  dyy_beta1 += 2;
  dyz_beta1 += 2;
  dzz_beta1 += 2;
  dxx_beta2 += 2;
  dxy_beta2 += 2;
  dxz_beta2 += 2;
  dyy_beta2 += 2;
  dyz_beta2 += 2;
  dzz_beta2 += 2;
