/**
 * @file grDef.h
 * @brief Variable enums, coordinate macros, and name arrays for smokemin.
 *
 * Generated by dendrosym. If you add variables in the Python config,
 * regenerate this file. Custom enums or macros can be added below
 * the generated sections.
 *
 * The VAR enum ordering matches the order variables were added via
 * add_evolution_variables() in the Python config, which also determines
 * the layout of the uZipVars array.
 */

#ifndef DENDRO_GRDEF_H
#define DENDRO_GRDEF_H

// coordinate transforms between grid space and physical space
#define Rx (smokemin::SMOKEMIN_COMPD_MAX[0] - smokemin::SMOKEMIN_COMPD_MIN[0])
#define Ry (smokemin::SMOKEMIN_COMPD_MAX[1] - smokemin::SMOKEMIN_COMPD_MIN[1])
#define Rz (smokemin::SMOKEMIN_COMPD_MAX[2] - smokemin::SMOKEMIN_COMPD_MIN[2])

#define RgX (smokemin::SMOKEMIN_OCTREE_MAX[0] - smokemin::SMOKEMIN_OCTREE_MIN[0])
#define RgY (smokemin::SMOKEMIN_OCTREE_MAX[1] - smokemin::SMOKEMIN_OCTREE_MIN[1])
#define RgZ (smokemin::SMOKEMIN_OCTREE_MAX[2] - smokemin::SMOKEMIN_OCTREE_MIN[2])

#define GRIDX_TO_X(xg) \
    (((Rx / RgX) * (xg - smokemin::SMOKEMIN_OCTREE_MIN[0])) + smokemin::SMOKEMIN_COMPD_MIN[0])
#define GRIDY_TO_Y(yg) \
    (((Ry / RgY) * (yg - smokemin::SMOKEMIN_OCTREE_MIN[1])) + smokemin::SMOKEMIN_COMPD_MIN[1])
#define GRIDZ_TO_Z(zg) \
    (((Rz / RgZ) * (zg - smokemin::SMOKEMIN_OCTREE_MIN[2])) + smokemin::SMOKEMIN_COMPD_MIN[2])

#define X_TO_GRIDX(xc) \
    (((RgX / Rx) * (xc - smokemin::SMOKEMIN_COMPD_MIN[0])) + smokemin::SMOKEMIN_OCTREE_MIN[0])
#define Y_TO_GRIDY(yc) \
    (((RgY / Ry) * (yc - smokemin::SMOKEMIN_COMPD_MIN[1])) + smokemin::SMOKEMIN_OCTREE_MIN[1])
#define Z_TO_GRIDZ(zc) \
    (((RgZ / Rz) * (zc - smokemin::SMOKEMIN_COMPD_MIN[2])) + smokemin::SMOKEMIN_OCTREE_MIN[2])

enum RKType { RK3 = 0, RK4, RK45 };

namespace smokemin {

// evolution variable enum -- ordering matches the python config
enum VAR
{
    U_U = 0,
    U_V
};

// constraint variable enum
enum VAR_CONSTRAINT
{
};

// human-readable name arrays (for logging and vtu output)
static const char *SMOKEMIN_VAR_NAMES[] = {"U_U", "U_V"};


static const char *SMOKEMIN_VAR_CONSTRAINT_NAMES[] = {};


// iterable lists for looping over all variables
static const VAR SMOKEMIN_VAR_ITERABLE_LIST[] = {U_U, U_V};


static const VAR_CONSTRAINT SMOKEMIN_VAR_CONSTRAINT_ITERABLE_LIST[] = {};


// refinement strategy
enum RefinementMode {
    WAMR = 0,
    EH,
    EH_WAMR,
    BH_LOC,
    BH_WAMR,
    REFINE_MODE_NONE
};

}  // namespace smokemin

#endif  // DENDRO_GRDEF_H
