/**
 * @file grUtils.h
 * @brief Initial data and utility declarations for the smokemin solver.
 *
 * Generated by dendrosym. Safe to edit.
 */

#ifndef GRUTILS_H
#define GRUTILS_H

#include "grDef.h"

namespace smokemin {

/**@brief Initial data dispatcher. Called for every grid point during init.
 *
 * Receives grid (octree) coordinates -- the conversion to physical coords
 * happens inside this function via the GRIDX_TO_X macros.
 */
void initDataFuncToPhysCoords(const double xx, const double yy,
                              const double zz, double *var);

/**@brief Cheap-estimate IC dispatcher used by function2Octree. Real IC is
 * applied via smokeminCtx::init_grid() after the mesh is built.
 */
void initDataFuncToPhysCoordsForMesh(const double xx, const double yy,
                                     const double zz, double *var);


/**@brief Position-dependent wavelet tolerance, selected by
 * SMOKEMIN_USE_WAVELET_TOL_FUNCTION. (x,y,z) are domain coords and hx the
 * element spacing in domain units, as passed by Mesh::isReMeshUnzip.
 */
double computeWTolDCoords(double x, double y, double z, double *hx);


}  // namespace smokemin

#endif  // GRUTILS_H
