/**
 * @file parameters.h
 * @brief Parameter declarations for the smokemin solver.
 *
 * Generated by dendrosym. Safe to edit -- add new parameters as needed.
 *
 * Parameters are read from a TOML file at runtime. The TOML file uses
 * sections to organize parameters by category:
 *
 *   [solver]          - mesh, time stepping, I/O
 *   [physics]         - equation-specific theory parameters
 *   [initial_data]    - initial condition setup
 *   [bh1] / [bh2]    - per-black-hole parameters
 *   [refinement]      - AMR settings
 *   [dissipation]     - KO dissipation settings
 *   [wave_extraction] - gravitational wave extraction
 */

#ifndef PARAMETERS_H
#define PARAMETERS_H

#include <string.h>
#include <iostream>
#include <vector>

#include <toml.hpp>

#include "dendro.h"
#include "memory_pool.h"
#include "parUtils.h"
#include <memory>
#include "derivatives.h"

#include "grDef.h"

namespace smokemin {

// -----------------------------------------------------------------
// Core functions
// -----------------------------------------------------------------
void readParamFile(const char* inFile, MPI_Comm comm);
void dumpParamFile(std::ostream& sout, int root, MPI_Comm comm);

// -----------------------------------------------------------------
// Runtime state (not from TOML)
// -----------------------------------------------------------------
extern mem::memory_pool<double> SMOKEMIN_MEM_POOL;


extern double SMOKEMIN_CURRENT_RK_COORD_TIME;
extern unsigned int SMOKEMIN_CURRENT_RK_STEP;

extern double* SMOKEMIN_DERIV_WORKSPACE;
extern double SMOKEMIN_CURRENT_MIN_DX;

// -----------------------------------------------------------------
// [solver] - Mesh and time stepping
// -----------------------------------------------------------------
extern unsigned int SMOKEMIN_ELE_ORDER;
extern unsigned int SMOKEMIN_PADDING_WIDTH;
extern double SMOKEMIN_COMPD_MIN[3];
extern double SMOKEMIN_COMPD_MAX[3];
extern double SMOKEMIN_OCTREE_MIN[3];
extern double SMOKEMIN_OCTREE_MAX[3];
extern unsigned int SMOKEMIN_DIM;
extern unsigned int SMOKEMIN_MAXDEPTH;
extern unsigned int SMOKEMIN_MINDEPTH;

// Block-adaptive mesh: if true, the initial octree is a uniform grid at
// MINDEPTH over the block region [BLK_MIN, BLK_MAX], with AMR disabled.
// If false, function2Octree is used (wavelet-driven AMR enabled).
// Matches BSSN_GR's BSSN_ENABLE_BLOCK_ADAPTIVITY convention.
extern bool SMOKEMIN_ENABLE_BLOCK_ADAPTIVITY;
extern double SMOKEMIN_BLK_MIN_X;
extern double SMOKEMIN_BLK_MIN_Y;
extern double SMOKEMIN_BLK_MIN_Z;
extern double SMOKEMIN_BLK_MAX_X;
extern double SMOKEMIN_BLK_MAX_Y;
extern double SMOKEMIN_BLK_MAX_Z;

extern double SMOKEMIN_RK_TIME_BEGIN;
extern double SMOKEMIN_RK_TIME_END;
extern unsigned int SMOKEMIN_RK_TYPE;
extern double SMOKEMIN_RK45_TIME_STEP_SIZE;
extern double SMOKEMIN_RK45_DESIRED_TOL;
extern double SMOKEMIN_CFL_FACTOR;

// I/O
extern unsigned int SMOKEMIN_IO_OUTPUT_FREQ;
extern unsigned int SMOKEMIN_TIME_STEP_OUTPUT_FREQ;
extern unsigned int SMOKEMIN_CHECKPT_FREQ;
extern bool SMOKEMIN_RESTORE_SOLVER;
extern std::string SMOKEMIN_VTU_FILE_PREFIX;
extern std::string SMOKEMIN_CHKPT_FILE_PREFIX;
extern std::string SMOKEMIN_PROFILE_FILE_PREFIX;

extern unsigned int SMOKEMIN_NUM_EVOL_VARS_VTU_OUTPUT;
extern unsigned int SMOKEMIN_NUM_CONST_VARS_VTU_OUTPUT;
extern unsigned int SMOKEMIN_VTU_OUTPUT_EVOL_INDICES[2];
extern unsigned int SMOKEMIN_VTU_OUTPUT_CONST_INDICES[0];
// terminal_output norm selection: variable index lists (count = list length)
extern std::vector<unsigned int> SMOKEMIN_TERMINAL_OUTPUT_EVOL_INDICES;
extern std::vector<unsigned int> SMOKEMIN_TERMINAL_OUTPUT_CONST_INDICES;
extern bool SMOKEMIN_VTU_X_SLICE;
extern bool SMOKEMIN_VTU_Y_SLICE;
extern bool SMOKEMIN_VTU_Z_SLICE;

// Mesh management
extern unsigned int SMOKEMIN_DENDRO_GRAIN_SZ;
extern double SMOKEMIN_DENDRO_AMR_FAC;
extern double SMOKEMIN_LOAD_IMB_TOL;
extern unsigned int SMOKEMIN_ASYNC_COMM_K;
extern unsigned int SMOKEMIN_INIT_GRID_ITER;
extern unsigned int SMOKEMIN_REMESH_TEST_FREQ;
extern unsigned int SMOKEMIN_NUM_REFINE_VARS;
extern unsigned int SMOKEMIN_REFINE_VARIABLE_INDICES[2];
extern double SMOKEMIN_WAVELET_TOL;
extern unsigned int SMOKEMIN_USE_WAVELET_TOL_FUNCTION;
extern double SMOKEMIN_WAVELET_TOL_MAX;
extern double SMOKEMIN_WAVELET_TOL_FUNCTION_R0;
extern double SMOKEMIN_WAVELET_TOL_FUNCTION_R1;
extern RefinementMode SMOKEMIN_REFINEMENT_MODE;

// grid bounds (physical domain for domain decomposition)
extern double SMOKEMIN_GRID_MIN_X;
extern double SMOKEMIN_GRID_MIN_Y;
extern double SMOKEMIN_GRID_MIN_Z;
extern double SMOKEMIN_GRID_MAX_X;
extern double SMOKEMIN_GRID_MAX_Y;
extern double SMOKEMIN_GRID_MAX_Z;
extern unsigned int SMOKEMIN_SPLIT_FIX;
extern unsigned int SMOKEMIN_ASYNC_COMM_K;
// ENABLE_BLOCK_ADAPTIVITY declared earlier as `bool` (BSSN-style).

// Logging
extern std::string DENDRO_LOG_FILE;
extern int DENDRO_LOG_FILE_LEVEL;
extern int DENDRO_LOG_CONSOLE_LEVEL;
extern bool DENDRO_LOG_FORCE_FILE_FLUSH;

// -----------------------------------------------------------------
// [physics] - Equation-specific parameters
//
// These correspond to the ParameterVariable objects defined in the
// Python equation config file.
// -----------------------------------------------------------------

// -----------------------------------------------------------------
// [dissipation]
// -----------------------------------------------------------------
// [initial_data]
extern unsigned int SMOKEMIN_ID_TYPE;

// evolution constraint floors

extern double KO_DISS_SIGMA;
extern bool USE_CONST_KO;
extern unsigned int DISSIPATION_TYPE;

// -----------------------------------------------------------------
// DendroDerivatives object (configurable stencils + filtering)
//
// This replaces the old per-stencil-order derivs.cpp approach.
// Derivative type, order, and filtering are all set at runtime
// from the TOML parameter file.
// -----------------------------------------------------------------
extern std::unique_ptr<dendroderivs::DendroDerivatives> SMOKEMIN_DERIVS;
extern std::string SMOKEMIN_DERIVTYPE_FIRST;
extern std::string SMOKEMIN_DERIVTYPE_SECOND;
extern std::vector<double> SMOKEMIN_DERIV_FIRST_COEFFS;
extern std::vector<double> SMOKEMIN_DERIV_SECOND_COEFFS;
extern unsigned int SMOKEMIN_DERIV_FIRST_MATID;
extern unsigned int SMOKEMIN_DERIV_SECOND_MATID;
extern std::string SMOKEMIN_INMATFILT_FIRST;
extern std::string SMOKEMIN_INMATFILT_SECOND;
extern std::vector<double> SMOKEMIN_INMATFILT_FIRST_COEFFS;
extern std::vector<double> SMOKEMIN_INMATFILT_SECOND_COEFFS;
extern std::string SMOKEMIN_POST_RHS_FILTER;
// fused in-kernel stencils: a runtime request, not a guarantee. Only explicit
// local stencils can be inlined into the RHS body -- a compact/matrix engine
// derivative is a banded solve along a whole line -- so the solver degrades to
// the precomputed derivative pass when the engine cannot honour it.
extern bool SMOKEMIN_USE_FUSED_STENCILS;

// -----------------------------------------------------------------
// Derivative count (auto-computed from equations)
// -----------------------------------------------------------------
extern unsigned int SMOKEMIN_NUM_DERIVATIVES;

}  // namespace smokemin



// -----------------------------------------------------------------
// [wave_extraction]
// -----------------------------------------------------------------


#endif  // PARAMETERS_H
