/**
 * @file rhs.h
 * @brief RHS function declarations for the smokemin solver.
 *
 * Generated by dendrosym. Safe to edit.
 */

#ifndef RHS_H
#define RHS_H

#include <time.h>
#include <cmath>
#include <iostream>

#include "block.h"
#include "derivatives.h"
#include "grDef.h"
#include "mathUtils.h"
#include "parameters.h"
#include "profile_params.h"

/**@brief Computes complete RHS iterating over all the blocks.
 * @param[out] uzipVarsRHS Unzipped variables for computed RHS.
 * @param[in]  uZipVars Unzipped variables.
 * @param[in]  blkList Block list.
 * @param[in]  numBlocks Number of blocks.
 * @param[in]  curr_time Current simulation time.
 * @param[in]  uZipConstVars Constant (constraint) variables.
 */
void smokeminRHS(double **uzipVarsRHS, const double **uZipVars,
             const ot::Block *blkList, unsigned int numBlocks,
             const double curr_time, const double **uZipConstVars);

/**@brief Per-block RHS computation. */
void smokeminrhs(double **uzipVarsRHS, const double **uZipVars,
             const unsigned int &offset, const double *ptmin,
             const double *ptmax, const unsigned int *sz,
             const unsigned int &bflag, const double t,
             const double **uZipConstVars);

/**@brief Sommerfeld-like radiation boundary conditions. */
void smokemin_bcs(double *f_rhs, const double *f,
              const double *dxf, const double *dyf, const double *dzf,
              const double *pmin, const double *pmax,
              const double f_falloff, const double f_asymptotic,
              const unsigned int *sz, const unsigned int &bflag);

/**@brief Freeze boundary conditions (zero RHS at boundary). */
void freeze_bcs(double *f_rhs, const unsigned int *sz,
                const unsigned int &bflag);

#endif  // RHS_H
