/**
 * @file smokeminCtx.h
 * @brief Solver context for the smokemin solver.
 *
 * Generated by dendrosym. Safe to edit.
 *
 * Inherits from Dendro's ts::Ctx base class to provide:
 *   - RHS dispatch to generated equation code
 *   - Evolution constraint enforcement (metric det, traceless, floors)
 *   - Black hole location tracking and merger detection
 *   - Constraint variable computation
 *   - VTU output, checkpointing, and remeshing
 */

#ifndef SMOKEMIN_CTX_H
#define SMOKEMIN_CTX_H

#include <iostream>
#include <vector>
#include <utility>

#include "dendro.h"
#include "dvec.h"
#include "ctx.h"
#include "grDef.h"
#include "parameters.h"
#include "rhs.h"
#include "physcon.h"
#include "smokemin_constraints.h"

namespace smokemin {

typedef ot::DVector<DendroScalar, unsigned int> DVec;

/**@brief Storage slots for zipped/unzipped variable vectors. */
enum VL {
    CPU_EV = 0,        // zipped evolution variables (primary storage)
    CPU_CV,            // zipped constraint variables
    CPU_EV_UZ_IN,      // unzipped evolution (input to RHS)
    CPU_EV_UZ_OUT,     // unzipped evolution (output from RHS)
    CPU_CV_UZ_IN,      // unzipped constraint (input)
    END
};

class SMOKEMINCtx : public ts::Ctx<SMOKEMINCtx, DendroScalar, unsigned int> {

   protected:
    DVec m_var[VL::END];


    // State flags
    bool m_bConstraintsComputed;
    // checkpoint restore guard: initialize() is invoked twice (once directly,
    // once from ets->init()); restore only on the first call.
    bool m_bCheckpointRestored = false;

    // Grid stats
    DendroIntL m_uiGlobalMeshElements;
    DendroIntL m_uiGlobalGridPoints;
    bool m_uiWroteGridInfoHeader;

   public:
    SMOKEMINCtx(ot::Mesh *pMesh);
    ~SMOKEMINCtx();

    // ---- Core RHS interface ----
    int initialize();
    int init_grid();
    int rhs(DVec *in, DVec *out, unsigned int sz, DendroScalar time);
    int finalize();

    // ---- RK stage/timestep hooks ----
    int pre_stage(DVec &sIn);
    int post_stage(DVec &sIn);
    int pre_timestep(DVec &sIn);
    int post_timestep(DVec &sIn);

    // Block-wise hooks (called by Dendro per octree block)
    int pre_stage_blk(DendroScalar *unzipIn, DendroScalar *unzipOut,
                      unsigned int *blkIDs, unsigned int numBlocks,
                      DendroScalar *blk_dx);
    int post_stage_blk(DendroScalar *unzipIn, DendroScalar *unzipOut,
                       unsigned int *blkIDs, unsigned int numBlocks,
                       DendroScalar *blk_dx);
    int post_timestep_blk(DendroScalar *unzipIn, DendroScalar *unzipOut,
                          unsigned int *blkIDs, unsigned int numBlocks,
                          DendroScalar *blk_dx);

    // ---- Constraint computation ----
    void compute_constraint_variables();
    int extract_constraints();




    // ---- Output ----
    int write_vtu();
    int terminal_output();
    void write_grid_summary_data();

    // ---- Remeshing ----
    bool is_remesh();
    int grid_transfer(const ot::Mesh *m_new);
    void calculate_full_grid_size();

    // ---- Checkpointing ----
    int write_checkpt();
    int restore_checkpt();


    // ---- Accessors ----
    DVec &get_evolution_vars() { return m_var[VL::CPU_EV]; }
    DVec &get_constraint_vars() { return m_var[VL::CPU_CV]; }
    ot::Mesh *get_mesh() { return m_uiMesh; }

    void prepare_for_next_iter();
};

}  // namespace smokemin

#endif  // SMOKEMIN_CTX_H
