/**
 * @file smokemin_constraints.h
 * @brief Evolution constraint enforcement for the smokemin solver.
 *
 * Generated by dendrosym. Safe to edit.
 *
 * Called after each RK timestep (and during initialization) to enforce
 * algebraic constraints on the evolution variables. Important for numerical
 * stability -- conformal metric determinant must stay 1, traceless tensors
 * must stay traceless, and some fields need positive floors to avoid
 * division by zero.
 *
 * enforce_smokemin_constraints() receives a 2D array of variable
 * pointers and a node index. Reads and modifies variables in-place.
 */

#ifndef SMOKEMIN_CONSTRAINTS_H
#define SMOKEMIN_CONSTRAINTS_H

#include "grDef.h"
#include "parameters.h"

#include <cmath>
#include <iostream>

namespace smokemin {

inline void enforce_smokemin_constraints(double **uzipVars,
                                     const unsigned int node) {
    // no evolution constraints configured.
    // to add constraints, use dendroConfigs.add_evolution_constraint()
    // in the python config, or add them manually here.
}

}  // namespace smokemin

#endif  // SMOKEMIN_CONSTRAINTS_H
