/**
 * @file smokemax_main.cpp
 * @brief Main entry point for the smokemax solver.
 *
 * Generated by dendrosym. Safe to edit -- add custom diagnostics,
 * change the evolution loop, add post-processing steps, etc.
 *
 * Based on the EM4 solver main from dendrolib.
 */

#include <algorithm>
#include <iostream>
#include <vector>

#include "TreeNode.h"
#include "dendro.h"
#include "ets.h"
#include "mesh.h"
#include "meshUtils.h"
#include "mpi.h"
#include "octUtils.h"

#include "grDef.h"
#include "profile_params.h"
#include "grUtils.h"
#include "parameters.h"
#include "smokemaxCtx.h"
#include "TwoPunctures.h"
#include "smokemax_tpid_writer.h"

#ifndef NRM
#define NRM "\x1B[0m"
#define YLW "\x1B[33m"
#define GRN "\x1B[32m"
#endif

int main(int argc, char **argv) {
    MPI_Init(&argc, &argv);
    MPI_Comm comm = MPI_COMM_WORLD;

    int rank, npes;
    MPI_Comm_rank(comm, &rank);
    MPI_Comm_size(comm, &npes);

    if (argc < 2) {
        if (rank == 0)
            std::cerr << "Usage: " << argv[0] << " <parameter_file.toml>" << std::endl;
        MPI_Finalize();
        return 1;
    }

    // read parameters
    smokemax::readParamFile(argv[1], comm);

    TPID::registerPunctureVarsWriter(smokemax::writePunctureVars);

    if (rank == 0) {
        std::cout << GRN << "========================================" << NRM << std::endl;
        std::cout << GRN << "  SMOKEMAX Solver" << NRM << std::endl;
        std::cout << "  Processes: " << npes << std::endl;
        std::cout << "  Element order: " << smokemax::SMOKEMAX_ELE_ORDER << std::endl;
        std::cout << "  Max depth: " << smokemax::SMOKEMAX_MAXDEPTH << std::endl;
        std::cout << "  Evolution variables: 24" << std::endl;
        std::cout << "  Constraint variables: 6" << std::endl;
        std::cout << GRN << "========================================" << NRM << std::endl;
    }

    smokemax::dumpParamFile(std::cout, 0, comm);

    // mesh generation
    _InitializeHcurve(smokemax::SMOKEMAX_DIM);

    // set the dendrolib globals for max depth and element order
    m_uiMaxDepth = smokemax::SMOKEMAX_MAXDEPTH;

    const unsigned int eOrder = smokemax::SMOKEMAX_ELE_ORDER;

    // mesh-refinement IC: cheap estimate for singular ICs; full IC applied
    // by ctx->init_grid() below.
    std::function<void(double, double, double, double *)> f_init =
        [](double x, double y, double z, double *var) {
            smokemax::initDataFuncToPhysCoordsForMesh(x, y, z, var);
        };

    std::vector<ot::TreeNode> tmpNodes;

    const unsigned int interpVars = 24;
    unsigned int varIndex[24];
    for (unsigned int i = 0; i < 24; i++) varIndex[i] = i;

    // cap function2Octree depth (mirrors dendrogr_upstream BSSN pattern); the
    // remaining levels are reached by the init_grid_iter loop below.
    const unsigned int bh_max_lev =
        std::min(smokemax::SMOKEMAX_BH1_MAX_LEV,
                 smokemax::SMOKEMAX_BH2_MAX_LEV);
    if (bh_max_lev < MAXDEAPTH_LEVEL_DIFF + 2) {
        if (rank == 0)
            std::cerr << "BH max level (" << bh_max_lev
                      << ") must be at least " << (MAXDEAPTH_LEVEL_DIFF + 2)
                      << std::endl;
        MPI_Abort(comm, 0);
    }
    unsigned int maxDepthIn = bh_max_lev - MAXDEAPTH_LEVEL_DIFF - 2;

    if (smokemax::SMOKEMAX_ENABLE_BLOCK_ADAPTIVITY) {
        // block-adaptive mode (matches BSSN_GR bssngr_main.cpp:291):
        // uniform grid at MAXDEPTH-2 inside [BLK_MIN, BLK_MAX]; the
        // -2 leaves headroom for the mesh constructor's 2:1 balancing
        // outside the box. Set MAXDEPTH = (desired-uniform-level)+2
        // to choose the in-box resolution.
        // X_TO_GRIDX/Y/Z relies on OCTREE_MAX being set to (1<<MAXDEPTH)
        // at TOML-load time (see parameters.cpp.j2).
        const unsigned int regLev =
            smokemax::SMOKEMAX_MAXDEPTH - 2;

        if (rank == 0)
            std::cout << YLW
                      << "Using block adaptive mesh at level " << regLev
                      << " inside [BLK_MIN, BLK_MAX]. AMR disabled."
                      << NRM << std::endl;

        const double blk_box_min[3] = {smokemax::SMOKEMAX_BLK_MIN_X,
                                       smokemax::SMOKEMAX_BLK_MIN_Y,
                                       smokemax::SMOKEMAX_BLK_MIN_Z};
        const double blk_box_max[3] = {smokemax::SMOKEMAX_BLK_MAX_X,
                                       smokemax::SMOKEMAX_BLK_MAX_Y,
                                       smokemax::SMOKEMAX_BLK_MAX_Z};

        ts::seed_block_adaptive_octree(
            tmpNodes, blk_box_min, blk_box_max,
            smokemax::SMOKEMAX_COMPD_MIN,
            smokemax::SMOKEMAX_COMPD_MAX,
            smokemax::SMOKEMAX_OCTREE_MIN,
            smokemax::SMOKEMAX_OCTREE_MAX,
            regLev);
    } else {
        if (rank == 0)
            std::cout << YLW << "Using function2Octree. AMR enabled." << NRM
                      << std::endl;

        function2Octree(f_init, 24, varIndex, interpVars,
                        tmpNodes, maxDepthIn,
                        smokemax::SMOKEMAX_WAVELET_TOL,
                        eOrder, comm);
    }

    // if the wavelet test won't trigger (e.g. flat IC), enable block_adaptivity
    // in TOML so the mesh seeds uniformly at MAXDEPTH-2 inside [BLK_MIN, BLK_MAX]

    if (rank == 0) std::cout << "Now generating mesh" << std::endl;

    ot::Mesh *mesh = ot::createMesh(
        tmpNodes.data(), tmpNodes.size(), eOrder, comm, 1,
        ot::SM_TYPE::FDM, smokemax::SMOKEMAX_DENDRO_GRAIN_SZ,
        smokemax::SMOKEMAX_LOAD_IMB_TOL,
        smokemax::SMOKEMAX_SPLIT_FIX);

    mesh->setDomainBounds(
        Point(smokemax::SMOKEMAX_GRID_MIN_X,
              smokemax::SMOKEMAX_GRID_MIN_Y,
              smokemax::SMOKEMAX_GRID_MIN_Z),
        Point(smokemax::SMOKEMAX_GRID_MAX_X,
              smokemax::SMOKEMAX_GRID_MAX_Y,
              smokemax::SMOKEMAX_GRID_MAX_Z));

    tmpNodes.clear();

    if (rank == 0) std::cout << "Mesh created successfully." << std::endl;

    // allocate derivative workspace (sized for the largest block)
    smokemax::SMOKEMAX_DERIV_WORKSPACE = ts::realloc_deriv_workspace(
        smokemax::SMOKEMAX_DERIV_WORKSPACE, mesh,
        smokemax::SMOKEMAX_NUM_DERIVATIVES);

    // ctx first; ETS comes after init_grid_iter so its state is sized to
    // the refined mesh.
    smokemax::SMOKEMAXCtx *ctx =
        new smokemax::SMOKEMAXCtx(mesh);

    // apply real IC once, then refine; intergrid transfer interpolates so
    // the expensive IC is only evaluated at the initial coarse mesh.
    ctx->initialize();
    // On restore, the mesh + state come straight from the checkpoint; skip the
    // initial-refinement loop so we don't remesh/alter the restored grid.
    if (!smokemax::SMOKEMAX_RESTORE_SOLVER) {
        ctx->refine_initial_grid(
            comm,
            smokemax::SMOKEMAX_INIT_GRID_ITER,
            smokemax::SMOKEMAX_DENDRO_GRAIN_SZ,
            smokemax::SMOKEMAX_LOAD_IMB_TOL,
            smokemax::SMOKEMAX_SPLIT_FIX);
        // Redundant today (ets->init() re-enters initialize()), but that is an
        // implicit dependency on dendrolib's ETS. Does not touch hanging nodes.
        ctx->init_grid();
    }

    // keep the local mesh pointer current: init_grid_iter (or a checkpoint
    // restore) may have replaced the mesh inside the ctx, leaving the original
    // `mesh` dangling. Track ctx->get_mesh() so the final `delete mesh` is safe.
    mesh = ctx->get_mesh();

    // resize the workspace for the (possibly refined) mesh
    smokemax::SMOKEMAX_DERIV_WORKSPACE = ts::realloc_deriv_workspace(
        smokemax::SMOKEMAX_DERIV_WORKSPACE, ctx->get_mesh(),
        smokemax::SMOKEMAX_NUM_DERIVATIVES);

    ts::ETS<DendroScalar, smokemax::SMOKEMAXCtx> *ets =
        new ts::ETS<DendroScalar, smokemax::SMOKEMAXCtx>(ctx);

    ets->set_evolve_vars(ctx->get_evolution_vars());

    // configure RK method
    switch (smokemax::SMOKEMAX_RK_TYPE) {
        case 0: ets->set_ets_coefficients(ts::ETSType::RK3); break;
        case 1: ets->set_ets_coefficients(ts::ETSType::RK4); break;
        case 2: ets->set_ets_coefficients(ts::ETSType::RK45_CASH_KARP); break;
        default:
            if (rank == 0) std::cerr << "Unknown RK type, defaulting to RK4" << std::endl;
            ets->set_ets_coefficients(ts::ETSType::RK4);
    }

    ets->init();

    // initial dt from CFL on the finest level (else a no-remesh grid keeps the
    // par's fixed rk45_time_step_size). Same formula as the remesh block.
    {
        smokemax::SMOKEMAX_RK45_TIME_STEP_SIZE = ts::compute_cfl_dt(
            ctx->get_mesh(),
            smokemax::SMOKEMAX_CFL_FACTOR,
            smokemax::SMOKEMAX_COMPD_MAX[0] -
                smokemax::SMOKEMAX_COMPD_MIN[0],
            smokemax::SMOKEMAX_ELE_ORDER);
        ctx->set_timestep(smokemax::SMOKEMAX_RK45_TIME_STEP_SIZE);
    }

    if (rank == 0)
        std::cout << "Time stepper initialized. dt="
                  << smokemax::SMOKEMAX_RK45_TIME_STEP_SIZE
                  << std::endl;

    // main evolution loop
    const double time_end = smokemax::SMOKEMAX_RK_TIME_END;
    const unsigned int io_freq = smokemax::SMOKEMAX_IO_OUTPUT_FREQ;
    const unsigned int ts_output_freq = smokemax::SMOKEMAX_TIME_STEP_OUTPUT_FREQ;
    const unsigned int checkpt_freq = smokemax::SMOKEMAX_CHECKPT_FREQ;
    unsigned int remesh_freq = smokemax::SMOKEMAX_REMESH_TEST_FREQ;

    ctx->compute_constraint_variables();
    ctx->write_grid_summary_data();

    while (ets->curr_time() < time_end) {
        const unsigned int step = ets->curr_step();
        const double time = ets->curr_time();

        // periodic remeshing
        if (remesh_freq > 0 && (step % remesh_freq) == 0 && step != 0) {
            if (ctx->is_remesh()) {
                if (rank == 0)
                    std::cout << "[Remesh] step=" << step << std::endl;

                // this does: remesh -> grid_transfer -> swap meshes
                ctx->remesh_and_gridtransfer(
                    smokemax::SMOKEMAX_DENDRO_GRAIN_SZ,
                    smokemax::SMOKEMAX_LOAD_IMB_TOL,
                    smokemax::SMOKEMAX_SPLIT_FIX);

                // reallocate derivative workspace for new mesh block sizes
                smokemax::SMOKEMAX_DERIV_WORKSPACE = ts::realloc_deriv_workspace(
                    smokemax::SMOKEMAX_DERIV_WORKSPACE, ctx->get_mesh(),
                    smokemax::SMOKEMAX_NUM_DERIVATIVES);

                // sync the time stepper with the new mesh
                ets->sync_with_mesh();

                // recompute dt based on new finest level
                smokemax::SMOKEMAX_RK45_TIME_STEP_SIZE = ts::compute_cfl_dt(
                    ctx->get_mesh(),
                    smokemax::SMOKEMAX_CFL_FACTOR,
                    smokemax::SMOKEMAX_COMPD_MAX[0] -
                        smokemax::SMOKEMAX_COMPD_MIN[0],
                    smokemax::SMOKEMAX_ELE_ORDER);
                ctx->set_timestep(smokemax::SMOKEMAX_RK45_TIME_STEP_SIZE);

                ctx->calculate_full_grid_size();

                // update local mesh pointer (old one was deleted during remesh)
                mesh = ctx->get_mesh();

                if (rank == 0)
                    std::cout << "[Remesh] new elements="
                              << mesh->getNumLocalMeshElements()
                              << " dt=" << smokemax::SMOKEMAX_RK45_TIME_STEP_SIZE
                              << std::endl;
            }
        }

        ctx->evolve_bh_loc();

        if (ctx->is_bh_merged(0.1) && !ctx->is_bh_merged(0.0)) {
            ctx->set_is_merged(time, step);
            if (rank == 0)
                std::cout << "[MERGER DETECTED] t=" << time << std::endl;
        }

        if ((step % ts_output_freq) == 0) {
            ctx->write_bh_coords();
        }

        if ((step % ts_output_freq) == 0) {
            ctx->terminal_output();
        }

        if (io_freq > 0 && (step % io_freq) == 0) {
            ctx->compute_constraint_variables();
            ctx->write_vtu();
        }

        // gravitational wave extraction
        if (smokemax::SMOKEMAX_GW_EXTRACT_FREQ > 0 &&
            (step % smokemax::SMOKEMAX_GW_EXTRACT_FREQ) == 0) {
            ctx->extract_gravitational_waves();
        }

#ifdef SOLVER_ENABLE_AH
        // apparent horizon finder
        if (AH::AH_SOLVER_FREQ > 0 && (step % AH::AH_SOLVER_FREQ) == 0) {
            ctx->findAH();
        }
#endif

        ets->evolve();

        if (checkpt_freq > 0 && (step % checkpt_freq) == 0 && step != 0) {
            ctx->write_checkpt();
        }

        ctx->prepare_for_next_iter();
    }

    // final output
    ctx->compute_constraint_variables();
    ctx->write_vtu();

    if (rank == 0) {
        std::cout << GRN << "========================================" << NRM << std::endl;
        std::cout << GRN << "  SMOKEMAX Solver complete." << NRM << std::endl;
        std::cout << "  Final step: " << ets->curr_step() << std::endl;
        std::cout << "  Final time: " << ets->curr_time() << std::endl;
        std::cout << GRN << "========================================" << NRM << std::endl;
    }

    // profiling option: MPI-reduced timer table (rhs body / derivs / KO / BCs / zip / unzip)
    smokemax::timer::print_profile(comm);

    delete ets;
    delete ctx;
    delete mesh;

    if (smokemax::SMOKEMAX_DERIV_WORKSPACE != nullptr)
        delete[] smokemax::SMOKEMAX_DERIV_WORKSPACE;

    MPI_Finalize();
    return 0;
}
