"""cascade_cuda_ffi.py -- emit a standalone fused CUDA cascade BSSN-RHS kernel
and an XLA-FFI handler so JAX (dendrojax) can call it.

The per-thread body is vikr's scalar cascade (`emit_bssn_ir(simd='scalar', ...)`)
-- plain `double` arithmetic, one CUDA thread per interior grid point. All
per-point leaves (state + precomputed derivs + eta) are packed into one
`(n_leaf, N)` device buffer; the 8 gauge scalars are FFI attributes; outputs
are one `(24, N)` buffer. This keeps the FFI binding small while the kernel body
is the full fused RHS (the cascade's low register pressure is the bet vs XLA's
flat path).

Generated against jaxlib XLA FFI (`xla/ffi/api/ffi.h`). Build with nvcc -> .so;
register via `jax.ffi.register_ffi_target` and call via `jax.ffi.ffi_call`.
"""
from __future__ import annotations
import os, subprocess, sys

# the 24 RHS outputs, in dendrojax stack order
RHS_OUT = ["a_rhs", "chi_rhs", "K_rhs",
           "gt_rhs00", "gt_rhs01", "gt_rhs02", "gt_rhs11", "gt_rhs12", "gt_rhs22",
           "b_rhs0", "b_rhs1", "b_rhs2",
           "At_rhs00", "At_rhs01", "At_rhs02", "At_rhs11", "At_rhs12", "At_rhs22",
           "Gt_rhs0", "Gt_rhs1", "Gt_rhs2", "B_rhs0", "B_rhs1", "B_rhs2"]
SCALARS = ["lambda_0", "lambda_1", "lambda_2", "lambda_3",
           "lambda_f_0", "lambda_f_1", "ssl_fac", "cahd_coef"]


def leaf_order():
    """The packed-buffer row order for per-point leaves (state+derivs+eta)."""
    from dendrosym.cascade.systems.bssn.cascade import build_specs
    _, leaves = build_specs(gauge="standard", ssl=True, cahd=True, eta_mode="array")
    return sorted(s.name[:-4] for s in leaves if s.name.endswith("[pp]"))


def _scalar_body(inline_threshold: int = 2):
    """vikr scalar cascade body (reads <leaf>[pp], writes <rhs>[pp]).

    inline_threshold controls how aggressively CSE temps are inlined: higher =
    fewer named temps (less register pressure, more recompute). The scalar emit
    path inlines internally; pass through emit_bssn_ir's knob."""
    from dendrosym.cascade.systems.bssn.emit import emit_bssn_ir
    return emit_bssn_ir(simd="scalar", ssl=True, cahd=True, eta_mode="array",
                        inline_threshold=inline_threshold)


def emit_cu(threads: int = 128, min_blocks: int = 2,
            inline_threshold: int = 2) -> str:
    # min_blocks=2 default: __launch_bounds__(threads,2) occupancy hint -- ~3-5%
    # over no bound on a free GPU (register count unchanged at 255; the wall is
    # structural). Forcing fewer registers (-maxrregcount) spills harder = slower.
    leaves = leaf_order()
    body = _scalar_body(inline_threshold)
    n_leaf, n_out = len(leaves), len(RHS_OUT)
    # __launch_bounds__(threads, min_blocks): cap registers so >=min_blocks CTAs
    # fit per SM (trades spilling for occupancy). 0 = no bound (let ptxas pick).
    lb = f" __launch_bounds__({threads}, {min_blocks})" if min_blocks else ""

    L = []
    L.append("// Auto-generated by cascade_cuda_ffi.py -- fused BSSN cascade RHS")
    L.append("// (scalar cascade body, 1 thread/point) + XLA-FFI handler for JAX.")
    L.append("#include <cmath>")
    L.append("#include <cuda_runtime.h>")
    L.append('#include "xla/ffi/api/ffi.h"')
    L.append("namespace ffi = xla::ffi;")
    L.append("")
    # --- kernel ---
    args = ["const double* __restrict__ in", "double* __restrict__ out"]
    args += [f"double {s}" for s in SCALARS] + ["int N"]
    L.append(f"__global__ void{lb} cascade_rhs_kernel({', '.join(args)}) {{")
    L.append("    int pp = blockIdx.x * blockDim.x + threadIdx.x;")
    L.append("    if (pp >= N) return;")
    for k, name in enumerate(leaves):
        L.append(f"    const double* {name} = in + {k}*N;")
    L.append("    const double lambda[4] = {lambda_0, lambda_1, lambda_2, lambda_3};")
    L.append("    const double lambda_f[2] = {lambda_f_0, lambda_f_1};")
    for j, name in enumerate(RHS_OUT):
        L.append(f"    double* {name} = out + {j}*N;")
    L.append("    {")
    L.append(body)
    L.append("    }")
    L.append("}")
    L.append("")
    # --- host launcher + FFI handler ---
    L.append(f"#define KTHREADS {threads}")
    L.append("static void launch(const double* in, double* out,")
    L.append("        const double* S, int N, cudaStream_t stream) {")
    L.append("    int blocks = (N + KTHREADS - 1) / KTHREADS;")
    L.append("    cascade_rhs_kernel<<<blocks, KTHREADS, 0, stream>>>(in, out,")
    L.append("        S[0],S[1],S[2],S[3],S[4],S[5],S[6],S[7], N);")
    L.append("}")
    L.append("")
    L.append("ffi::Error CascadeImpl(cudaStream_t stream,")
    L.append("        ffi::Buffer<ffi::F64> in,")
    for s in SCALARS:
        L.append(f'        double {s},')
    L.append("        ffi::ResultBuffer<ffi::F64> out) {")
    L.append("    auto dims = in.dimensions();")
    L.append("    int N = (int) dims.back();")
    L.append(f"    double S[8] = {{{', '.join(SCALARS)}}};")
    L.append("    launch(in.typed_data(), out->typed_data(), S, N, stream);")
    L.append("    return ffi::Error::Success();")
    L.append("}")
    L.append("")
    bind = ["ffi::Ffi::Bind()", "    .Ctx<ffi::PlatformStream<cudaStream_t>>()",
            "    .Arg<ffi::Buffer<ffi::F64>>()"]
    bind += [f'    .Attr<double>("{s}")' for s in SCALARS]
    bind += ["    .Ret<ffi::Buffer<ffi::F64>>()"]
    L.append("XLA_FFI_DEFINE_HANDLER_SYMBOL(CascadeRhs, CascadeImpl,")
    L.append("    " + "\n    ".join(bind) + ");")
    L.append("")
    L.append(f"// n_leaf={n_leaf}  n_out={n_out}")
    return "\n".join(L) + "\n"


# BSSN var order in the (24,S,S,S) block (matches dendrojax)
VARNAME = ["alpha", "chi", "K", "gt0", "gt1", "gt2", "gt3", "gt4", "gt5",
           "beta0", "beta1", "beta2", "At0", "At1", "At2", "At3", "At4", "At5",
           "Gt0", "Gt1", "Gt2", "B0", "B1", "B2"]
_C1 = ["(-1.0/60.0)", "(9.0/60.0)", "(-45.0/60.0)", "0.0",
       "(45.0/60.0)", "(-9.0/60.0)", "(1.0/60.0)"]   # 6th-order 1st-deriv, 7pt
_S, _E, _PW = 13, 7, 3                                # eleorder=6 block geometry


def _split_leaves():
    """Partition packed leaves into 1st-derivs (-> inline stencils) and the rest
    (state + 2nd-derivs + eta, stay in the packed buffer)."""
    import re
    grad1, packed = [], []
    g1 = re.compile(r"^grad_([0-2])_(\w+)$")
    for n in leaf_order():
        m = g1.match(n)
        (grad1 if m else packed).append(n)
    return grad1, packed


def emit_cu_fused1(threads: int = 128, min_blocks: int = 2) -> str:
    """Kernel that fuses the 1st-derivative stencils (read from the padded block)
    into the cascade; 2nd-derivs + state + eta come from the packed buffer."""
    import re
    grad1, packed = _split_leaves()
    body = _scalar_body()
    # rename grad_d_var[pp] -> local inline gd_var
    body = re.sub(r"grad_([0-2])_(\w+)\[pp\]", r"g\1_\2", body)
    lb = f" __launch_bounds__({threads}, {min_blocks})" if min_blocks else ""

    L = ["// Auto-generated: fused-1st-deriv BSSN cascade RHS + XLA-FFI handler.",
         "#include <cmath>", "#include <cuda_runtime.h>",
         '#include "xla/ffi/api/ffi.h"', "namespace ffi = xla::ffi;", "",
         f"#define SS {_S}", f"#define EE {_E}", f"#define PW {_PW}",
         f"#define E3 ({_E*_E*_E})", ""]
    args = ["const double* __restrict__ blk", "const double* __restrict__ pk",
            "double* __restrict__ out"] + [f"double {s}" for s in SCALARS] + \
           ["double inv_hx", "double inv_hy", "double inv_hz", "int N"]
    L.append(f"__global__ void{lb} cascade_fused1_kernel({', '.join(args)}) {{")
    L.append("    int pp = blockIdx.x * blockDim.x + threadIdx.x;")
    L.append("    if (pp >= N) return;")
    L.append("    int e = pp / E3; int p = pp - e*E3;")
    L.append("    int lz = p/(EE*EE), ly = (p/EE)%EE, lx = p%EE;")
    L.append("    int iz = lz+PW, iy = ly+PW, ix = lx+PW;")
    L.append("    #define BIDX(v,dz,dy,dx) blk[(((e*24+(v))*SS+(iz+(dz)))*SS+(iy+(dy)))*SS+(ix+(dx))]")
    # packed aliases (state + grad2 + eta)
    for k, name in enumerate(packed):
        L.append(f"    const double* {name} = pk + {k}*N;")
    L.append("    const double lambda[4] = {lambda_0, lambda_1, lambda_2, lambda_3};")
    L.append("    const double lambda_f[2] = {lambda_f_0, lambda_f_1};")
    # inline 1st-deriv stencils
    vidx = {v: i for i, v in enumerate(VARNAME)}
    for name in grad1:
        d, var = re.match(r"grad_([0-2])_(\w+)", name).group(1, 2)
        v = vidx[var]; d = int(d)
        terms = []
        for a in range(7):
            off = a - 3
            dz, dy, dx = (off, 0, 0) if d == 2 else (0, off, 0) if d == 1 else (0, 0, off)
            if _C1[a] != "0.0":
                terms.append(f"{_C1[a]}*BIDX({v},{dz},{dy},{dx})")
        invh = ["inv_hx", "inv_hy", "inv_hz"][d]
        L.append(f"    double g{d}_{var} = ({' + '.join(terms)})*{invh};")
    for j, name in enumerate(RHS_OUT):
        L.append(f"    double* {name} = out + {j}*N;")
    L.append("    {")
    L.append(body)
    L.append("    }")
    L.append("    #undef BIDX")
    L.append("}")
    L.append("")
    # host launcher + FFI handler (two input buffers + scalars)
    sl = ["blk", "pk", "out"] + SCALARS + ["inv_hx", "inv_hy", "inv_hz", "N"]
    L.append("ffi::Error CascadeF1Impl(cudaStream_t stream, ffi::Buffer<ffi::F64> blk,")
    L.append("        ffi::Buffer<ffi::F64> pk,")
    for s in SCALARS + ["inv_hx", "inv_hy", "inv_hz"]:
        L.append(f"        double {s},")
    L.append("        ffi::ResultBuffer<ffi::F64> out) {")
    L.append("    int N = (int) pk.dimensions().back();")
    L.append(f"    int T = {threads}; int B = (N+T-1)/T;")
    L.append("    cascade_fused1_kernel<<<B,T,0,stream>>>(blk.typed_data(), pk.typed_data(),")
    L.append("        out->typed_data(), " + ", ".join(SCALARS) + ", inv_hx, inv_hy, inv_hz, N);")
    L.append("    return ffi::Error::Success();")
    L.append("}")
    bind = ["ffi::Ffi::Bind().Ctx<ffi::PlatformStream<cudaStream_t>>()",
            "    .Arg<ffi::Buffer<ffi::F64>>().Arg<ffi::Buffer<ffi::F64>>()"]
    bind += [f'    .Attr<double>("{s}")' for s in SCALARS + ["inv_hx", "inv_hy", "inv_hz"]]
    bind += ["    .Ret<ffi::Buffer<ffi::F64>>()"]
    L.append("XLA_FFI_DEFINE_HANDLER_SYMBOL(CascadeF1, CascadeF1Impl,")
    L.append("    " + "\n    ".join(bind) + ");")
    L.append(f"// grad1_inlined={len(grad1)} packed={len(packed)}")
    return "\n".join(L) + "\n"


_C2 = ["(1.0/90.0)", "(-3.0/20.0)", "(3.0/2.0)", "(-49.0/18.0)",
       "(3.0/2.0)", "(-3.0/20.0)", "(1.0/90.0)"]    # 6th-order 2nd-deriv, 7pt

# FD stencil weights by accuracy order (matches dendrojax GRAD_WEIGHTS). The
# kernel geometry/stencils follow eleorder: grad_order=2*(eleorder//2), the
# stencil is (grad_order+1)-point, S=2*eo+1, E=eo+1, pw=eo//2.
_W1 = {
    6: _C1,
    8: ["(1.0/280.0)", "(-4.0/105.0)", "(1.0/5.0)", "(-4.0/5.0)", "0.0",
        "(4.0/5.0)", "(-1.0/5.0)", "(4.0/105.0)", "(-1.0/280.0)"],
}
_W2 = {
    6: _C2,
    8: ["(-1.0/560.0)", "(8.0/315.0)", "(-1.0/5.0)", "(8.0/5.0)", "(-205.0/72.0)",
        "(8.0/5.0)", "(-1.0/5.0)", "(8.0/315.0)", "(-1.0/560.0)"],
}


def _off(ax, o):
    return [(0, 0, o), (0, o, 0), (o, 0, 0)][ax]      # axis 0=x,1=y,2=z -> (dz,dy,dx)


_WKO = ["-1.0", "6.0", "-15.0", "20.0", "-15.0", "6.0", "-1.0"]   # KO grad_order=4


def _resched_min_live(body: str) -> str:
    """GPU-only min-live reschedule of the cascade body (does NOT touch the CPU
    emitter). The body is pure SSA -- 571 write-once `const double T = expr;`
    temps + 24 write-once `out[pp] = expr;` sinks, no accumulation -- so any
    dependency-respecting reorder is BIT-IDENTICAL (each stmt recomputes the same
    expression from the same inputs). We demand-schedule: walk the sinks in order
    and emit each temp's cone depth-first just before its first consumer, so a
    value is materialized as late as possible -> shorter live ranges, lower peak
    pressure (the Ricci R00..R22 block stops being live across the whole tail).
    External names (deriv locals g*_*, leaf ptrs, lambda[]) are computed before
    the body block, so they're always-available and never reordered.

    MEASURED (eo=6, sm_86): NEUTRAL-TO-NEGATIVE. Bit-identical (4.98e-15) but the
    255-reg wall did NOT move (255->255), spill stayed flat (2612->2600 B st),
    runtime 48.6->49.4 ns/pt (0.98x). ptxas re-derives its own schedule, so source
    reordering can't reduce the DAG's intrinsic peak register demand. 255 is the
    HARDWARE per-thread ceiling on NVIDIA (cc>=3.5): the cascade's peak live set
    exceeds it at the Ricci/RHS contraction points (trace = igt^ij R_ij needs all
    6 R_ij live), so spill is intrinsic regardless of order. Kept as a default-off
    knob for the record; the real lever is fewer simultaneous intermediates
    (algorithmic) or a wider register file (A100/H100 same 255 cap, but fp64
    unthrottled hides the spill latency)."""
    import re
    raw = [l for l in body.split("\n")]
    comments = [l for l in raw if l.strip().startswith("//")]
    stmts = [l for l in raw if l.strip() and not l.strip().startswith("//")]
    tok = re.compile(r"[A-Za-z_]\w*")
    def_of, deps, sinks, order_temps = {}, {}, [], []
    for s in stmts:
        m = re.match(r"\s*const double (\w+) =\s*(.*);\s*$", s)
        if m:
            name, rhs = m.group(1), m.group(2)
            def_of[name] = s
            deps[name] = set(tok.findall(rhs))
            order_temps.append(name)
        else:
            sinks.append((s, set(tok.findall(s))))      # out[pp] = ... ;
    temp_set = set(def_of)
    emitted, out = set(), []
    import sys as _sys
    _sys.setrecursionlimit(10000)
    def emit(name):
        if name in emitted:
            return
        emitted.add(name)
        for d in deps[name]:
            if d in temp_set:
                emit(d)
        out.append(def_of[name])
    for s, uses in sinks:
        for u in uses:
            if u in temp_set:
                emit(u)
        out.append(s)
    # any temp not reached by a sink (dead/none expected) -> append in orig order
    for name in order_temps:
        if name not in emitted:
            out.append(def_of[name])
    return "\n".join(comments + out)


def emit_cu_fused2(threads: int = 128, min_blocks: int = 2, ko: bool = False,
                   smem: bool = False, eleorder: int = 6, resched: bool = False) -> str:
    """Fully-fused kernel: ALL derivs (1st 7pt + diagonal-2nd 7pt + mixed-2nd
    36-term tensor product) computed inline from the padded block. Only state +
    eta are packed; no derivative arrays cross the FFI boundary.

    ko=True also adds Kreiss-Oliger dissipation inline (7pt [-1,6,-15,20,-15,6,-1]
    per axis, scale -1/(64 h), ·ko_sigma) so the kernel computes the COMPLETE RHS
    dendrojax does (derivs + algebra + KO) -- a fully-fair drop-in replacement."""
    import re
    go = 2 * (eleorder // 2)                  # FD accuracy order
    S, E, PWv = 2 * eleorder + 1, eleorder + 1, eleorder // 2
    width, half = go + 1, go // 2             # stencil width / center offset
    w1, w2 = _W1[go], _W2[go]
    grad1 = [n for n in leaf_order() if re.match(r"grad_[0-2]_", n)]
    grad2 = [n for n in leaf_order() if re.match(r"grad2_", n)]
    packed = [n for n in leaf_order() if not n.startswith("grad")]   # state + eta
    body = _scalar_body()
    # smem: derivative values live in shared-memory scratch sd[idx][tid] (not
    # registers) to relieve the 255-reg pressure. Each thread reads only its own
    # column -> no cross-thread sharing, no __syncthreads.
    didx = {n: i for i, n in enumerate(grad1 + grad2)}
    if smem:
        body = re.sub(r"grad2_([0-2])_([0-2])_(\w+)\[pp\]",
                      lambda m: f"sd[{didx['grad2_%s_%s_%s' % m.group(1,2,3)]}][threadIdx.x]", body)
        body = re.sub(r"grad_([0-2])_(\w+)\[pp\]",
                      lambda m: f"sd[{didx['grad_%s_%s' % m.group(1,2)]}][threadIdx.x]", body)
    else:
        body = re.sub(r"grad2_([0-2])_([0-2])_(\w+)\[pp\]", r"g2_\1\2_\3", body)
        body = re.sub(r"grad_([0-2])_(\w+)\[pp\]", r"g\1_\2", body)
    if resched:                              # GPU-only min-live reorder (bit-identical)
        body = _resched_min_live(body)
    lb = f" __launch_bounds__({threads}, {min_blocks})" if min_blocks else ""
    vidx = {v: i for i, v in enumerate(VARNAME)}
    invh = ["inv_hx", "inv_hy", "inv_hz"]
    scalars = SCALARS + (["ko_sigma"] if ko else [])
    ND = len(grad1) + len(grad2)
    def _dvar(name):                       # LHS for a deriv: shared slot or local
        return f"sd[{didx[name]}][threadIdx.x]" if smem else None

    L = ["// Auto-generated: FULLY-fused BSSN cascade RHS (all derivs inline) + FFI.",
         "#include <cmath>", "#include <cuda_runtime.h>",
         '#include "xla/ffi/api/ffi.h"', "namespace ffi = xla::ffi;", "",
         f"#define SS {S}", f"#define EE {E}", f"#define PW {PWv}",
         f"#define E3 ({E*E*E})", ""]
    args = ["const double* __restrict__ blk", "const double* __restrict__ pk",
            "double* __restrict__ out"] + [f"double {s}" for s in scalars] + \
           ["double inv_hx", "double inv_hy", "double inv_hz", "int N"]
    L.append(f"__global__ void{lb} cascade_fused2_kernel({', '.join(args)}) {{")
    L += ["    int pp = blockIdx.x*blockDim.x + threadIdx.x;",
          "    if (pp >= N) return;",
          "    int e = pp/E3; int p = pp - e*E3;",
          "    int lz = p/(EE*EE), ly = (p/EE)%EE, lx = p%EE;",
          "    int iz = lz+PW, iy = ly+PW, ix = lx+PW;",
          "    #define BIDX(v,dz,dy,dx) blk[(((e*24+(v))*SS+(iz+(dz)))*SS+(iy+(dy)))*SS+(ix+(dx))]"]
    for k, name in enumerate(packed):
        L.append(f"    const double* {name} = pk + {k}*N;")
    L.append("    const double lambda[4] = {lambda_0,lambda_1,lambda_2,lambda_3};")
    L.append("    const double lambda_f[2] = {lambda_f_0,lambda_f_1};")
    if smem:
        L.append(f"    __shared__ double sd[{ND}][{threads}];   // deriv scratch")
    dlhs = lambda nm, loc: (f"sd[{didx[nm]}][threadIdx.x]" if smem else f"double {loc}")
    # 1st derivs (width-point, order go)
    for name in grad1:
        d, var = re.match(r"grad_([0-2])_(\w+)", name).group(1, 2)
        d = int(d); v = vidx[var]
        t = [f"{w1[a]}*BIDX({v},{','.join(map(str, _off(d, a-half)))})"
             for a in range(width) if w1[a] != "0.0"]
        L.append(f"    {dlhs(name, f'g{d}_{var}')} = ({' + '.join(t)})*{invh[d]};")
    # 2nd derivs (diagonal width-point, mixed (nonzero w1)^2 tensor product)
    for name in grad2:
        a1, a2, var = re.match(r"grad2_([0-2])_([0-2])_(\w+)", name).group(1, 2, 3)
        a1, a2 = int(a1), int(a2); v = vidx[var]
        if a1 == a2:
            t = [f"{w2[a]}*BIDX({v},{','.join(map(str, _off(a1, a-half)))})" for a in range(width)]
            L.append(f"    {dlhs(name, f'g2_{a1}{a2}_{var}')} = ({' + '.join(t)})*{invh[a1]}*{invh[a1]};")
        else:
            t = []
            for i in range(width):
                if w1[i] == "0.0":
                    continue
                for j in range(width):
                    if w1[j] == "0.0":
                        continue
                    dz1, dy1, dx1 = _off(a1, i-half); dz2, dy2, dx2 = _off(a2, j-half)
                    t.append(f"{w1[i]}*{w1[j]}*BIDX({v},{dz1+dz2},{dy1+dy2},{dx1+dx2})")
            L.append(f"    {dlhs(name, f'g2_{a1}{a2}_{var}')} = ({' + '.join(t)})*{invh[a1]}*{invh[a2]};")
    for j, name in enumerate(RHS_OUT):
        L.append(f"    double* {name} = out + {j}*N;")
    L += ["    {", body, "    }"]
    if ko:
        L.append("    // Kreiss-Oliger dissipation (matches dendrojax); RHS_OUT[j] <-> var j")
        for j, name in enumerate(RHS_OUT):
            parts = []
            for ax in range(3):
                t = [f"{_WKO[a]}*BIDX({j},{','.join(map(str, _off(ax, a-3)))})" for a in range(7)]
                parts.append(f"(({' + '.join(t)})*(-{invh[ax]}/64.0))")
            L.append(f"    {name}[pp] += ko_sigma*({' + '.join(parts)});")
    L += ["    #undef BIDX", "}", ""]
    # FFI handler
    L.append("ffi::Error CascadeF2Impl(cudaStream_t stream, ffi::Buffer<ffi::F64> blk,")
    L.append("        ffi::Buffer<ffi::F64> pk,")
    for s in scalars + ["inv_hx", "inv_hy", "inv_hz"]:
        L.append(f"        double {s},")
    L.append("        ffi::ResultBuffer<ffi::F64> out) {")
    L.append("    int N = (int) pk.dimensions().back();")
    L.append(f"    int T = {threads}; int B = (N+T-1)/T;")
    L.append("    cascade_fused2_kernel<<<B,T,0,stream>>>(blk.typed_data(), pk.typed_data(),")
    L.append("        out->typed_data(), " + ", ".join(scalars) + ", inv_hx, inv_hy, inv_hz, N);")
    L.append("    return ffi::Error::Success();")
    L.append("}")
    bind = ["ffi::Ffi::Bind().Ctx<ffi::PlatformStream<cudaStream_t>>()",
            "    .Arg<ffi::Buffer<ffi::F64>>().Arg<ffi::Buffer<ffi::F64>>()"]
    bind += [f'    .Attr<double>("{s}")' for s in scalars + ["inv_hx", "inv_hy", "inv_hz"]]
    bind += ["    .Ret<ffi::Buffer<ffi::F64>>()"]
    L.append("XLA_FFI_DEFINE_HANDLER_SYMBOL(CascadeF2, CascadeF2Impl,")
    L.append("    " + "\n    ".join(bind) + ");")
    L.append(f"// grad1={len(grad1)} grad2={len(grad2)} packed={len(packed)} ko={ko}")
    return "\n".join(L) + "\n"


def build(cu_path: str, so_path: str, arch: str = "sm_86", verbose: bool = True,
          maxreg: int = 0):
    inc = _jax_ffi_include()
    cmd = ["nvcc", "-O3", "-std=c++17", "-Xcompiler", "-fPIC", "-shared",
           f"-arch={arch}", "--expt-relaxed-constexpr",
           f"-I{inc}", cu_path, "-o", so_path]
    if maxreg:
        cmd.insert(1, f"-maxrregcount={maxreg}")   # cap registers per thread
    if verbose:
        cmd.insert(1, "--ptxas-options=-v")
    print("nvcc:", " ".join(cmd))
    out = subprocess.run(cmd, check=True, capture_output=True, text=True)
    return out.stderr   # ptxas info (registers/spills) goes to stderr


def _jax_ffi_include():
    import jax
    return jax.ffi.include_dir()


def load_and_register(so_path: str, name: str = "cascade_rhs"):
    """Load the .so, register the FFI handler with JAX, return a callable
    rhs(in_buffer, scalars dict, N) -> (24, N) jnp array."""
    import ctypes, jax, jax.numpy as jnp
    lib = ctypes.cdll.LoadLibrary(so_path)
    cap = jax.ffi.pycapsule(lib.CascadeRhs)
    jax.ffi.register_ffi_target(name, cap, platform="CUDA")

    def rhs(in_buf, scalars, N):
        out_type = jax.ShapeDtypeStruct((len(RHS_OUT), N), jnp.float64)
        return jax.ffi.ffi_call(name, out_type)(
            in_buf, **{s: float(scalars[s]) for s in SCALARS})
    return rhs


if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--out-cu", default="/home/denv/research/vikr/generated/cascade_rhs_ffi.cu")
    p.add_argument("--out-so", default="/home/denv/research/vikr/generated/cascade_rhs_ffi.so")
    p.add_argument("--threads", type=int, default=128)
    p.add_argument("--build", action="store_true")
    a = p.parse_args()
    os.makedirs(os.path.dirname(a.out_cu), exist_ok=True)
    with open(a.out_cu, "w") as f:
        f.write(emit_cu(threads=a.threads))
    print("wrote", a.out_cu)
    if a.build:
        build(a.out_cu, a.out_so)
        print("built", a.out_so)
