/**
 * @file grUtils.cpp
 * @brief Initial data dispatcher and utilities for the smokemin solver.
 *
 * Generated by dendrosym. Designed to be extended -- add new initial
 * data types by:
 *   1. Add a forward declaration at the top
 *   2. Add a case to the switch in initDataFuncToPhysCoords()
 *   3. Implement the function (here or in a separate file)
 *
 * Each initial data function receives physical (not grid) coordinates
 * and fills var[0..N-1] for all evolution variables. The ordering
 * matches the VAR enum in grDef.h:
 *   var[0] = u
 *   var[1] = v
 */

#include "grUtils.h"
#include "grDef.h"
#include "parameters.h"

#include <cmath>
#include <cstdlib>  // rand()/RAND_MAX for raw-C++ random initial data (e.g. noise IC)
#include <iostream>

namespace smokemin {

// forward declarations for initial data types
void minkowskiInit(double x, double y, double z, double *var);

/**
 * @brief Initial data dispatcher. Called for every grid point during init.
 *
 * Receives grid (octree) coordinates. Converts to physical coords
 * via the GRIDX_TO_X macros, then dispatches to the appropriate
 * initial data function based on the id_type runtime parameter.
 */
void initDataFuncToPhysCoords(const double xx1, const double yy1,
                              const double zz1, double *var) {
    // convert grid coords to physical coords
    const double xx = GRIDX_TO_X(xx1);
    const double yy = GRIDY_TO_Y(yy1);
    const double zz = GRIDZ_TO_Z(zz1);

    // zero everything first
    for (unsigned int i = 0; i < 2; i++) {
        var[i] = 0.0;
    }

    switch (SMOKEMIN_ID_TYPE) {
        case 0:
            minkowskiInit(xx, yy, zz, var);
            break;



        default:
            std::cout << "Unknown ID type: " << SMOKEMIN_ID_TYPE << std::endl;
            exit(1);
            break;
    }
}

/**@brief Cheap-estimate IC dispatcher used by function2Octree. Real IC is
 * applied via smokeminCtx::init_grid() after the mesh is built. */
void initDataFuncToPhysCoordsForMesh(const double xx1, const double yy1,
                                     const double zz1, double *var) {
    initDataFuncToPhysCoords(xx1, yy1, zz1, var);
}

// -------------------------------------------------------------------------
// flat spacetime (minkowski) -- useful for testing and as a base
// -------------------------------------------------------------------------

void minkowskiInit(double x, double y, double z, double *var) {
    // everything defaults to zero from the dispatcher.
    // set the non-zero values for flat spacetime:
}


// -------------------------------------------------------------------------
// Position-dependent wavelet tolerance. No TwoPunctures dependency, so this
// stays outside the tpid guard -- solver_ctx calls it unconditionally.
// -------------------------------------------------------------------------
double computeWTolDCoords(double x, double y, double z, double *hx) {
    const double tolMin = SMOKEMIN_WAVELET_TOL;
    const double tolMax = SMOKEMIN_WAVELET_TOL_MAX;
    const double R0     = SMOKEMIN_WAVELET_TOL_FUNCTION_R0;
    const double R1     = SMOKEMIN_WAVELET_TOL_FUNCTION_R1;
    const double r      = std::sqrt(x * x + y * y + z * z);

    // Degenerate config: no usable ramp, so stay flat rather than divide by 0.
    if (!(tolMax > tolMin) || !(R1 > R0)) return tolMin;

    switch (SMOKEMIN_USE_WAVELET_TOL_FUNCTION) {
        case 1:  // linear ramp tolMin@R0 -> tolMax@R1 (BSSN computeWTol)
            return std::min(
                tolMax, std::max(tolMin, (tolMax - tolMin) / (R1 - R0) *
                                                 (r - R0) +
                                             tolMin));

        case 3: {
            // Decade-exponential falloff. BSSN keys the ceiling off its
            // outermost GW extraction radius; there is none here, so tolMax is
            // the ceiling and the profile is purely radial.
            if (r < R0) return tolMin;
            const double fac = (R1 - R0) / std::log10(tolMax / tolMin);
            return std::min(tolMax,
                            tolMin * std::pow(10.0, (r - R0) / fac));
        }

        case 0:
            return tolMin;

        default: {
            // 2/4/5/6 depend on GW radii or BH-tracking state not carried here.
            // Warn rather than silently flatten -- a flat tolerance saturates
            // below any depth ceiling and makes maxdepth look inert.
            static bool warned = false;
            if (!warned) {
                warned = true;
                std::cerr << "[smokemin] WARNING: use_wavelet_tol_function = "
                          << SMOKEMIN_USE_WAVELET_TOL_FUNCTION
                          << " is not implemented; falling back to a flat "
                             "wavelet_tol. Supported: 0, 1, 3." << std::endl;
            }
            return tolMin;
        }
    }
}






}  // namespace smokemin
