/**
 * @file parameters.cpp
 * @brief Parameter definitions and TOML reading for the smokemin solver.
 *
 * Generated by dendrosym. Safe to edit -- add new parameters, change
 * defaults, or customize the TOML reading logic as needed.
 *
 * TOML file format:
 *   Instead of flat keys like "emda::EMDA_LAMBDA", parameters are organized
 *   into TOML tables (sections). The reader searches each section for its
 *   expected keys, with no namespace prefix needed in the TOML file:
 *
 *     [solver]
 *     ele_order = 6
 *     compd_min = [-50.0, -50.0, -50.0]
 *
 *     [physics]
 *     lambda = [1, 1, 1, 1]
 *     eta = [0.4, 0.4]
 *
 *   For backward compatibility, flat keys like "EMDA_LAMBDA" (no quotes
 *   or namespace prefix needed) are also accepted at the top level.
 */

#include "parameters.h"

#include <param_reader.h>  // dendro_params:: generic TOML reader (shared)
#include <mpi.h>
#include <any>
#include <cctype>
#include <cstdlib>
#include <limits>
#include <stdexcept>
#include <type_traits>
#include <unordered_set>
#include <vector>

// =========================================================================
// Color codes for terminal output
// =========================================================================
#ifndef NRM
#define NRM "\x1B[0m"
#define RED "\x1B[31m"
#define GRN "\x1B[32m"
#define YLW "\x1B[33m"
#define BLU "\x1B[34m"
#endif

// =========================================================================
// Global variable definitions
// =========================================================================

namespace smokemin {
mem::memory_pool<double> SMOKEMIN_MEM_POOL = mem::memory_pool<double>(0, 16);

// Runtime state
double SMOKEMIN_CURRENT_RK_COORD_TIME = 0;
unsigned int SMOKEMIN_CURRENT_RK_STEP = 0;
double* SMOKEMIN_DERIV_WORKSPACE = nullptr;

// [solver] defaults
unsigned int SMOKEMIN_ELE_ORDER = 6;
unsigned int SMOKEMIN_PADDING_WIDTH = SMOKEMIN_ELE_ORDER >> 1u;
double SMOKEMIN_COMPD_MIN[3] = {-50.0, -50.0, -50.0};
double SMOKEMIN_COMPD_MAX[3] = {50.0, 50.0, 50.0};
double SMOKEMIN_OCTREE_MIN[3] = {0.0, 0.0, 0.0};
// MAXDEPTH declared before OCTREE_MAX — TU static init runs in declaration
// order, so the OCTREE_MAX initializer reads the correct value
unsigned int SMOKEMIN_MAXDEPTH = 16;
unsigned int SMOKEMIN_MINDEPTH = 3;

// BSSN-style toggle: true = uniform grid at MINDEPTH inside [BLK_MIN, BLK_MAX],
// AMR off; false = function2Octree (wavelet-driven AMR)
bool SMOKEMIN_ENABLE_BLOCK_ADAPTIVITY = false;
double SMOKEMIN_BLK_MIN_X = -50.0;
double SMOKEMIN_BLK_MIN_Y = -50.0;
double SMOKEMIN_BLK_MIN_Z = -50.0;
double SMOKEMIN_BLK_MAX_X = 50.0;
double SMOKEMIN_BLK_MAX_Y = 50.0;
double SMOKEMIN_BLK_MAX_Z = 50.0;
double SMOKEMIN_OCTREE_MAX[3] = {
    (double)(1u << SMOKEMIN_MAXDEPTH),
    (double)(1u << SMOKEMIN_MAXDEPTH),
    (double)(1u << SMOKEMIN_MAXDEPTH)};
unsigned int SMOKEMIN_DIM = 3;

double SMOKEMIN_RK_TIME_BEGIN = 0.0;
double SMOKEMIN_RK_TIME_END = 800.0;
unsigned int SMOKEMIN_RK_TYPE = 1;
double SMOKEMIN_RK45_TIME_STEP_SIZE = 0.01;
double SMOKEMIN_RK45_DESIRED_TOL = 0.001;
double SMOKEMIN_CFL_FACTOR = 0.25;

unsigned int SMOKEMIN_IO_OUTPUT_FREQ = 1000;
unsigned int SMOKEMIN_TIME_STEP_OUTPUT_FREQ = 10;
unsigned int SMOKEMIN_CHECKPT_FREQ = 5000;
bool SMOKEMIN_RESTORE_SOLVER = false;
std::string SMOKEMIN_VTU_FILE_PREFIX = "vtu/smokemin_gr";
std::string SMOKEMIN_CHKPT_FILE_PREFIX = "cp/smokemin_cp";
std::string SMOKEMIN_PROFILE_FILE_PREFIX = "smokemin_prof";

unsigned int SMOKEMIN_NUM_EVOL_VARS_VTU_OUTPUT = 2;
unsigned int SMOKEMIN_NUM_CONST_VARS_VTU_OUTPUT = 0;
unsigned int SMOKEMIN_VTU_OUTPUT_EVOL_INDICES[2] = {
    0,
    1
};
unsigned int SMOKEMIN_VTU_OUTPUT_CONST_INDICES[1] = {0};

// which variables terminal_output computes norms for. Just list the indices in
// the par ([] = none); the count is the list length. Defaults to all (current
// behaviour). Each selected var costs a ghost exchange, so narrow these to cut
// synchronization; constraints are only computed if the constraint list is set.
std::vector<unsigned int> SMOKEMIN_TERMINAL_OUTPUT_EVOL_INDICES = {
    0,
    1
};
std::vector<unsigned int> SMOKEMIN_TERMINAL_OUTPUT_CONST_INDICES = {
};

bool SMOKEMIN_VTU_X_SLICE = true;
bool SMOKEMIN_VTU_Y_SLICE = false;
bool SMOKEMIN_VTU_Z_SLICE = false;

unsigned int SMOKEMIN_DENDRO_GRAIN_SZ = 50;
double SMOKEMIN_DENDRO_AMR_FAC = 0.1;
double SMOKEMIN_LOAD_IMB_TOL = 0.1;
unsigned int SMOKEMIN_ASYNC_COMM_K = 4;
unsigned int SMOKEMIN_INIT_GRID_ITER = 10;
unsigned int SMOKEMIN_REMESH_TEST_FREQ = 10;
unsigned int SMOKEMIN_NUM_REFINE_VARS = 2;
unsigned int SMOKEMIN_REFINE_VARIABLE_INDICES[2] = {
    0,
    1
};
double SMOKEMIN_WAVELET_TOL = 1e-05;
unsigned int SMOKEMIN_USE_WAVELET_TOL_FUNCTION = 3;
double SMOKEMIN_WAVELET_TOL_MAX = 0.001;
double SMOKEMIN_WAVELET_TOL_FUNCTION_R0 = 30.0;
double SMOKEMIN_WAVELET_TOL_FUNCTION_R1 = 220.0;
RefinementMode SMOKEMIN_REFINEMENT_MODE = static_cast<RefinementMode>(0);

double SMOKEMIN_GRID_MIN_X = -400.0;
double SMOKEMIN_GRID_MIN_Y = -400.0;
double SMOKEMIN_GRID_MIN_Z = -400.0;
double SMOKEMIN_GRID_MAX_X = 400.0;
double SMOKEMIN_GRID_MAX_Y = 400.0;
double SMOKEMIN_GRID_MAX_Z = 400.0;
unsigned int SMOKEMIN_SPLIT_FIX = 2;
// ENABLE_BLOCK_ADAPTIVITY defined above as bool

unsigned int SMOKEMIN_NUM_DERIVATIVES = 9;

std::string DENDRO_LOG_FILE = "logfile";
int DENDRO_LOG_FILE_LEVEL = 1;
int DENDRO_LOG_CONSOLE_LEVEL = 2;
bool DENDRO_LOG_FORCE_FILE_FLUSH = false;

// [dissipation]
double KO_DISS_SIGMA = 0.4;
bool USE_CONST_KO = false;
unsigned int DISSIPATION_TYPE = 0;

double SMOKEMIN_CURRENT_MIN_DX = (SMOKEMIN_COMPD_MAX[0] - SMOKEMIN_COMPD_MIN[0]) *
                             (1.0 / (double)(1u << SMOKEMIN_MAXDEPTH));

// evolution constraint floors (for pos_floor constraints).
// Independent per-variable floors, settable at runtime via [physics] <name>_floor.
// Default 1e-4 for all (incl. alpha): the moving-puncture lapse must be allowed to
// collapse toward 0 at a puncture, or the CCZ4 R/chi^2 source in Theta/Khat cannot be
// regularized by the gauge -- see BSSN (floors alpha at CHI_FLOOR=1e-4).

// initial data type (set from toml [initial_data] section)
unsigned int SMOKEMIN_ID_TYPE = 0;

// [physics] parameters from equation config

// DendroDerivatives system -- see dendrolib's derivs_factory.h for the full
// list of stencil names (E4/E6/E8, KIM*, BYU*, A4/A6/B4/B6/C4/C6, etc.)
std::unique_ptr<dendroderivs::DendroDerivatives> SMOKEMIN_DERIVS = nullptr;
std::string SMOKEMIN_DERIVTYPE_FIRST = "E6";
std::string SMOKEMIN_DERIVTYPE_SECOND = "E6";
bool SMOKEMIN_USE_FUSED_STENCILS = true;
std::vector<double> SMOKEMIN_DERIV_FIRST_COEFFS = {};
std::vector<double> SMOKEMIN_DERIV_SECOND_COEFFS = {};
unsigned int SMOKEMIN_DERIV_FIRST_MATID = 1;
unsigned int SMOKEMIN_DERIV_SECOND_MATID = 1;
std::string SMOKEMIN_INMATFILT_FIRST = "none";
std::string SMOKEMIN_INMATFILT_SECOND = "none";
std::vector<double> SMOKEMIN_INMATFILT_FIRST_COEFFS = {};
std::vector<double> SMOKEMIN_INMATFILT_SECOND_COEFFS = {};
std::string SMOKEMIN_POST_RHS_FILTER = "default";

}  // namespace smokemin





// =========================================================================
// TOML Parameter Reading
// =========================================================================

namespace smokemin {

namespace {

// Thin forwarders to the shared dendro_params reader, binding this solver's
// legacy fallbacks ("smokemin::KEY" and "SMOKEMIN_KEY"). The
// section-first + case-insensitive + flat-key logic lives in <param_reader.h>.
template <typename T>
inline bool try_read(const toml::value& root, const std::string& section,
                     const std::string& key, T& out) {
    return dendro_params::try_read(root, section, key, out,
                                   "smokemin::", "SMOKEMIN_");
}

template <typename T, std::size_t N>
inline bool try_read_array(const toml::value& root, const std::string& section,
                           const std::string& key, T (&out)[N]) {
    return dendro_params::try_read_array(root, section, key, out,
                                         "smokemin::", "SMOKEMIN_");
}

}  // anonymous namespace

void readParamFile(const char* inFile, MPI_Comm comm) {
    int rank, npes;
    MPI_Comm_rank(comm, &rank);
    MPI_Comm_size(comm, &npes);

    const auto root = toml::parse(inFile);

    // Macro for required params: fail if not found
    #define READ_REQUIRED(section, key, var) \
        if (!try_read(root, section, key, var)) { \
            if (rank == 0) std::cerr << RED << "MISSING REQUIRED PARAMETER: " \
                << "[" << section << "] " << key << NRM << std::endl; \
            throw std::runtime_error("Missing required parameter: " + \
                                     std::string(key)); \
        }

    // Macro for optional params: warn if not found, keep default
    #define READ_OPTIONAL(section, key, var) \
        if (!try_read(root, section, key, var)) { \
            if (rank == 0) std::cout << YLW << "\tOptional param '" << key \
                << "' not found, using default" << NRM << std::endl; \
        }

    #define READ_REQUIRED_ARRAY(section, key, var) \
        if (!try_read_array(root, section, key, var)) { \
            if (rank == 0) std::cerr << RED << "MISSING REQUIRED ARRAY: " \
                << "[" << section << "] " << key << NRM << std::endl; \
            throw std::runtime_error("Missing required array: " + \
                                     std::string(key)); \
        }

    #define READ_OPTIONAL_ARRAY(section, key, var) \
        try_read_array(root, section, key, var)

    // =================================================================
    // [solver] - Mesh and time stepping
    // =================================================================
    READ_REQUIRED("solver", "maxdepth", SMOKEMIN_MAXDEPTH);
    READ_REQUIRED("solver", "dim", SMOKEMIN_DIM);
    READ_REQUIRED("solver", "rk_type", SMOKEMIN_RK_TYPE);
    READ_REQUIRED("solver", "rk_time_begin", SMOKEMIN_RK_TIME_BEGIN);
    READ_REQUIRED("solver", "rk_time_end", SMOKEMIN_RK_TIME_END);
    READ_REQUIRED("solver", "rk45_time_step_size", SMOKEMIN_RK45_TIME_STEP_SIZE);
    READ_REQUIRED("solver", "rk45_desired_tol", SMOKEMIN_RK45_DESIRED_TOL);
    READ_REQUIRED("solver", "io_output_freq", SMOKEMIN_IO_OUTPUT_FREQ);
    READ_REQUIRED("solver", "remesh_test_freq", SMOKEMIN_REMESH_TEST_FREQ);
    READ_REQUIRED("solver", "checkpt_freq", SMOKEMIN_CHECKPT_FREQ);
    READ_REQUIRED("solver", "vtu_file_prefix", SMOKEMIN_VTU_FILE_PREFIX);
    READ_REQUIRED("solver", "chkpt_file_prefix", SMOKEMIN_CHKPT_FILE_PREFIX);
    READ_REQUIRED("solver", "profile_file_prefix", SMOKEMIN_PROFILE_FILE_PREFIX);
    READ_REQUIRED("solver", "restore_solver", SMOKEMIN_RESTORE_SOLVER);
    READ_REQUIRED("solver", "dendro_grain_sz", SMOKEMIN_DENDRO_GRAIN_SZ);
    READ_REQUIRED("solver", "async_comm_k", SMOKEMIN_ASYNC_COMM_K);
    READ_REQUIRED("solver", "dendro_amr_fac", SMOKEMIN_DENDRO_AMR_FAC);
    READ_REQUIRED("solver", "load_imb_tol", SMOKEMIN_LOAD_IMB_TOL);

    READ_OPTIONAL("solver", "ele_order", SMOKEMIN_ELE_ORDER);
    READ_OPTIONAL("solver", "mindepth", SMOKEMIN_MINDEPTH);
    READ_OPTIONAL("solver", "enable_block_adaptivity",
                  SMOKEMIN_ENABLE_BLOCK_ADAPTIVITY);
    READ_OPTIONAL("solver", "blk_min_x", SMOKEMIN_BLK_MIN_X);
    READ_OPTIONAL("solver", "blk_min_y", SMOKEMIN_BLK_MIN_Y);
    READ_OPTIONAL("solver", "blk_min_z", SMOKEMIN_BLK_MIN_Z);
    READ_OPTIONAL("solver", "blk_max_x", SMOKEMIN_BLK_MAX_X);
    READ_OPTIONAL("solver", "blk_max_y", SMOKEMIN_BLK_MAX_Y);
    READ_OPTIONAL("solver", "blk_max_z", SMOKEMIN_BLK_MAX_Z);
    READ_OPTIONAL("solver", "cfl_factor", SMOKEMIN_CFL_FACTOR);
    READ_OPTIONAL("solver", "init_grid_iter", SMOKEMIN_INIT_GRID_ITER);
    READ_OPTIONAL("solver", "time_step_output_freq", SMOKEMIN_TIME_STEP_OUTPUT_FREQ);
    READ_OPTIONAL("solver", "num_refine_vars", SMOKEMIN_NUM_REFINE_VARS);
    READ_OPTIONAL("solver", "num_evol_vars_vtu_output", SMOKEMIN_NUM_EVOL_VARS_VTU_OUTPUT);
    READ_OPTIONAL("solver", "num_const_vars_vtu_output", SMOKEMIN_NUM_CONST_VARS_VTU_OUTPUT);
    // terminal_output norm selection: list of variable indices (count = length)
    if (root.contains("solver")) {
        const auto& _solver = root.at("solver");
        if (_solver.contains("terminal_output_evol_indices"))
            SMOKEMIN_TERMINAL_OUTPUT_EVOL_INDICES =
                toml::find<std::vector<unsigned int>>(_solver, "terminal_output_evol_indices");
        if (_solver.contains("terminal_output_const_indices"))
            SMOKEMIN_TERMINAL_OUTPUT_CONST_INDICES =
                toml::find<std::vector<unsigned int>>(_solver, "terminal_output_const_indices");
    }
    READ_OPTIONAL("solver", "vtu_x_slice", SMOKEMIN_VTU_X_SLICE);
    READ_OPTIONAL("solver", "vtu_y_slice", SMOKEMIN_VTU_Y_SLICE);
    READ_OPTIONAL("solver", "vtu_z_slice", SMOKEMIN_VTU_Z_SLICE);

    READ_REQUIRED_ARRAY("solver", "compd_min", SMOKEMIN_COMPD_MIN);
    READ_REQUIRED_ARRAY("solver", "compd_max", SMOKEMIN_COMPD_MAX);
    READ_OPTIONAL_ARRAY("solver", "octree_min", SMOKEMIN_OCTREE_MIN);
    // recompute OCTREE_MAX from the toml-loaded MAXDEPTH (static init used the
    // declared default); READ_OPTIONAL_ARRAY below overrides if user set it
    SMOKEMIN_OCTREE_MAX[0] = (double)(1u << SMOKEMIN_MAXDEPTH);
    SMOKEMIN_OCTREE_MAX[1] = (double)(1u << SMOKEMIN_MAXDEPTH);
    SMOKEMIN_OCTREE_MAX[2] = (double)(1u << SMOKEMIN_MAXDEPTH);
    READ_OPTIONAL_ARRAY("solver", "octree_max", SMOKEMIN_OCTREE_MAX);

    // recompute dependent values
    SMOKEMIN_PADDING_WIDTH = SMOKEMIN_ELE_ORDER >> 1u;
    SMOKEMIN_CURRENT_MIN_DX = (SMOKEMIN_COMPD_MAX[0] - SMOKEMIN_COMPD_MIN[0]) *
                                         (1.0 / (double)(1u << SMOKEMIN_MAXDEPTH));

    // =================================================================
    // [refinement]
    // =================================================================
    READ_OPTIONAL("refinement", "wavelet_tol", SMOKEMIN_WAVELET_TOL);
    READ_OPTIONAL("refinement", "wavelet_tol_max", SMOKEMIN_WAVELET_TOL_MAX);
    READ_OPTIONAL("refinement", "use_wavelet_tol_function", SMOKEMIN_USE_WAVELET_TOL_FUNCTION);
    READ_OPTIONAL("refinement", "wavelet_tol_function_r0", SMOKEMIN_WAVELET_TOL_FUNCTION_R0);
    READ_OPTIONAL("refinement", "wavelet_tol_function_r1", SMOKEMIN_WAVELET_TOL_FUNCTION_R1);
    {
        unsigned int mode_int = static_cast<unsigned int>(SMOKEMIN_REFINEMENT_MODE);
        try_read(root, "refinement", "mode", mode_int);
        SMOKEMIN_REFINEMENT_MODE = static_cast<RefinementMode>(mode_int);
    }

    // =================================================================
    // [dissipation]
    // =================================================================
    READ_REQUIRED("dissipation", "ko_diss_sigma", KO_DISS_SIGMA);
    READ_OPTIONAL("dissipation", "use_const_ko", USE_CONST_KO);
    READ_OPTIONAL("dissipation", "dissipation_type", DISSIPATION_TYPE);

    // =================================================================
    // [physics] - Equation-specific parameters
    // These are read with their short names (no project prefix)
    // =================================================================

    // evolution constraint floors (optional; compiled defaults 1e-4)

    // =================================================================
    // [initial_data]
    // =================================================================
    READ_OPTIONAL("initial_data", "id_type", SMOKEMIN_ID_TYPE);



    // =================================================================
    // [wave_extraction]
    // =================================================================

    // =================================================================
    // [logging]
    // =================================================================
    READ_OPTIONAL("logging", "log_file", DENDRO_LOG_FILE);
    READ_OPTIONAL("logging", "log_file_level", DENDRO_LOG_FILE_LEVEL);
    READ_OPTIONAL("logging", "log_console_level", DENDRO_LOG_CONSOLE_LEVEL);
    READ_OPTIONAL("logging", "force_file_flush", DENDRO_LOG_FORCE_FILE_FLUSH);


    // [derivatives] -- see dendrolib's derivs_factory.h for valid type names
    READ_OPTIONAL("derivatives", "type_first", SMOKEMIN_DERIVTYPE_FIRST);
    READ_OPTIONAL("derivatives", "type_second", SMOKEMIN_DERIVTYPE_SECOND);
    READ_OPTIONAL("derivatives", "matid_first", SMOKEMIN_DERIV_FIRST_MATID);
    READ_OPTIONAL("derivatives", "matid_second", SMOKEMIN_DERIV_SECOND_MATID);
    READ_OPTIONAL("derivatives", "filter_first", SMOKEMIN_INMATFILT_FIRST);
    READ_OPTIONAL("derivatives", "filter_second", SMOKEMIN_INMATFILT_SECOND);
    READ_OPTIONAL("derivatives", "post_rhs_filter", SMOKEMIN_POST_RHS_FILTER);
    READ_OPTIONAL("derivatives", "use_fused_stencils",
                  SMOKEMIN_USE_FUSED_STENCILS);

    SMOKEMIN_DERIVS = std::make_unique<dendroderivs::DendroDerivatives>(
        SMOKEMIN_DERIVTYPE_FIRST, SMOKEMIN_DERIVTYPE_SECOND,
        SMOKEMIN_ELE_ORDER,
        SMOKEMIN_DERIV_FIRST_COEFFS, SMOKEMIN_DERIV_SECOND_COEFFS,
        SMOKEMIN_DERIV_FIRST_MATID, SMOKEMIN_DERIV_SECOND_MATID,
        SMOKEMIN_INMATFILT_FIRST, SMOKEMIN_INMATFILT_SECOND,
        SMOKEMIN_INMATFILT_FIRST_COEFFS, SMOKEMIN_INMATFILT_SECOND_COEFFS,
        SMOKEMIN_POST_RHS_FILTER);

    if (rank == 0) {
        std::cout << "DendroDerivatives initialized: "
                  << SMOKEMIN_DERIVS->toString() << std::endl;
    }

    #undef READ_REQUIRED
    #undef READ_OPTIONAL
    #undef READ_REQUIRED_ARRAY
    #undef READ_OPTIONAL_ARRAY

    if (rank == 0) {
        std::cout << GRN << "Parameter file loaded successfully." << NRM << std::endl;
    }
}

void dumpParamFile(std::ostream& sout, int root, MPI_Comm comm) {
    int rank;
    MPI_Comm_rank(comm, &rank);
    if (rank != root) return;

    // Dumps parsed in-memory values, not the par file, so a silently-kept
    // compiled default is visible in the log.
    const std::streamsize old_prec = sout.precision();
    sout << std::setprecision(17);

    auto arr = [&sout](const char* name, const auto* a, std::size_t n) {
        sout << name << " = [";
        for (std::size_t i = 0; i < n; ++i)
            sout << a[i] << (i + 1 < n ? ", " : "");
        sout << "]" << std::endl;
    };

    sout << "# ==== SMOKEMIN parameter dump (parsed values, not the par file) ===="
         << std::endl;

    sout << "\n[solver]" << std::endl;
    sout << "dim = " << SMOKEMIN_DIM << std::endl;
    sout << "ele_order = " << SMOKEMIN_ELE_ORDER << std::endl;
    sout << "padding_width = " << SMOKEMIN_PADDING_WIDTH << std::endl;
    sout << "maxdepth = " << SMOKEMIN_MAXDEPTH << std::endl;
    sout << "mindepth = " << SMOKEMIN_MINDEPTH << std::endl;
    arr("compd_min", SMOKEMIN_COMPD_MIN, 3);
    arr("compd_max", SMOKEMIN_COMPD_MAX, 3);
    arr("octree_min", SMOKEMIN_OCTREE_MIN, 3);
    arr("octree_max", SMOKEMIN_OCTREE_MAX, 3);
    sout << "enable_block_adaptivity = " << SMOKEMIN_ENABLE_BLOCK_ADAPTIVITY
         << std::endl;
    sout << "rk_type = " << SMOKEMIN_RK_TYPE << std::endl;
    sout << "rk_time_begin = " << SMOKEMIN_RK_TIME_BEGIN << std::endl;
    sout << "rk_time_end = " << SMOKEMIN_RK_TIME_END << std::endl;
    sout << "rk45_time_step_size = " << SMOKEMIN_RK45_TIME_STEP_SIZE << std::endl;
    sout << "rk45_desired_tol = " << SMOKEMIN_RK45_DESIRED_TOL << std::endl;
    sout << "cfl_factor = " << SMOKEMIN_CFL_FACTOR << std::endl;
    sout << "io_output_freq = " << SMOKEMIN_IO_OUTPUT_FREQ << std::endl;
    sout << "time_step_output_freq = " << SMOKEMIN_TIME_STEP_OUTPUT_FREQ
         << std::endl;
    sout << "checkpt_freq = " << SMOKEMIN_CHECKPT_FREQ << std::endl;
    sout << "restore_solver = " << SMOKEMIN_RESTORE_SOLVER << std::endl;
    sout << "dendro_grain_sz = " << SMOKEMIN_DENDRO_GRAIN_SZ << std::endl;
    sout << "dendro_amr_fac = " << SMOKEMIN_DENDRO_AMR_FAC << std::endl;
    sout << "load_imb_tol = " << SMOKEMIN_LOAD_IMB_TOL << std::endl;
    sout << "async_comm_k = " << SMOKEMIN_ASYNC_COMM_K << std::endl;
    sout << "init_grid_iter = " << SMOKEMIN_INIT_GRID_ITER << std::endl;
    sout << "remesh_test_freq = " << SMOKEMIN_REMESH_TEST_FREQ << std::endl;
    sout << "num_refine_vars = " << SMOKEMIN_NUM_REFINE_VARS << std::endl;

    sout << "\n[refinement]" << std::endl;
    sout << "mode = " << static_cast<unsigned int>(SMOKEMIN_REFINEMENT_MODE)
         << "   # 0=WAMR 1=EH 2=EH_WAMR 3=BH_LOC 4=BH_WAMR" << std::endl;
    sout << "wavelet_tol = " << SMOKEMIN_WAVELET_TOL << std::endl;
    sout << "wavelet_tol_max = " << SMOKEMIN_WAVELET_TOL_MAX << std::endl;
    sout << "use_wavelet_tol_function = " << SMOKEMIN_USE_WAVELET_TOL_FUNCTION
         << std::endl;
    sout << "wavelet_tol_function_r0 = " << SMOKEMIN_WAVELET_TOL_FUNCTION_R0
         << std::endl;
    sout << "wavelet_tol_function_r1 = " << SMOKEMIN_WAVELET_TOL_FUNCTION_R1
         << std::endl;

    sout << "\n[dissipation]" << std::endl;
    sout << "ko_diss_sigma = " << KO_DISS_SIGMA << std::endl;
    sout << "use_const_ko = " << USE_CONST_KO << std::endl;
    sout << "dissipation_type = " << DISSIPATION_TYPE << std::endl;

    sout << "\n[derivatives]" << std::endl;
    sout << "type_first = \"" << SMOKEMIN_DERIVTYPE_FIRST << "\"" << std::endl;
    sout << "type_second = \"" << SMOKEMIN_DERIVTYPE_SECOND << "\"" << std::endl;
    sout << "use_fused_stencils = "
         << (SMOKEMIN_USE_FUSED_STENCILS ? "true" : "false") << std::endl;

    // [physics]: generated from the equation config's ParameterVariables, so a
    // system's own parameters appear here without touching this template.
    sout << "\n[physics]" << std::endl;

    sout << "\n[initial_data]" << std::endl;
    sout << "id_type = " << SMOKEMIN_ID_TYPE;
    sout << std::endl;


    sout << "\n# ==== end parameter dump ====" << std::endl;
    sout << std::setprecision(old_prec);
}

}  // namespace smokemin
