/**
 * @file rhs.cpp
 * @brief RHS computation for the smokemin solver.
 *
 * Generated by dendrosym. Safe to edit -- only gencode/*.cpp.inc files
 * get regenerated when equations change.
 *
 * Layout:
 *   1. Block-level dispatch (smokeminRHS)
 *   2. Per-block RHS (smokeminrhs)
 *      - variable extraction (pointers into unzipped arrays)
 *      - parameter extraction (local copies of global params)
 *      - derivative workspace + stencil computation
 *      - main RHS equation loop (the generated code)
 *      - boundary conditions (Sommerfeld radiation)
 *      - KO dissipation / filtering
 *   3. Boundary condition implementation
 */

#include "rhs.h"
#include "parameters.h"
#include "profile_params.h"
#include "block_geometry.h"

using namespace std;
using namespace smokemin;

// -------------------------------------------------------------------------
// block-level dispatch -- iterates over octree blocks and calls per-block rhs
// -------------------------------------------------------------------------

void smokeminRHS(double **uzipVarsRHS, const double **uZipVars,
             const ot::Block *blkList, unsigned int numBlocks,
             const double curr_time, const double **uZipConstVars) {

    const Point pt_min(smokemin::SMOKEMIN_COMPD_MIN[0],
                       smokemin::SMOKEMIN_COMPD_MIN[1],
                       smokemin::SMOKEMIN_COMPD_MIN[2]);
    const Point pt_max(smokemin::SMOKEMIN_COMPD_MAX[0],
                       smokemin::SMOKEMIN_COMPD_MAX[1],
                       smokemin::SMOKEMIN_COMPD_MAX[2]);
    const Point oct_min(smokemin::SMOKEMIN_OCTREE_MIN[0],
                        smokemin::SMOKEMIN_OCTREE_MIN[1],
                        smokemin::SMOKEMIN_OCTREE_MIN[2]);
    const Point oct_max(smokemin::SMOKEMIN_OCTREE_MAX[0],
                        smokemin::SMOKEMIN_OCTREE_MAX[1],
                        smokemin::SMOKEMIN_OCTREE_MAX[2]);

    // ot::BlockGeometryRange yields per-block offset/sz/bflag/dx/ptmin/ptmax and
    // hoists the grid->physical scaling out of the per-block loop.
    for (const auto &b : ot::BlockGeometryRange(blkList, numBlocks, pt_min,
                                                pt_max, oct_min, oct_max))
        smokeminrhs(uzipVarsRHS, (const double **)uZipVars, b.offset,
                b.ptmin, b.ptmax, b.sz, b.bflag, curr_time,
                (const double **)uZipConstVars);
}

// -------------------------------------------------------------------------
// per-block rhs -- this is where the actual computation happens
// -------------------------------------------------------------------------

// derivative-workspace struct (grouped buffers + self-sizing bind/count)
#include "../gencode/smokemin_evolution_deriv_struct.cpp.inc"

void smokeminrhs(double **unzipVarsRHS, const double **uZipVars,
             const unsigned int &offset, const double *pmin, const double *pmax,
             const unsigned int *sz, const unsigned int &bflag, const double t,
             const double **uZipConstVars) {

    // -- variable extraction --
    // const pointers into the unzipped arrays for this block.
    // each pointer (alpha, chi, gt00, ...) starts at `offset` into
    // the global unzipped array. rhs pointers are where we write output.
        struct {
        const double *u;
        const double *v;
    } in;
    in.u = &uZipVars[VAR::U_U][offset];
    in.v = &uZipVars[VAR::U_V][offset];


        struct {
        double *u;
        double *v;
    } out;
    out.u = &unzipVarsRHS[VAR::U_U][offset];
    out.v = &unzipVarsRHS[VAR::U_V][offset];


    mem::memory_pool<double> *__mem_pool = &SMOKEMIN_MEM_POOL;

    const unsigned int nx = sz[0];
    const unsigned int ny = sz[1];
    const unsigned int nz = sz[2];

    const double hx = (pmax[0] - pmin[0]) / (nx - 1);
    const double hy = (pmax[1] - pmin[1]) / (ny - 1);
    const double hz = (pmax[2] - pmin[2]) / (nz - 1);

    // -- parameters --
    

    int idx[3];
    const unsigned int PW = smokemin::SMOKEMIN_PADDING_WIDTH;
    unsigned int n = sz[0] * sz[1] * sz[2];

    smokemin::timer::t_deriv.start();

    const unsigned int BLK_SZ = n;
    const unsigned int bytes = n * sizeof(double);

    // derivative workspace -- one big allocation that holds all precomputed
    // derivative arrays. each alpha_x etc. is a pointer at offset N*BLK_SZ.
    double *const deriv_base = smokemin::SMOKEMIN_DERIV_WORKSPACE;

    // configurable derivative object (replaces old per-order derivs.cpp)
    auto &SOLVER_DERIVS = *smokemin::SMOKEMIN_DERIVS;

    // -- standard derivative computation --
    // d.bind() carves the workspace into named buffers (d.alpha_x, d.alpha_xy, ...).
    smokemin_evolution_derivs_t d;
    d.bind(deriv_base, BLK_SZ);

    // -- intermediate (compound-expression) derivatives --
    // when equations differentiate a compound expression (e.g. d(chi*gt)), the
    // compound is materialized once into a staged d.* buffer here; deriv_calc
    // below then differentiates it alongside the ordinary derivatives.
#include "../gencode/smokemin_evolution_intermediate_grad.cpp.inc"

    // deriv_calc fills the derivative buffers with the finite-difference stencils
    // (including the staged derivatives of the intermediate buffers above).
#include "../gencode/smokemin_evolution_deriv_calc.cpp.inc"

    smokemin::timer::t_deriv.stop();

    // -- main rhs loop --
    // this is where the generated equations live. the included file has
    // all the CSE-optimized code with DENDRO_nnnn temporaries.
    smokemin::timer::t_rhs.start();
    for (unsigned int k = PW; k < nz - PW; k++) {
        for (unsigned int j = PW; j < ny - PW; j++) {
            for (unsigned int i = PW; i < nx - PW; i++) {
                const double x = pmin[0] + i * hx;
                const double y = pmin[1] + j * hy;
                const double z = pmin[2] + k * hz;

                const unsigned int pp = i + nx * (j + ny * k);
                const double r_coord = sqrt(x * x + y * y + z * z);

#include "../gencode/smokemin_evolution_rhs_eqns.cpp.inc"
            }
        }
    }
    smokemin::timer::t_rhs.stop();

    // -- deallocate intermediate derivatives --
#include "../gencode/smokemin_evolution_intermediate_grad_dealloc.cpp.inc"

    // -- boundary conditions --
    // sommerfeld radiation bcs: each variable gets an outgoing-wave condition
    // with a specified falloff rate and asymptotic value.
    if (bflag != 0) {
        smokemin::timer::t_bdyc.start();
            // per-variable sommerfeld bc data: {rhs, field, dx, dy, dz, falloff, asymptotic}
    struct __bc_row {
        double *rhs;
        const double *f, *gx, *gy, *gz;
        double falloff, asymptotic;
    };
    const __bc_row __bc_rows[] = {
        {out.u, in.u, d.u_x, d.u_y, d.u_z, 1.0, 0.0},
        {out.v, in.v, d.v_x, d.v_y, d.v_z, 1.0, 0.0},
    };
    for (const auto &__r : __bc_rows)
        smokemin_bcs(__r.rhs, __r.f, __r.gx, __r.gy, __r.gz, pmin, pmax, __r.falloff, __r.asymptotic, sz, bflag);

        smokemin::timer::t_bdyc.stop();
    }

    // -- kreiss-oliger dissipation --
    // adds numerical dissipation to damp high-frequency noise.
    // using the DendroDerivatives filter api -- handles ko internally
    if (!SOLVER_DERIVS.do_filter_before()) {
        smokemin::timer::t_ko.start();
        const double sigma = KO_DISS_SIGMA;

        // per-variable ko filter inputs: {field, rhs, dx, dy, dz}
        struct __ko_row {
            const double *u;
            double *u_rhs;
            double *gx, *gy, *gz;
        };
        const __ko_row __ko_rows[] = {
            { in.u, out.u, d.u_x, d.u_y, d.u_z },
            { in.v, out.v, d.v_x, d.v_y, d.v_z },
        };
        for (const auto &__r : __ko_rows)
            SOLVER_DERIVS.filter(__r.u, __r.u_rhs, __r.gx, __r.gy, __r.gz,
                                   hx, hy, hz, sigma, sz, bflag);
        smokemin::timer::t_ko.stop();
    }

    // -- deallocate standard derivatives --
    smokemin::timer::t_deriv.start();
#include "../gencode/smokemin_evolution_deriv_memdealloc.cpp.inc"
    smokemin::timer::t_deriv.stop();
}

// -------------------------------------------------------------------------
// sommerfeld radiation boundary conditions
//
// applies an outgoing-wave condition at domain boundaries:
//   f_rhs = -(1/r)(x*dxf + y*dyf + z*dzf + falloff*(f - f_asymptotic))
//
// each variable has its own falloff rate and asymptotic value, set by
// the config's set_bhs_falloff_and_asymptotic() call.
// -------------------------------------------------------------------------

void smokemin_bcs(double *f_rhs, const double *f,
              const double *dxf, const double *dyf, const double *dzf,
              const double *pmin, const double *pmax,
              const double f_falloff, const double f_asymptotic,
              const unsigned int *sz, const unsigned int &bflag) {

    const unsigned int nx = sz[0];
    const unsigned int ny = sz[1];
    const unsigned int nz = sz[2];

    double hx = (pmax[0] - pmin[0]) / (nx - 1);
    double hy = (pmax[1] - pmin[1]) / (ny - 1);
    double hz = (pmax[2] - pmin[2]) / (nz - 1);

    const unsigned int PW = smokemin::SMOKEMIN_PADDING_WIDTH;

    unsigned int ib = PW;
    unsigned int jb = PW;
    unsigned int kb = PW;
    unsigned int ie = nx - PW;
    unsigned int je = ny - PW;
    unsigned int ke = nz - PW;

    double x, y, z;
    unsigned int pp;
    double inv_r;

    // apply on each boundary face that's flagged
    if (bflag & (1u << OCT_DIR_LEFT)) {
        for (unsigned int k = kb; k < ke; k++) {
            z = pmin[2] + k * hz;
            for (unsigned int j = jb; j < je; j++) {
                y = pmin[1] + j * hy;
                for (unsigned int i = ib; i < ib + PW; i++) {
                    x = pmin[0] + i * hx;
                    pp = i + nx * (j + ny * k);
                    inv_r = 1.0 / sqrt(x * x + y * y + z * z);
                    f_rhs[pp] = -inv_r * (x * dxf[pp] + y * dyf[pp] + z * dzf[pp]
                                + f_falloff * (f[pp] - f_asymptotic));
                }
            }
        }
    }

    if (bflag & (1u << OCT_DIR_RIGHT)) {
        for (unsigned int k = kb; k < ke; k++) {
            z = pmin[2] + k * hz;
            for (unsigned int j = jb; j < je; j++) {
                y = pmin[1] + j * hy;
                for (unsigned int i = ie - PW; i < ie; i++) {
                    x = pmin[0] + i * hx;
                    pp = i + nx * (j + ny * k);
                    inv_r = 1.0 / sqrt(x * x + y * y + z * z);
                    f_rhs[pp] = -inv_r * (x * dxf[pp] + y * dyf[pp] + z * dzf[pp]
                                + f_falloff * (f[pp] - f_asymptotic));
                }
            }
        }
    }

    if (bflag & (1u << OCT_DIR_DOWN)) {
        for (unsigned int k = kb; k < ke; k++) {
            z = pmin[2] + k * hz;
            for (unsigned int j = jb; j < jb + PW; j++) {
                y = pmin[1] + j * hy;
                for (unsigned int i = ib; i < ie; i++) {
                    x = pmin[0] + i * hx;
                    pp = i + nx * (j + ny * k);
                    inv_r = 1.0 / sqrt(x * x + y * y + z * z);
                    f_rhs[pp] = -inv_r * (x * dxf[pp] + y * dyf[pp] + z * dzf[pp]
                                + f_falloff * (f[pp] - f_asymptotic));
                }
            }
        }
    }

    if (bflag & (1u << OCT_DIR_UP)) {
        for (unsigned int k = kb; k < ke; k++) {
            z = pmin[2] + k * hz;
            for (unsigned int j = je - PW; j < je; j++) {
                y = pmin[1] + j * hy;
                for (unsigned int i = ib; i < ie; i++) {
                    x = pmin[0] + i * hx;
                    pp = i + nx * (j + ny * k);
                    inv_r = 1.0 / sqrt(x * x + y * y + z * z);
                    f_rhs[pp] = -inv_r * (x * dxf[pp] + y * dyf[pp] + z * dzf[pp]
                                + f_falloff * (f[pp] - f_asymptotic));
                }
            }
        }
    }

    if (bflag & (1u << OCT_DIR_BACK)) {
        for (unsigned int k = kb; k < kb + PW; k++) {
            z = pmin[2] + k * hz;
            for (unsigned int j = jb; j < je; j++) {
                y = pmin[1] + j * hy;
                for (unsigned int i = ib; i < ie; i++) {
                    x = pmin[0] + i * hx;
                    pp = i + nx * (j + ny * k);
                    inv_r = 1.0 / sqrt(x * x + y * y + z * z);
                    f_rhs[pp] = -inv_r * (x * dxf[pp] + y * dyf[pp] + z * dzf[pp]
                                + f_falloff * (f[pp] - f_asymptotic));
                }
            }
        }
    }

    if (bflag & (1u << OCT_DIR_FRONT)) {
        for (unsigned int k = ke - PW; k < ke; k++) {
            z = pmin[2] + k * hz;
            for (unsigned int j = jb; j < je; j++) {
                y = pmin[1] + j * hy;
                for (unsigned int i = ib; i < ie; i++) {
                    x = pmin[0] + i * hx;
                    pp = i + nx * (j + ny * k);
                    inv_r = 1.0 / sqrt(x * x + y * y + z * z);
                    f_rhs[pp] = -inv_r * (x * dxf[pp] + y * dyf[pp] + z * dzf[pp]
                                + f_falloff * (f[pp] - f_asymptotic));
                }
            }
        }
    }
}

void freeze_bcs(double *f_rhs, const unsigned int *sz,
                const unsigned int &bflag) {
    const unsigned int nx = sz[0];
    const unsigned int ny = sz[1];
    const unsigned int nz = sz[2];
    const unsigned int PW = smokemin::SMOKEMIN_PADDING_WIDTH;

    unsigned int ib = PW, jb = PW, kb = PW;
    unsigned int ie = nx - PW, je = ny - PW, ke = nz - PW;

    // zero out rhs at each flagged boundary face
    if (bflag & (1u << OCT_DIR_LEFT))
        for (unsigned int k = kb; k < ke; k++)
            for (unsigned int j = jb; j < je; j++)
                for (unsigned int i = ib; i < ib + PW; i++)
                    f_rhs[i + nx * (j + ny * k)] = 0.0;

    if (bflag & (1u << OCT_DIR_RIGHT))
        for (unsigned int k = kb; k < ke; k++)
            for (unsigned int j = jb; j < je; j++)
                for (unsigned int i = ie - PW; i < ie; i++)
                    f_rhs[i + nx * (j + ny * k)] = 0.0;

    if (bflag & (1u << OCT_DIR_DOWN))
        for (unsigned int k = kb; k < ke; k++)
            for (unsigned int j = jb; j < jb + PW; j++)
                for (unsigned int i = ib; i < ie; i++)
                    f_rhs[i + nx * (j + ny * k)] = 0.0;

    if (bflag & (1u << OCT_DIR_UP))
        for (unsigned int k = kb; k < ke; k++)
            for (unsigned int j = je - PW; j < je; j++)
                for (unsigned int i = ib; i < ie; i++)
                    f_rhs[i + nx * (j + ny * k)] = 0.0;

    if (bflag & (1u << OCT_DIR_BACK))
        for (unsigned int k = kb; k < kb + PW; k++)
            for (unsigned int j = jb; j < je; j++)
                for (unsigned int i = ib; i < ie; i++)
                    f_rhs[i + nx * (j + ny * k)] = 0.0;

    if (bflag & (1u << OCT_DIR_FRONT))
        for (unsigned int k = ke - PW; k < ke; k++)
            for (unsigned int j = jb; j < je; j++)
                for (unsigned int i = ib; i < ie; i++)
                    f_rhs[i + nx * (j + ny * k)] = 0.0;
}
