"""BSSN front-end of the cascade emitter.

Moved verbatim from vikr `codegen/cascade_emit.py` (emit_bssn_ir_avx2, emit_bssn_ir,
the argparse `main`); the generic pieces stay in `dendrosym.cascade.emit`. Emitted bytes
must match vikr's checked-in kernels (scripts/regen_vikr_kernels.sh is the oracle).
"""
import argparse
import os
import sys

from dendrosym.cascade.emit import (
    _inline_low_use_temps, _classify_leaves, _emit_avx_prologue,
    _emit_avx_chunks, _emit_avx_global_cse, _lazy_reorder,
)


def emit_bssn_ir_avx2(target_L=None, verbose=False, fold_vfma_passes: int = 0,
                      auto_layers=False, auto_search_order=False,
                       smart_split=None, inline_threshold: int = 2,
                       gauge="standard", ssl=False, cahd=False,
                       eta_mode="scalar", fused=False,
                       lazy_prologue=True, fma_tree: bool = False,
                       fma_split: int = 1, global_cse: bool = False) -> str:
    """Build the IR and emit a SIMD-agnostic VEC-macro body.

    The body is included inside a batched harness wrapper that provides:
      - the outer i/j/k loop with i stepping in fours (AVX2) or eights (AVX-512)
      - per-batch eta computation as a VEC
      - typedef VEC = __m256d / __m512d and macro defines

    The body declares all leaves via VLOAD (state, derivs) or VSET broadcast
    (lambda, lambda_f), runs the cascade chunks, and VSTOREs RHS outputs.

    Same body compiles for both AVX2 and AVX-512 — only the wrapper differs.

    `fold_vfma_passes`: post-process the emitted text to fold
    `VADD(VMUL(a, b), c)` into `VFMA(a, b, c)`. Compiler usually does this at
    -O3 -mfma, but folding in source guarantees it. Default 0 (off).

    `smart_split`: when True and target_L > natural_L, use the post-CSE
    smart split (Phase 4 / talk Algorithm 3) that hoists shared CSE temps
    into a precursor sub-chunk, eliminating cross-half duplication.
    """
    from dendrosym.cascade.systems.bssn.cascade import build_ir

    result = build_ir(auto_layers=auto_layers, auto_search_order=auto_search_order,
                      target_L=target_L, smart_split=smart_split,
                      gauge=gauge, ssl=ssl, cahd=cahd, eta_mode=eta_mode,
                      verbose=verbose)
    if inline_threshold > 0:
        result = _inline_low_use_temps(result, threshold=inline_threshold)
    leaves = _classify_leaves(result, fused=fused)

    L = len(result.chunks)
    if L == 7:
        kind = "natural"
    elif L > 7:
        kind = "split from 7"
    else:
        kind = "collapsed from 7"

    lines = [
        "// BSSN RHS via polynomial cascade -- IR-driven, SIMD-batched",
        "// Generated by cascade_emit.emit_bssn_ir_avx2()",
        f"// L = {L} chunks ({kind}); 4-wide batches (AVX2) or 8-wide (AVX-512)",
        f"// VFMA folding passes: {fold_vfma_passes}",
        "// Per-chunk CSE only; named tensors survive as chunk boundaries.",
    ]
    if gauge != "standard" or ssl or cahd or eta_mode != "scalar":
        lines.append(
            f"// gauge={gauge} ssl={ssl} cahd={cahd} eta_mode={eta_mode} -- "
            "wrapper must provide ssl_fac/cahd_coef as VEC-broadcastable scalars.")
    if fused:
        lines.append(
            "// FUSED: 1st/pure-2nd derivs inlined as stencils; wrapper runs "
            "mixed-2nd-only pre-pass; interior-only (bflag==0).")
    lines.append("")
    lines += _emit_avx_prologue(leaves)
    if global_cse:
        lines += _emit_avx_global_cse(result, leaves, fma=fma_tree, split=fma_split)
    else:
        lines += _emit_avx_chunks(result, leaves, fma=fma_tree, split=fma_split)
    if lazy_prologue:
        lines = _lazy_reorder(lines)
    text = "\n".join(lines) + "\n"
    if fold_vfma_passes > 0:
        from dendrosym.cascade.vec_printer import fold_vfma
        text = fold_vfma(text, max_passes=fold_vfma_passes)
    return text


def emit_bssn_ir(simd: str = "scalar", target_L=None, verbose: bool = False,
                 fold_vfma_passes: int = 0, smart_split=None,
                 inline_threshold: int = 0,
                 gauge="standard", ssl=False, cahd=False,
                 eta_mode="scalar", fused=False, global_cse=False,
                 fma_tree=False, fma_split=1, auto_layers=False,
                 auto_search_order=False) -> str:
    """Build the BSSN IR cascade at depth target_L and return the C++ body.

    `target_L=None` => physics-natural depth (7).
    `simd` is "scalar" (Phase 1a) or "avx2" (Phase 1b; same source compiles
    for AVX-512 via a different wrapper). VFMA folding only applies to the
    SIMD path; scalar emit uses plain operators.
    """
    if simd == "avx2":
        return emit_bssn_ir_avx2(
            target_L=target_L, verbose=verbose, auto_layers=auto_layers,
            auto_search_order=auto_search_order,
            fold_vfma_passes=fold_vfma_passes,
            smart_split=smart_split,
            inline_threshold=inline_threshold,
            gauge=gauge, ssl=ssl, cahd=cahd, eta_mode=eta_mode,
            fused=fused, fma_tree=fma_tree, fma_split=fma_split,
            global_cse=global_cse,
        )
    if fused:
        raise NotImplementedError(
            "fused=True requires the VEC emitter (--simd avx2); the scalar "
            "unrolled path reads precomputed derivative arrays only.")
    if simd != "scalar":
        raise NotImplementedError(
            f"cascade_emit: simd={simd!r} not implemented yet; "
            "supported: 'scalar', 'avx2'."
        )

    from dendrosym.cascade.systems.bssn.cascade import build_ir

    result = build_ir(target_L=target_L, smart_split=smart_split,
                      gauge=gauge, ssl=ssl, cahd=cahd,
                      eta_mode=eta_mode, verbose=verbose,
                      auto_layers=auto_layers,
                      auto_search_order=auto_search_order)
    # Same IR-level low-use inlining as the SIMD path; the regex-based
    # emit_cpp_unrolled inliner stays off (naïve substring matching corrupts
    # CASC_*_N vs CASC_*_NN prefixes), so pass inline_threshold=0 below.
    if inline_threshold > 0:
        result = _inline_low_use_temps(result, threshold=inline_threshold)
    if global_cse:
        # One global symbol-aware CSE instead of per-chunk: removes cross-chunk
        # subexpression recompute. Scalar register-pressure win; SIMD-neutral.
        body = result.emit_cpp_global_cse(dendro_var_style=True, short_names=True)
    else:
        body = result.emit_cpp_unrolled(
            dendro_var_style=True, inline_threshold=0, short_names=False
        )

    L = len(result.chunks)
    if L == 7:
        kind = "natural"
    elif L > 7:
        kind = "split from 7"
    else:
        kind = "collapsed from 7"
    header = [
        "// BSSN RHS via polynomial cascade -- IR-driven (auto-decomposed)",
        "// Generated by cascade_emit.py from bssn_cascade.build_ir()",
        f"// L = {L} chunks ({kind})",
        ("// Global symbol-aware CSE (named tensors atomic; cross-chunk sharing)."
         if global_cse else
         "// Per-chunk CSE only; named tensors survive as chunk boundaries."),
    ]
    if gauge != "standard" or ssl or cahd or eta_mode != "scalar":
        header.append(
            f"// gauge={gauge} ssl={ssl} cahd={cahd} eta_mode={eta_mode} -- "
            "wrapper must provide ssl_fac/cahd_coef scalars as applicable.")
    header.append("")
    return "\n".join(header) + body + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--simd", choices=["scalar", "avx2"], default="scalar",
        help="output dialect: 'scalar' (Phase 1a) or 'avx2' (Phase 1b)",
    )
    parser.add_argument(
        "--L", type=int, default=None,
        help="target cascade depth (default: physics-natural 7)",
    )
    parser.add_argument(
        "--output", "-o", required=True,
        help="path for the generated C++ body file",
    )
    parser.add_argument(
        "--vfma", type=int, default=0, metavar="N",
        help="regex VFMA-folding passes (only with --simd avx2). 0 = off "
        "(default). Superseded by --fma-tree.",
    )
    parser.add_argument(
        "--fma-tree", action=argparse.BooleanOptionalAction, default=True,
        help="tree-level FMA (DEFAULT ON): fold every product term into "
        "VFMA/VFNMADD (robust superset of --vfma; needs VFNMADD in the macro "
        "header). Closes clang/icpx's contraction gap to gcc -ffp-contract=fast; "
        "neutral on gcc. Use --no-fma-tree to disable.",
    )
    parser.add_argument(
        "--fma-split", type=int, default=1, metavar="K",
        help="split long sums into K independent FMA accumulator chains "
        "joined by a balanced VADD tree (ILP/latency win; implies --fma-tree). "
        "1 = single serial chain (default).",
    )
    parser.add_argument(
        "--split-mode", choices=("auto", "smart", "dumb"), default="auto",
        help="Split strategy when L > natural. 'auto' uses smart for "
        "even-delta L, dumb otherwise. 'smart' forces Algo 3, 'dumb' "
        "forces pre-CSE partitioning.",
    )
    parser.add_argument(
        "--inline-threshold", type=int, default=2, metavar="N",
        help="Inline CSE temps with ≤N uses. 0 disables (most CSE temps "
        "kept). Default 2: matches the legacy hand-written form's "
        "compactness, ~3× fewer named declarations.",
    )
    parser.add_argument(
        "--gauge", choices=["standard", "rochester"], default="standard",
        help="shift gauge condition (default standard Gamma-driver).",
    )
    parser.add_argument(
        "--ssl", action="store_true",
        help="shock-avoiding lapse term on a_rhs (wrapper provides ssl_fac).",
    )
    parser.add_argument(
        "--cahd", action="store_true",
        help="Hamiltonian-constraint damping on chi_rhs (wrapper provides "
        "cahd_coef).",
    )
    parser.add_argument(
        "--eta-mode", choices=["scalar", "array"], default="scalar",
        help="gauge-B damping: 'scalar' eta in scope (default) or eta[pp].",
    )
    parser.add_argument(
        "--fused", action="store_true",
        help="inline 6th-order stencils for 1st/pure-2nd derivs (VEC emitter "
        "only). Default OFF: the non-fused path is primary (compact-FD work "
        "composes only with non-fused).",
    )
    parser.add_argument(
        "--global-cse", action="store_true",
        help="one global symbol-aware CSE (named tensors atomic) instead of "
        "per-chunk; removes cross-chunk recompute. Works for scalar and SIMD "
        "(--simd avx2 composes with --fma-tree).",
    )
    parser.add_argument(
        "--looped", action="store_true",
        help="structured looped emitter: emit regular tensor layers as nested "
        "for-loops from their index structure (generic cascade_tensor_eqn; BSSN "
        "layers from bssn_looped), shrinking .text to fit the AVX2 icache. SIMD "
        "only. Equivalent to `python bssn_looped.py --simd <w> -o <out>`.",
    )
    parser.add_argument("--search-order", action="store_true",
                        help="with --auto: also search evaluation orders "
                             "(exact bottleneck DP over the object DAG)")
    parser.add_argument("--auto", action="store_true",
                        help="choose layer boundaries automatically (exact DP "
                             "over the declared evaluation order; --L picks the "
                             "depth, no --L lets the DP choose it)")
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args(argv)

    if args.looped:
        from dendrosym.cascade.systems.bssn.looped import build as build_bssn_looped
        simd = "avx512" if args.simd == "avx512" else "avx2"
        cpp = build_bssn_looped(simd=simd)
        out_dir = os.path.dirname(os.path.abspath(args.output))
        os.makedirs(out_dir, exist_ok=True)
        with open(args.output, "w") as f:
            f.write(cpp)
        print(f"wrote {len(cpp.splitlines())} lines to {args.output}")
        return

    smart = {"auto": None, "smart": True, "dumb": False}[args.split_mode]
    cpp = emit_bssn_ir(
        simd=args.simd, target_L=args.L, verbose=args.verbose,
        auto_layers=args.auto, auto_search_order=args.search_order,
        fold_vfma_passes=args.vfma,
        smart_split=smart,
        inline_threshold=args.inline_threshold,
        gauge=args.gauge, ssl=args.ssl, cahd=args.cahd,
        eta_mode=args.eta_mode, fused=args.fused,
        global_cse=args.global_cse,
        fma_tree=args.fma_tree or args.fma_split > 1,
        fma_split=args.fma_split,
    )

    out_dir = os.path.dirname(os.path.abspath(args.output))
    os.makedirs(out_dir, exist_ok=True)
    with open(args.output, "w") as f:
        f.write(cpp)
    print(f"wrote {len(cpp.splitlines())} lines to {args.output}")


if __name__ == "__main__":
    sys.exit(main())
